### ISSUE TITLE
6/20 +Microsoft Dynamics CRM - Phase II + 21

### ISSUE THREAD

**Issue by anazariz** [lzim/teampsd#1023]
**Functional Requirements (FR) for Microsoft Dynamics CRM** 

Need the software to perform the following: 
1. Map incoming service request emails (to **mtl.help@va.gov**) to facilitator and co-facilitator inboxes. 
2. Report emails response cadence.
3. Scheduled emails.

**Comment by anazariz** [comment]
Microsoft Dynamics has the following Modules:

1. Finance and Operations
2. Retail
3. Talent
4. Sales
5. Customer Service
6. Project Service Automation
7. Field Service
8. Marketing

As Dynamics is a CRM platform, it lacks ITSM (IT Service Management) ServiceDesk functionality (similar to the Remedy, ServiceNow, and ZenDesk platforms) . The closest thing to a ServiceDesk in Dynamics is the Customer Service module. With it operators can maintain a record of calls, emails and other interactions. However, Dynamics plugs into Microsoft’s Power Platform and ServiceDesk-like capabilities can be custom-built.

**Comment by anazariz** [comment]
Revising the FR (Functional Requirements) 
**Functional Requirements for Microsoft Dynamics CRM** 

Need the software to perform the following: 
1. Send a copy of the inbound emails to the **mtl.help@va.gov** and **mtl.info@va.gov** shared email accounts to the facilitator, co-facilitator and support inboxes.  
2. Report emails response cadence.
3. Send scheduled emails.

**Comment by lzim** [comment]
**Cross-ref #1299 - feature_req** 
- Call scheduled for Friday 4/16 at 11AM w/Enterprise Cloud Computing w/@staceypark @anthonycpichardo @anazariz

**Comment by anthonycpichardo** [comment]
##Decisions from 4/16 Call with Enterprise Cloud Computing:
Enterprise Cloud Computing team will be our primary point of contact, spoke with Rey today.
- We have Rey's support to move forward and advocate for funding. We will also have Mimi as a partner to work with Ash on moving this forward.

- If we choose not to maintain our instance and "retire" it we will need to restart the process when we are ready to get this moving.
- Because OIT initially funded the licenses and we have national impact we were able to start requesting licenses and applying for $15k of funding; if that is approved it would make sense for us to move forward and allow Ash to get going on this. 
- We could then work with the Microsoft team and see what we can get moving.
- Recommendation is that if the funding is approved it makes sense to move forward consistent with the modernization emphasis in the VA.

Next Steps:
- If funding is approved, contract representative will renew our license agreement.
- Ash would then get Developer access and create our Dynamics environment in Dev
- System would need to be registered in VACI once it is ready for production
- We will also need an ATL (authority to operate) to use the platform which Rey and Mimi will support us with.
- Stacey will run point on keeping the team informed on the approval status and collaboration pieces
- Anthony will run point on the Compliance pieces (ATL, VACI)
- The only step completed was Microsoft's initial build. The owner of that build for our group is likely to be Lindsey.

**Comment by anazariz** [comment]
One additional point that I heard, Lindsey, as the Program Manager/Platform Owner, will be in charge of account provisioning (who gets access to what). She will delegate that task as necessary.

**Comment by lzim** [comment]
Just to keep these together:
#1330 
#1299 
#1275
#1023

**Comment by jamesmrollins** [comment]
According to @anazariz this is being managed by Story 6.  Will associate this card with #1299 and close this card.  Any actions or issues associated with CRM are now in the #1299 card.
