### ISSUE TITLE
Create new logos for MTL Red Comparator Arm to use in emails, videos, and guides

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1033]
1.  "mtl part 1 over data UI" 
2. "mtl part 2 over data UI" 
3. "mtl session 1... session 6 over data UI" 
4. "mtl session 7...session 12 over team data"

**Comment by staceypark** [comment]
We will move guides over with the original MTL Red logo. And then fix the logo itself later as we make them.

**Comment by lzim** [comment]
@staceypark 

Working on this now, but I’m assuming  this: 
> "mtl part 1 over data UI"
"mtl part 2 over data UI"

Is really:
 "mtl part 1 over data UI"
"mtl part 2 over team data"

Right?

**Comment by lzim** [comment]
@staceypark @lijenn and @ritahitching 

## VAPOR Videos the same for MTL Red and Blue
### Title Slides in Weeks used in VAPOR Videos:
Posted here: https://github.com/lzim/teampsd/tree/master/resources/title_slides_weeks
- This decision was made so that the VAPOR videos included in the 24 pre/post emails was the same for _MTL Red_ and _MTL Blue_ 

## MTL Red Guides
###  R01 & IIR comparator RED GUIDES:  The logo will say "mtl part 1 over data UI" or "mtl part 2 over team data" 
Posted here: https://github.com/lzim/teampsd/tree/master/resources/logos
- This decision was made so that there is ONE set of RED guides at mtl.how.

## MTL Red Emails - Will get a weekly email about using the resources and team meetings but we will use different logos for R01 and IIR MTL Red Sites.
Purpose of VAPOR videos: Remind our learners why became a VA provider in the first place. The VA made such an impact on the lives of these Veterans they they have sustained their recovery and decided to join in the VA mission as staff.

### New R01 "Red" email logos (24 total emails) 
All are posted here: https://github.com/lzim/teampsd/tree/master/resources/logos
- Pre/post session 1: "mtl part 1 over data UI"
- Pre/post session 2: "mtl part 2 over team data"
- Then for the remaining 20 weekly emails use the play "mtl.how/red" logo.

### New IIR "Red" email logos (24 total emails)
All are posted here:
- Pre/post sessions 1-6: "mtl session 1...session 6 over data UI"
- Pre/post sessions 7-12: "mtl session 7...session 12 over team data"

**Comment by lzim** [comment]
Closing #1033 (see details above)

Cross-ref #987 - This blocked pre/post issues can proceed for the logos (videos still coming)

Guides using Red and Blue for #1050 and #1059 were already closed.
