### ISSUE TITLE
4/26 + Task + File Size causes SharePoint issues + 1

### ISSUE THREAD

**Issue by anazariz** [lzim/teampsd#1153]
Create 1 year datasets (instead of 2) for the following Stations to prevent large file size issues in  splash folders:

659, 534, 516, 637, 589, 549, 671, 593, 600, 644, 565, 646, 691

**Comment by anazariz** [comment]
@anthonycpichardo  we need to test this please.

**Comment by anthonycpichardo** [comment]
@anazariz sure I'll put it in my queue

**Comment by anthonycpichardo** [comment]
This looks good! Closing this @anazariz

**Comment by lzim** [comment]
@anazariz and @anthonycpichardo 

- Where is the information related to large HCS providing 1 year of data made available to our learners in the field?
- How are we sure the list of 13 facilities is exhaustive of all those that will not load without this adjustment?

**Comment by anthonycpichardo** [comment]
>>Where is the information related to large HCS providing 1 year of data made available to our learners in the field?
@lzim Not sure what you mean by this. Are you asking how we're telling our learners that large sites will only have 1 year of data?
>>How are we sure the list of 13 facilities is exhaustive of all those that will not load without this adjustment?
The list above is from sites that wouldn't load when I was manually checking each one on the splashpage. It is in addition to the sites that we've already marked as too large. To guarantee that this is an error that is caught ahead of time we would need to implement some logic that checks file size.

**Comment by anthonycpichardo** [comment]
March prop is complete. Next steps will be to verify that each of the above sites is able to load properly then this will be ready to close.

**Comment by anthonycpichardo** [comment]
- [ ] 659, 
- [ ] 534, 
- [ ] 516, 
- [ ] 637, 
- [ ] 589, 
- [ ] 549, 
- [ ] 671, 
- [ ] 593, 
- [ ] 600, 
- [ ] 644, 
- [ ] 565, 
- [ ] 646,  
- [ ] 691

**Comment by lzim** [comment]
@anthonycpichardo 

These notes were comments are about your responsibility as our _Analyst/Technical Writer_ to make sure all the **mtl.how/documents** dependencies for this are reflected in the respective _MTL Resources_ Let me know if you have any other questions 🤔 
> Where is the information related to large HCS providing 1 year of data made available to our learners in the field?

Right. This needs to be documented for **learners** and **facilitators** - @staceypark, @branscombj or @dlkibbe can likely review these pull-requests:
- **learner** (Cross-ref & re-open: #509, #1012) 
- **facilitator** (Cross-ref & re-open: #950, #674)
---
> How are we sure the list of 13 facilities is exhaustive of all those that will not load without this adjustment?

**team** (Cross-ref: #626) - This is already on your plate to finish. @anazariz May be able to review this **document_team** how to procedure.

_Other Dependencies:_
@lijenn and @staceypark Can you clarify where the list of _"future video edits"_ are for the **depend_products** column (Cross-ref: #556, but have to wait for a new video release).
- It would be great to have a card there in the column for all of these.

Thanks!

**Comment by anthonycpichardo** [comment]
@lzim 
We updated the list of sites that should use 1 year of data because of their file size and the limitations on sharepoint. Unfortunately, **1 year of data was still large for facility 589.**

I need guidance on how we want to handle exceptions like this, do we want to continue to decrease by 1 month, 2 months, or 6 months until the file is less than 50 mbs?

I mentioned this to @branscombj during the wg leads meeting and she will help craft the language for the learner and facilitator guides when we make a decision.

I will create a new feature to introduce logic that will check file size based on record count and reduce the time span of the data set if needed.

**Comment by lzim** [comment]
@anthonycpichardo  and @branscombj 

Thanks! I’m thinking that in general, rather than have incremental 1 month reductions, we should:
 
- a) **standardize** it to something like 6 months, 12 months, 18 months and 24 months based on size.
- b) provide instruction on **opening in Excel** - that was the old instruction, is that still the case? Or, are we simply making it a size that fits on the BISL site and no Excel at all.

**Comment by anthonycpichardo** [comment]
> * b) provide instruction on **opening in Excel** - that was the old instruction, is that still the case? Or, are we simply making it a size that fits on the BISL site and no Excel at all?

@lzim  This is the case currently. For example, 589 still has the option to "Open in Excel". The implementation you've described in A, would not have an Excel download by default but it could. 

Would you like that as an option? 

If we wanted to have an "Open in Excel" option for the full 2 years we would need to generate two separate spreadsheets for these corner cases. One that gets displayed and one that is available for "Opening in Excel".

We can define this feature further on #1372.

I've pulled the relevant info over and I think this card is ready to close.

**Comment by lzim** [comment]
Cool, thanks @anthonycpichardo I’ll close for us to handle this on #1372
