### ISSUE TITLE
wk2 MTL Data - Request New Team Folder Issues

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1225]
After submitting a request to create a new team folder:

1. I lose privileges to the PTSD OMHO Team Folder Administrators.
2. My request automatically goes into "in progress" instead of "not started".

FYI: @staceypark @ritahitching @anazariz

**Comment by anthonycpichardo** [comment]
huh, interesting. I think I'll need you at some point next week to recreate this scenario.

**Comment by lzim** [comment]
@anthonycpichardo I've edited the title to reflect **wave1_teams**

**Comment by staceypark** [comment]
@anthonycpichardo @anazariz 
FYI @lzim 

@lijenn and I did some testing and:
### It seems neither the "Request New Team Folder" nor the "Request Team Membership Change" buttons work if you don't already have some set of permissions to the SharePoint site.

#### Because Jenn was having a weird bug that's mentioned in the original comment of this post, here's what we tried:
1. Test: Jenn with only Site Owner permissions:
- Can see the request team folder dialogue.
- Loses admin permissions once she submits the request.

2. Jenn with only Team Folder Admin permissions:
- Cannot see the request team folder dialogue. Instead when she clicks on that button, she gets redirected to a list of all current team folders.
- Loses admin permissions once she submits the request.

3. Jenn with permissions to both:
- Can see the request team folder dialogue.
- Loses admin permissions once she submits the request.

4. Jenn with permissions to neither:
- Cannot see the request team folder dialogue (nor the request team membership change). She sees the buttons but once she clicks on them, she gets a "Sorry you don't have access to this page" block.
- I asked Ella K. to also try and she gets the same block to both buttons.

#### Other things I checked:
- Looked at all the previous open/completed requests to see who was the requester - It is a mix of folks who have owner/admin privileges but also clinicians we worked with during the R21. 
  - Based on this, I considered if anyone with any level of permissions to the site would not be blocked. Since Jenn does not have any permissions to individual folders, I tried adding her to one, but this did not change her ability to access these request team folder buttons.

#### Current hypothesis: Separate from Jenn having weird permissions disappearing issues, I think based on the fact that previously R21 clinicians have been able to use these buttons and submit requests, the problem must be a more recent one.

**Comment by lijenn** [comment]
@anazariz @anthonycpichardo 
fyi: @staceypark 

Here is the error message I get when going to Request New Team Folder and/or Request Team Membership Change tabs:
![](https://user-images.githubusercontent.com/59668647/96193591-4e69bf80-0efd-11eb-840a-0da0af9c6c59.png)

**Comment by staceypark** [comment]
Update - 
@anthonycpichardo and I did some more testing.
- We can change it so that "Everyone" has "Contribute" permissions to the "Request New Team Folder" and "Request Team Membership".
- This should not change any access (increase or decrease) for the rest of the site, based on our testing. We also checked if "Everyone" meant "everyone" with some level of permissions already for PTSD_OMHO or actually "Everyone". 
- We removed Jenn from any individual team folders and from any admin access to test the above bullet and it still worked, so seems like we should be fine if we do this.

**Unresolved question:** This still doesn't explain how some clinicians were previously able to submit requests with these buttons. Perhaps SharePoint changed their permissions rules since then.
- As such, for now, we've changed it back so that "Everyone" does not have "Contribute" permissions for these buttons right now. But its a quick change to revert it if you give us the green light @lzim

**Comment by lzim** [comment]
Not to start with something obvious, but did y'all double-check the "standard work" files created by Elizabeth May that are in the administrative files of the site? 

Re-reading @staceypark's post, I'm wondering if we always had to grant them permissions to the BISL site first, and then they can request a folder...It's just a scenario that we may not have considered for the newer "_Modeling to Learn_ for all" approach on TMS.

I am fine taking your recommendation's @staceypark and @anthonycpichardo based on your testing, but please do double-check that "standard work" documentation created by Liz May when she set up the BISL site carefully first.
 
Thanks!

**Comment by staceypark** [comment]
@lzim @anthonycpichardo 
Ok I've checked all the videos and documents we have including the Standard Work items in that Administrative section. None of them give us instructions on permissioning for these two buttons. The Standard Work permissions refer only to the permissions folks get for their folders. Based on our testing yesterday, those permissions are unrelated to the permissions for these buttons.

It seems like we will need to give "Everyone" permissions to "Contribute" for just these two buttons specifically then. And this should work for the "_Modeling to Learn_" for all approach.

I think this was a good reminder for us also to make sure to test everything with different types of permissions. Most of our use of those buttons have been from us (everyone who has admin privileges on the SharePoint), so we wouldn't have caught this until far later if it weren't for Jenn's permissions bug.

**Comment by anthonycpichardo** [comment]
@staceypark @lijenn 

How do we want to handle Jenn's permissions bug? You may need to reach out to support @lijenn

**Comment by staceypark** [comment]
@anthonycpichardo Like SharePoint support? Do you have an email for them

> @staceypark @lijenn
> 
> How do we want to handle Jenn's permissions bug? You may need to reach out to support @lijenn

**Comment by lzim** [comment]
We briefly discussed this at **workgroup_leads** this AM @staceypark @anthonycpichardo and @lijenn 

So...to access this is there any issue with "Everyone" having "Contribution" permissions to request their folders?

FYI: @anazariz

**Comment by staceypark** [comment]
As far as @anthonycpichardo and I can tell, no there shouldn't be any issue.

> We briefly discussed this at **workgroup_leads** this AM @staceypark @anthonycpichardo and @lijenn
> 
> So...to access this is there any issue with "Everyone" having "Contribution" permissions to request their folders?
> 
> FYI: @anazariz

**Comment by anthonycpichardo** [comment]
Closing this issue and creating a new one for @lijenn's permission issue. #1539

**Comment by hnorthcraft** [comment]
#adjudicate_memo update vs
