### ISSUE TITLE
Review code change in Data Tool

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1226]
Review the changes to the data tool regarding where the file is saved. 

See email for more details.

**Comment by anazariz** [comment]
@anthonycpichardo , I tested the code segment (please see the test excel file in the same folder). The code segment works as expected.  It saves the XL file to the same level directory with "data_table' in its name. Otherwise saves it to the current directory. 
An issue may arise if there are two 'data_table' folders. But the possibility of that happening may be negligible.

**Comment by anthonycpichardo** [comment]
thanks @anazariz ! will push the changes to the master now.

**Comment by anthonycpichardo** [comment]
Review completed closing this issue
