### ISSUE TITLE
Due Ongoing Update to tt_template to include ZenHub Reporting

### ISSUE THREAD

**Issue by ritahitching** [lzim/teampsd#1228]
**Updates to tt_template to include ZenHub Reporting** 

1. Include updates on the relevant epic via ZenHub Reporting  on weekly tt_report
2. Update template going forward [here](https://github.com/lzim/teampsd/blob/master/resources/training_guides/emails_outlook/tt_teampsd.md)
Changes in new branch rita_2020_03_23_tt_template 
3. Objective to to augment #hqhuddles and workgroup leads meetings and facilitate awareness of where we are on the priority epic - include reporting on burndown charts how fast we are closing issues and story points left.
4. Mock-up example for review All Hands March 24

@anthonycpichardo lets catch up after our HQ meeting

**Comment by ritahitching** [comment]
Thanks @staceypark for your suggestions
Add ZenHub reporting charts to tt_report - include burndown visual charts how fast we are closing issues and story points left.

**Comment by ritahitching** [comment]
@lzim 
I created a draft tt_report with new ZenHub reporting, it is ready for you to review in our shared folder.
@staceypark 
I created a new branch and updated the tt_report template . I'll make a pull request once we finalize the choice of reports
thanks!

**Comment by ritahitching** [comment]
@staceypark 
Proposed new tt_report template  
[tt_report_new_template_zenhub.docx](https://github.com/lzim/teampsd/files/4395412/tt_report_new_template_zenhub.docx)

**Comment by lijenn** [comment]
@ritahitching I just sent you potential updates/reminders that could be added to the tt report. Please check your messages on Teams!

**Comment by staceypark** [comment]
@ritahitching the top blue box needs a header, like Announcements or something.

It seems weird that we would give the GitHub report and the ZenHub burndown in opposite places of the report. I think they should be grouped together. In your burndown report screenshot, please include the epic name.

I don't think the control chart is necessary. I'm fine with just the burndown report.

**Comment by ritahitching** [comment]
@staceypark I updated the GitHub tt_report template to reflect the changes agreed on today. I will make a pull request on the branch rita_2020_03_23_tt_template. I will close this issue once the pull request is accepted. thanks

**Comment by ritahitching** [comment]
@staceypark I'm closing this issue as the template request has been merged to master.
thanks,

**Comment by lzim** [comment]
Re-opening to address how this **tt_teampsd** template was edited and closed, but then I found the issues below in @ritahitching emails deviating from the “official” template finalized the prior week.

_Need to make sure the template and the actual tt emails are consistent & can be followed consistently by anyone - **without so much reliance on my review to ensure consistency.**_

- [ ] Did not use the tt_062 subject line I typed in to our hq_huddle chat in Teams: “HSRD Rapid Response for COVID-19 MTL Adaptations"

- [ ] HSRD COVID-19 announcement isn’t in the top announcement section (it’s in the priority epic section). Please put it at the top of the other two announcements about team_temp and use of Teams.

- [ ] announcement doesn’t italicize MTL as is always the style we use, this is the I put in my Teams test: “We are submitting an HSRD Rapid Response proposal on Monday to make COVID-19 adaptations to Modeling to Learn.”

- [ ] Please keep the language from the template in the priority epic reports section, but say:  “april” priority epic is underway and ends 4/24.

- [ ] Priority Epic Section – Both the Burndown and the Velocity reports look inaccurate. Let’s get to the bottom of this ASAP before sending & at the top of the Monday Workgroup Leads Meeting.

- [ ] Lucid – Let’s see why there are two 3PM Support Workgroup meetings before we send this out.

- [ ] Last week for the template that I edited I described in Teams keeping the manuscripts_tracker to just first 05_approve_letter columns, which will continue to make it readable. 

- [ ] the change from last week’s template for the feature_tracker adds to many columns to be readable, let’s use the template I edited last week, which went through functional_testing (Bugs, & Documents look good! 😊).

Goal resolve the checklist above _and_ determine how **tt_062** and **tt_teampsd** template are insufficient to resolve these problems, so that @lzim is not required to get this single key Team PSD weekly communication standardized, correct & clear.

https://github.com/lzim/teampsd/blob/master/resources/training_guides/emails_outlook/tt_teampsd.md

**Comment by ritahitching** [comment]
**from @ritahitching** 
I replaced the subject field to reflect the exact working on MS Teams
**from @lzim** 
> * [ ]  Did not use the tt_062 subject line I typed in to our hq_huddle chat in Teams: “HSRD Rapid Response for COVID-19 MTL Adaptations"

____________________________________________________________________________________
**from @ritahitching** 
I moved the announcement to the tip announcement section. I updated the tt_report template on GitHub to reflect this change, including the emphasis on italicizing  _MTL_ or _Modeling to Learn_
**from @lzim** 
> * [ ]  HSRD COVID-19 announcement isn’t in the top announcement section (it’s in the priority epic section). Please put it at the top of the other two announcements about team_temp and use of Teams.
> * [ ]  announcement doesn’t italicize MTL as is always the style we use, this is the I put in my Teams test: “We are submitting an HSRD Rapid Response proposal on Monday to make COVID-19 adaptations to Modeling to Learn.”

____________________________________________________________________________________
**from @ritahitching** 
I replaced the subject field to reflect the exact working on MS Teams
**from @lzim** 
> * [ ]  Please keep the language from the template in the priority epic reports section, but say:  “april” priority epic is underway and ends 4/24.

____________________________________________________________________________________
**from @ritahitching** 
I too thought the burndown reports looked strange due to new epic - check at HQ meeting 4/2 Thursday with Stacey and team - I was told to keep the reports as they were. I've re-updated to reflect burndown reports up to today's date.
**from @lzim** 
> * [ ]  Priority Epic Section – Both the Burndown and the Velocity reports look inaccurate. Let’s get to the bottom of this ASAP before sending & at the top of the Monday Workgroup Leads Meeting.

____________________________________________________________________________________
**from @ritahitching** 
Regarding Lucid: I check with Anthony and he said _**"There's a double 3pm this week for some reason. for all intents, both seem to be part of the series of Support WG meetings and looks exactly the same. I think it's just a Lucid blip. I would caution deleting one or the other, inc case we lose stuff and rather reach out to Lucid instead.**_" 
**from @lzim** 
> * [ ]  Lucid – Let’s see why there are two 3PM Support Workgroup meetings before we send this out.

____________________________________________________________________________________
**from @ritahitching** 
I updated the tt_report template on Github to add more specificity of the number of columns for each screen shots to have 5 columns (to increase visibility take screenshots in full-screen mode).
1. Features tracker - work_breakdown to functional_testing.
2. Manuscript tracker - 01_OSF_project to approval_letter.
3. Documents tracker - describe_learners to dependent_products.

**from @lzim** 
> * [ ]  Last week for the template that I edited I described in Teams keeping the manuscripts_tracker to just first 05_approve_letter columns, which will continue to make it readable.
> * [ ]  the change from last week’s template for the feature_tracker adds to many columns to be readable, let’s use the template I edited last week, which went through functional_testing (Bugs, & Documents look good! 😊).

**Comment by ritahitching** [comment]
@staceypark please merge pull request to add more specs to the tt_report regarding fonts etc #1283.
I hope you feel better soon 👍

**Comment by ritahitching** [comment]
I'm closing this issue as updates have been made to the tt_template and pull request merged.

**Comment by ritahitching** [comment]
- [ ] Updated tt_report template to reflect changes to the Burndown & Control charts
- [ ] Branch:  rita_2020_04_10_tt_template
- [ ] Pull request issue #1326

**Comment by ritahitching** [comment]
Pull request made. Close issue.
