### ISSUE TITLE
5/29: Timestamp & Link to section for Tutor function

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1234]
Would it be possible to have the video link be timestamped to the relevant section of the video that the user is asking about?

Also have the guides be linked to the relevant section for their question?

**Comment by lijenn** [comment]
I believe the See guides and TMS Videos have been linked in Tutor. We could not do timestamp because that feature isn't available in TMS. 

We thought about uploading the MTL Videos to YouTube to get timestamps, but previous documentation #1041 indicated that all the videos would require a significant amount of editing for it to be compliant with Public Affairs. 

Since our SIM UI and Data UI are now out-of-date with the TMS videos, I think we should close this and focus on bigger fish to fry.
