### ISSUE TITLE
NIH-NIDA and COVID-19

### ISSUE THREAD

**Issue by branscombj** [lzim/teampsd#1243]
**[NIH FAQ Page C. Salary/Stipend Costs](https://grants.nih.gov/faqs#/covid-19.htm?anchor=question55769**)

**1. Can a recipient continue to pay personnel costs under awards in the event of an emergency?**
Charging salaries to NIH grants when no work is being performed is allowable if your organization’s policy allows for the charging of salaries and benefits to currently active awards (under unexpected or extraordinary circumstances) from all funding sources, Federal and non-Federal. If you have such a policy, and anticipate a need to charge personnel costs, please notify the funding IC. NIH may request documentation to confirm the requirements of the institutional policy.

**5. Can grant recipients shift NIH grant money from one ongoing grant project to a different, COVID-19 related grant project?**

No, grant funds allocated for a specific NIH grant may not be transferred to another grant project. General cost principles related to allocability of funds still apply to NIH grants.
Grant recipients interested in applying for COVID-19 related research projects can find Funding Opportunity Announcements for competitive supplements and new awards in the NIH Guide and on our COVID-19 page.  

**[From COVID-19 page](https://grants.nih.gov/grants/natural_disasters/corona-virus.htm)**

PA-18-935 Urgent Competitive Revision to Existing NIH Grants and Cooperative Agreements (Urgent Supplement - Clinical Trial Optional) is intended to provide funds for NIH grantees applying to expand the scope of their active grant.

**Which includes these things that seem in our wheelhouse:**
•	Research to understand _system- or organizational-level responses to identify, prevent, or mitigate the impact of COVID-19 in service settings that serve vulnerable populations,_ including people who are homeless or unstably housed.
•	Research on _how potential overcrowding of_ emergency departments and _health services will impact the treatment of opioid overdoses and of opioid use disorder_
•	Research _using ongoing studies to understand the broad impacts of COVID-19_ (e.g., school closures, food insecurity, anxiety, social isolation, family loss) on neurodevelopment, substance use, substance use disorders, and _access to addiction treatment._
@lzim @staceypark @TomRust @dlkibbe @dlounsbu @lijenn

**Comment by dlkibbe** [comment]
With regard to the notes in team-temp report from 3/16 pm and the FAQ #8 from NIH info page: Notes: "A question was raised about whether NIH would continue to support faculty salaries if faculty activities are shifted to COVID19 testing. NIH will have to look in to that situation to find the best way to handle it and will report back."
@lzim is it worth an "ask" to the project officer relative to the question if "staff time" could be considered an "existing resource" that is being diverted due to COVID-19? That is, if NIH would consider including FTE time under donated items to support COVID-patient care specific to veterans?
**FAQ 8. Under which circumstances will NIH provide administrative supplements?** NIH funding ICs will consider administrative supplements to support existing resources that were diverted due to COVID-19, where the faculty member may have donated personal protective equipment, lab equipment, lab supplies, or travel costs to **_support COVID-patient care_**, etc.

**Comment by lzim** [comment]
@branscombj and @dlkibbe 

Happy Friday 🎉 

Thanks for great work on review the guidance. I am in communication with NIDA about an administrative supplement that addresses unexpected/unforeseen events within existing scope.
