### ISSUE TITLE
ICEBOX MTL Facilitate EES Project 

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1258]
Work with EES for virtual training of new facilitators

**Comment by lijenn** [comment]
from WG Leads meeting on 4/11:

This is being pushed to next epic, but we need to have a plan for when we are ready to discuss this with EES.

Lindsey pointed out that we may be needing to train more co-facs sooner than later if we are ready to roll with teams before QIICs are free from unexpected COVID burden.

**Comment by lzim** [comment]
@lijenn 

Let's try to flesh out the requirements for this in the top of the issue.

**Comment by branscombj** [comment]
> Work with EES for virtual training of new facilitators

**I see this as two projects:** 
1. Finalize a standard training program for *MTL* Facilitate (by which I mean the curriculum itself; but also the additional pieces below)
2. Work with EES to get the program accredited for CEU (whether as a complete course or more likely by components)

**Additional parts to 1. Curriculum**
-    Eligibility - What are the requirements for becoming a *MTL* co-fac?
-    Certification - Is completion of *MTL* Facilitate sufficient for serving as a co-fac, or if not, are there requirements for initially becoming one, or for continuing as one?
-    Expectations - Are there expectations beyond the learning and practice of *MTL* Facilitate that would-be co-facs should be aware of? E.g. facilitating at least x teams; participating in in-service training on updates and versions; maintaining certain standards of practice?

**1. *MTL* Facilitate Curriculum (straw draft - what I think we did)**
**a.** Participate in a complete *MTL* Live Blue (or *MTL* Video) 12-session series as a learner.
**b.** Co-facilitate 2 mock teams (using 2 modules) in *MTL* Live with other Facilitate learners. Each candidate participates in all sessions as either a co-fac or a learner, co-facilitating at least x sessions. TeamPSD may substitute some specific sessions (e.g. Team 2, S01) for focused training in *MTL* resources (e.g. Data UI, SimUI, or different modules in the Sim)
**c.** Participate in pre-session planning and post-session debriefs for all mock sessions serving as a co-facilitator; and sessions when serving as a learner.
**d.** Participate in co-facilitator Group Supervision sessions throughout the practice facilitation of *MTL* Live.

**2. EES accreditation for *MTL* Facilitate - by above components**
**a.** For this part, learners get credit as anyone else for participating in *MTL* Live or Video.
**b/c.** EES partners can advise us on what getting this accredited looks like. The sessions would be 2 hours each and have a fixed, redundant agenda (pre-session checklist; session run-through; post-session checklist); but since their roles are different from that of learners, this might need to be accredited as a different type of session.
**d.** It might be most efficient for everyone involved for all the rest of *MTL* Facilitate after step (a) -- i.e. practice facilitation including pre-/post- and group supervision -- to be accredited as a multi-part activity. I would want EES advisement on this as well.

**Additional parts to 2. EES accreditation**
- Need a Planning Team that includes people from all the disciplines involved.
- Need to write up separately for any unit to stand as an activity in TMS the stuff that goes in the brochure: Title; Purpose; Need; Disciplines; Presenters; Agenda; Dates; materials.
- 508 Review

**Comment by lzim** [comment]
@branscombj Thanks for documenting your understanding of what we already clarified with Fawn & EES 

@staceypark Will you please put what Jane added at the top of the issue and turn whatever needs to be in checklist form, into a checklist to be completed?

- We also need to add a VERIFY DATE in the Title for when we will review this in May.

Thanks!

**Comment by lijenn** [comment]
8AM WG Leads 8/10:
- Move to icebox as we need to pick back MTL with the field in September.
- Kelly M. had 2-3 mentors that could participate in becoming co-facilitators.

**Comment by lzim** [comment]
#adjudicate_memo
_MTL Facilitate_ was replaced by _MTL Consults_ over 2023 per request by OMHSP to pivot the strategy for support to the field and sites.

All learning roles are self-help or consults as of #2024_mar_epic and in the pending release of _MTL 3.7_ on this roadmap.
