### ISSUE TITLE
How to compare Results to Team Data Table

### ISSUE THREAD

**Issue by branscombj** [lzim/teampsd#126]
When I minimize the Expanded Outputs tile (Chrome), I can't see anything except the first 3 text boxes. I cannot resize the minimized screen or scroll down in it to compare results with the team data table. Since it's also not possible to have the Outputs and Experiments tiles open at the same time, the only things I can compare are the numbers in the diagram with the output charts in the Outputs window.

**Comment by lzim** [comment]
@branscombj 

Thanks for asking about this.

What you should be able to see in the minimized Expanded Outputs are the Q/H/F/D boxes for text - but not output charts. I can move mine anywhere on screen including nearly out of windows in Safari.

1. I can move the Q/H/F/D boxes to the right to view the main tile model diagram and it's values, which was a key feature we wanted, so that folks can type their text while reviewing the "systems story" in the main tile.

and

2. I can move the Q/H/F/D box to the left and have the Experiments Tile open at the same time to view the team data table, and adjust sliders in the experiments tile according to what we drafted in the Q/H/F/D text boxes.

I think it's true what you say, we don't have a way to view numbers in the output charts against the numbers in the main tile at the same time.  Instead, we have the ability to compare experiments against the base case in the expanded outputs results dashboard.

Is this getting at what you've noticed?

Thanks for the question!

Lindsey

@TomRust @jamesmrollins @staceypark @TomRust @dlounsbu @dlkibbe
