### ISSUE TITLE
1/6 support wg: SOP and Rules Definition for mtl.help & mtl.info inbox

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1329]
Stacey will be lead  provide feedback and Define SOP for how we define the

a) inbound rules

b) outbound rules

c) We will ALL have full team visibility on email inbox/outbox team sub-folders, but use of Outlook Rules Wizard provides no additional reporting functions as a back-stop against slow responses, missed responses, teams that are particularly active etc. cross-ref #1299 #1023

**Comment by lijenn** [comment]
8AM WG Leads 8/10:
- We can develop a MVP prototype of the documentation just so we can have something to work off of, but we should keep in mind and check in with CRM dependencies when changes are needed.

**Comment by staceypark** [comment]
See #1585 for key functions we need from the inboxes.
Instead of a dashboard, facilitators and admin will need to interact with incoming directly from the mtl.help and mtl.info inbox folders. Each team will probably need to be a subfolder in the inbox.

@anazariz take a look at the documents related to #1585 and help us think about how this would be implemented in your prototype.

**Comment by lijenn** [comment]
Discuss at Support WG 12/16:
- Can @anazariz help create a flow map for the current process (some notes in #1299) to go over on 12/16
- Will need a new task card for documentation/SOP in early Jan

**Comment by anthonycpichardo** [comment]
is this ready for review @anazariz

**Comment by anthonycpichardo** [comment]
@staceypark @lijenn Flow map has been updated.

Please review and close this issue if there are no outstanding questions

**Comment by lijenn** [comment]
Ah, thanks @anthonycpichardo. We had previously planned to review this at the Support WG meeting this Wed.
I'll add this to the agenda.
