### ISSUE TITLE
wk2 mar_epic: R01 Baseline Edits/Create short links to all projects on VA RedCap

### ISSUE THREAD

**Issue by ritahitching** [lzim/teampsd#1353]
**Create and Update short links to all projects on VA RedCap** 
Note: MTL Menu's short link needs to link to VA, not Stanford.
Cross ref #483

**Comment by ritahitching** [comment]
@lijenn this is issue is blocked by the #1192 and the MVP process.
If you read the thread you will find details of the links that need to be created.
I recommend we keep this issue open.

**Comment by lijenn** [comment]
@lijenn Split and re-scope into cards that can be done a week at a time based on team time meetings.
Bring wk1-4 cards that are scoped.

**Comment by lzim** [comment]
@lijenn 

Can you please bring the information from our **Friday huddle** into this card so that @staceypark sees what I proposed would be the short-links for these?

Thanks!

**Comment by lzim** [comment]
- [ ] **Aim 2 - Provider Surveys - 4 VERSIONS** 
- One baseline survey for all NIH teams; One 6-month survey all NIH teams.
- One baseline survey for all VA teams; One 6-month survey all VA teams.

**Need: We need to close surveys after they are open for 30-days at baseline or 30 days at 6-months.**
- [ ] Decision: Use 4 quick links. 
- [ ] We use **team drop down selection to "close" the survey** when it's been open for 30 days.

DROP DOWN - Need Two Columns
- [ ] **Team** Align our **Aim 2 team_intervention** level to the survey - Team name: "v15_657_st_louis_john_cochran_mhc"
- [ ] **sta6a** Align our **Aim 1 observation level** to the right patients
- [ ] We do want to capture variation in a team that is **cross-cutting sta6as**:
e.g., TMH VAMC cross-cutting (meaning it serves more sta6a than 1).
Teams may vary when they are all at one sta6a verseus when sta6a is synonymous w/team (e.g., stc 640ha)
- [ ] **Aligning Aim 1 and 2**: We need to carefully consider what happens when a team services multiple sta6a in Aim 1 (e.g., 640 included PCT & TMH).

**LZ Possible Solution to align Aim 1 and Aim analyses by team (not just sta6a) for intervention-level:**
- [ ] **Use their VISTA clinic selections used for Team Data**: _MTL Red Part 2_ or _MTL Blue Session 3_ 

SURVEY USER INTERFACE
- [ ] VISN > Facility > sta6a - Drop-down sta6a teams need the "name" not alphanumeric

**Comment by staceypark** [comment]
Since we were not able to use the 11am quant research meeting for this today, I'll try my best to outline concerns here: 

@lzim 
We're realizing that the "drill down" portion of the survey cannot be voluntary if we are to "close off" the survey after 30 days _and_ be able to ensure everyone outside of that 30 day window cannot take the survey.

In the structure we described above, 
- everyone gets the same link by trial and baseline vs. 6 mos
- they drill down to their team
- at this point either they go to their team specific survey OR they are told the survey is now closed.

@lijenn and I are also thinking that we need more granularity in the survey links or else the backend for the drilldown will quickly become very unwieldly and prone to error:

For example, let's take our NIH Baseline and say it has 20 facilities.
The survey front end for the drilldown will look like 4 simple fields (visn, facility, sta6a, and team), but in the backend we would have:

1. 1 drilldown instrument with:
- 1 field asking visn (let's say there's 10 visns across the 20 facilities)
- 10 fields asking facility based on visn picked above (let's say there's 2 facilities per visn)
- 20 fields asking which sta6a(s) based on facility picked above
- 20 fields asking which team based on facility picked above (lets say 5 facilities have 2 teams, 15 facilities have one team)

2. 25 instruments each with the 50+ items we defined in our measures.

_In this example, we end up with 26 instruments, where the "drill down" portion has 51 fields that need to conditionally branch to show the correct next set of options and 25 instruments that need to be conditionally linked to based on the response from the drilldown instrument._ This may be easiest to explain/visualize if we can sharescreens and walk through it.

@dkngenda here's a sample of what the data export would look like right now.
[TestR01Measures_DATA_LABELS_2021-02-24_1346.xlsx](https://github.com/lzim/teampsd/files/6039086/TestR01Measures_DATA_LABELS_2021-02-24_1346.xlsx)

**Comment by staceypark** [comment]
VISN > List of Facilities > List of Teams > Routed to that teams survey (there isn't team-specific survey content).

#1. We need it by Red vs. Blue (CRT). We need this information, but don't have to ask because we can get it from Team Name. #1 Red and Blue & NIH or VA.
#2. But, we do need their data by teams. - Mandatory sta6a AND team name, captured as two separate items.
#3. And, we need it by time (baseline vs. 6-month). - We don't have to close the survey. We just need to know when it was completed and define their baseline/6 mos dates for each team. If they're outside the window, we exclude the data for time measurement.


Remaining question on #1/2: Each group of surveyees will at most consist of 15 teams (based on the gantt chart), which shouldnt be too long of a dropdown. Based on the team they pick, we can show a different set of sta6a so they don't have to pick from all 15 facilities' sta6a.

For the sta6a, I think if we include both the 5 digit code and the actual name in the answer choices, we won't need a separate excel/crosswalk attached to that question for folks to identify their sta6a.
