### ISSUE TITLE
wk4: lzim/mtl Repo Design 

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1422]
**Hypotheses:**
Purpose:
The purpose of this repo is to aid facilitators, learners and community researchers to find information about  Modeling to Learn. The repo also provides actions that automate time-consuming editing tasks such as find and replace, style and language standardization.  

**Task:** 
We want to redesign the repo to be better suited to it's purpose, while also thinking about other use cases or dependencies based off of other repositories like lzim/teampsd & the proposed SIM UI repo (#1430)

MVP Flowmap: **lzim/teampsd prototype flow map by @jamesmrollins**
https://app.lucidchart.com/documents/edit/a3dc1b14-af8e-40d6-8a67-712fcf4e05fd/0_0

User feedback audience: Facilitate Workgroup (@branscombj & @dlkibbe)

**Comment by lijenn** [comment]
**From Discuss Repository Design and Workflow Proposals Call on 7/13:**

**- Regarding Folder Structure :**
1. Do the learners need to have a need to see the standard folders (fonts, images, .github, etc.)?
2. The standard folders don't contribute to learning.
3. There is a lot of visual clutter - when a busy learner navigates to the page, they may be put off.
4. Can we put the "utilities" under a single folder?
5. Can we get an exception to standard folders for this repository?
6. Accessing the resources for MTL is the primary purpose of this repository. Unnecessarily complicating the directory structure goes counter to that purpose.

Is there a higher guidance of principles rather than the purpose of the repo? 
What is the trade off between needs of standardization vs needs of the repository?

**- Suggestions/feedback:** 
1. Recommendation to leave the Folder Structure of lzim/mtl as is.
 Folders and files related to Models/Refactoring could be done via webhooks and/or through a separate SIM UI Repository.
2. Refactoring: find_n_replace action would be very useful at removing a pain-point that the facilitate designers currently suffer.
3. Orienting to folders and where you arrive when you first get on GitHub as a Learner: 
Update .README's to better orient what folks are seeing (e.g .README would describe where you are at and what the folders are for when you go to https://mtl.how/blue)

**Comment by lzim** [comment]
Thanks for posting these comments @lijenn 

I think that posting this feedback early and often is critical 😺, because I see that there were a number of **assumptions that could pull us out-of-sync with our Team PSD CI workflow user pain points for lzim/mtl**

Here is my **asynchronous PI user feedback for week 2 prototyping** - my guidance for next steps is also on Teams.

**Bottom Line:** The recommendations above focus too narrowly on learners and syncing with the Sim UI, and too little on the **true 80/20 painpoints for the necessary coverage of the CI build** on this repo, given:

a) **total set of resources** on the repo,
b) the **total users** of the repo (learners, facilitators, public, team members), and
c) the **specific Team PSD users** who need a rebooted **_Team PSD 2.0 Continuous Integration workflow_** to keep the MTL resources current with each other.
It is the later group (us! 🤣 ) that our **july_epic is designing to serve**. Keep that in mind for all that follows and you'll see support from some proposals, but also a **_wider_ empathic view of all users of lzim/mtl that requires a CI workflow.**

**Assumption/Hypothesis 1: "lzim/mtl repo's Purpose" is for learners.**
- Agree that the _primary purpose_ is learners. But - this is **_key_**: the **_primary Team PSD 2.0 Continuous Integration (CI) workflow to support those users' needs that we're trying to solve is OUR "limited scale" NEEDS as Team PSD users_** who update the resources on that repo by hand.
- However, learners are not the sole users of https://mtl.how, it is also our _primary_ public-facing resource in general (i.e., not just for learners).
- Therefore, keeping the a) _secondary_ "public" users' needs in mind, only secondary to our a) primary "learner" users' needs will help to rule in/out appropriate next steps by synthesizing the primary and secondary users of the repo.
	- As you'll see in the list below, to meet the learner and public needs, we currently keep 11 types of resources on lzim/mtl (see the list a through k below). I've noted the file type.
		 
**Assumption/Hypothesis 2: "Repo Folder Structure"**
- Following from hypothesis 1, we do want to follow the necessary folder structure for **automating CI workflow tasks for anything learner or public-focused** that "lives" there.
- Therefore, the the key is finalizing the **standard repo and folder structure** necessary to **automate CI workflows related _MTL_ Live and _MTL_ Video** for _Modeling to Learn 2.0 (and the models), and _Modeling to Learn 1.7 (and the models)_  At a minimum, this workflow includes:
		
a. **Learner SEE guides** (file type: .md)
		b. **Learner resources,** e.g., "tt_reports" and "cheatsheets" (file types: .md and .pdf)
		c. **Facilitate SAY guides** (file type: .md)  
		d. **Facilitator Checklists** (file type: .md)
		e. the **README.md** repo home page (file type: .md) - see Lindsey's exemplar repo README.md from Mar 2020 (GH Issues #1192 & 1220).
		f. the **decision algorithm visual map on the README** for knowing which folders to access as a user (learner or public) and how to access them (file type: currently .pdf, may be connected to LucidCharts and repo folder README.md structure for real time syncing?)
		g. **_MTL Videos_** ("file" type: .url links)
		h. **_MTL 2.0 Vensim DSS models, ModelParameters.xlsx file, & documentation_** (file types: .mdl, .xlsx, TBD for model documentation).
		i. **_MTL 1.7 Vensim DSS models, ModelParameters.xlsx & & documentation_** (file types: .mdl, .xlsx, TBD for model documentation
		j. **_MTL "Community of Practice"_ - the GH Issues** on this issue are the FAQ knowledge base we are developing on GitHub, which is consistent with the "Community" Button of the Simulation UI.
		k. _**MTL Manual**_ - _the MTL Bookdown Manual on the pages branch to parallel the Team PSD manual at lzim/teampsd._
		 
	
	_Assumptions made in hypothesis 2 are that "refactoring" and "find_n_replace" funds between **models and guides and sim UI** as a primary use case, which **too narrowly** focuses on the work of syncing guides with models, rather than **syncing guides with themselves (e.g., a change to session 8 that needs to sync across four types of files on that repo: SEE guide, SAY guide, Checklist, etc.)**
	As a result of the too narrow focus, and the too narrow focus in hypothesis 1, the group proposed hypothesis 3 below._

 
**Assumption/Hypothesis 3: "have a separate repo for SIM UI" under the assumption that** "folders and files related to Models/Refactoring could be done via webhooks and/or through a separate SIM UI Repository.

- It's true that there may need to be a separate repository for the models <> Sim UI/Forio and that a separate repository that uses webhooks to sync with lzim/mtl may be enough for model <> guide synching. I support further evaluating this smaller need, **as long the focus on the larger 80/20 need to make sure MTL resources at lzim/mtl have the necessary "Continuous Integration Coverage" in to set up the GH Actions (automation)** to scale and be sustained by Team PSD.
- As is obvious be reviewing the hypothesis 3 in light of the results of **user-centered** results for hypothesis 1 and 2, **a separate Sim UI repository would not solve the 80/20 "painpoint" pareto rule on the lzim/mtl repo**, because it assumes that the changes would be coming from the proposed new Sim UI to the guides at lzim/mtl. 
- Therefore, **we still need to determine the folder structure necessary on lzim/mtl that DOES solve the VERY expensive (in terms of team time, and "not working top of license) needs on the lzim/mtl repository to meet learner and public user needs (see the list of current resoures/file types a-k above).**
	
	Thanks! Hopefully this **PI user feedback will keep the focus on the broader base of Team PSD user** needs (not MTL Learners), and make sure that the focus is on the **overall team's 80/20 pain points** The initial set of feedback didn't address the majority of the work currently done by hand on that repo, by a much larger number of Team PSD members, Jane, Debbie, Jenn, Stacey, Lindsey (and our incoming hires) 😅

**Comment by lzim** [comment]
@lijenn Where are we with this one?

**Comment by lijenn** [comment]
We'll be closing this by the end of the month as James has gotten the linter and GitHub actions in #1450 working. He is working on the documentation and moving the automated workflow to both lzim/mtl and #1436  lzim/teampsd. I will also clean up excess files lzim/teampsd repo.

This issue and #1436 are both on track to close as early next week or by week 4 of oct_epic, will edit in the due date.

**Comment by lijenn** [comment]
Closing as all automation/branches has been set up, just needs use-case testing which can be done via other tasks for the Team PSD Manual or MTL manual. 

No additional changes needed for the lzim/mtl repo design.
