### ISSUE TITLE
wk2: lzim/teampsd Repo Design

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1436]
**Hypothesis/Purpose Questions:** (see 1st comment below for proposals)
- How will the folder structure look like?
   - Manual Resources for guides will be moved into the GH-Pages branch due to #1192 TeamPSD Manual for Bookdown
   - Other resources will continue to live in the Resources folder where they make sense
   - Could use Jane's table from [here](https://github.com/lzim/teampsd/issues/1423#issuecomment-650594603) to brainstorm ideas for folder structure
- What from the list of standard environmental folders and variables do we want for this repo? All?
- What Actions/Apps do we need?
- Should we move workgroup specific files from lzim/teampsd to their respective repository to remove redundancy?
   - Will See/Say guides remain on both lzim/teampsd or move to lzim/mtl?
   - What about additional MTL resources like cheetsheets or MTL/SIM UI related files like model files?
- How would each workgroup store their files on this repo, if any? Should folder structure be workgroup specific? Standardized?

---------------------------------------------------------------------------
What environment variables and folder structure will we use?
**Proposed Environment Variables & Folders**
1. readme.md - will be main page you see on the repo explaining what the repo has and how they work
2. .gitignore - for temp files you want to ignore
3. license.md - outlines what can and cannot be done with our code (there are different license templates on GitHub that help you figure out what kind you want)
4. code-of-conduct.md - similar to what James created for the lzim/mtl repo CoC under wiki (outlines how interaction should be conducted i.e. no trolling etc.)
5. fonts folder - for teampsd look and feel
6. css folder - for teampsd colors
7. images folder- for teampsd logos
8. .yml config file - sets parameters and initial settings in environment for running an app
9. docs folder - explains how actions work?
10. tests folder - folder of test scripts within the scripts folder
11. scripts folder - tools
12. packages folder - multiple tools brought together (scripts build the package)
13. vignettes - as a subset nested under packages
14. .github folder - configure issue and pull request templates. have example of “good first issue”
15. .workflow folder - needed for GH actions 
16. secrets - encrypted environment variables using a libsodium sealed box to that it is encrypted before reaching GitHub - note for a repository secret, only the repository owner can create this
17. gh-pages branch - GH Actions for Bookdown Manuals 
18. api
19. web - probably only for mtl.how repo

**Comment by lijenn** [comment]
Working Draft lzim/teampsd Repo Folder Structure

Branches:
- Master: Up to date version of files live in this branch
- gh-pages: bookdown resources go here

Root Folders:
- readme.md - will be main page you see on the repo explaining what the repo has and how they work
- .gitignore - for temp files you want to ignore
- license.md - outlines what can and cannot be done with our code (there are different license templates on GitHub that help you figure out what kind you want)
- code-of-conduct.md - similar to what James created for the lzim/mtl repo CoC under wiki (outlines how interaction should be conducted i.e. no trolling etc.)
- fonts folder - for teampsd look and feel
- css folder - for teampsd colors
- images folder- for teampsd logos
- .yml config file - sets parameters and initial settings in environment for running an app
- docs folder - explains how actions work?
- tests folder - folder of test scripts within the scripts folder
- scripts folder - tools
- packages folder - multiple tools brought together (scripts build the package)
   - vignettes - as a subset nested under packages
- .github folder - configure issue and pull request templates. have example of “good first issue”
   - .workflow folder - needed for GH actions .yml files
- secrets - encrypted environment variables using a libsodium sealed box to that it is encrypted before reaching GitHub - note for a repository secret, only the repository owner can create this
- api
- web - probably only for mtl.how repo (should we also keep this for lzim/teampsd due to mtl.how/team website)
- Resources(?) - for Resources like team bios, headshots, etc. Or will these be better triaged within the fonts & images folder. Should these be moved to SIM UI as their main purpose was for the mtl.how/team website?

- Will Workgroups have folders? What is the purpose of having them stored on lzim/teampsd?

**Comment by staceypark** [comment]
@lijenn @staceypark are proposing the below.
@lzim @anthonycpichardo @branscombj @dlkibbe @dlounsbu @jamesmrollins 

### Hypotheses  
1. TeamPSD repo should focus on TeamPSD workflow and helping individual members understand how to work effectively
2. Easier to "google" in the Bookdown search function than to try to learn how the repo structure works. There will also be a chapter structure for those that want to follow that.

### Assumptions
1. Everything on lzim/teampsd is essentially a resource for all teampsd or a specific workgroup. All other stuff can be sent to other repos (see proposal below).
2. Learners won't randomly change branches on lzim/mtl so having works-in-progress items on other branches shouldn't be a problem (see proposal below for why this is relevant).
3. Not everyone will be updating or creating resources. Only those who are will need to learn how to do it. That process will use the pull request processes we already know how to do but with the end point being the gh-pages branch instead of the master.

### Proposal
Everything on lzim/teampsd repo will be in the Bookdown and whatever doesn't apply would be in a different repo.
1. Any quant code should be moved to one of the four quant repos.
2. Anything that's on the lzim/mtl repo already will not have a duplicate in the lzim/teampsd repo. Instead, we are proposing we have a "works-in-progress" branch on the lzim/mtl repo. Whenever we are ready for release, we would just merge that branch with the master.
3. We will have 2 main standing branches on the lzim/teampsd repo (apart from ones people are using to work on):
- master: Explains how to get to the bookdown link, what can be found there, and how to interact with it.
- gh-pages: Required by Bookdown for hosting all the Bookdown markdown files. the "backend" for the resources that will be on the Bookdown.

### Addresses persona feedback of...
- Confusing and complicated to work on SEE/SAY guides across two repos and multiple releases
- Hard to find resource for a specific need (how to use MS Teams) or for a specific workflow (how to be effective member of the qual workgroup)
- Reducing complexity of folder structure
- Resources are in multiple places
- Learning curve of understanding GitHub structure

### Next steps:
Deciding chapter organization within the Bookdown. See Jane's crosswalk on #1423.

**Comment by lzim** [comment]
@lijenn Where are we with TeamPSD repo design?

**Comment by lijenn** [comment]
Overall repo design is completed (i.e readme, automation, branches), automation just needs further testing which can be done via remaining Manual tasks.
