### ISSUE TITLE
7/16 + Task End to End Data Lineage STTM Prototype

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1439]
Problem Statement - What is the most effective way to show the end to end data flow?

Hypothesis:

As a user having an STTM that represents our data flow through a database accessible from R Studio and SSMS and on Github via XML would enable me to understand the data lineage and answer any question I may have about it's transformations.

Assumptions:

We need to be able to view transformations across mediums (R, SQL, Excel)
We want a scalable solution that can be modified easily
We want the solution to be queriable in order to quickly answer questions
Important for this to be accessible on Github
ix. **Add dependencies** - assess for and add dependencies *blocking* & *blocked by* this issue

**Comment by anazariz** [comment]
## **STTM (Source to Target Mapping) MVP**

**Users:**

 1. **Power Users:** PI, Data Scientist, Data Engineer, Data Analyst - May need to interact with, configure and query the system.
**Means of engagement** – SSMS, R/RStudio/MD, GitHub
 2. **Non-Power Users:** May need just the output - not engage with/configure the system directly
**Means of engagement** – GitHub/RStudio Shiny App/MD/XML

**How:**

Core Objects: 6 Database tables, 1 Recursive Store Procedure,  1 View.

As there is no PHI involved, any online database including MS 365 Azure (used for MS Dynamics as well) can host the objects. This will allow deeper levels of interaction from users outside of VA.

**MAP ANY SOURCE TO ANY TARGET**

![image](https://user-images.githubusercontent.com/39805164/88841010-2f774f00-d192-11ea-98a4-7a0d6a32b266.png)

The **TeamPSD Quantitative Group** recommends creating the tables in SQL Server and displaying the results in GitHub. Git will be used for version control. Using the SQL Server XML capabilities, the STTM contents can be shared with those who do not have access to the VA SQL Server platforms. 


![image](https://user-images.githubusercontent.com/39805164/88841231-7f561600-d192-11ea-81e7-85c1d0533876.png)

**Creating the SQL Tables**
<PRE><CODE>
USE STTM;
GO

--+++++++++++++++++++++++++++++++++++++++++++++++++++++
--Build the core tables
--+++++++++++++++++++++++++++++++++++++++++++++++++++++

ALTER  TABLE [DBO].[DATASET] DROP  CONSTRAINT  fk_environment
ALTER  TABLE [DBO].[FIELD] DROP  CONSTRAINT  fk_dataset
drop  table  if  exists [dbo].[source]
drop  table  if  exists [dbo].[field]
drop  table  if  exists [dbo].[mapping]
drop  table  if  exists [dbo].[dataset]
drop  table  if  exists [dbo].[environment]
DROP  TABLE  IF  EXISTS [dbo].[results]
CREATE  TABLE [dbo].[environment](
[sk] [int] NOT  NULL  IDENTITY,
[environment_name] [varchar](50)  NULL
CONSTRAINT  pk_environment  PRIMARY  KEY (sk)
)  ON [PRIMARY]
GO

CREATE  TABLE [dbo].[dataset](
[sk] [int] NOT  NULL  IDENTITY,
[dataset_name] [varchar](50)  null,
[environment_sk] [int] not  null,
CONSTRAINT  pk_dataset  PRIMARY  KEY (sk),
CONSTRAINT  fk_environment  FOREIGN  KEY (environment_sk)  REFERENCES environment(sk)  ON  DELETE  CASCADE
)  ON [PRIMARY]

GO
CREATE  TABLE [dbo].[mapping](
[sk] [int] NOT  NULL  IDENTITY,
[mapping_text] [varchar](5000)  NULL,
CONSTRAINT  pk_mapping  PRIMARY  KEY (sk),
)  ON [PRIMARY]
GO

CREATE TABLE [dbo].[field](
[sk] [int] NOT NULL IDENTITY,
[field_name] [varchar](50) null,   
[field_type] [varchar](30) null,
[dataset_sk] [int] not null,
[mapping_sk] [int] null
CONSTRAINT pk_field PRIMARY KEY (sk),
CONSTRAINT fk_dataset FOREIGN KEY (dataset_sk) REFERENCES dataset(sk) ON DELETE CASCADE,
CONSTRAINT fk_mapping FOREIGN KEY (mapping_sk) REFERENCES mapping(sk) 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[source](
[target_field_sk] [int] not null,   
[source_field_sk] [int] not null
CONSTRAINT pk_source PRIMARY KEY (target_field_sk,source_field_sk),
CONSTRAINT fk_target_field_sk FOREIGN KEY (target_field_sk) REFERENCES field(sk) ON DELETE CASCADE,
CONSTRAINT fk_source_field_sk FOREIGN KEY (source_field_sk) REFERENCES field(sk)
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[results](
[source] [int] NULL,
[mapping_text] [varchar](30) NULL,
[target] [int] NULL,
[lvl] [int] NULL,
[id] [varchar](30) NULL
) ON [PRIMARY]
GO
</code></pre>

**Creating the View**
<PRE><CODE>
--+++++++++++++++++++++++++++++++++++++++++++++++++++++
--Build the view
--+++++++++++++++++++++++++++++++++++++++++++++++++++++

CREATE OR alter VIEW dbo.v_source_to_target AS
select 
   s.source_field_sk as source,
 --t.mapping_sk      as mapping_sk,
   m.mapping_text    as mapping_text,
   t.sk              as target
from
             dbo.field  as t
   join dbo.source as s
   on        t.sk = s.target_field_sk
   join mapping as m
   on        t.mapping_sk = m.sk
</code></pre>

Sample Output
<PRE><CODE>
select  *  from  v_source_to_target order  by  target,source

source	mapping_text	target
1	text1	4
2	text1	4
3	text1	4
5	text2	8
6	text2	8
7	text2	8
9	text4	12
10	text4	12
11	text4	12
13	text5	16
14	text5	16
15	text5	16
4	text3	17
8	text3	17
12	text6	18
16	text6	18
</code></pre>

**What is simple recursion?**
A **Stored Procedure**  is a bunch of SQL  (set oriented) and T-SQL (SQL Server’s Procedural Language like R or Python) instructions that acts like a mini program. It’s a cousin of SQL Server Function.

Before we go over what our single stored procedure does, we need to know what recursion is and how our stored procedure implements it.

![image](https://user-images.githubusercontent.com/39805164/88841444-da880880-d192-11ea-92a2-8cc7f05705ea.png)

As seen above, to understand how **Element5** was created, one need to trace it backwards to **Element1** 

Our case is a bit more complex than that since an **Element** can have multiple Parents (or **Source Elements**).

![image](https://user-images.githubusercontent.com/39805164/88842042-b678f700-d193-11ea-897e-988790498be4.png)

**Benefits:**
 - Simple Recursive SQL Queries that can be run from any platform(SQL,R, Forio) to display Inter-Platform Data Lineage at any Depth
 - Resulting output can be checked into GitHub (via Git) as shared via XML
 - Results can be combined with **ERD** (Entity Relationship Diagram) for maximum visibility

**Creating our Recursive Stored Procedure**
<PRE><CODE>
--+++++++++++++++++++++++++++++++++++++++++++++++++++++
--Build the stored procedure
--+++++++++++++++++++++++++++++++++++++++++++++++++++++

CREATE OR ALTER procedure p_name (@p_target as int, @p_lvl as int = 1, @p_id as varchar(30) = 'unknown')  
AS   
BEGIN
   DECLARE 
      @source int, 
      @mapping_text varchar(30), 
      @target int, 
  @lvl int,
  @row int;

   DECLARE cursor_name CURSOR LOCAL FOR SELECT * FROM v_source_to_target WHERE target = @p_target 
   OPEN cursor_name 
   FETCH NEXT FROM cursor_name INTO @source, @mapping_text, @target
   PRINT(CAST(@target as varchar(10)) + 'read')
   WHILE @@FETCH_STATUS = 0  
   BEGIN
  INSERT INTO dbo.results (source, mapping_text,target,lvl,id) values(@source,@mapping_text,@target,@p_lvl,@p_id)
  set @lvl = @p_lvl + 1
      EXEC p_name @source, @lvl,@p_id 
      FETCH NEXT FROM cursor_name INTO @source, @mapping_text, @target
  PRINT(CAST(@target as varchar(10)) + 'read')
   END;
   CLOSE cursor_name
   DEALLOCATE cursor_name
end
go
</code></pre>

Stored Procedures are compiled code so there is less parsing at runtime. However, in this case the time savings will not be significant since the procedure runs only one time. 

**Executing the Recursive Stored Procedure and Viewing the results**
<PRE><CODE>
EXEC  p_name  17,1,'new run’;

select  *  FROM RESULTS order  by  lvl

source	mapping_text	target	lvl	id
4	text3	17	1	new run
8	text3	17	1	new run
5	text2	8	2	new run
6	text2	8	2	new run
7	text2	8	2	new run
1	text1	4	2	new run
2	text1	4	2	new run
3	text1	4	2	new run
</code></pre>
**Executing the Recursive Stored Procedure  
from RStudio  (Please note that an RODBC connection must be made to the database)**

![image](https://user-images.githubusercontent.com/39805164/88843574-356f2f00-d196-11ea-88cd-fba46bf6c5e8.png)

Although data can be entered directly via SQL (or even extracted via SQL Server Metadata), a simple application created in [Shiny R](https://shiny.rstudio.com/), MS PowerApps, MS Access or any other tool capable of being a front-end to SQL Server could  ease the data entry tasks.

**Comment by anthonycpichardo** [comment]
Front end code will be developed and tracked via https://github.com/lzim/research/issues/21

**Comment by anthonycpichardo** [comment]
R21 Backend development will be tracked in Feature #1458
