### ISSUE TITLE
Oct Epic + "Task": Style guides for R, MD, and SQL

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1440]
**1. Description:** 
Compile the style guides that Team PSD will be following.

Style Guides: 	
.md - GH, OSF standards
.R - tidyverse
.sql - VA example Jodie's repo

**Comment by lijenn** [comment]
- Standard Markdown Usage (Not all Markdown applications support these elements, such as OSF where the context is based on research/manuscript writing. For example, a task/check list would render or be relevant in a manuscript.)
   - [Markdown Syntax CheatSheet for Basic & Extended Syntax](https://www.markdownguide.org/cheat-sheet/#extended-syntax)

- Markdown for OSF
![image](https://user-images.githubusercontent.com/59668647/87704045-9dfaec80-c750-11ea-84f5-d7ddfcae1d1d.png)
   - OSF Use Cases: Consistent with standard Markdown use, with exception of hyperlinking or linking to images due to context of research/manuscript writing (i.e reference list)
   - [OSF Markdown Guide](https://help.osf.io/hc/en-us/articles/360019737474-Edit-the-Wiki)

- Markdown for GH
   - GH Use Cases: GitHub Flavored Markdown (seems pretty much consistent with Standard Markdown Usage)
       - [Basics and Formatting of Markdown on GH](https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax)
       - [Advanced Formatting of Markdown on GH (Tables, Code blocks, linking/referencing URLS)](https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting)
   - [GH Markdown 3 min CheatSheet of both some Basic & Advanced Syntax](https://guides.github.com/features/mastering-markdown/)

- Markdown for Bookdown Output
[in progress]

**Comment by lzim** [comment]
Hi All
@lijenn @anthonycpichardo @staceypark 

I know we're using:
- VA/OMSHP SQL Style
- Tidyverse R Style

But, as we are trying to get clearer and clearer about .md

In addition to @lijenn's resources above, I see this **makefile:** https://osf.io/zw7bx/?ref=9e7e78b9d3c5e1849b5be7faa6d8eecf32063a40

I want us to keep our "key stroke automation" and "google for yourself" goals in mind.
**_Meaning how can someone easily learn to do this for themselves to standard without a lot of overheard teaching/orienting/updating guides?_**

**Comment by lijenn** [comment]
Style guides needed for .md:
- vignettes
- training guides/resources (applies to both bookdown-related resources or not)
- see/say guides
- osf wiki for manuscripts
(will update list to include more .md related documents)

**Comment by lzim** [comment]
HQ & Quant Workgroups,

@dkngenda @lijenn @staceypark @anazariz @anthonycpichardo

Folks are really trying to produce a lot in these languages, and I believe there's a dependent SQL (following Jodie/PERC's stands) style issue too.

Are we all clear, so that we can avoid rework?
Should we be updating #1440 based on lessons learned trying to get R21 tests of specific aims and R01/IIR site selection code verified?

📚

**Comment by staceypark** [comment]
R & SQL are done.
OSF/manuscript markdown template is tracked under #1362.

**Comment by lijenn** [comment]
R and SQL done by Anthony, MD to be continued in 1592.
