### ISSUE TITLE
wk1 - Facilitator Dashboard Permissions Level Change 

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1481]
### Check off requirements to verify progress through feature_tracker.
- [ ] 1. **DEFINE in work_breakdown**
  - [ ] a. **what & why** - **written definitions of requirements** in a **numbered checklist** on the **master_feature_card.**
1. Facilitator Dashboard is currently accessed by switching roles from "learner" to "facilitator" in the group mapping system.

2. Functions in the Facilitator Dashboard include:
a. Team experiment progress & stats overview
b. Team chat
c. Review PLDR (see #1480 for bug report on the icon)
d. Edit More Info
e. Edit Tutor
f. Edit Quick Tips

3. It's weird that you would have to log into a team specific world as a facilitator to do functions c-f, given that they are general ones. Function a seems to allow you to view more than one team at a time in theory, but in practice is not so (making the multiple dial rows moot).

4. Would make more sense and be easier if the facilitator login was at "higher level" in organization category than the groups. Meaning all facilitators would have a *single* place they login to for facilitator functions, and they'd be able to choose a team from a dropdown list to review their experiment progress or to chat with them.
  - [ ] b. **date & who** -  @jamesmrollins Following this morning's 8/31 WG leads meeting, I know you're slammed, but was wondering if you could start thinking about this in the back of your mind. What are the estimates for this? Do you think we can get this done in September? When do you think we can train and orient folks to this?

---
- [ ] 2. **DESIGN** in **operations_to_do** and **research_to_do**
  - [ ] a. **what & why** - **_MVP_ of design** of requirements in a **algorithm map, wireframes or design** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** design **asynchronously** or an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 3. **DEVELOP** in **under_development** - "frozen"

  Task Cards:
  #
---
- [ ] 4. **TEST in functional_test**
  - [ ] a. **what & why** - **TEST requirements** using **testing_checklist** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** via TEST **asynchronously** or an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 5. **PROD in done**
  - [ ] a. **what & why** - **_DOCUMENT_ feature** using **document_tracker** for the **5 D's.** 
  - [ ] b. **date & who** -  **DELEGATE**
    - [ ] **describe_learners** [Jenn & Rita]
    - [ ] **detail_facilitators** [Jane & Debbie]
    - [ ] **document_team** [Anthony]
    - [ ] **disseminate_scientists_va** [Anthony]
    - [ ] **depend_products** [hq & ees]
  
  Task Cards:
  #
---
- [ ] 6. **closed** - fully documented, trained and ready for the next release.

**Comment by jamesmrollins** [comment]
Discussed issues with @staceypark regarding Facilitator Dashboard:

1.  James indicated the Dashboard might need a "reboot" as many of the features may not be solving facilitator pain points.  Stacey responded that the newly deployed CRM may also affect what a new design would look like.  Some places to look:
-  Surveys?  Can the Sim UI handle a majority of the Facilitator's workflow between prep, lesson and follow-up?
-  CRM API?  Is there a REST API that could be automatically report data between the SIM/UI and the CRM, or visa versa?  Is their an API that could transmit signals or triggers between the two platforms to release emails, or a related action?
2.  Stacey asked if there was a way to allow a facilitator to be in a learner and facilitator role within the same group, or have the ability to change roles from the webpage versus having to go into Epicenter.  We covered a few topics:
- We had to flatten the group-world hierarchy because we could not custom-name worlds.  Worlds are assigned sequentially by the system, and the user is assigned a world as a Team Leader or a Player. Groups can be custom named, which helps users find their appropriate "world."
- A facilitator can emulate a learner role using the "Impersonate User" function from the Groups End User Details tab. However, we also recall having some glitches using this function in the past.  We decided to test it out again, since Forio has been making regular releases and updates.  If this function is still buggy, then James will complain to Will and Dave.  They have been very responsive.
- In any case, the Facilitators will still need to be able to manipulate Epicenter.
-  James and Stacey agreed to get together when Stacey's internet is restored to test out the Facilitator Impersonate User function.

**Comment by staceypark** [comment]
@jamesmrollins  FYI I did run the test for Impersonating a user with @lijenn. We think it would work for the use case a facilitator would need. Otherwise, they would always be assigned "facilitator" as their role and just impersonate someone (perhaps the team lead) during a session.

**Comment by hnorthcraft** [comment]
#adjudicate_memo Heather attempting best estimate at SP.
