### ISSUE TITLE
WK3 xxx_facility.xlsb telephone clinics not visible

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1506]
Telehealth clinics (VISTA appointments) are not visible in the facility workbook.

From: Marcia

So it may be that telephone clinics are only not shown in the XXX_facility.xlsb which can be corrected if they are selected in the Data UI to create the XXX_facility.xlsb table—is this correct? 

LZ: I EXPECT YES, and WE CAN LOOK INTO IT.

As Stacey noted, though—what to do with telephone clinics during the COVID time frame (present to who knows when) is still something to think about, yes? 

LZ: RIGHT WE’LL BE HAVING MORE AND MORE CONVERSATIONS ABOUT THIS FOR SURE.

Is this something we want to address? if so, how? @staceypark @lzim

**Comment by anthonycpichardo** [comment]
pre-covid telephone clinics were not counted as billable..

Now they are billable and should be listed in our clinic list for the facility page.

If we have any questions, lets get them posted by EOD today

**Comment by lzim** [comment]
Note on your comment above @anthonycpichardo 
This is one working hypothesis about what is causing this.
But, I'm not sure technically whether it is the best explanation for what's going on.

It's definitely a "bug" though that we should try to squash ASAP.

**Comment by anthonycpichardo** [comment]
Great find by Marcia--this bug was caused by an improper WHERE clause in the SplashPage sql code that was only joining locations where the primary StopCode was in our list of StopCodes of interest and not considering cases where the Secondary Stop Code was in the list but not the Primary.

This is done when we are inserting data into the #tmpLocs table of the SplashSourceIncrement.sql file for those who would like to look at the code. 

To remediate the issue I have added an or condition that matches what we have in the data_ui. This corrected the issue and I am now able to see the missing Telephone clinic Marcia pointed out.

@anazariz can you  do the code review for the WHERE clause in the #tmpLocs table? All I've added was the or statement.

To roll this out we can either propagate the facility workbooks now or next month. 

**I propose we wait until next month as there is some additional work to be done to do this correctly.**

Additional Work:
@anazariz @lzim @staceypark 
The Splash Page is a rolling 2 year window* <sup>See Note 1</sup> that is updated monthly--for efficiency, the code is currently implemented such that we drop the data that is now more than 2 years old and only add the new month of data.

Because this bug exists and we'd like to correct it we will need to update the entire table as opposed to just the future month.

Shouldn't be a large effort but there will need to be a new script created to handle this.

I would estimate this to be 1 or 2 points and I believe it can be done in WK4 before next months propagation. 

If you approve of this @lzim we can get an issue created for "Updating the facility workbook data" and this one can be closed as the bug is fixed.

Note 1: I believe we previously restricted the 2 year window down to 1 year and even 6 months in some cases for certain sta3ns that were too large in size to be displayed on the Sharepoint. I don't believe the workbook size is still a constraint--is there any reason why we would still want to do this? If not, we can get an issue created and go back to showing 2 years of data for all sta3ns.

**Comment by lzim** [comment]
Thanks for this update @anthonycpichardo and recommendations.

Let me know if I have missed responding to anything.

Terminology: We're about to do October propagation to include data from the month of October.

1. I'm not sure if you're proposing to wait until November to fully implement the facility fixes, but we may be quite constrained if we wait too long, since we are going to be busy with co-planning meetings in which we look at the facility data with VISN and Facility leadership. 

2. Yes, we should go back to 2 years for all facilities if we do not believe we are constrained by Excel Web Services any more.

Thanks!

**Comment by anazariz** [comment]
**@lzim @staceypark @anthonycpichardo update:** 

I'm about to run the SplashPage update. As the primary StopCode code was changed (see above), I am running the update for 2018-10-01 to 2020-11-01 instead of  2020-10-01 to 2020-11-01. Also, I added the "Reset Chart" button to the workbook (on all the Viz worksheets), which is going to show up with the next propagation.

**Comment by lzim** [comment]
Great, thanks @anazariz !
