### ISSUE TITLE
wk?? Bug: SIM UI Prod - Ind worlds

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1611]
James, @branscombj is having trouble accessing her individual world.

We signed into SIM UI Prod through the facilitator login and tried to access our individual worlds by clicking the green Home home exactly how it is below:
![image](https://user-images.githubusercontent.com/59668647/101408905-ed71be80-3891-11eb-8224-fc7fffe6f9ab.png)
She got in, but was unable to go into a session with the following info below, it would just get stuck with the Play button loading continuously:
![image](https://user-images.githubusercontent.com/59668647/101409429-c23b9f00-3892-11eb-987b-af3d380d9140.png)

Are we just experiencing user error or an actual bug? 

FYI: @staceypark @dlkibbe

**Comment by jamesmrollins** [comment]
@lijenn based on the screen capture, I cannot determine if you selected a team before clicking home.  It appears that you didn't, but I don't know.  Also, did you just try reloading the page and repeating the process?

**Comment by lijenn** [comment]
@jamesmrollins I assigned Jane and myself to 'mtl_facilitate_2020_10_ind' where there is already a world assignment to another member. However, I still don't see our ind worlds in the dropdown. And yes, reloading the page and repeating the process didn't work.

**Comment by jamesmrollins** [comment]
Ok - so you are not facilitators in that world, which is why you are likely not seeing the selection in the facilitator dashboard teams dropdown.  However, you would likely see it in the login dropdown.

**Comment by staceypark** [comment]
hey @jamesmrollins ok that makes sense for how the home button works.
How does the individual_login work with the facilitator dashboard?

We still want facilitators to be able to go into an individual world for when they need to run experiments between sessions without messing up the team world. I see there's an individual login group but unsure how to access that either by inital login or through the facilitator dashboard.

**Comment by jamesmrollins** [comment]
Hi @staceypark.  Sorry I missed this. The 4 steps below will work to get someone an individual world of their own.

1. Create a group as an individual world.  
2. Load the individual as a facilitator to that group.
3. Load anyone else in the cohort as a player and assign to a world.  
4. The facilitator would access the group through the team dropdown in the facilitator panel. 

In the meantime, I will check out with @hirenp-waferwire the rules regarding world assignment.  I thought you could be assigned to a world and it would show in the login dropdown, but now I don't remember.

**Comment by jamesmrollins** [comment]
Hi @staceypark.  

BLUF:  You can only use the username associated with your facilitator or admin login for that purpose.  You cannot be a world-level participant AND a facilitator. One must choose one or the other.

WORKAROUND:  Easily create another alias for the facilitator, in a *_ind group and  assign to an individual world. Since facilitators have "god" (little-g) privileges, their world will show on their dropdown list.  They can navigate to there by selecting from the dropdown.

CONDITIONS:  The user must also be assigned to the *_ind group as a facilitator with the user id associated with their facilitator login.

1.  Navigate to the *_ind group.
2.  From the End User Details tab, click "Add End Users."
3.  In the Add/Invite an End User field, type in the user's alias and click Add/Invite User button.
4.  Enter the users name, assign a password, confirm, and with the Facilitator radio button set to "no," click the Create User button.
5.  The user will now appear on the End User Details.  
6.  Navigate to Multiplayer assignments and assign the person an individual world using their alias.
7.  The individual world should now show on the dropdown, when the user logs in as a facilitator.

We can go over this together - just let me know.  I have set your alias up in the jenn_test_ind group and assigned you to world003.  It should show up on your facilitator team dropdown as "stacey-YGG jenn_test_ind."
