### ISSUE TITLE
feb_wk2: VAPOR Video Edit with updated logo

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1616]
Edit the VAPOR logo and videos from Advisory to Affairs.
- [x] All 24 videos edited
- [x] All 24 video uploaded
- [x] https://mtl.how/intro edited
- [x] httpsL//mtl.how/intro video uploaded

**Comment by lzim** [comment]
@lijenn I've edited the logo and put it in Resources on GitHub here: https://github.com/lzim/teampsd/blob/master/resources/logos/vapor_logo_sm.png
Will you also save it to the Team PSD > logos folder, please?
Note that I purposefully replaced rather than renamed to keep all links working. 

@erinash I assigned this to you to be completed by wk3 of the January epic. THANK YOU!

**Comment by lijenn** [comment]
Erin can upload the videos around 1pm today, thank you @erinash!!!!!!!

**Comment by lijenn** [comment]
Oh @erinash  and we also mentioned that the video at https://mtl.how/intro 's logo still says advisory. 
If you could also please help us fix the logo on that video and have it uploaded, that would be awesome too :)

**Comment by erinash** [comment]
Hi @lijenn !

Sorry about the delay.
The edited video is uploaded _and_ URL changed in rebrandly so https://mtl.how/intro still works.
I checked off the two boxes in your 12/10 post.
And, I'm closing this issue. 😸

**Comment by lzim** [comment]
@lijenn I updated the estimate to 13 points as @erinash told me it was a two full days of editing work to get these logos all edited in each video and uploaded as HD videos to YouTube.
