### ISSUE TITLE
ASAP Bug: mtl.how/data 626 Facility File sta6a list in vizDiag graph not from 626

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1639]
Went to facility file for 626, opened the file, reviewed data and did not correspond to 626.

Lindsey will post screenshot below in a comment.

**Comment by anthonycpichardo** [comment]
Acknowledged. 

Will take a look now and resolve.

**Comment by lzim** [comment]
@anazariz & @anthonycpichardo 

- URGENT BUG:
1. During **facilitatate_workgroup** - We opened the **626 facility file** and were reviewing the list of sta6a listed under the **DivisionName** button of the **vizDiag** tab.

<img width="933" alt="data_facility_file_wrong" src="https://user-images.githubusercontent.com/7454688/104355117-10117b80-54bf-11eb-953c-cfdd6e2db841.PNG">

2.  We identified sites from New York (not Tennessee) in this list:
<img width="960" alt="626_sta6a_error" src="https://user-images.githubusercontent.com/7454688/104356141-6fbc5680-54c0-11eb-9641-b61644284503.png">

### Please provide an estimated timeframe to resolve ASAP. 
- Check whether the bug is across facility files from the December propagation.

**Comment by anthonycpichardo** [comment]
**Sites where the vizdiag tab has incorrect data**
666
519 
589
657


For 589 & 657, the divisionname list is the same as the 626 site above.

**Comment by lijenn** [comment]
Thanks for checking the scope of the issue @anthonycpichardo! 

To summarize our andon alert/Fire drill practice as a team from team temp:
1. **S**cope - impact on current wave sites.
Scope of our active sites that may have been impacted by the andon alert and alert HQ within 30 minutes.
2. **A**lert - on platforms.
Alert the andon message to partners and on platform (mtl.how/data in this case) - Every team member should know how to send out or set up andon message alert.
3. **C**ommunicate - until resolved.
Communicate with sites and partners until issue is resolved.

@lzim @staceypark @anazariz @dkngenda 

Should HQ communicate to the mapped QIIC and site leadership? 
A message like: Your site has been impacted by a bug causing incorrect facility data. We are not sure what went wrong, but are actively working on fixing this bug. We will keep you updated, thank you for your patience.

**Comment by anazariz** [comment]
**@lzim @staceypark @lijenn @anthonycpichardo** 

I completed the fix. The file to be tested is called SplashMothership-debug.xlsb and it's in the quant's splash_pages folder.  
I recommend that 3 of us perform independent testing. We need to test the facilities that had the issues (all 4 vis sheets and all 4 data sheets) as well as 4 good facilities (select on random) as a from of regression testing (making sure that nothing good is now broken).

**Comment by lzim** [comment]
@anazariz - great!

Do you mean that you have a "fix" that you have already propagated globally?
Or, a fix that applies to our 3 top priority sites 626, 657 & 589?

@anthonycpichardo - Let's update the Alert message once we test.
@staceypark and I are testing now. Are you able to too, Anthony?

**Comment by lzim** [comment]
@lzim is reviewing 626, 657 & 589 this morning for leadership coplanning.

@anthonycpichardo & @anazariz will work to test and implement the global fix today.

**Comment by lzim** [comment]
FYI @anazariz  @anthonycpichardo  @staceypark  @lijenn @dkngenda 

How is testing going? I'd like to briefly huddle about the issues and wonder if we **should meet earlier ~10:45AM than 11AM quant_operations to do so??**

I was just reviewing the 666_facility.xlsx file with leadership in SLC and **reproduced the error, it has 646 data in the viz tabs.**

**I noted several things that I want to review before propagating anything, which are:**
**1. vizEnc, vizHF and vizMeas tabs do NOT have the "divisionname" grey butto:n on their graphs** (like they should and like vizDiag does). Why?
2. I note that I don't see a "Control" tab, which I was looking for when this error first was observed, because that would help me see what facility the data was populated from. What have decided to do about that? I note that Ash describes fixes about deleting "hidden" elements, so I want to check on that.
3. I want to make sure the **scope of our problem(s) have been carefully checked (e.g., across the "locationname" data).**
4. Why are there grey buttons in the viz graphs that are "inert" (they don't do anything) like "Sum of PTSD." These are not familiar buttons to me in terms of using them.
5. I also want to **cross-check this pre-propagation with VVC #1638:** https://github.com/lzim/teampsd/issues/1638

**Comment by lzim** [comment]
@anazariz 

**facility.xlsb file**
- [ ] Need **divisionname** vizEnc, vizHF and vizMeas
- [ ] Hide grey buttons on graphs that are "inactive" - inert don't do anything for the user.

**detail_facilitate:** (for _MTL_ Manual - Facilitator section).
- [ ] Need documentation for unhiding the **Control** Tab and Refreshing.

**document_team**  (for _MTL_ Manual - Technical/Admin support section).
- [ ] In the hidden "Control" tab we need a "Do you want to update the facility.xlsb on the Splashpage?"
**We do not anticipate non-quant folks to propagate nationally, but we do need documentation beyond the current "Hidden" tab instruction to propagate a _single facility._**

**Comment by lzim** [comment]
This is still an ASAP bug and we are propagating January next week with several facilities leadership coplanning meetings underway.

Errors I'm getting working with the 657 facility file - The file has errors upon opening that crash Excel.
I have another Excel file open here, and you can see the errors referencing the 657 file.
![657_errors](https://user-images.githubusercontent.com/7454688/106320293-86d0a780-6227-11eb-893d-be2ae9a9c260.png)

When I click on "Open" next to the red repair message I get this error message:
![image](https://user-images.githubusercontent.com/7454688/106320541-dfa04000-6227-11eb-8b46-1ee0d15572d1.png)

**Comment by anazariz** [comment]
@lzim I am working on it. This is not code related otherwise it would be happening with all the files. This is related to the file size and the platform not being able to handle these volumes. I will refresh this one file.

**Comment by lzim** [comment]
@anazariz  Thanks will you update when the refresh is complete?

- I have a message pending for the chief of staff based on my ability to access these data.
- But, would be great to message about this back-channel and still catch the Project Special Forces (PSF) meeting w/Melanie and Matt regarding D365/CRM Story 6 right now.

**Comment by anazariz** [comment]
@lzim I refreshed 657 and verified that I could open it.

**Comment by lzim** [comment]
Thx! @anazariz testing now

**Comment by lzim** [comment]
### Scope - 
**Fresno 2/3 is Dr. Norlander** is "super user" might test the **VVC views** and **fiscal year.** 
- **QA Test:** Implementing, Testing by team(who?)/super users (Dr. Norlander); Documented and Release.

#### Facility
- [ ] VVC Views
- [ ] Fiscal Year

#### Team
- [ ] VVC Views
- [ ] Fiscal Year

**Comment by anazariz** [comment]
1. Data UI Fiscal Year and VVC coding was completed. I'm waiting to get the test results back and OK'ed from Jenn
2. Facility VVC has two components. 
Location: splash_pages\Dev
1) change to the monthly script splashSourceIncrementalUpdate_vvc.sql 
2) change to the workbook SplashMothership_vvc.xlsb

**Comment by lzim** [comment]
**Discussed at hq_workgroup wk1 feb_epic**

- We believe these are all implemented. 
- Only remaining questions are about the usability of the fiscal year implementation, which we will track on #1580
