### ISSUE TITLE
Data UI Testing

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1668]
Say Guides: 
(Red): https://github.com/lzim/mtl/blob/master/red/part1/part1_facilitator/mtl_red_part_1_say.md
(Red): https://github.com/lzim/mtl/blob/master/red/part2/part2_facilitator/mtl_red_part_2_say.md
(Blue): https://github.com/lzim/mtl/blob/master/blue/session02/s02_facilitator/mtl_session02_say.md
(Blue): https://github.com/lzim/mtl/blob/master/blue/session03/s03_facilitator/mtl_session03_say.md

See Guides:
(Red): https://github.com/lzim/mtl/blob/master/red/part1/part1_learner/mtl_red_part_1_see.md
(Red): https://github.com/lzim/mtl/blob/master/red/part2/part2_learner/mtl_red_part_2_see.md
(Blue): https://github.com/lzim/mtl/blob/master/blue/session02/s02_learner/mtl_session02_see.md
(Blue): https://github.com/lzim/mtl/blob/master/blue/session03/s03_learner/mtl_session03_see.md

**data_ui file** :
- [x] **divisionname**  filter is visible on vizEnc, vizDiag, vizHF and vizMeas
- [x] There are no unusable buttons on the graphs
- [x] VVC & Fiscal year filters are working and correctly drill down the data on the vizenc tab
  - To switch to fiscal year view you will right click the **table** behind the graph and select "switch to fiscal date" from the drop down. To revert back to the calendar year press the "reset pivot chart" button
- [x] The "Hidden" tab of the data_ui is not visible
- [x] LSV Run time alert pops up when you click the "Get Patient Data" or "Get Team Data Table" buttons

**data_ui cheatsheet**
- [ ] Instructions for creating a team_data folder are clear

**Comment by anthonycpichardo** [comment]
For the LSV messaging how does the following sound?

![image](https://user-images.githubusercontent.com/60201706/106535540-48e3b580-64ab-11eb-8b11-038ef0723fae.png)

This is an update to the existing confirmation message that existed which stated:

These queries may take a while, and Excel will be unresponsive until they complete. Proceed? 

Appreciate the feedback.

@lzim @lijenn @staceypark @anazariz

**Comment by anthonycpichardo** [comment]
@jamesmrollins @dkngenda @lijenn @staceypark 

The data ui file is ready to be tested for the criteria outlined above. 

Test files have been created for each tester in the quant_wg folder > final_datafiles > test

Once testing is completed please move your file into the completed folder.

To view the LSV alert remember that you will need to have clinics selected as instructed in the file. You will not need to run the query as the dialog box allows you to cancel.

**Comment by jamesmrollins** [comment]
@anazariz @anthonycpichardo 

1. The instruction above did not work as explained in the text shown below:

"VVC & Fiscal year filters are working and correctly drill down the data on the vizenc tab
  - To switch to fiscal year view you will right click the table behind the graph and select "switch to fiscal date" from the drop down. To revert back to the calendar year press the "reset pivot chart" button"

2.  I did run the LSV queries, and the warning dialogues appeared to work correctly.  However, the query was not able to run for what I suspect were connectivity issues.

**Comment by staceypark** [comment]
@anthonycpichardo @anazariz 
**data_ui file** :
- [x] **divisionname**  filter is visible on vizEnc, vizDiag, vizHF and vizMeas - **in vizMeas, the divisionname filter comes after rowtype. In all of our other viz, divisionname is always first on the top left. please change it to make it match**

- [x] There are no unusable buttons on the graphs - **in multiple filters and viz there's a "blank" instead of the filter option or month. Can we get rid of this? Is this a bug?**


- [x] VVC & Fiscal year filters are working and correctly drill down the data on the vizenc tab
  - To switch to fiscal year view you will right click the **table** behind the graph and select "switch to fiscal date" from the drop down. To revert back to the calendar year press the "reset pivot chart" button - **This is VERY confusing. We have not previously in any guide, cheatsheet, video, etc. interacted with the Excel in this way. It is always through the filters on the table. What is the rationale for this method of implementation? Can it not be a filter or button the graph?"**

- [x] The "Hidden" **tab** of the data_ui is not visible

- [x] LSV Run time alert pops up when you click the "Get Patient Data" or "Get Team Data Table" buttons - **Right now it says "Excel will be unresponsive." Just to double check the entire Excel app for any other file will be unresponsive right? I think it should clarify that even more somehow. Perhaps "These queries may take a while, and the Excel _app_ will be unresponsive until they complete. _You will not not be able to open any other Excel file during that time_."**

**Comment by anthonycpichardo** [comment]
> @anthonycpichardo @anazariz
> **data_ui file** :
> 
> * [x]  **divisionname**  filter is visible on vizEnc, vizDiag, vizHF and vizMeas - **in vizMeas, the divisionname filter comes after rowtype. In all of our other viz, divisionname is always first on the top left. please change it to make it match**
> * [x]  There are no unusable buttons on the graphs - **in multiple filters and viz there's a "blank" instead of the filter option or month. Can we get rid of this? Is this a bug?**
> * [x]  VVC & Fiscal year filters are working and correctly drill down the data on the vizenc tab
>   
>   * To switch to fiscal year view you will right click the **table** behind the graph and select "switch to fiscal date" from the drop down. To revert back to the calendar year press the "reset pivot chart" button - **This is VERY confusing. We have not previously in any guide, cheatsheet, video, etc. interacted with the Excel in this way. It is always through the filters on the table. What is the rationale for this method of implementation? Can it not be a filter or button the graph?"**
> * [x]  The "Hidden" **tab** of the data_ui is not visible
> * [x]  LSV Run time alert pops up when you click the "Get Patient Data" or "Get Team Data Table" buttons - **Right now it says "Excel will be unresponsive." Just to double check the entire Excel app for any other file will be unresponsive right? I think it should clarify that even more somehow. Perhaps "These queries may take a while, and the Excel _app_ will be unresponsive until they complete. _You will not not be able to open any other Excel file during that time_."**

Thanks for the feedback Stacey!

For the Fiscal Year implementation #1619, I agree that it is not ideal from a usability perspective but the need is because it can't be a filter or a button on the graph. The way the data cube is built wouldnt allow for a simple filter option to change between the fiscal & calendar year.

It could potentially be a button similar to the reset pivot chart if that is something we'd like pursue.

**Comment by lzim** [comment]
I agree with @staceypark's usability concerns here: 
>  VVC & Fiscal year filters are working and correctly drill down the data on the vizenc tab
To switch to fiscal year view you will right click the table behind the graph and select "switch to fiscal date" from the drop down. To revert back to the calendar year press the "reset pivot chart" button

I've asked @anthonycpichardo to propagate Fresno Data UI, I will try to work on their data as my test.

@anthonycpichardo  Can we clarify in the LSV query message something that helps them to interpret the message?
Also, I don't think any clinicians will know what LSV means, so strip that.

I propose the following message:

"Custom data queries for large VAs can take awhile.
VA limits query run times to 5 minutes between 6AM & 12noon Eastern and to 15 minutes from 12noon to midnight Eastern.
Excel will be unresponsive until queries are complete. 
Proceed now?"

**Comment by dkngenda** [comment]
Test results

**data_ui file** :
- [x] **divisionname**  filter is visible on vizEnc, vizDiag, vizHF and vizMeas
- [x] There are no unusable buttons on the graphs
- [x] VVC & Fiscal year filters are working and correctly drill down the data on the vizenc tab
  - To switch to fiscal year view you will right click the **table** behind the graph and select "switch to fiscal date" from the drop down. To revert back to the calendar year press the "reset pivot chart" button
- [x] The "Hidden" tab of the data_ui is not visible
- [x] LSV Run time alert pops up when you click the "Get Patient Data" or "Get Team Data Table" buttons

**data_ui cheatsheet**
- [x] Instructions for creating a team_data folder are clear

**Comment by dkngenda** [comment]
@anthonycpichardo  the folder structure shown in the screenshots used in the guides is not the same as the structure I see on the splash page. Is this folder structure dependent on the facility or is supposed to be standardized across facilities?

**Comment by lzim** [comment]
FYI @anazariz @anthonycpichardo 

![image](https://user-images.githubusercontent.com/7454688/106773132-9a985700-65f5-11eb-8193-7daae0fe9c6e.png)

I got this, this morning.

**Comment by lijenn** [comment]
@dkngenda Thanks for the feedback on the creating the team folders, think @jamesmrollins documented similar feedback as well from the [facility issue card](https://github.com/lzim/teampsd/issues/1667#issuecomment-772131451). 
@staceypark and I will work on getting the updated folder instructions in the data cheatsheet and the instructions in see/say guide blue 2/red part 1, will create a new issue card for these updates. 

We also documented issues with the current process/workflow for creating team folders at #1674 

> @ anthonycpichardo the folder structure shown in the screenshots used in the guides is not the same as the structure I see on the splash page. Is this folder structure dependent on the facility or is supposed to be standardized across facilities?

David and I clarified that the folder structure shown in the gifs were outdated as we have since cleaned up and hid the old folders shown in the gif. I will work on updating the gif.

**Comment by lzim** [comment]
@anazariz @anthonycpichardo 

Ongoing issues working with Data UI
**1. Time out error received after 12noon Eastern** 
![image](https://user-images.githubusercontent.com/7454688/106933605-f6ceaa00-66cd-11eb-8973-18d96450ebd0.png)

**2. Where I was in the process:**
![image](https://user-images.githubusercontent.com/7454688/106933746-1d8ce080-66ce-11eb-8a4b-65c80524c48e.png)

**Comment by anthonycpichardo** [comment]
I will be addressing the following feedback: 
- "Custom data queries for large VAs can take awhile.
VA limits query run times to 5 minutes between 6AM & 12noon Eastern.
The limit is 15 minutes from 12noon to midnight Eastern.
Excel will be unresponsive until queries complete.
Proceed now?"

- in vizMeas, the divisionname filter comes after rowtype. In all of our other viz, divisionname is always first on the top left. please change it to make it match

- Right now it says "Excel will be unresponsive." Just to double check the entire Excel app for any other file will be unresponsive right? I think it should clarify that even more somehow. Perhaps "These queries may take a while, and the Excel app will be unresponsive until they complete. You will not not be able to open any other Excel file during that time."

Ash will address:
- in multiple filters and viz there's a "blank" instead of the filter option or month. Can we get rid of this? Is this a bug?
- column name "visitids" in dataDiag contains blank values: see https://github.com/lzim/teampsd/issues/1668#issuecomment-772616798

**Comment by lzim** [comment]
@anthonycpichardo 
Will you please confirm you received my message on 2/2 - I don't see it captured anywhere
Thanks!

- [ ] Query message edit
> "Custom data queries for large VAs can take awhile.
VA limits query run times to 5 minutes between 6AM & 12noon Eastern.
The limit is 15 minutes from 12noon to midnight Eastern.
Excel will be unresponsive until queries complete.
Proceed now?"

**Comment by anthonycpichardo** [comment]
Confirmed.

**Comment by anazariz** [comment]
@lzim @staceypark @lijenn @anthonycpichardo 

I corrected multiple issues Data UI and propagated 666 and 589.

Issues Fixed:

1-an "out of range" error would come up with the viz sheets due to indexing inconsistency. I fixed it.
2-in vizMeas "sum of patients" was had replaced "distinct count of patients causing errors - I fixed it
3-a refresh on an empty table was throwing an error-I fixed it.
4-a click on the reset button on an empty pivot table was throwing error - I fixed it

**Comment by anthonycpichardo** [comment]
Documentation being tracked under #1678

**Comment by lzim** [comment]
@anthonycpichardo  and @anazariz 

What fixes should my 589 Data UI files have?

**Comment by anthonycpichardo** [comment]
This change is available for propagation.

Will you be impacted if I propagate the change now?

**Comment by hnorthcraft** [comment]
#adjudicate_memo per comment above, efforts tracked to other card, marking as dup
