### ISSUE TITLE
wk2 2/8 mtl.how/data one pager for facilitator/admin

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1674]
cross ref #1657, #1668

**Original request:** Create one pager for facilitator (and admin) to be able to create team folders while meeting with a team.
**Recommendation:** Create one pager on how to edit existing team folders names according to the naming convention, how to add team members live, and explains the team data vs. team data table folder setup. This way admin can pre-setup folders (a process that takes 20+ steps). Facilitators can tailor the team name live based on info the team gives them. And facilitators can add team members live so team can access files right away.

@lijenn @staceypark investigated the steps and here are our findings:
1. There are three streams on the mtl.how/data admin page - workflows, team folder requests, and team member requests - related to the buttons at the top.
2. Creating "a folder" for a team involves both creating folders and setting up permissions (involves 20+ steps) to do it from end to end. - We believe this is too complicated & time consuming to do live with a team.

Questions & double check of assumptions:
@lzim 
1. @lzim - Do we show the team specific data UI with the team during co-planning? Because otherwise, I think the original thought was that we would get the info we need (team name, members, etc.) during the co-planning and have a break in-between (because of session 01) to setup their folder structures. It seems like this is no longer true.

@anthonycpichardo @anazariz 
1. We're not sure what ends up in the "workflow" stream vs. "team folder/team member requests" on the admin page (see #1 under findings). It would seem each of the buttons correspond to their related streams, but then what is "workflow"?
2. Also, these buttons seem to provide us info, but don't do anything by way of making the folder creation process faster by for example pre-setting up folders from the info. Is there a way this could be changed with some type of Power function?
3. Is there any way in general to make the folder and permissions setup process automated or have less steps? With 20+ steps, there is high margin for error.
4. What is the purpose of the Permissions Index spreadsheet (in the administrative tab of mtl.how/data). Part of the steps is adding links for each team into that excel file, but I'm not sure why. We never go back to that page.

**Comment by lzim** [comment]
@staceypark @anazariz @anthonycpichardo @lijenn 

> Do we show the team specific data UI with the team during co-planning? Because otherwise, I think the original thought was that we would get the info we need (team name, members, etc.) during the co-planning and have a break in-between (because of session 01) to setup their folder structures. It seems like this is no longer true.

**Right,** what is happening more often now, is I s**tart to listen at co-planning 1 and 2**, and we start to get an idea of which team it might be (but not firm yet), so I **start to pull some local data together** _but everyone wants to see the features of the Data UI at the co-plannings._

- **What we are finding is that everyone basically asks for a walk through of the Data UI (_and Sim UI_ BTW, @jamesmrollins, no bugs for you yet 🐞 🏆 )** so that they can picture the resources and understand which team is likely going to be the best first team from their facility.

- I basically am already running Data UI queries throughout the co-planning process as information about local needs comes in.
_Well, I'm trying, but I'm mainly getting 🐛 these right now...See Data UI Testing #1668_

**Comment by lijenn** [comment]
From Support wg 2/4
1. Workflows shows all the actions/requests went through, @anthonycpichardo and @anazariz  think this is just a webpart that could be removed.
2. Since we already get some Team tailoring and contact info here:
![image](https://user-images.githubusercontent.com/59668647/106969029-edaa0100-66fe-11eb-97e0-8a4df2249a69.png)
@anthonycpichardo & @anazariz will keep this in mind when thinking of how we could automate the folder workflow with this information

3. @anthonycpichardo and @anazariz will look into how we can use Power BI to automate our folder creation process/workflow. (Could add this to a Story??) 
4. @anthonycpichardo and @anazariz aren't sure of the purpose of the Permissions Index spreadsheet, but recommend still keeping this in the current workflow to prevent causing bugs the workflow

**Comment by staceypark** [comment]
2/4 hq meeting:
simplified structure approved by @lzim 
@staceypark  and @lijenn will use the ees file on Teams to put the most accurate folder name and pre-setup the folders prior to the co-planning meetings.

**Comment by staceypark** [comment]
updated one pager based on feedback from @lzim (#1689) and QIICS 
- change naming convention flow font to myriad pro
- add details about what resources are in Master Data UI folder
- rename file to include the word "facilitator" to clarify difference bewteen mtl.how/data cheatsheet and the mtl.how/data facilitator one pager

created #1699 for propagating to every facility
