### ISSUE TITLE
wk2: QA PROD - Review RedCap surveys

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1681]
James, I will provide you links to help test the MTL surveys on VA intranet hosted on RedCap. You do not need an account, just access the link on Citrix. I'll ping you when I update with links. 
Thank you!

@jamesmrollins Here are the 2 survey links and requirements to please test! You will need to be on VA intranet to access the links.

Requirements for [R01 Baseline Survey](https://vhacdwweb05.vha.med.va.gov/surveys/?s=9K8HTNWL74):
- [x] Follows general Team PSD style (MTL blue logo & Team PSD colors). 
- [ ] It is clear that there are 4 different survey sections within the one link (Starts with PACT measures and ends with Demographics). 
- [x] The entire survey is optional, there should be no questions that require an answer/you can skip questions you don't want to answer and exit any time.
- [x] Measures/Questions do not ask for PHI or any identifiable information.

Requirements for [R01 Follow-Up Survey](https://vhacdwweb05.vha.med.va.gov/surveys/?s=9LL8M9JDDY):
- [x] Follows general Team PSD style (MTL blue logo & Team PSD colors). 
- [ ] It is clear that there are 7 different survey sections within the one link (Starts with Acceptability of Intervention measures and ends with Systems thinking scale). 
- [ ] The entire survey is optional, there should be no questions that require an answer/you can skip questions you don't want to answer and exit any time.
- [x] Measures/Questions do not ask for PHI or any identifiable information.

**Comment by jamesmrollins** [comment]
### Feedback regarding survey:

**Regarding  "It is clear that there are 4 different survey sections within the one link (Starts with PACT measures and ends with Demographics)."**

1. The beginning screen does not outline any organization to the survey.  While it does say there are 4 other sections, it does not identify them.  Consider numbering and listing the sessions and then use the same in the header of each section.
2. There is no way to navigate back to sections that are incomplete
3.  Sometimes the instructions don't match up with what the person is seeing and is confusing (see below). What numbers?

![image](https://user-images.githubusercontent.com/30132017/107710655-d7122580-6c7b-11eb-887b-09875a589142.png)

4.  The "Submit" button is usually reserved for a last step.  Consider using "next" for each section, as it implies there is something else.

![image](https://user-images.githubusercontent.com/30132017/107711337-50117d00-6c7c-11eb-9f81-59e699fb613b.png)

**Regarding the QA item where, "The entire survey is optional, there should be no questions that require an answer/you can skip questions you don't want to answer and exit any time."**

1.  See picture below.  The summary screen says, "...Which lists any other surveys that you have not yet completed."  But lists only the surveys that have been completed.  Further, there are 4 surveys, right?  So should the others be listed there? 
2.  The highlighted text is confusing, because if the entire survey is optional and you will accept partial surveys, then this message may imply they aren't done, and have to go back to achieve success.

![image](https://user-images.githubusercontent.com/30132017/107712011-7be13280-6c7d-11eb-820e-d156488210e0.png)

**Comment by jamesmrollins** [comment]
### Feedback regarding RO1 Follow up survey:

**Regarding "It is clear that there are 7 different survey sections within the one link (Starts with Acceptability of Intervention measures and ends with Systems thinking scale).**  

1.  While it is clear there are seven sections, it is not clear it start with with Acceptability of Intervention and ends with Systems thinking scale.
2.  Consider numbering and identifying the other sections, if that is important.
3.  Consider using "Next" instead of "Submit" if it is possible.

**Regarding "The entire survey is optional, there should be no questions that require an answer/you can skip questions you don't want to answer and exit any time."**  The pop up shown below does not allow me to leave blanks, or skip questions.  Is this quality measure relevant for this questionnaire?

![image](https://user-images.githubusercontent.com/30132017/107713034-489fa300-6c7f-11eb-9b1d-a3878cc754de.png)


### When I finished the Feasibility of Intervention Measure survey, it took me back around to the Burnout questionnaire, which was already asked and answered.  This appears to be a malfunction.
