### ISSUE TITLE
wk3 Feb Epic: Story 1/6 - Review REDCap flowmaps/documentation 

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1682]
Could James help review the Redcap documentation and flowmaps, check if the flows make sense and are easy to follow.
Jenn will update links here.

**Comment by jamesmrollins** [comment]
Hi @lijenn !

Overall observations regarding VA REDCap Flow Maps are below, comments specific to the maps are in LucidCharts.

1.  Change title from "VA REDCap Flow Map" to "VA REDCap Flow Maps" since there are more than one.
2.  Consider subtitle headings (i.e., Create Log-in to REDCap) for each flow map, as the first block is difficult to read when scanning.  
3.  Is it "REDCap" or "RedCap?"  These two variations are used interchangeably.
4.  When writing procedures, it is very important to identify the starting conditions or starting point.  A user can come into an app a variety of ways that may not make any sense when they reference your procedures. 
5. When ordering steps, ensure they are in the precise order they would actually have to occur.   (see comment in Create/Update Instruments)

Thanks for the opportunity to review!
