### ISSUE TITLE
2/22 wk4 feb_epic story 1: Authorship QA test

### ISSUE THREAD

**Issue by dkngenda** [lzim/teampsd#1686]
split from #1437 
QA Test card: [Authorship App](https://teampsd.shinyapps.io/teampsd_authorship_app/)

**1. workgroup:**
- [x] Calendar pops up when date text box is clicked.
- [x] After selecting right paper and clicking submit, text below the button mentions the right paper.
**2. prior_work:**
_Under prior_work_weights_
- [x] Click in the textbox and check whether you can select subcategories by using dropdown menu or searching using a key work
**3. prior_work_rank**
- [x] Change prior work contribution in the previous tab and check whether the  pie chart changes  appropriately
- [x]  Check to see if there is an error message when your enter and submit subcategory weights.
_Under manuscript_prior_work_summary_
- [x] Check if all navigation buttons and search box for the table are functional.
- [x] Does the entries in prior_work_contribution add up to the percent assigned to prior work 
- [x] Check the pie chart to see if all contributors in the table are also represented in the pie.
_saved_prior_work_
- [x] Test the table navigation buttons and search box. 
**4. write_analyze_edit**
_select_authors_
- [x] Select authors and verify that all of them are listed in the identified contributors section.
_author_contributions_
- [x] Enter authors contributions and verify that they are reflected in the pie chart.
**5. author_order**
- [x] Check if all navigation buttons and search box for the table are functional.
- [x] Check to see if all authors' contribution appear on the pie chart.
**6. authorship_overview**
- [x] Check if all navigation buttons and search box for the table are functional.

**Verify whether your entries have been stored. Refresh the browser then** 
- [x]  Review prior work using the search box in  _saved_prior_work_ tab ... within tab 3. prior_work_rank_
- [x]  Review previously assigned authorship ranks using the search box in tab _6. authorship_overview._

**Adding a subcategory** 
- [x] Click on tab _2.prior_work_ , in the text box type _Add a subcategory_ or select it from the dropdown menu. Enter the required textbox

**Comment by dkngenda** [comment]
Hi @staceypark,  This is the QA test card for the Authorship App

**Comment by staceypark** [comment]
@dkngenda Thanks for creating these cards. I've edited this card and #1688 to cross-ref the original issue #1437 since that's where the requirements were originally discussed. I think it's important to have that in the future so we can make sure everything was tracked without having to fish.

## 2. prior_work
It isn't immediately clear that this piece is a dropdown + type & search feature.
![image](https://user-images.githubusercontent.com/31089501/107544770-68e83880-6b7f-11eb-89f0-3b9ec2e62a7c.png)

Right now, it looks like a fill in the blank. It could benefit from two things:
1. Add an additional instruction that says "**2. Choose manuscript subcategories by selecting them from the dropdown menu or searching for key words. Once you are finished, click on the 3. prior_work_rank tab above.**"
2. Add an arrow button that makes it look like it's a dropdown (like below).

![image](https://user-images.githubusercontent.com/31089501/107545331-03487c00-6b80-11eb-98e5-fc9e7f7fd248.png)

## 3. prior_work_rank
1. I tried both making the table add and not add to 100. The red error message is always there and I'm always able to submit and move to the next tab. For this feature, I'm picturing either:
  - additional error message when total doesn't equal to 100 OR
  - the bottom cell of the table shows a "total" (imagine 'SUM' function in Excel) that calculates as you add a weight for each subcategory and that row would be red if the total was ever under/over 100
![image](https://user-images.githubusercontent.com/31089501/107569386-19b10080-6b9d-11eb-93c6-e5dff172e5bf.png)

2. Took me awhile to figure out what "perc_contribution" was.  I think just calling it "weights" is fine.
3. The pie on this page currently shows prior work vs. write analyze. This pie should be on the 2. prior_work tab. The pie on this page on the prior_work_weights tab should show the prior work vs. write analyze pie with the prior work section divided further based on the weights entered on the subcategories (this is Pie 1 from the original reqs). This should come after the subcategory weight feature on the page in terms of visual order.
4. Add/edit instruction "Enter weights for subcategories chosen on the previous page. Then, click submit and click on the manuscript_prior_work_summary tab to view prior_work weight breakdown by author."

## write_analyze_edit
1. I'm having the same issue with the table here as I did with the subcategory one. Regardless of whether they do/do not equal the correct totals, I'm able to move to the next tab (see previous section comments for suggestions on how to handle this). Also, not sure why I'm getting the message below but I get it regardless of the numbers I put into the table.
![image](https://user-images.githubusercontent.com/31089501/107572143-ae692d80-6ba0-11eb-9463-25a7a4eec1de.png)

2. There should be a pie here that is a continuation of "Pie 1" (Pie by category), where:
- prior_work shows the pie divided between prior_work and write_analyze
- prior_work_rank > prior_work_weights shows the same pie above with the addition of the prior_work sections divided by the subcategories chosen
- write_analyze_edit shows same pie as above with the addition of the write_analyze section divided by the division of the write_analyze just done

## author_order
1. Author order is only showing me authors from the write_analyze portion. Instead of a combination of the prior_work and write_analyze like it says on the instructions.
2. This tab should have an update of Pie 2 (Pie by author) previously shown in prior_work_rank > manuscript_prior_work_summary, where it is now updated to show how much weight each author gets based on data entered in both the prior_work and the write_analyze.


## general comments
1. Even though I went through the app and saved my work, when I refreshed I could not find it in the saved items.
2. What is the point of being able to see saved entries of prior_work and of overall authorship? Is it just for general knowledge? I thought we were supposed to be able to choose something and edit it. Meaning, if we save how we define prior_work for a paper, I can grab that saved entry, and then add the write_analyze portions for that manuscript. Or, if there's already a saved overall authorship weighting for a manuscript, I can grab that and edit it if the work changes.
3. We are still missing the ability to choose workgroup first to filter the subcategories. Here are some links I found that might be helpful for chasing that feature down:
  - https://stackoverflow.com/questions/51153184/dynamic-filters-and-reactive-plot-in-shiny
  - https://github.com/dgkf/shinyDataFilter
  - https://stackoverflow.com/questions/58275062/dynamic-conditional-filtering-in-shiny-select-multiple-inputs-selectizeinput-m

**Comment by dkngenda** [comment]
2. prior_work

- [ ] Add an additional instruction that says "2. Choose manuscript subcategories by selecting them from the dropdown menu or searching for key words. Once you are finished, click on the 3. prior_work_rank tab above."
- [ ] Add an arrow button that makes it look like it's a dropdown (like below).

- [ ]Add a subcategory function needs to be outside of that dropdown. Otherwise it is buried and is not clear. Make it a button underneath the dropdown.
- [ ] For the workgroup category and names, it is fill in the blank right now, but it should be restricted to dropdown. Otherwise, we will have issues from individual variability (for example, hq vs. HQ vs. hq_workgroup vs. HQ_wkgrp >>> these all mean the same thing but to the app, they will be different).
- [ ] There may be situations where we need to add a new workgroup or a new author. There should be a separate function for that outside of this subcategory function. We have a function for adding new authors in the write_analyze, but not in the prior_work.
- [ ] I tried adding a subcategory and saving it but, when I refreshed, I couldn't find it.
- [ ] _prior_work_rank_ I tried both making the table add and not add to 100. The red error message is always there and I'm always able to submit and move to the next tab. For this feature, I'm picturing either:
additional error message when total doesn't equal to 100 OR the bottom cell of the table shows a "total" (imagine 'SUM' function in Excel) that calculates as you add a weight for each subcategory and that row would be red if the total was ever under/over 100

- [ ] Took me awhile to figure out what "perc_contribution" was. I think just calling it "weights" is fine.
- [ ] The pie on this page currently shows prior work vs. write analyze. This pie should be on the 2. prior_work tab. The pie on this page on the prior_work_weights tab should show the prior work vs. write analyze pie with the prior work section divided further based on the weights entered on the subcategories (this is Pie 1 from the original reqs). This should come after the subcategory weight feature on the page in terms of visual order.
- [ ] Add/edit instruction "Enter weights for subcategories chosen on the previous page. Then, click submit and click on the manuscript_prior_work_summary tab to view prior_work weight breakdown by author."
- [ ] _write_analyze_edit_ I'm having the same issue with the table here as I did with the subcategory one. Regardless of whether they do/do not equal the correct totals, I'm able to move to the next tab (see previous section comments for suggestions on how to handle this). Also, not sure why I'm getting the message below but I get it regardless of the numbers I put into the table.

- [ ] There should be a pie here that is a continuation of "Pie 1" (Pie by category), where:

prior_work shows the pie divided between prior_work and write_analyze
prior_work_rank > prior_work_weights shows the same pie above with the addition of the prior_work sections divided by the subcategories chosen
write_analyze_edit shows same pie as above with the addition of the write_analyze section divided by the division of the write_analyze just done
author_order
- [ ] Author order is only showing me authors from the write_analyze portion. Instead of a combination of the prior_work and write_analyze like it says on the instructions.
- [ ]This tab should have an update of Pie 2 (Pie by author) previously shown in prior_work_rank > manuscript_prior_work_summary, where it is now updated to show how much weight each author gets based on data entered in both the prior_work and the write_analyze.

general comments

- [ ] Even though I went through the app and saved my work, when I refreshed I could not find it in the saved items.
What is the point of being able to see saved entries of prior_work and of overall authorship? Is it just for general knowledge? I thought we were supposed to be able to choose something and edit it. Meaning, if we save how we define prior_work for a paper, I can grab that saved entry, and then add the write_analyze portions for that manuscript. Or, if there's already a saved overall authorship weighting for a manuscript, I can grab that and edit it if the work changes.
- [ ] We are still missing the ability to choose workgroup first to filter the subcategories.

**Comment by lzim** [comment]
Discussed at **hq_workgroup**

Anticipate this will be closed by end of wk3.

**Comment by lzim** [comment]
Is this ready to close @dkngenda and @staceypark?
It's blocking PROD QA. Thanks!

**Comment by lzim** [comment]
> Is this ready to close @dkngenda and @staceypark?
> It's blocking PROD QA. Thanks!

I made some changes after Stacey's feedback. Once we are satisfied that her concerns are full addressed, we will close it.

**Comment by staceypark** [comment]
@dkngenda sorry just finishing this now. A couple comments below. Otherwise, it's looking really good! :) 

## 2. prior_work 
1. Instructions says to click on "Reload App" button but don't see that anywhere.
![image](https://user-images.githubusercontent.com/31089501/109051234-28181580-768f-11eb-8e85-713e7a2fa87c.png)

2. Instead of fill in the blank, these names should be chosen by dropdown of a pre-populated list, to prevent error from individual variability. Also, there needs to be an ability to add more than three authors.
![image](https://user-images.githubusercontent.com/31089501/109051319-4120c680-768f-11eb-8839-b048897aab91.png)


## 3. prior_work_rank
1. Current total only calculates once I click on the submit button. This makes sense in terms of backend code. If there is no way to make it update as I'm putting the numbers into the cells, that is fine. Nothing stops me from moving forward if it's over 100, though. If that's not possible, can you at least:
  a) make the number font size bigger
  b) have the font color change conditionally to red when it's over 100 and say "Warning, you're over 100 points"
![image](https://user-images.githubusercontent.com/31089501/109052148-269b1d00-7690-11eb-8c7e-4e7620e85f1c.png)

2. Something is wrong with the math in this pie, because I chose 18% for prior work 
![image](https://user-images.githubusercontent.com/31089501/109052170-2d299480-7690-11eb-90c6-8fff47c8a029.png)

##4. write_analyze_edit
1. Are you able to add something that does a calculation? Even if it does not throw an exception or prevent folks from moving on. A simple calculator like there is in **prior_work_rank**

## author_order
1. The text says this is the write_analyze distribution, but I believe is prior_work + write_analyze no?
![image](https://user-images.githubusercontent.com/31089501/109053736-e8066200-7691-11eb-9e9c-71c82daf6d66.png)

**Comment by dkngenda** [comment]
>> ## 2. prior_work 
1. Instructions says to click on "Reload App" button but don't see that anywhere.
![image](https://user-images.githubusercontent.com/31089501/109051234-28181580-768f-11eb-8e85-713e7a2fa87c.png)

2. Instead of fill in the blank, these names should be chosen by dropdown of a pre-populated list, to prevent error from individual variability. Also, there needs to be an ability to add more than three authors.
![image](https://user-images.githubusercontent.com/31089501/109051319-4120c680-768f-11eb-8839-b048897aab91.png)


## 3. prior_work_rank
1. Current total only calculates once I click on the submit button. This makes sense in terms of backend code. If there is no way to make it update as I'm putting the numbers into the cells, that is fine. Nothing stops me from moving forward if it's over 100, though. If that's not possible, can you at least:
  a) make the number font size bigger
  b) have the font color change conditionally to red when it's over 100 and say "Warning, you're over 100 points"
![image](https://user-images.githubusercontent.com/31089501/109052148-269b1d00-7690-11eb-8c7e-4e7620e85f1c.png)

2. Something is wrong with the math in this pie, because I chose 18% for prior work 
![image](https://user-images.githubusercontent.com/31089501/109052170-2d299480-7690-11eb-90c6-8fff47c8a029.png)

##4. write_analyze_edit
1. Are you able to add something that does a calculation? Even if it does not throw an exception or prevent folks from moving on. A simple calculator like there is in **prior_work_rank**

## author_order
1. The text says this is the write_analyze distribution, but I believe is prior_work + write_analyze no?
![image](https://user-images.githubusercontent.com/31089501/109053736-e8066200-7691-11eb-9e9c-71c82daf6d66.png)

**Comment by dkngenda** [comment]
## 2. prior_work 
- [ ] 1. Instructions says to click on "Reload App" button but don't see that anywhere.
![image](https://user-images.githubusercontent.com/31089501/109051234-28181580-768f-11eb-8e85-713e7a2fa87c.png)

- [ ] 2.. Instead of fill in the blank, these names should be chosen by dropdown of a pre-populated list, to prevent error from individual variability. Also, there needs to be an ability to add more than three authors.
![image](https://user-images.githubusercontent.com/31089501/109051319-4120c680-768f-11eb-8839-b048897aab91.png)


## 3. prior_work_rank
- [ ] 1. Current total only calculates once I click on the submit button. This makes sense in terms of backend code. If there is no way to make it update as I'm putting the numbers into the cells, that is fine. Nothing stops me from moving forward if it's over 100, though. If that's not possible, can you at least:
  a) make the number font size bigger
  b) have the font color change conditionally to red when it's over 100 and say "Warning, you're over 100 points"
![image](https://user-images.githubusercontent.com/31089501/109052148-269b1d00-7690-11eb-8c7e-4e7620e85f1c.png)

- [ ] 2. Something is wrong with the math in this pie, because I chose 18% for prior work 
![image](https://user-images.githubusercontent.com/31089501/109052170-2d299480-7690-11eb-90c6-8fff47c8a029.png)

## 4. write_analyze_edit
- [ ] 1. Are you able to add something that does a calculation? Even if it does not throw an exception or prevent folks from moving on. A simple calculator like there is in **prior_work_rank**

## 5.author_order
- [ ] 1. The text says this is the write_analyze distribution, but I believe is prior_work + write_analyze no?
![image](https://user-images.githubusercontent.com/31089501/109053736-e8066200-7691-11eb-9e9c-71c82daf6d66.png)

**Comment by dkngenda** [comment]
@staceypark I am unable to add the functionality you mention in step 4. write_analyze_edit during feb_epic. I'll be moving it to authorship 2.0. I am thinking maybe we move the app to production QA as I research how to implement this functionality

**Comment by staceypark** [comment]
@dkngenda ok sounds good to me
