### ISSUE TITLE
wk2 feb_epic: Edit "SP Referrals" Tab based on asynchronous discussion - Finalize Recommendation by hq_workgroup 2/11

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#1690]
**1. "SPReferrals" Tab name and instructions were written for _MTL Blue_ teams and are likely to confuse _MTL Red_ teams:** 

**I've added four folks who can briefly approve (or provide alternatives to) my two recommended edits below:**
- [x] @branscombj 
- [x] @staceypark 

@anthonycpichardo and @anazariz you may want to track this with **other open Data UI tasks**. 
_Do you want to create a separate **quant_workgroup DEV/TEST/PROD** cards for this?_
#1617
#1618
#1668
#1649
#1677
#1678

**TAB** - **EDIT 1: Recommend that this tab simply say "Referrals" instead of "SPReferrals."**
![image](https://user-images.githubusercontent.com/7454688/107304165-6083e680-6a35-11eb-916e-56f364b90936.png)

**INSTRUCTIONS** - **Recommended edit is to remove the first sentence. But, keep other references to "All with SP" or "SP" because the **SPParams** will continue to be an option that is produced for _MTL Red_ teams.** 
![image](https://user-images.githubusercontent.com/7454688/107304039-24508600-6a35-11eb-8a4e-7ac1b38a59ba.png)

**Comment by staceypark** [comment]
I think we should either keep the "SP" everywhere or remove it everywhere. It is a visual indicator/reminder for me to do an action on that SPReferrals tab if I'm including it in my choice for the Create Team Data Table button.

**Comment by branscombj** [comment]
> I think we should either keep the "SP" everywhere or remove it everywhere. It is a visual indicator/reminder for me to do an action on that SPReferrals tab if I'm including it in my choice for the Create Team Data Table button.
> 
> @branscombj @dlkibbe thoughts?

I think I agree with @staceypark . Facilitators will need to be clear that SP is short for Suicide Prevention but the full name of this  module is Measurement Based *Stepped Care* and Suicide Prevention - if I understand correctly, it's the "stepped care" aspect that brings in the referral to/from piece. So maybe we could try to use the second two phrases instead of just the last one as shorthand in calling out this module: Stepped Care & Suicide Prevention, SC&SP... Not change labels anywhere; just in our verbalizations.

I reviewed the Say guide from a facilitation of  MTL Red point of view and wonder if it would be good to put better descriptions of the modules in, perhaps more like those in the More Info page of the sim UI only edited to remove "model" language. See these versions re: CC as an example:

**Current description and list of complexity reveals in sim UI:**

This model shows how a variety of team decisions interact to impact multiple outcomes at the same time. You can explore trade-offs between decisions such as desired new patient wait times, current patient return visit intervals, and overbooking and how they affect team outcomes like total missed appointments, number of patients in care, and number of patients completing care.

- Balancing Patients
- Overbooking Affects No Shows
- Wait Time Affects Referrals
- Show Sensitivity Sliders

**Current description in Say guides:**

CCParams: Key variables of interest in CC may include median engagement in weeks, appointment supply in appointments per week, return visit interval in weeks, starting rate in patients per week, and new patient wait times.

**Recommended description for Say guides – Red, at least:**

A variety of team decisions interact to impact multiple outcomes at the same time. There are trade-offs between decisions such as desired new patient wait times, current patient return visit intervals and overbooking, and how they affect team outcomes like total missed appointments, number of patients in care, and number of patients completing care. Consider how you balance new and existing patients; how overbooking affects no shows; and how wait time affects referrals.

**Comment by lzim** [comment]
@branscombj 
@lijenn 
@staceypark 
@anthonycpichardo 

**Decision at hq_workgroup:** We're going to to with **no change** on this for now other than considering it more carefully in our language.

**Comment by dlkibbe** [comment]
@lzim does that mean there is no change at all to facilitation/say guides or will there be additional clarification or wording changes in say guides to reflect @branscombj points and your comment to consider it "more carefully in our language?"
