### ISSUE TITLE
wk3_apr_epic: re-create_stockton_agg_experiments_in_sim_ui

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#1691]
I'm in the PSY module of the 640_pct and I can't click go on the pull up text from last time.<br/><br/><br/><br/><br/>

**Comment by jamesmrollins** [comment]
I ran a test of this function and see the below.  This appears to be working normally.

![image](https://user-images.githubusercontent.com/30132017/107707335-8d730c00-6c76-11eb-9620-6a3d2888193d.png)

**Comment by lzim** [comment]
@jamesmrollins 

The is not whether can type and save _new_ meaningless text. 😄 
**The bug is that I could not pull up the text from prior experiments** for **640_pct** in the **PSY module** 😟 
Please test - thanks!

_Please do bring up bugs at **meetings** or via a **ping with a mention** sooner as 2 weeks is too long for any bugs at this point._

FYI for the **PSY Manuscript** - Is the text in the Sim is consistent with the **tt3 for team 1** and what is OSF [jan_write_analyze] r21_psy_jccp - https://osf.io/87chm/ [added the dependency]
@branscombj 
@dlounsbu 
@staceypark

**Comment by jamesmrollins** [comment]
@lzim 

My test above validates that I can save and pull up an experiment.  The function works. 

- How long ago was ". . . experiments from the last time?"  
- Can you see the experiment on your drop down and text doesn't populate, or is the experiment missing entirely?
- Do the experimental settings adjust to the past experiment?

Thanks,
James

**Comment by jamesmrollins** [comment]
@lzim 
**FYI** @branscombj @dlounsbu @staceypark

- Please see table below or also [attached](https://github.com/lzim/teampsd/files/6029773/Copy.of.Experiments_640_pct_2018_05_team.xlsx) for easier viewing.
- Verify if these are the experiments you seek.  
- Please indicate if you need the experiment slider settings, or just the text.  These are old experiments and they are not mapped to the current experiment variable setup.  

Thank you, James

Experiment   name | ourQuestion | ourHypothesis | ourDecisions | ourFindings | time | team data file | group name | model | created | lastModified
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
cwg_50_cetppm_75_2018_9_26 | Combining exp 1 (graduate more people) with exp 2 | Increase in starting rate and increase in graduating rate because we are   spending more time on the first three months. We expect a greater case load   annually. | It is costly to keep existing patients in individual psychotherapy (e.g.   9083X CPT code) in terms of starting more new patients in psychotherapy. The   team can consider stepping patients down out of individual psychotherapy to   services in the Modeling to Learn Aggregate module, such as group or   adjunctive services to think through what would be best for most patients   served by the PCT. | Ten fold increase in completers who graduate over two years and because   of the feedback it should be even greater over time. | 104 | 640_pct_2018_07_18.xlsx | 640_pct_2018_05_team | Psy_PROD.vmf | 2018-11-06T00:28:46.895Z | 2018-11-06T00:36:40.151Z
cetppm_75_2018_9_12 | What happens when we cut the engagement duration by 75%? | We'll be able to start more patients than when we increased the   graduation rate. | For clients on the cusp of being done, more tempted to graduate them ...   "might push out a small percentage a little sooner" | We are able to start ~3 more patients per week (about double the current   rate). | 104 | 640_pct_2018_07_18.xlsx | 640_pct_2018_05_team | Psy_PROD.vmf | 2018-11-06T00:24:00.006Z | 2018-11-06T00:28:45.415Z
cwg_50_2018_9_12 | What if we graduate more patients who complete 8 or more psychotherapy   sessions in their first 3 months? | We expect that if we increase our completers who graduate to 50%, then   we'll free up more slots in the clinic for more patients to start   psychotherapy/EBPsy. | For experiment 2, we will try to step more patients down out of   psychotherapy/EBPsy who are engaged for greater than 3 months. | We found that we increased the start rate for psychotherapy, but not by   as much as we'd hoped. | 104 | 640_pct_2018_07_18.xlsx | 640_pct_2018_05_team | Psy_PROD.vmf | 2018-11-06T00:18:24.762Z | 2018-11-06T00:23:58.43Z
bc_2018_9_12 | What is likely to happen in our team over the next two years if we make   no new decisions? | We expect that we will continue to see fewer Psy and EBPsy patients than   we want because we aren't graduating our psychotherapy patients. | For our next experiment we will reduce the duration of engagement of   patients after 3 months by 75%. | 65% of our patients are in care more than 3 months. We were right - it   was about 76% of patients in care for greater than 3 months. - Sankey diagram   showed that for 1/4 of our patients. The median number of visits is 16 for   75% of patients. | 104 | 640_pct_2018_07_18.xlsx | 640_pct_2018_05_team | Psy_PROD.vmf | 2018-11-06T00:00:52.036Z | 2018-11-06T00:18:22.895Z

**Comment by jamesmrollins** [comment]
#1691 - Pull in anything that we can.

- Models have changed.
- Models will always be updated.
- So, backward capability will be needed moving forward (second half of 2021 as we graduate our wave 1 NIH sites). e.g., We register a log of teams using MTL 2.0 (clear about the model versions, v33 etc.).
- Pull back up what they did in past

### To Do

- [ ] @staceypark Need to recreate the experiments. 
- [ ] @jamesmrollins Send Lindsey exports. Delete the table from the issue.  
- [ ] Put these in a shared folder in Sim UI. Send link to addressees.

**Comment by jamesmrollins** [comment]
Hi @lzim @branscombj @staceypark @dlounsbu .  DEV has successfully downloaded the experiment files for the version 1.7 psy experiments discussed above.  We used the psy model and team data file available in the lzim/mtl/blue/mtl1.7_models directory.  These files are located in the Sim UI Channel of the VA Teams instance available [here](https://teams.microsoft.com/_#/files/sim_ui_workgroup?threadId=19%3Acd8c8a) .  I have also emailed these to you.  Please let me know if you did not get them.

**Comment by jamesmrollins** [comment]
## Discussed at Sim UI Meeting 3/10/21

- Not most urgent for next 14-21 days. 
- Writing up case studies for papers, and need it for that reason too. 
- James start with one team.  Recreate Stockton AGG. 

**Decision:  Start with Stockton.** 
- Stockton cleaner
- Site=Team at Stockton.

**Comment by jamesmrollins** [comment]
Will complete this week and provide a reviewer to @lzim. The charts will provide side-by-side comparisons.  When I get a thumbs from PI, will build in the experiments in "640ha_stc."

**Comment by jamesmrollins** [comment]
@lzim and @staceypark  please find the attached PDF of charts comparing results from the current sim versus the results portrayed in the tt3_agg_team6 report from Stockton.  

### Recommendation

Rebuild the experiments described in tt3_agg_team6 report, verbatim, in the current PROD environment - 640ha_stc_2018_05_team, including QHFD inputs. Follow experiment naming convention.

### Findings

- "Group" service appears to have a slightly higher starting value in the current sim, versus the sim used in 2018 for "Patients Waiting to Start a Service" chart for base case and experiments 1, 2 and 3.  
- All other charts appear to be consistent with the tt3 report

### Concurrence

- [ ]  Concur with recommendation
- [ ]  Concur with comments
- [ ]  Do not concur

--

**Comment by jamesmrollins** [comment]
@lzim @staceypark  I would like to target the SIM UI Meeting, Wednesday, 14 April to validate the Recommendation above, if possible.  Thanks, James

**Comment by jamesmrollins** [comment]
@jamesmrollins will review this card and consider reorganizing into a card for each experiment recreation.  Will complete by 4/19.

**Comment by jamesmrollins** [comment]
From 4/14 meeting:

1.  We want to recreate the R21 Module for AGG and PSY experiments.
2. We want to reproduce all 6 R21 Team Time reports based on reverse engineering the experiments, using the team data from that time.
3. To support participatory research, clinician will need to be able to refer to old experiments in the Sim UI.
4. Stacey Park will provide MTL Menu reports from these teams so @jamesmrollins can upload into the data API in Epicenter supporting the MTL Menu reports.  Note; This was task was completed 4/19 by Stacey Park.
5.  James will create a new card to support experiment reverse engineering.
