### ISSUE TITLE
wk1-3_apr_epic_story_7: Code tt Report Automation

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#1748]
### Objectives:

- [ ] Execute wireframes
- [ ] Test development

**Comment by jamesmrollins** [comment]
## As per conversation with @lijenn 4/21:

**FYI:** @staceypark @branscombj @MattMoore2 @lzim 

### Issue
Jane and Matt would like to ask **660gg_st_george_cboc** team members at their meeting on 4/27 to complete the mtl.how/menu right away.  That will enable Jane and Matt to review mtl.menu results at their prep meeting on 5/4.  Since the Sim UI version of the mtl.how/menu will not be available until May 3, teams may not be able to use the Sim UI version in time to support Jane and Matt's preparation needs.

### Facts Bearing on the Issue
- The VA RedCAP version is still available.
- There are 7 members of this team.
- It would be relatively easy to migrate the data from RedCAP to the Sim UI when the time comes.
- The data migration would directly support testing of the mtl.how/menu function and tt reporting.
- For participants who have not taken the survey by 5/3 (Sim UI menu release), the mtl.how/menu would redirect them to the Sim UI version and tally with the migrated data.
- Sim UI DEV is tracking for delivery of tt reports and Sim UI Admin functionality to TEST by 26 April.  Testing of both functions and documentation review can begin next week.

### Decisions
- We will stay the course for SIM UI Development.  Target 4/28 SIM UI Meeting for QA PROD review.  James will create card by 4/22.
- Jenn will track RedCAP data and coordinate migration tasks with James.
- Migration of RedCAP data will also support testing function of the tt Report.

**Comment by jamesmrollins** [comment]
## ADDENDUM

**FYI: @staceypark @branscombj @MattMoore2 @lzim**

### Additional Facts That Have Come to Light
1. REDCap surveys are truly anonymous.  Since the Sim UI tracks the individual username and associates individual results to the others in the report, we need to know how people responded.  Therefore, we cannot enter in user data from REDCap into the Sim UI since we do not have their identity.
2. The Sim UI based mtl.how/menu can be ready-to-go by Monday morning.  
3. The Sim UI based mtl.how/menu is dependent on the Team Setup feature of the new Admin Dashboard.  This also can be ready-to-go by Monday morning.
4. The blue and red document analysis documented in issue #1907 shows only a few references to mtl.how/menu and the tt report via GIF screen casts.  In all cases, we would need the Sim UI version of mtl.how/menu associated with the "mtl.how/menu" redirect before capturing an updated GIF, because the GIF shows the user entering "mtl.how/menu" into the URL line.  
5. Associated tt reports in the _resources folders associated with affected red and blue documents will need to wait for the completion of issue #1900 Re-create experiments in Sim UI.

### Recommendations/Decisions
1. Move Sim UI version of mtl.how/menu and Admin dashboard to PROD by Monday Morning (likely there by Friday, 4/23 morning).
2. Use the upcoming team as the test case for using Admin dashboard to set up users.
3. Change mtl.how/menu redirect to Sim UI version.
4. Capture updated GIFs.  Open pull requests for relevant lzim/mtl_blue documents and update GIFs. Complete by Monday, 4/26.

**Comment by staceypark** [comment]
@jamesmrollins prototype is looking great for the most part!
1. I'm having issues getting the PDF to come up. I even tried refreshing and pages 2 & 3 are not loading. I am accessing this as "Ralph Malph" outside of the VA. 
![image](https://user-images.githubusercontent.com/31089501/115791119-b69dd000-a37c-11eb-8d51-ae6d1612615f.png)

2. Font type & size
- the logo should always be Myriad Pro since it's an image file
- all the text should be Myriad Pro, and if the system cannot load that, it should default to a sans serif font like Calibri or Arial instead.
- I would make the headings bigger across the graph sections; also make the titles for each of the graphs bigger and black instead of grey. 
![image](https://user-images.githubusercontent.com/31089501/115791178-d6cd8f00-a37c-11eb-8392-0dbeed709dce.png)

3. I think there needs to be more white space in the graph output on the sides.

**Comment by jamesmrollins** [comment]
Hi @staceypark - thanks for the review.

1.  I already have the font issue on my investigation list and am going to check it out.
2.  I will add more spacing to between the graphs, if possible.
3.  I will increase the size of the headings and the questions, and change the color of the questions to black.
4.  I see typos and will fix.
5.  I am having trouble recreating the PDF issue you show above, but will investigate it. 

If we get these fixed tonight, do you want to follow the recommendations shown above?

**Comment by staceypark** [comment]
@jamesmrollins yes the above recommendations seem good to me.
Note for the RedCap <> Epicenter transfer of recreating r21 reports, we could just assign different responses to different known people. Folks wouldnt be going back to look at their indivdual responses & no one else but the facilitators/admin should ever be able to see who is associated with which response, so it doesnt ultimately matter if we don't assign the correct names to people, as long as we get the general team aggregated responses correct.

**Comment by jamesmrollins** [comment]
@staceypark  Thanks for the clarification - I will make it so!

**Comment by lijenn** [comment]
TEST Instance - QA:
- [x] Created a team
- [x] Added members
- [x] Tested MTL Menu from new member (take Menu survey, view results, download pdf)

Feedback for @jamesmrollins 
1. James, for 'Enter Name' here, should it be email instead of name?
![image](https://user-images.githubusercontent.com/59668647/115927111-c549bd00-a438-11eb-8e52-66e52293355d.png)

EDIT: James will edit PROD ver. to look like this:
![image](https://user-images.githubusercontent.com/59668647/115927059-b6fba100-a438-11eb-8c48-825b94335c77.png)

**Capitalize the following:**
2. The h in "how overbooking or overworking.."
![image](https://user-images.githubusercontent.com/59668647/115927262-0510a480-a439-11eb-9e3a-18c370e7952f.png)

3. and H in 'Very high'
![image](https://user-images.githubusercontent.com/59668647/115927292-0c37b280-a439-11eb-89de-c4da63676a62.png)

**Bold the following:**	
4. Bold 'Psychotherapy'
![image](https://user-images.githubusercontent.com/59668647/115927313-135ec080-a439-11eb-90ca-e48dc53ab977.png)

**Language Edit:**
5. Learning Needs - Burnout 
Should say: Burnout - How to reduce provider burnout and improve patient satisfaction with care. 
![image](https://user-images.githubusercontent.com/59668647/115927364-25d8fa00-a439-11eb-9f64-810370bcdf4e.png)
	
6. **TT logo in myriad pro**
The tt logo still looks like its defaulting to times new roman or you could use this logo here?
https://github.com/lzim/teampsd/blob/master/resources/logos/tt_title.png
![image](https://user-images.githubusercontent.com/59668647/115927393-35584300-a439-11eb-87e7-39ee3e36a5dc.png)

**Comment by staceypark** [comment]
@jamesmrollins here's my test:

- [x] create test team
- [x] add members
1. Related to @lijenn's comments above, it should say "Enter Email" instead of "Enter Name" in the first box.  Also once I do enter the person, I only see the email address. The list should show first & last name and the email. 
![image](https://user-images.githubusercontent.com/31089501/115940763-9b53c300-a457-11eb-9f63-7b7e6c300728.png)

![image](https://user-images.githubusercontent.com/31089501/115940720-752e2300-a457-11eb-97ce-5f1dc99094d5.png)

2. From the above second screenshot, I see the options to edit the team vision and arm, but I think we also need the ability to edit the team name in case someone gets it wrong, or it changes or something. 

3. After I created the team, I went to the dashboard and tried to queue the team up, but it does not show up in the dropdown. I refreshed the dashboard and it did. 
 - can you either have it auto refresh once you close out of the Team set-up dialogue or add an instruction to do so for it to process

4. I find it confusing that the logo for all of these are the same when they don't go to the same thing , and they don't function in the same way (meaning some of these are pop-out dialogues and some navigate you to a new page).

![Screen Shot 2021-04-23 at 5 28 31 PM](https://user-images.githubusercontent.com/31089501/115941225-56309080-a459-11eb-93a9-c354c2cd60ad.png)

- [x] test mtl menu: in addition to jenn's edits, here are a few more on wording and spelling. Don't forget to make sure these edits propagate through to the results page as well 😄 
![image](https://user-images.githubusercontent.com/31089501/115941931-71e96600-a45c-11eb-8ee8-ff11cec62ebb.png)

![image](https://user-images.githubusercontent.com/31089501/115943083-bd9f0e00-a462-11eb-95aa-782293d308b2.png)

![image](https://user-images.githubusercontent.com/31089501/115943089-c394ef00-a462-11eb-97c2-a533bbe471f6.png)



5. The PDF shows what my own choice is. I thought we decided it would not do that?
![Screen Shot 2021-04-23 at 6 31 58 PM](https://user-images.githubusercontent.com/31089501/115943000-32257d00-a462-11eb-8abf-a5986c7b659a.png)

6. I figured out that by using my facilitator-associated email on the MTL Menu login page, I can see the team's survey results and how many folks completed it. How does a facilitator view the comments sections (the "Other needs" questions). I'm not seeing it in this view either.

**Comment by jamesmrollins** [comment]
Hi @staceypark and @lijenn - Thank you for your review and comments.  I have incorporated these items into the next push Sunday night, so should have them ready for Monday morning.

**Comment by staceypark** [comment]
@staceypark will test today 4/26 and update the shortlink to mtl.how/menu upon signoff for prod

**Comment by jamesmrollins** [comment]
Hi @staceypark and @lijenn .  Below is what I am tracking for matters related to this issue:

- [ ] Bulletize and increase font size of comments by 20%.

![image](https://user-images.githubusercontent.com/30132017/116157070-325f8b80-a6a1-11eb-826c-0e709a47bbd9.png)

- [ ] PDF report orphan control (cuts charts in half in printed report).  The current PDF generator captures the entire screen as an image object.  We have to figure out how to capture each chart as an image object, in order to control the page breaks.  How to do this is not clear today, we must investigate further.
- [ ] Report outputs as an r-notebook (I may need to create a separate issue for this so we can close some of the tt report work).  This is a custom application that will require some investigation on our part.  We are hopeful, since the r-notebook is a formatted html document.  We are thinking by understanding that format, we should be able to translate report contents into the r-notebook html format.  More to be revealed . . .

**Comment by staceypark** [comment]
@jamesmrollins 
@lijenn and I are reviewing right now. Few questions
1. Related to the gear icon for MTL Demo/TeamPSD/Team Setup/TT
- If we decided on a different icon later, how easy/hard is it to change?
- I feel like all of the functions in the Admin login are "setup functions", but Jenn made a good point that all of the other ones are learner facing too (which is why we have specific icons for them). But those four are not learner facing buttons in the sim.
- I think we had said at some point that we want the learners to be able to pull their own tt reports if they want? Do you remember this being true as well? And if so, we're going to want a specific icon for that. Otherwise, I think the gears are fine for now. 

2. Please edit this error message to say: 
- "Your team has not been set up to take the _Modeling to Learn_ Menu. Please contact mtl.help@va.gov to set up your team."
![image](https://user-images.githubusercontent.com/31089501/116166755-86736b80-a6b3-11eb-871f-e4937afe4e0f.png)

3. The team set-up is buggy making sure team name ends in _team or _ind.
![image](https://user-images.githubusercontent.com/31089501/116167035-406ad780-a6b4-11eb-89c0-025e16656651.png)

4. I noticed this list doesn't auto-sort by time or alphanumeric. Can you add buttons so the name and date/time columns can sort ascending & descending. 
![image](https://user-images.githubusercontent.com/31089501/116167067-4fea2080-a6b4-11eb-859f-700bb8d690f4.png)

5. This still initially prompts to add name instead of email, first name, and last name. Once you add once person though, the first and last name fields start popping up. It's finicky. Also, once members are added, we are still only seeing the email address instead of all three pieces of information. 
![image](https://user-images.githubusercontent.com/31089501/116167148-7e67fb80-a6b4-11eb-8fba-ab514b5e36fd.png)
![image](https://user-images.githubusercontent.com/31089501/116167351-e1f22900-a6b4-11eb-8f96-d4300c3c5bfc.png)

Team Member Set-up

![image](https://user-images.githubusercontent.com/31089501/116167516-372e3a80-a6b5-11eb-84a2-c5bfc89f012f.png)


![image](https://user-images.githubusercontent.com/31089501/116167647-7d839980-a6b5-11eb-92dd-0a9b073732f0.png)

**Comment by staceypark** [comment]
@jamesmrollins regarding the above list of 10 issues.
Unless #3 and #5 (or any other issues) will pose problems with user management, errors in completing the menu, or errors in retaining information about the menu (i.e. teams disappear, user answers disappear because their setup on the backend changes, etc.), then @lijenn and I don't see an issue with moving the shortlink to PROD for tomorrow's use for the team's Session 3 post email.

**Comment by jamesmrollins** [comment]
Hi @staceypark and @lijenn - Thanks for the detailed review.  See my responses below.  I don't think it will be a problem to get most of these up before tomorrow.  Did you plan to set up the first team tomorrow?  If so, I will prioritize the team functionality and turn on the email end user functionality in PROD.

> @jamesmrollins
> @lijenn and I are reviewing right now. Few questions
> 
> 1. Related to the gear icon for MTL Demo/TeamPSD/Team Setup/TT
> 
> * If we decided on a different icon later, how easy/hard is it to change?  **Easy Change**
> * I feel like all of the functions in the Admin login are "setup functions", but Jenn made a good point that all of the other ones are learner facing too (which is why we have specific icons for them). But those four are not learner facing buttons in the sim.

**True**

> * I think we had said at some point that we want the learners to be able to pull their own tt reports if they want? Do you remember this being true as well? And if so, we're going to want a specific icon for that. Otherwise, I think the gears are fine for now.
**When the user navigates back to the mtl.how/menu, they will land in the latest report.  If Report #2 has been published, then it will present when they login.**

> 
> 1. Please edit this error message to say:
> 
> * "Your team has not been set up to take the _Modeling to Learn_ Menu. Please contact [mtl.help@va.gov](mailto:mtl.help@va.gov) to set up your team."  **Got it, will be in place by tomorrow.**
>   ![image](https://user-images.githubusercontent.com/31089501/116166755-86736b80-a6b3-11eb-871f-e4937afe4e0f.png)
> 
> 1. The team set-up is buggy making sure team name ends in _team or _ind. I refreshed and it worked.

**I will check it out**

>    ![image](https://user-images.githubusercontent.com/31089501/116167035-406ad780-a6b4-11eb-89c0-025e16656651.png)
> 2. I noticed this list doesn't auto-sort by time or alphanumeric. Can you add buttons so the name and date/time columns can sort ascending & descending. 

**Got it.  i will see if we can get in by tomorrow, but may prioritize it lower, depending on other things we are correcting.**

>    ![image](https://user-images.githubusercontent.com/31089501/116167067-4fea2080-a6b4-11eb-859f-700bb8d690f4.png)
> 3. This still initially prompts to add name instead of email, first name, and last name. Once you add once person though, the first and last name fields start popping up. It's finicky. Also, once members are added, we are still only seeing the email address instead of all three pieces of information. 

 **We didn't have time last night to put in the fix for this.  Bottom line is it has been redesigned and we intend to construct that interface so it is much clearer.**

>    ![image](https://user-images.githubusercontent.com/31089501/116167148-7e67fb80-a6b4-11eb-8fba-ab514b5e36fd.png)
>    ![image](https://user-images.githubusercontent.com/31089501/116167351-e1f22900-a6b4-11eb-8f96-d4300c3c5bfc.png)
> 
> 6, The add, edit, delete buttons look exactly the same for team setup and team member setup. It would be helpful if in the second pop-up where you add/edit/delete the team _members_, if it denoted as such (i.e. "Team Member Set-up) next to those three sets of buttons in the buttom half of that screen (refer to screenshots from #5 for reference.  

**Yes, this has been included in the re-design**
> 
> 1. The image is a little wide. It needs to be narrower or taller. See original image for proportions.

**Got it, will check it out.**

>    ![image](https://user-images.githubusercontent.com/31089501/116167516-372e3a80-a6b5-11eb-84a2-c5bfc89f012f.png)
> 2. The "b" in "Evidence-based" should be lowercase, but otherwise you got all the text fixes 🥳

**Got it**

>    ![image](https://user-images.githubusercontent.com/31089501/116167647-7d839980-a6b5-11eb-92dd-0a9b073732f0.png)

> 3. Is this in reference to the issue about the PDF not rendering properly? 

**PDF renders ok now, but just doesn't have orphan control."
> 
> > PDF report orphan control (cuts charts in half in printed report). The current PDF generator captures the entire screen as an image object. We have to figure out how to capture each chart as an image object, in order to control the page breaks. How to do this is not clear today, we must investigate further.

**Comment by jamesmrollins** [comment]
@staceypark and @lijenn Update:

- All matters regarding mtl.how/menu above have been resolved **with exception to the PDF rendering with orphan controls.**  We need more time with that.  
- I delayed any more work on the Admin workflows (#1759) until we come to consensus about who is using it and how it will be displayed.  We should discuss this at the 4/28 SIM UI meeting.  I will reference this part of the discussion in #1759.  The questions I have are:
  - Are Facilitators going to set up teams?  If so, do we want to move the Team Setup icon to the facilitator dashboard?  We could change the logo to make it unique.
  - Do we want the set up to be viewed as a single page, or as pop ups as in the current version?
  - Are facilitators going to update team data and p-charts?
  - Are facilitators going to set up tt reports?

**Comment by staceypark** [comment]
decisions from 4/28 sim ui workgroup: 
we will add the team name and specific experiment names in the tt report (for both the recreated experiments and moving forward).

team name can be parsed from the "group/team name" entered into epicenter

**Comment by jamesmrollins** [comment]
Hi @staceypark.  

## Problem
After some thinking this through - while we can parse the team name from the team name string from Team set up, we would have difficulty interpreting what needs to be capitalized.  For example, if we take a sample team name like shown below and convert it with the rules shown below, the outputs would be:

Title Case:  666aaa_st_francis_bhip  would be St Francis Bhip
Upper Case:  would be ST FRANCIS BHIP
lower case:  would be st francis bhip

I could look like:

![image](https://user-images.githubusercontent.com/30132017/116613351-6d55ff00-a8ed-11eb-8a6b-c55765c2bef7.png)



Which do you prefer?  It will be difficult, but not impossible, to create conditional logic to detect acronyms but we would need to assemble and maintain the listing (creating more work).  **I don't recommend this.**

## Recommendation

Recommend that we use the team name verbatim and post it on the lower bottom left of the report?

**Comment by staceypark** [comment]
@jamesmrollins I think we could either do title case (I think it looks fine like that) or do all lowercase since they're used to that in the sim already.

@lijenn what are your thoughts on it?

**Comment by jamesmrollins** [comment]
@lijenn @staceypark it would look like this:

![image](https://user-images.githubusercontent.com/30132017/116620475-bc546200-a8f6-11eb-816e-45639bf18d41.png)

**Comment by lijenn** [comment]
@jamesmrollins I think we should use all lower-case as Stacey mentioned to stay consistent with other parts of the Sim.

**Comment by jamesmrollins** [comment]
@lijenn @staceypark   Lower case - Roger

![image](https://user-images.githubusercontent.com/30132017/116632572-5672d500-a90c-11eb-9a17-1ab5338b7add.png)

**Comment by jamesmrollins** [comment]
## DEV Completed with This Card
1. Completed mtl.how/menu login functionality.
2. Completed mtl.how/menu main page and facilitator dashboard, with missed question error control.
3. Completed tt1 report page, with PDF print out capability.  tt1 report page includes individual results in orange, that can be toggled off.
4. Completed preliminary tt Admin functionality (pop up structure, team-model-experiment query and listing)

## Work Moved to May Epic
1. Development of mtl blue tt 2 report.
2. Development of the mtl red tt2 report.
3. Completion of the tt admin functionality.
4. r-notebook export functionality.

## Work Moved to June Epic
1. Development of p-chart functionality in Sim UI.
2. Development of tt3 report - p-chart inclusion.
