### ISSUE TITLE
may_epic_story_7: Automate MTL Red tt Reports 

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#1812]
### Check off requirements to verify progress through feature_tracker.
- [ ] 1. **DEFINE in work_breakdown**
  - [ ] a. **what & why** - **written definitions of requirements** in a **numbered checklist** on the **master_feature_card.**
    - [ ] 1. Create new wireframe for producing tt reports for MTL Red sites 
    - [ ] 2. See #1536 for decisions on which elements to include
  - [ ] b. **date & who** -  **Verified** requirement definitions an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 2. **DESIGN** in **operations_to_do** and **research_to_do**
  - [ ] a. **what & why** - **_MVP_ of design** of requirements in a **algorithm map, wireframes or design** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** design **asynchronously** or an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 3. **DEVELOP** in **under_development** - "frozen"

  Task Cards:
  #
---
- [ ] 4. **TEST in functional_test**
  - [ ] a. **what & why** - **TEST requirements** using **testing_checklist** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** via TEST **asynchronously** or an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 5. **PROD in done**
  - [ ] a. **what & why** - **_DOCUMENT_ feature** using **document_tracker** for the **5 D's.** 
  - [ ] b. **date & who** -  **DELEGATE**
    - [ ] **describe_learners** [Jenn & Rita]
    - [ ] **detail_facilitators** [Jane & Debbie]
    - [ ] **document_team** [Anthony]
    - [ ] **disseminate_scientists_va** [Anthony]
    - [ ] **depend_products** [hq & ees]
  
  Task Cards:
  #
---
- [ ] 6. **closed** - fully documented, trained and ready for the next release.

**Comment by staceypark** [comment]
@lzim @jamesmrollins @lijenn 
I found this decision from last November on #1536. 
If this is true, then we need to have this menu piece ready before the next red team's part 2 session which I believe is April 1 (@lijenn can you validate that I'm reading the calendar correctly) 
> **Discussed at 11/2/2020 Workgroup Leads**
> 
> **1. Can we get tt_reports exported directly from the Sim (what about Red conditions?)?**
> 
> * If we move this from RedCap (keep RedCap for research measure only), then this can be in the Sim and we can use mtl.how/menu for blue and Red.
> 
> **2. Do we want to include the needs assessment in Red Sites to narrow down to which Team Data Table is really the focus?**
> 
> * Does this fit w/what we said in the R01 about AF (and in IIR about uQI)?
> 
> **3. Ultimate feature request functionality here would be that when teams click on the "Export" icon from the Expanded Outputs and Text Section, it would produce all their work to date, i.e., their tt_report.**
> 
> FYI: @staceypark @lijenn @anthonycpichardo @jamesmrollins

**Comment by staceypark** [comment]
Second piece of decision regarding MTL Red found on #1536.
@lzim I'm not sure why we thought there would be 3 tt reports following the survey measures timeline though. We mapped out only 1 tt report for NIH Red and 2 reports for VA Red.

> 12/9 support wg:
> 
> * _mtl_ red tt report: create tables similar to team data table in the sim (see below)
> * we want 3 tt reports similar to _mtl_ blue with new query run for all team data tables (cc, mm, psy, agg, sp tabs) each time:
>   
>   * baseline
>   * 3 months
>   * 6 months (including pcharts* just like _mtl_ blue)
> * *adding pcharts to the tt report is a SQL-R workflow that needs to be fleshed out and automated as well
> 
> ![image](https://user-images.githubusercontent.com/31089501/101696717-60626d00-3a2b-11eb-81be-ae25134e0e9a.png)

**Comment by jamesmrollins** [comment]
Hi @staceypark .  I am still a little fuzzy, and concerned about timeline.  With what I have currently planned for MTL Blue, I should be able to deliver a Blue MVP by next week Thursday.   I am not sure if I can support the same timeline on this, yet.  With that said,

### Understandings:
1.  I hear that we want to provide the user functionality from the _Export function of the Outputs and Text page_, that would allow them to download a tt report, in a pdf format.
2.  I hear that there will be two RED formats, NIH Red and VA Red.  NIH will require 2 reports, and VA will require 1 report OR both will require 3 reports. This needs to be decided.  But in general, RED teams are NOT using the sim.  They are in effect making changes (or not) based on trends identified in Team Data only.  They are kind of a "control group" to differentiate the effect of SIM usage vice BISL usage.
3.  The proposed Epicenter based RED tt formats will provide tables and charts based on team data results only, as they are downloaded at interval from BISL. **There will be NO Sim UI results.**

### Observations:
1.  If they are not doing experiments, they will not have logins to the Sim UI.  If they don't have logins, then they cannot access the tt report from the Outputs and Text menu as was described back in November.  
2.  They can identify their team ID from mtl.how/menu and select an export from there.  **However, any team would be able to access their results.  This is not true for BLUE team's TT2 and TT3 reports because only the admin has access.**
3.  We will likely have to figure out a way to read the team data file directly into the data api through the Dynamic Data folder.  In the current strategy, the Sim UI does NOT read the Team Data file directly, it reads it through the "Get direct constants" function of the model variable which is associated with each data element in the table.  This will become less of an issue when we develop the admin dashboard by May 1.

### Questions:
1.  Will they take the MTL Menu questionnaire? OR is there a questionnaire unique to them?  This is important - we will need to present RED teams with a landing page to access their reports.
2.  Is there a listing of the standard charts they will want to see, by iteration, for each data set (i.e., cc, mm, psy, agg, sp)?  BTW I will need this for BLUE reports as well.

**Comment by lijenn** [comment]
> @lzim @jamesmrollins @lijenn
> I found this decision from last November on #1536.
> If this is true, then we need to have this menu piece ready before the next red team's part 2 session which I believe is April 1 (@lijenn can you validate that I'm reading the calendar correctly)
> 
> > **Discussed at 11/2/2020 Workgroup Leads**
> > **1. Can we get tt_reports exported directly from the Sim (what about Red conditions?)?**
> > 
> > * If we move this from RedCap (keep RedCap for research measure only), then this can be in the Sim and we can use mtl.how/menu for blue and Red.
> > 
> > **2. Do we want to include the needs assessment in Red Sites to narrow down to which Team Data Table is really the focus?**
> > 
> > * Does this fit w/what we said in the R01 about AF (and in IIR about uQI)?
> > 
> > **3. Ultimate feature request functionality here would be that when teams click on the "Export" icon from the Expanded Outputs and Text Section, it would produce all their work to date, i.e., their tt_report.**
> > FYI: @staceypark @lijenn @anthonycpichardo @jamesmrollins

The next Red Team's Part II is **Wed. March 24th**.

**Comment by jamesmrollins** [comment]
@lijenn @staceypark  The dates is going the wrong way!! Working on wireframe, introducing a mtl.how/menu splash page so red and blue users can be directed to the appropriate actions and reports.  I think we might make it 😁, we'll see. I will give it my best shot.

**Comment by jamesmrollins** [comment]
This issue does not have an estimate since coding effort estimate is in issue #1748

**Comment by hnorthcraft** [comment]
#adjudicate_memo per comment above adding dup label as efforts tracked on another card.
