### ISSUE TITLE
 Create video walk/talk-throughs of system stories

### ISSUE THREAD

**Issue by branscombj** [lzim/teampsd#1815]
### Use system stories in #1510  to create very short, clear, video talk-throughs with mouse-work of the system stories in each module: 

Work had been split into each of their own smaller task cards:

MM  #1946
- [ ] Balancing existing and new patients 
- [ ] Wait time affect referrals

PSY #1946
- [ ] Balancing existing and new patients

AGG #1947 & #1948

- [ ] Fatigue increases clinic cancellations (R)
- [ ] Appointment backlog extends return visit interval (B)
- [ ] Overtime relieves work pressure slowly (B)
- [ ] Overtime relieves work pressure quickly (B)
- [ ] Burnout increases clinician quits (B)
- [ ] Fatigue increases ending early (B)
- [ ] Wait times affect intake evaluations (B)
- [ ] Start delays affect treatment decisions (B)
- [ ] RVI delays affects [sic] treatment decisions (B)

CC #1949
- [ ] Balancing existing and new patients 
- [ ] Wait time affects referrals 

SP #1949
- [ ] ??

**Comment by lzim** [comment]
@dlkibbe @staceypark @lijenn 
- Re-named title to say **"video"** not "**gif**.
- These need the audio story telling that goes with tracing the loops that .gifs don't have.

**Comment by branscombj** [comment]
### Recording a video in Teams
Go to the calendar in Teams; click Meet Now and you can start a meeting with yourself, click More Actions and Start Recording. Share screen, use mousework, talk, etc. Go to More Actions to Stop Recording. Recording is saved in Chat.

@lzim @staceypark @lijenn @dlkibbe

**Comment by staceypark** [comment]
@branscombj I see your question about how to use the template.
This template is for documents that go in the document_tracker. Not sure if you meant to use that one or a regular task card template?

I reassigned the 'assignees' on the right side to be you & @dlkibbe as the folks working on the issue, which is how we have standardized these.

**Comment by branscombj** [comment]
@staceypark - OK great, so when I create an issue I don't have to use the issue template? I have deleted all the extra template instructions so I don't have a lot of other stuff to read and ponder what to do with 😌

**Comment by lzim** [comment]
**Discussed 4/29/21 hq_workgroup**
- [x] @lijenn  to co-facilitator prep for **session 6 wk4 may_epic**

**Comment by lijenn** [comment]
Hi @branscombj and @dlkibbe @dlounsbu ! Since teams are either entering the Sim/about to enter the Sim, we should plan to get the video walk through for the system stories up before Facilitators enter Blue Session 6 which focuses on System Story.

The first S6 prep meeting starting next Tues. 6/1.
The Live s6 team meeting on Tues. 6/8.

To record, Jane documented steps [here](https://github.com/lzim/teampsd/issues/1815#issuecomment-801978159) on how to start a meeting by yourself and recording the meeting to create these videos. 

Any thoughts or ideas on how we could divvy up the work? 

We could try to split up the system stories that need to be walk through, I have tried to split up the stories in the following issue cards before:
- MM and Psy - #1946
- AGG - #1947 & #1948
- CC & SP - #1949

**Comment by branscombj** [comment]
Hi @lijenn - Yes, I've been thinking about it since Matt and I will be prepping a "system story" for St. George next Tuesday. In terms of prioritizing, St. George will be **AGG** and KC will probably be **PSY**, so those should be among the first - not sure about the other Blue teams, @dlkibbe and @dlounsbu ?

I suggest the 3 of us meet in Teams and each practice walking through one or two loops using the scripts I wrote out, then divvy them up. We could record the practice ones during the meeting. I have a couple of questions about additional content to include or not for the video renditions that we can discuss. I think I finalized system stories for everything except SP? which I think you and I divvied up David?
