### ISSUE TITLE
wk4 mar_epic: edit time stamp and language in mtl blue session 2 say guide

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#1819]
- [x] **align language for session 2 about # of ways to view data to this text:**
“Data UI Excel tabs are either viz (team trends) or data (Veterans-specific). Within viz tabs, the graphs and count tables can be viewed separately, but correspond to one another. Changes you make to filters on a viz tab table, show up in the graph, and selections you make in the graph are reflected in the counts. Data tabs are where you can view detailed information about Veterans served in your team’s clinics within the last two years.”
- [x] **double-check the time stamps for MTL Blue Session 2**

**Comment by lijenn** [comment]
Hi @branscombj and @dlkibbe :)! May I please get some feedback the wording/instructions for the types of ways to view the data in the facility/data ui file mentioned in the [Facilitator Session 2 Say Guide](https://github.com/lzim/mtl/blob/master/blue/session02/s02_facilitator/mtl_session02_say.md)?

See below for the highlighted portion, a QIIC brought up that this may be confusing as its mentioned 2 types of ways to view the data and then at the end it says 3 ways to view the data. 

In the facility/data ui file, there are 2 types of tabs (the Viz and Data tabs at the bottom of the spreadsheet), but the Viz tabs have the graph and the table (referred to as Count), so there is technically a total of 3 ways to view the data.

![image](https://user-images.githubusercontent.com/59668647/111812448-61f6c900-8895-11eb-91b1-5f8efbd5eb84.png)

I looked in the Learner Say guide and we don't mention the number of tabs/views there are so no edits are needed there. 

**Thoughts on editing the top highlighted part to be: "There are three types of view options across the two types of tabs at the bottom of the spreadsheet." and keeping the bottom highlight to be the same?**

**Comment by dlkibbe** [comment]
@lijenn @branscombj -- something to start with / react to:

In the data UI, we can view the data in two ways: 1) a graphic or visual "VIZ" format, or 2) a sortable spreadsheet.
For the VIZ format, we have two options: 1) visual charts of trends over time, or 2) visual representation of counts per month.
For the data spreadsheet format, we look at the patient-level data.

**Comment by branscombj** [comment]
I've always been a little confused by what we refer to as the data UI. My understanding has been that even though you browse to mtl.how/data and open up some views with data for your VISN, you're not in the "data UI" until you're in the interactive excel spreadsheet. Do we still call that first interface the "splash page"? I need a data UI refresher anyway before I start co-facilitating (!) so I'll go in and practice this afternoon after my meeting at 2.

**Comment by lijenn** [comment]
@dlkibbe Sounds like your thinking of sticking to two ways to view the data in the data UI (from the VIZ and Data tabs) and then specifying that theres 2 formats in the VIZ tab. 

Something to consider as well to the language change is how the markdown tables would change since it's the only visual representation of the instructions. Trying to think of the most minimal amount of changes we could make...

@branscombj No worries, here's the updated workflow in a nutshell.
Might help you and @dlkibbe to think through this language update in the Say guide if you guys go through the workflow? 
I just emailed you both a team that has completed MTL Red and you could refer to their folders as they are the most up-to-date, not including the team info here due to confidentiality. 
1. Go to mtl.how/data
2. Look at the facility data file, e.g. xxx_facility.xlsx. This file is not filtered to the team's patient level data as its showing the entire health care facility's data. 
   - This was previously known as the "splash page" where we would have an interactive excel sheet appear on the website (you didn't have to manually open a file). We removed this due the website not being able to support this feature anymore so it is now it's own excel file known as a facility file that needs to be manually opened.
3. After looking facility, the team will go to their team folder which will have their:
- team data ui folder with their team data_ui excel file (This file is filtered down to their team's patient level data)
   - This is used in MTL Blue Session 2/MTL Red Part I
- team data table folder with their team data table excel file
   - This is used in MTL Blue Session 3/MTL Red Part II
