### ISSUE TITLE
wk4 mar_epic BUG: Data_UI unable to grab previously selected clinic list

### ISSUE THREAD

**Issue by anthonycpichardo** [lzim/teampsd#1825]
From the data_ui users are unable to populate their previously run clinic lists from get-patient-level-data.

Expected behavior: When the button is pressed, the selected clinic list should populate.

**Comment by anazariz** [comment]
@lzim @staceypark @lijenn @anthonycpichardo 

Following is the code segment that runs when the "Get previous clinic..." button is pressed.
------------------------------------------------------------------
Sub getPreviousClinicsPatientLevel()

On Error Resume Next
'clear out clinic list
For i = 0 To Sheets("ClinicSelection").clinicBox.ListCount - 1
    Sheets("ClinicSelection").clinicBox.RemoveItem (0)
Next i

'go fetch clinics from hidden sheet
**If Sheets("Hidden").Range("l3") = "" Then**
   **Set rng = Sheets("Hidden").Range("l2")**
**Else**
    **Set rng = Sheets("Hidden").Range("l2", Sheets("Hidden").Range("l2").End(xlDown))**
**End If**

If rng = "none" Then
    Exit Sub
End If

For Each cell In rng
    Sheets("clinicselection").clinicBox.AddItem cell
    msg = MsgBox("Row:" & cell.Row & " Col:" & cell.Column, vbOKOnly, "2")
Next cell
On Error GoTo 0
End Sub


**Code works based on values in Columns 12 and 13 (see bold text above). The line with the "msg =" shows what cell is selected (when the button is pressed.)**
  
![image](https://user-images.githubusercontent.com/39805164/113068433-243a5000-9173-11eb-8b6f-c8b92aa3e2ab.png)

However, there is nothing at that location and I do not see a code segment that will put something there!

![image](https://user-images.githubusercontent.com/39805164/113068703-b0e50e00-9173-11eb-9064-5582174ef9b7.png)

I tested this with an older version of the Data UI to make sure that this is not due to a recent change. 
So, I need to understand what the requirements are for this click (what should it do?).

**Comment by anthonycpichardo** [comment]
@anazariz  My understanding of the functionality is that when the button is pressed, the cliniclist should be update to "populate the Selected Clinics when either 'Get Patient-Level Data' or 'Create Team Data Table' was last run"

Meaning if I pressed either of those two buttons with Clincs 12, 25, and 42 selected from the list then if I change my selected clinic list for some reason (reset my filters, started selecting different clincs, etc.) I should be able to press the "Get Previous Clinic List" buttons and have my previous selection be restored i.e. Clinics 12, 25 and 42 are the clinics in the selected clinic list again.

**Comment by anazariz** [comment]
Closing this issue as it's being handled in #1867
