### ISSUE TITLE
wk2 may_epic story_5 task: ATO for PHI/PII

### ISSUE THREAD

**Issue by anazariz** [lzim/teampsd#1915]
**ATO for PHI/PII**

Need the same level of ATO for our new Online SharePoint as we have for our existing On-Premises version.

**Comment by staceypark** [comment]
from 4/29 quant workgroup:
In order to retain the data tabs of the data UI that we know frontline teams need, and we hoped to learn ATO lessons from Story 6, need to be applied to Story 5.

ATO Epic as something they're moving forward without us.

Preventing Liberty IT - witholding, moving forward.

Key Learning Need: How to navigate the ATO world of OIT...Team PSD needs to learn this across the board

**Comment by lzim** [comment]
**discussed at hq_workgroup 4/29/21**

@staceypark will you see if you can get the links from @anazariz 
It sounds like he didn't find any information about this.

Will you try and I will escalate to Melanie?

**Comment by staceypark** [comment]
@anazariz can you provide an update on where the links are?

**Comment by anazariz** [comment]
@staceypark, Related Links (Story 5 - SharePoint only - PBI will be appended to this list shortly) : #1915, #1917, #1918, #1938, #1939

**Comment by staceypark** [comment]
@anazariz emailed Melanie again 5/6

**Comment by anazariz** [comment]
TeamPDS met with Melanie's team on 5/10. Melanie said that her team could help us work through the ATO process. She'll update us on her progress in a couple of days.

**Comment by staceypark** [comment]
update 5/13 we will be inheriting the parent ATO and do not need to pursue our own separate one.
