### ISSUE TITLE
wk3 may_epic task: story_5 - close the gaps

### ISSUE THREAD

**Issue by anazariz** [lzim/teampsd#1917]
**Story 5 - Close the gaps**

Make our online SharePoint look and act like our on-premises version. 

Migration did not bring in all the components of our on-premises SharePoint to the Online platform. The gaps need to be close.

1. Make the Menus look similar
2. Make the pages look similar
3. Make sure all links are there and behaving as expected

**Comment by staceypark** [comment]
@anazariz 
Can you help me understand the specific ask for this task? 

FYI: @lijenn

**Comment by anazariz** [comment]
Did a walkthrough with Jenn Li of our SharePoint online platform. I added Jenn Li to the list of administrators a brief training for what web parts are and how they can be used to close the gaps (make the online version look and act like the on-premises version).

**Comment by lijenn** [comment]
@anazariz, @staceypark and I have made the final updates to the SharePoint homepage, it now looks and acts like the on-premise version. This specific edit was tracked in #1904.

**Comment by staceypark** [comment]
5/6 update:
@lijenn and @staceypark updated the new sharepoint page to match the old one.
only remaining items are:
1. Request New Team Folder
2. Request Team Membership Change

@anazariz will look into using PowerForms instead of Publisher tomorrow Friday 5/7 and provide an update on how to do this.

**Comment by anazariz** [comment]
Worked with @lijenn on Friday (5/7) on exporting the InfoPath forms from the on-premises SharePoint and then importing them back into to online SharePoint (work is currently in progress). 

It must also be noted that Microsoft InfoPath has been deprecated in favor of the Microsoft Power Platform. InfoPath will not see new improvements or feature, but it will be supported for a few more years (the date of retirement has been changing).

**Comment by staceypark** [comment]
hq meeting 5/13:
**two buttons request new team folder & request team membership change**
- look and feel of buttons for learners will have minimal impact even on new SharePoint (this also means no learner-facing documentation needs to change)
- we will use Power Forms instead of InfoPath, which will allow us to have automation on the backend when users fill out the form (@lijenn @staceypark will include this update in admin mtl.how/data documentation)

**Comment by anazariz** [comment]
**SharePoint OnLine Update:**
 
@lzim  @staceypark  @lijenn 
 
I have closed most, if not all, of the gaps of our SharePoint online site.
 
I created the missing links (a bunch of them) 
I created 2 new InfoPath forms and linked them to the correct SharePoint menus.
I created a Power Automate job that sends emails to Admins (on behalf of whomever we ask it to - e.g. MTL.Help) - we can do a lot of automation with it now that it's based on Power Automate (including creating new folders).
By the way, SharePoint Workflows are also being deprecated in favor of Power Automate.
 
All in all, the heavy work is complete. We still have to do testing including security checks.  
 
Note - Power Automate has to run under someone's account. Right now it's running under my account but in cases like these, it should be running under a systems account. We'll have to figure that out.
