### ISSUE TITLE
Increments in the sim UI - Proposal based on today's Team Meeting

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#193]
Hello Everyone,

This is something we discovered using the MTL 1.6 save dialogue, related to the team data table, the experiment sliders and the sensitivity test sliders in particular. We have a proposal below. 

- Right now the sensitivity sliders in the experiment display increments by 0.1 from 0 to 2. But in the save tile, you can only pick numbers in increments of 1.  

We have also previously had issues with dividing values (i.e. appointment supply) evenly, with the increment availability we had in the sliders. 

Proposed solution:

- use increments of 0.5 in experiment tile sliders to account for both issues

- AND

- Make team data table values whole numbers

Andrew and Tom will work to have the values feeding into the sim come out to whole numbers through rounding functions.

James would need to adjust the experiment sliders and save tile dialogue to account for 0.5 increments.

@TomRust @holbrooa @jamesmrollins @staceypark @branscombj @dlkibbe @dlounsbu

**Comment by branscombj** [comment]
This will be a huge help and relief. Thank you all!

**Comment by jamesmrollins** [comment]
Hi All,
Some feedback here:
1.  If Andrew rounds the outputs into the Team Data, they will reflect as such in the tables.  However, BC icon base case values are calculated and may still return decimal fractions.  
2.  We can increase the increment on the sensitivity sliders to .5, no problem.
3.  We will not be able to use decimals in the filename string in the save function.  Since we are dealing with .5 increments, perhaps we should just use the word "half" or a code, such as hlf.  So 1.5 would be 1hlf, implying "One and a half."  Or, perhaps, we could use "pt" to take the place of the decimal, so 1.5 would be 1pt5.

Thank you,
James

**Comment by lzim** [comment]
Thanks @jamesmrollins 

1. This is going to have to be a second discussion with at a minimum, @TomRust @holbrooa when Andrew returns to resolve who exactly will do any rounding.
2. Okay, let's consider this in relation to 3.
3. The save dialogue uses the first initial of each word in the variable name, and I find "hlf" confusing in that context. Standardization is "pt" and "pts" refer to patients in units elsewhere. So, I don't love the use for "pt5." We decided to use "pnt" as our for point. So, I prefer "pnt5" as our standard if we also move to all .5 increments on sliders. 

Others? We're going to need a decision on this by Monday 9/24/2018!
:hourglass_flowing_sand:

Thanks!

**Comment by jamesmrollins** [comment]
Let me talk to dev on the decimal issue. Maybe a work around available.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by jamesmrollins** [comment]
@lzim @TomRust @branscombj @holbrooa 
This is our proposed work-around for the decimal-in-the-filename problem.  We will offer another drop-down for the sensitivity variables that are broken down by tenths.  However, the naming is still alpha-numeric in the filename.  For example, "1.5" would be "1dc5" with "dc" meaning decimal. 

Any movement on changing the rounding on the Team Data?

Thank you,
James
![all sensitivity variable decimal fractions](https://user-images.githubusercontent.com/30132017/46021818-4d576280-c096-11e8-9004-0a8a63d8ba67.png)

**Comment by branscombj** [comment]
For nearest-half rounding, how about just adding "f" for hal**f** or **f**ive - e.g. 2.5 = 2f; 0.5 = 0f. 
I would've suggested "h" but we use that in other unit abbreviations. 
This doesn't help with nearest-tenth rounding, so if we have that for the sensitivities, the "dc" makes better sense (and should be used in both cases for consistency). Could sensitivities be thought of as percents (i.e., move the decimal place over so we only have whole numbers)?

**Comment by holbrooa** [comment]
Easy enough on my end.  Are we talking about just rounding some values, or all of them? There are a few that can get pretty small, so rounding to whole numbers would be a big deal. Start rates are a good example - 1 new patient per week would be a lot for some teams/services. Maybe those get rounded to tenths? And I assume the percentages would be whole numbers per cent, i.e. 0.##

**Comment by jamesmrollins** [comment]
Sorry, I just realized I am going the wrong way with the scale!  I thought we needed tenths, not halves.

Sensitivities are dimensionless variables and percents are easily understood by most people.  So it should be possible.  If I give 150% effort, I know that is above and beyond.  In the sim, it would be 1.5.  

Another option may be to use a Likert type scaling:  0= not sensitive at all (NSA), .5 = not very sensitive (NVS), 1 = somewhat sensitive (SWS), 1.5=sensitive (S), 2 = very sensitive (VS).    

@holbrooa  I will defer to @branscombj  regarding the needed rounding.  My impression, and I may be incorrect, is that the decimal fractions subliminally indicate a degree of accuracy not really present in the model.

**Comment by lzim** [comment]
We made a decision - for adding a sensitivity drop-down to the save dialogue.
It will be in 0.5 increments, but as part of the variable name it will use "d" for decision.

Example is 1.5 would be 1d5

**Comment by lzim** [comment]
@holbrooa Welcome back!!

If you recommend rounding to the tenth and can do it in the team data table, can we call that decision?
Sound okay to you, Tom from a model point of view?

Thanks!
@jamesmrollins

**Comment by jamesmrollins** [comment]
@lzim @staceypark @dlkibbe @branscombj  @holbrooa @TomRust 

OK, the sensitivity sliders should be set at .5 increments.  The way one uses the decimal fraction in  experiment naming is explained below.

First, the term "Decimal" is listed in the Variable Drop Down menu of the Save Tile.  It is in the Variable Drop Down, instead of with the Number Drop Down, because the Number Drop Down can only have integers.
 
To use the "Decimal" in your number string, do the following:

1.  Select your Variable from the drop down and click on ADD.
2.  Select your first number from the Number drop down and click on ADD
3.  Select "Decimal" from the Variable Drop Down and click on ADD. When you click ADD, it should put the letter "d" right behind the number. If you selected "1" and then "Decimal" it should look like "1d" in the filename string.  
4.  Select your next number and click ADD.  The next number should fall in directly behind the "d" in the string.

Let me know if you have any questions.

James

**Comment by lzim** [comment]
Andrew will implement rouding - Rounding will occur in the data table.

In the data table variables will be mixed with some whole numbers, some tenth and some hundredth:

- Percent will be whole digits.

- Slider increments need to have the same granularity increments as the team data table:

- For example, appointment supply in data table and experiment sliders needs tenth decimal.

- New patient start rate is the only varible that requires granularity to the hundredth.

DECIDED to add a column to the Master Crosswalk:

https://github.com/lzim/teampsd/blob/master/resources/master_crosswalk/Master_Crosswalk_Table_v11_12SEP18.xlsx
