### ISSUE TITLE
AGG change proposal -- Rename variable "Appropriate Patient Start Rate for Supply" MERGE with #185

### ISSUE THREAD

**Issue by TomRust** [lzim/teampsd#194]
It seemed like this variable was hard to explain and hard for the TAS people to understand, and should be re-named.  I've attached a proposal to make it clearer and more accurate -- changing both the variable name and the blue lines in that area of the model diagram.

What do you all think?

[Change to AGG diagram - Sept21.pptx](https://github.com/lzim/teampsd/files/2406866/Change.to.AGG.diagram.-.Sept21.pptx)

**Comment by branscombj** [comment]
Hmmm. I appreciate your working on it. Telephone would probably be more efficient but some things going through myhead:

- If it's not something that gets turned off/on or adjusted, does it need to be there at all? Why not just have all the arrows from supply, RVI etc that determine start rate point to start rate?
- If it does get turned off/on so the user can shut off those connections and dial in a start rate, how about showing it as a switch like the service proportions one?
- Seems like the variable is something like "auto-adjust start rate to accommodate supply and demand".

**Comment by lzim** [comment]
Thanks @TomRust and @branscombj !!!

**PROPOSALS to RESOLVE RELATED ISSUES #185 and #194**
- Importantly, there is incompleteness in this issue #194. Based on our open issues https://github.com/lzim/teampsd/issues **this issue #194 is part of it, but it omits the related KEY variable switches that EVERYONE struggled to understand in AGG,**  represented by issue #185 **already open** in TeamPSD issues with label "need_decision" (*GitHub pro tip:* For any issue just type # and the number and it will be automatically hyperlinked to that issue thread for everyone, for example, #185 and #194 - So EASY :boom:).

**ISSUE #185**
@staceypark started this issue 10 days ago and asked for an update 3 days ago. However, she only pinged @TomRust, @jamesmrollins and myself. Now everyone is in the loop, which is better. ⚡️ The proposal from our meeting was to use this language indicated in #185: "Service proportions matched across model variables"

**Here is my slightly adapted proposal, based on @staceypark's recommendation to use "balance" and my understanding of equilibria in system dynamics modeling. The .png below show the places it occurs.  *I propose that we WILL move forward with this language unless we discuss and adopt something different via GitHub by Monday 9/24/2018:***

- **Use "Service proportions balanced across team variables"** instead of
- "Appropriate service proportions from supply," which we learned was a *misnomer* because this is estimated from many more variables than simply appointment supply, and as @jamesmrollins has been saying "appropriate" is loaded and may misrepresent what is estimated/meant.

*I like **"Service proportions balanced across team variables,"** because **this clarifies the key difference between the red and green service proportion experiments in AGG.**  **Red** "Service Proportions from Team Data" are **read** from team data and likely unbalanced, as decisions were historically made without MTL resources. **Green** experiments "Service Proportions Balanced across Team Variables," balances service proportions accounting for several team variables (better than to say "team variables" than  to say "model variables," I think).* 
-  Shout-out to @branscombj who (I believe) coined **"Red equals read from team data,"** at the *MTL Facilitate Pilot.* It's going in the ***MTL fidelity*** lexicon for sure 📝 ]
- Note here is the current **"i" information in the Experiment Tile:** *"User can set a new percent of patients triaged into each downstream service each week after their intake appointment, regardless of whether or not the team has enough supply for the patient demand. The default value of "-0.05" uses the equilibrium value, based on the supply available."*

- **We need our final decision ASAP. Changes to anything as big as re-doing a standardized *MTL 1.6*  component is undoing and redoing the work of our 😿 last 60-day milestone MTL Standardization https://github.com/lzim/teampsd/milestones?state=closed** 
- **A change like this ripples throughout *all but one* of our TeamPSD development workgroups: (sim_ui_workgroup, model_workgroup, qual_workgroup, quant_workgroup, facilitate_workgroup, ees_workgroup, and pubs_workgroup) and therefore, it presents a barrier to fully moving forward on other key next steps across these workgroups.** For example, this section of the diagram is explained in session 5 (experiment tile), session 6 (systems story/model diagram), and from then on. Folks are developing several *MTL* resources and Team PSD scientific products around this now. 
- Here are the 3 **Green** locations to consider adopting **"Service Proportions Balanced Across Team Variables."**

![diagram_service_proportions_green](https://user-images.githubusercontent.com/7454688/45918996-f9edd600-be43-11e8-972f-89f493158ab7.png)

![experiment_slider1](https://user-images.githubusercontent.com/7454688/45918995-f9edd600-be43-11e8-9da1-711b6521db2a.png)

![experiment_slider2](https://user-images.githubusercontent.com/7454688/45918994-f9edd600-be43-11e8-83e9-c011fcb169f0.png)

**ISSUE #194**
I've uploaded @TomRust's files as .png files below so that we can see, review and discuss them online, without needing to download a .ppt. Click on the image file to expand your view.

My proposal for issue #194 
- **change simply to "Team Patient Start Rate** 
- from "Appropriate Patient Start Rate for Supply"
- leave the diagram unchanged.
- Here is the "i" information for this, *"The appointment completion rate is the rate at which appointments would be completed in each service by the current team at the standard allocation of hours and hours lost to appointment re-scheduling for each service. Used to initialize the model, so the referral, start, and end rates for patients in each service is in equilibrium.*

**Current State**
![current_agg](https://user-images.githubusercontent.com/7454688/45918760-931aed80-be40-11e8-9874-9e4652a3bed7.png)

**Tom's Proposal**
![tom_proposal](https://user-images.githubusercontent.com/7454688/45918761-931aed80-be40-11e8-8d30-93735ad9d831.png)

***Summary Action Items***: Please provide any concerns with the two open proposals for the language change in issue #185 and Issue #194 **They will be closed on MONDAY 9/24/2018**

- **PROPOSED Language**
1. Service proportions balanced across team variables
2. Team Patient Start Rate

Thanks! 

Lindsey

**Comment by lzim** [comment]
See issue #194 - both will be resolved by Monday 9/24/2018

**Comment by dlkibbe** [comment]
@lzim @branscombj @TomRust @dlounsbu @jamesmrollins @staceypark 
Question regarding #185 -- practically speaking, if we are going to use the word "balanced" (i.e. Service proportions balanced across team variables) it would be helpful if the word "balanced" appeared in the "i" information so the user knows what is being balanced.
Question regarding #194  - 
1. will the user understand the phrase "Team Patient"in the descriptor "Team Patient Start Rate" 
2. given the first sentence of the "i" focuses on completion "completion rate is the rate at which appointments would be completed in each service" vs. the title of "Team Patient Start Rate" should the "i" information be corrected to ensure the reader can make the link between the title and the description

**Comment by lzim** [comment]
Thanks @dkibbe!

1. Agreed. “i” information needs to be updated to match final variable name, e.g. “balanced”
2. Not sure about the “team patient” phrase, didn’t bother me. Others? 

- Perhaps even simpler “patient start rate,” with the two downstream impacts on intakes and the other services flow.  

Yes, will need to update “i” information here too.
Note: The old “i” excerpt that Debbie highlighted notes that this is an intermediate variable that translates between appointments and patients. But, it’s not just the appointment supply variable (which was confusing) it’s other upper appointment variables (and units - RVI weeks) too. 
@TomRust is the unit translation idea something that could be a meaningful variable name to frontline staff?

Need to resolve this today! Thanks :smile:

**Comment by lzim** [comment]
**Issue #185 and Issue #194 are now closed.**

**Final language for the two variables:**
1. **Service proportions balanced across team variables** (short version for switch in main tile = "Balanced" so switch is between "**Team Data**" and "**Balanced**" not "From Data" and "From Supply")
2. **Patient Start Rate**

@TomRust and @jamesmrollins We will need Tom to complete the first draft of updated "i" information for each according to the thread above. Please let me know if you have any questions.

@jamesmrollins If needed, we can discuss implementation of this variable naming in the sim UI and Master Crosswalk table v11 this afternoon at 4PM after we meet our 24-hour spring for today's *MTL 1.7* deliverables: https://github.com/lzim/teampsd/blob/master/resources/master_crosswalk/Master_Crosswalk_Table_v11_12SEP18.xlsx

Thanks!

Lindsey

**Comment by TomRust** [comment]
Okay!  I'll rename those two variables and push a new version of AGG .

**Comment by lzim** [comment]
> Okay! I'll rename those two variables and push a new version of AGG .

Great, thanks @TomRust and @jamesmrollins

**Comment by jamesmrollins** [comment]
The Sim UI has been updated in PROD and this can be closed.

**Comment by lzim** [comment]
Great work! Thanks
