### ISSUE TITLE
wk5 nov_epic: Create MM & PSY video walk/talk-throughs of system stories 

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1946]
Split from the Master Card tracking all system stories: #1815 

### Recording a video in Teams
Go to the calendar in Teams; click Meet Now and you can start a meeting with yourself, click More Actions and Start Recording. Share screen, use mousework, talk, etc. Go to More Actions to Stop Recording. Recording is saved in Chat.

MM 
- [ ] Balancing existing and new patients 
- [x] Wait time affect referrals

PSY
- [ ] Balancing existing and new patients

**Comment by branscombj** [comment]
https://user-images.githubusercontent.com/29778290/122619143-c3c5fb00-d05d-11eb-8de6-5b590688f20c.mp4

**Comment by branscombj** [comment]
For CC (#1949) and MM and PSY - Balancing Existing and New Patients am hoping one recording will suffice - but not sure since the diagrams have different elements in them. (Unlike Wait Time Affects Referrals in CC/MM which look exactly the same.)

@lijenn @staceypark @lzim 
- Please review videos in #1947, #1948, & above and let @dlkibbe and me know if they're on track. 
- Let us know where you put these so facilitators/team members can access them (_link to them in More Info/MTL Modules in the sim??_)
- We edited the written stories in #1510 to make them clearer and better narration for videos; those written versions could also be helpful for facilitators and team members. 

@dlounsbu In my memory, you were going to write up the feedback system stories for SP? If you have done that (e.g. possibly in the OSF systems thinking coding guide?) please let me know. Otherwise I will work on those early next week, hopefully in time for our SP-candidate team.

**Comment by branscombj** [comment]
> For CC (#1949) and MM and PSY - Balancing Existing and New Patients am hoping one recording will suffice - but not sure since the diagrams have different elements in them. (Unlike Wait Time Affects Referrals in CC/MM which look exactly the same.)
> 
> @lijenn @staceypark @lzim
> 
> * Please review videos in [jun_epic: Create AGG (1st half) video walk/talk-throughs of system stories  #1947](https://github.com/lzim/teampsd/issues/1947), [jun_epic: Create AGG (2nd half) video walk/talk-throughs of system stories  #1948](https://github.com/lzim/teampsd/issues/1948), & above and let @dlkibbe and me know if they're on track.
> * Let us know where you put these so facilitators/team members can access them (_link to them in More Info/MTL Modules in the sim??_)
> * We edited the written stories in [wk2 mar_epic story 1 #mm: Model manuscript walkthrough of systems stories for CC, MM, Psy, & Agg #1510](https://github.com/lzim/teampsd/issues/1510) to make them clearer and better narration for videos; those written versions could also be helpful for facilitators and team members.
> 
> @dlounsbu In my memory, you were going to write up the feedback system stories for SP? If you have done that (e.g. possibly in the OSF systems thinking coding guide?) please let me know. Otherwise I will work on those early next week, hopefully in time for our SP-candidate team.

@staceypark  @dlounsbu @lijenn @lzim: @dlkibbe and I are looking for 
a) confirmation the videos so far are on the right track before we do more
b) whether and how these (and the written versions) are being made accessible to users
c) david's response on SP; i haven't gotten to those yet so if you have good write-ups that would be very helpful!

Thanks!

**Comment by staceypark** [comment]
@lzim can you provide feedback on these so @branscombj & @dlkibbe can create more

**Comment by lzim** [comment]
@branscombj 

Happy Thanksgiving Week! Is this something you're working on wrapping up??
😊 
Anything you need from me?
