### ISSUE TITLE
jun_epic: Create AGG (1st half) video walk/talk-throughs of system stories 

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1947]
Split from the Master Card tracking all system stories: #1815 

### Recording a video in Teams
Go to the calendar in Teams; click Meet Now and you can start a meeting with yourself, click More Actions and Start Recording. Share screen, use mousework, talk, etc. Go to More Actions to Stop Recording. Recording is saved in Chat.

AGG
- [x] Fatigue increases clinic cancellations (R)
- [x] Appointment backlog extends return visit interval (B)
- [x] Overtime relieves work pressure slowly (B)
- [x] Overtime relieves work pressure quickly (B)
- [x] Burnout increases clinician quits (B)

**Comment by staceypark** [comment]
@branscombj @dlkibbe could I get an update on this?

**Comment by branscombj** [comment]
Hi @staceypark , I scheduled time to work on this with @dlkibbe this Wednesday (Debbie, please propose a different time if that doesn't work). I was hoping that we could meet also with @dlounsbu in order to get a plan for how the batch of all of these would go (preamble; level of detail; etc). David, do you happen to be available this Wednesday at 4-5p Eastern? If not, Debbie and I can use our best judgment and get started.

**Comment by branscombj** [comment]
I am not sure if this finished uploading. Let's see
Uploading AGG_AppointmentBacklogExtendsRVI.mp4…

**Comment by branscombj** [comment]
https://user-images.githubusercontent.com/29778290/122471395-3f0bac00-cf8d-11eb-944d-5fd155b2c420.mp4

**Comment by branscombj** [comment]
https://user-images.githubusercontent.com/29778290/122474965-f0144580-cf91-11eb-9d0d-3078c72fe347.mp4

**Comment by branscombj** [comment]
https://user-images.githubusercontent.com/29778290/122474984-f9051700-cf91-11eb-91e5-2a4f5a452d37.mp4

**Comment by branscombj** [comment]
@lijenn @staceypark These 5 are here!

**Comment by hnorthcraft** [comment]
#adjudicate_memo adding operations label
