### ISSUE TITLE
wk1 may_epic story_1: authorship app user test

### ISSUE THREAD

**Issue by dkngenda** [lzim/teampsd#1950]
Please follow [these instructions](https://teams.microsoft.com/l/file/1CA0A0D8-E478-412E-9CF5-DEDA47815F81?tenantId=e95f1b23-abaf-45ee-821d-b7ab251ab3bf&fileType=docx&objectUrl=https%3A%2F%2Fdvagov.sharepoint.com%2Fsites%2Fteampsd_vha%2FShared%20Documents%2Fqual_workgroup%2FAuthorshipApp%20user%20testing%20instructions.docx&baseUrl=https%3A%2F%2Fdvagov.sharepoint.com%2Fsites%2Fteampsd_vha&serviceName=teams&threadId=19:d4e1a7c7b0a749fdb9b44fe15c04b5f5@thread.skype&groupId=1db500d5-0d01-4254-af42-ad3f78bafacd) (which can also be found in the qual workgroup files on VA teams) to do user test for the authorshipAPP

**Comment by dkngenda** [comment]
@dlounsbu @swapmush @teampsdkathryn @jessfroe @lzim 

Hi all,

Just wanted to get this issue on your radar in case you haven't noticed it on your notifications :)

Please ping me on this card or teams when you are done.

Thank you!

**Comment by teampsdkathryn** [comment]
I have tried this three times and I am unable to get thru it.
I am not able to navigate to the recording to listen to it to learn how to use the app.
Next for task 1 the sub-categories do not show up on my laptop at home or in my office computer.
I stop halfway thru task one because there is no way for me to advance.

Best Regards, Kathryn

From: dkngenda ***@***.***>
Sent: Thursday, May 13, 2021 12:24 PM
To: lzim/teampsd ***@***.***>
Cc: Azevedo, Kathryn J. ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [lzim/teampsd] wk1 may_epic story_1: authorhshipAPP user test (#1950)


@dlounsbu<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdlounsbu&data=04%7C01%7C%7Cbb693babb1b4438a319708d91644a8c6%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637565306446639759%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=AM1ITXcjQScAAJ3%2F0GB%2FX86Zjqf85c5G5N173FbbdlQ%3D&reserved=0> @swapmush<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fswapmush&data=04%7C01%7C%7Cbb693babb1b4438a319708d91644a8c6%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637565306446649715%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=BNZhQdCpPg4GG8jJVqLjw25MvU4dTzPJfXviTf1WfJE%3D&reserved=0> @teampsdkathryn<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fteampsdkathryn&data=04%7C01%7C%7Cbb693babb1b4438a319708d91644a8c6%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637565306446649715%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=T4AEkRzKEAHwntxFjW8GUrkYcuEVEeYY9u8YEfkvgPw%3D&reserved=0> @jessfroe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjessfroe&data=04%7C01%7C%7Cbb693babb1b4438a319708d91644a8c6%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637565306446649715%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=g2KDsmMTLb7ui2ANJfCCV3chiYyu3HojIsuwmEjZo%2BM%3D&reserved=0> @lzim<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flzim&data=04%7C01%7C%7Cbb693babb1b4438a319708d91644a8c6%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637565306446659671%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=wDyYPKZqtoyMnX8tIIkrvGaegJA0YT%2BGZEmHzXNehnc%3D&reserved=0>

Hi all,

Just wanted to get this issue on your radar in case you haven't noticed it on your notifications :)

Please ping me on this card or teams when you are done.

Thank you!

-

**Comment by dkngenda** [comment]
@teampsdkathryn 

Thanks for trying this out! Curious if you selected workgroups associated with the paper on the landing page (i.e 1. workgroup)

![image](https://user-images.githubusercontent.com/66848852/118196158-83e67500-b41a-11eb-8d20-0fed2fc59560.png)

**Comment by teampsdkathryn** [comment]
I chose qual workgroup. Best Regards, Kathryn

From: dkngenda ***@***.***>
Sent: Thursday, May 13, 2021 3:40 PM
To: lzim/teampsd ***@***.***>
Cc: Azevedo, Kathryn J. ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [lzim/teampsd] wk1 may_epic story_1: authorhshipAPP user test (#1950)


@teampsdkathryn<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fteampsdkathryn&data=04%7C01%7C%7C4b8f673038a8494487b908d91660189e%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637565424247353138%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qy26FGf9yh7kxcxqbQRw2mrncjb7Asxvy1XXxZS9HxU%3D&reserved=0>

Thanks for trying this out! Curious if you selected workgroups associated with the paper on the landing page (i.e 1. workgroup)

[image]<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F66848852%2F118196158-83e67500-b41a-11eb-8d20-0fed2fc59560.png&data=04%7C01%7C%7C4b8f673038a8494487b908d91660189e%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637565424247363073%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Gen0RJonP%2BAs358TTDbtJJ0G8VCcRjU7Ojcea%2FliIrI%3D&reserved=0>

-

**Comment by dkngenda** [comment]
@teampsdkathryn 

Just checking on my assumptions  regarding your comments on TEAMS
 
Am assuming that the subcategories actually load into the app but they are not immediately visible because they are  tucked way below on the screen and would require scrolling  to view. Is this correct?

**Comment by teampsdkathryn** [comment]
Yes. I scrolled down but could not reach it. Thank you, Kathryn

From: dkngenda ***@***.***>
Sent: Friday, May 14, 2021 6:37 AM
To: lzim/teampsd ***@***.***>
Cc: Azevedo, Kathryn J. ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [lzim/teampsd] wk1 may_epic story_1: authorhshipAPP user test (#1950)


@teampsdkathryn<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fteampsdkathryn&data=04%7C01%7C%7C746ea4523f3346ceab6d08d916dd6c3f%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637565962534535071%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ztkGRBvELBw%2FMzbj3agigIGqQNdSEFdn5e%2BpPaVpUUg%3D&reserved=0>

Just checking on my assumptions regarding your comments on TEAMS

Am assuming that the subcategories actually load into the app but they are not immediately visible because they are tucked way below on the screen and would require scrolling to view. Is this correct?

-
