### ISSUE TITLE
wk4 apr_epic/wk1 may_epic due MAY 4TH BUG: MTL Menu Label error 

### ISSUE THREAD

**Issue by branscombj** [lzim/teampsd#1960]
**In the summary of team menu results for the team prep on Tues. May 4th from 6:30-8:30am Pacific , 1 chart has an incomplete title** 
It reads: "our existing patient mix / patients down to primary care"
Report #1: team name here - team vision here

See screenshot from @lijenn below

**Comment by branscombj** [comment]
### Also note: 
When I copy-pasted the title from the top of the report, the "#1" part of it got treated by GH as a reference to the Style Files. I don't think it's a problem here, but it may be worth keeping in mind that **formatting in any of our resources that mirrors R coding will be interpreted by GH as R code**.

**Comment by lijenn** [comment]
Great catch @branscombj! I removed the team name and replaced it with the date/time for May 4th since the team knows to refer to the MTL Help Calendar for the actual site.

@jamesmrollins I believe this needs to say: 
Stepped Care - How to decide when to step patients down to primary care.
![image](https://user-images.githubusercontent.com/59668647/116744776-9c34a980-a9af-11eb-8416-98d06591ab95.png)

**Comment by jamesmrollins** [comment]
Thank you @lijenn and @branscombj.  This has been reported to DEV and will be corrected by Monday morning, 5/3.

**Comment by jamesmrollins** [comment]
@lijenn and @branscombj the title has been corrected.
