### ISSUE TITLE
 jun_epic: RedCap Baseline Schedule & Excel Data Structure 

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#1972]
Baseline Schedule: ees_mtl_live_team_links_tables_master.xlsx in mtl_live_ees_team_links_table folder in facilitate_wg channel on VA Teams.

Excel Data Structure pulled from API via RedCap: @dkngenda to link a pull request connected to this issue card.

**Comment by dkngenda** [comment]
@lzim @staceypark @lijenn 

Checking in on a few  questions/clarification/assumptions regarding the data structure. See attached codebook for reference
[R01 Baseline Codebook.pdf](https://github.com/lzim/teampsd/files/6453975/R01.Baseline.Codebook.pdf)


- Each row represents a  team member?
- Do we plan to join the baseline and 6-months responses at  record level (team member level) or team level? Am assuming the later is correct since R01 proposal  points out that we will use team aggregate scores but if in future (post-hoc analyses) we are interested in understanding individual improvements we might want to think how to track a team member from baseline to various follow-up times.

**Comment by lijenn** [comment]
@dkngenda Yes, currently each row in the excel file represents a team member/Learner that has taken the provider survey. However, I believe this is tracking the results only from the team level.

If so, for your second question, @staceypark would we need to enable something like participant identifiers in order to track each Learner that takes both the Baseline and 6 month survey? Anything we might need to think through with anonymity while still being able to track individuals?

**Comment by lijenn** [comment]
Discussed at HQ 5/13:
We will use team mean to account for missing data.
We will use a team mean at baseline and a team mean at 6 month.

Discuss surveys at tomorrow Fri. 5/14 8am @dkngenda @lzim (@staceypark if needed)

**Comment by lijenn** [comment]
Surveys were sent on 6/8 and David is getting the survey data into RStudio via the RedCap API. Closing this card.
