### ISSUE TITLE
wk3 sep_epic "Task": Alignment of intersession prep checklist and post-session checklist

### ISSUE THREAD

**Issue by dlkibbe** [lzim/teampsd#1998]
**1. Add description:** 

Alignment / editing needed to: 
MTL Facilitate Post-Session Checklist
https://github.com/lzim/teampsd/blob/master/mtl_facilitate_workgroup/checklists/post_session_checklist.md

and

Intersession Checklist 
teampsd/mtl_facilitate_workgroup/checklists/inter_session_checklist.md
 
**2. Click on the right:**  @staceypark @lijenn 

Only minor edits needed. Intersession checklist says under "1. what you need"; 2. Review post-session checklist notes especially **#6** from the prior session.
The post-session checklist (link above) only has 5 items listed (not 6). 
*Maybe I'm looking at an older or the wrong post-session checklist.*

**3. If you anticipate that your **issue card** or **bug card** will have **dependencies** these can be added once the issue has been submitted.   

May impact intersession prep

**Comment by staceypark** [comment]
Thanks @dlkibbe 

I fully ran down the issue with @lijenn by cross-referencing Lucid and tracking down the commit history in our repo:
![image](https://user-images.githubusercontent.com/31089501/119891793-412e9d80-beee-11eb-879f-1ff1e796e461.png)

Looks like we decided to reduce the post-session checklist since it is redundant. I will edit the intersession checklist to make sure the numbering isn't confusing.

- 
@lzim I don't think we should have a separate team tracker checklist and SAY checklist. The SAY checklist is already a truncation of the SAY guide, and it would make sense for facilitators to copy + paste the SAY checklist into the tracker (or later pull up in the CRM), and check stuff off or add notes as they go through the session.
