### ISSUE TITLE
wk4 may_epic: Review and Finalize ERD MTL Entity/Dimensions

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2012]
@hsnyder2 I've filled out some immediate details in setting up this card in preparation to discuss this on **Mon. 5/24 8am Workgroup leads** meeting. **Can you provide an estimate for us?**
This is sounding like a 5 or 8 points to me based on the effort and discussion needed from all of us.

**Link:** [Initial draft of ERD](https://dvagov.sharepoint.com/:b:/r/sites/teampsd_vha/Shared%20Documents/msd365_workgroup/Requirements%20Elaboration/MTL%20High%20Level%20ERD.pdf?csf=1&web=1&e=NOJZ4O)
**Questions:**
So, specific follow ups we'd like to discuss related to the info presented in the diagram:
1. How to incorporate Versions to work with Programs, possibly collapsing them into Session Type.
2. Discuss how this supports multiple teams associated w a facility or clinic over time.
3. Discuss pros/cons of having D365 dynamically generate CPG and Team names (remaining editable?).
4. Discuss bulk uploads vs all done in D365.  Can demo the later in Wednesday’s call(s).
5. Discuss putting Phase Type on tasks, email and invites (aka meetings).

---------------------------------------
@lzim's feedback 
FYI @anazariz @staceypark @lijenn @branscombj @MattMoore2 
I've provided an initial review of the file. Unfortunately, since it's a PDF we can't offer annotated comments on the file itself.
 
It appears that **red is used to identify some of the entities** we've outlined for **MTL Live emailing workflows**, which are "**Program"** (**Red, Blue**, etc.), **"Phase of Engagement"** **(Coplan, Team meeting, Follow-up).**
 
**"Evaluation" appears to be omitted from the top level row, which should be clarified.** Consistent with the **original 13 MTL Workflow diagrams, the Hierarchy of Set relations above,** and the meeting Wed with our emphasis on the **need for their combinations to provide all the necessary views or reports**, without "Evaluation" (NIH, VA, etc.), at our top level, we do NOT enough enough information about **"Program"** where _"MTL Red" evaluated by NIH funds differs from "MTL Red" evaluated by VA funds, and we would want views/reports that bothg group and distinguish them accordingly._

**program_
evaluation_
phase_of_engagement_
facility_
team_
date**
 
**I would strongly recommend against Liberty's introduction of "Session Types"** as language for the entity groupings that you are trying to clarify principally because "session" plays such a prominent role in the logic and workflows of the _Modeling to Learn_ emails across the "_MTL_ 12 _session_ plan" and we will need it then.
 
To further improve the clarity @hsnyder2 
**Are you able align what Liberty is calling "Session Detail" ->"Checklist Detail" -> and "Schedule Detail" -> "Scheduled Task" with the 13 "MTL Live" workflows and the language for tasks and schedules used therein?** It would really speed us along in ensuring clarity.
 
It would also be valuable to account for the emails that we receive outside of MTL Live, (i.e., MTL Video and MTL Facilitate), and that are received at mtl.info@va.gov to ensure we aren't boxing ourselves in, even if these do not have the same level of volume/scale issues that led to the prioritized in the MVP project plan.

**Comment by hsnyder2** [comment]
My reply on Teams to Lindsey's feedback and question:

@Zimmerman, Lindsey E. - Replying to multiple posts from above:
 
Our edge case question? > Can a Co-Planning grp ever be associated w more than one grant or more than one program?
Stacey's Reply:  No.
Our Conclusion:  We can put those attributes on the Co-Planning Group, per diagram above (because it will never happen).
 
Don't see any scribing about "version" on Wednesday's 12:30 CRM call.  "Video" ... you thought could go into Program (?)  In any event, discussion around #1 in list above is warranted to clarify requirements related to Programs, Versions and relationships between the two.
 
GitHub card for ERD review/discussion:  #2012
 
Per note at top of ERD:  Red text are attributes whose values, taken together, define a unique entity record.  There is no information implied or otherwise by the order of the attributes listed for each entity.
 
Yes, much of what is covered in the 13 CRM flowmaps will be supported by the entities running along the top (session > checklist > schedule > tasks/email/invites).  One design decision we've made in this diagram is to put the phase information there (discussion topic #5).
 
You'll be able to run reports using combinations of attribute values across multiple entities (unless the entities are unrelated -- they are not in this diagram).
 
We can call "Sessions" something else.
 
Discussion #1 will help to clarify how the 2 email accounts work in the system but, at this stage, we think this diagram supports both info and help email accounts.  Implementation details related to "how" are TBD (& need discussion #1).  We're still waiting for DEV and QA versions of help and info to begin working on Outlook related entities in that diagram to dig into the "how."

**Comment by hsnyder2** [comment]
@lijenn Not familiar with your points system but I suspect (actually, **_hope_**), that we can arrive at a mutual understanding and agreement on the design (per the 5 discussion topics we'd like to cover and any questions you all have that we need to address) by the end of Wednesday's CRM & Supp WG calls.  If that's all we do in those calls, that's fine, but if we can't arrive at a mutual comfort level by the end of this sprint (Wednesday) and we need the following Wednesday to get there, that could be a problem.  So I'd say, score the LOE for whatever time we'll have between Leads, CRM and Supp WG calls this week.
