### ISSUE TITLE
wk1 jun_epic Bug: Master Data UI file - Unable to create Team Data Table for "SP" and "All with SP" Module

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2019]
Initially identified by @hmarcia @branscombj on Mon. 5/24
FYI @lzim 

Updated on Fri. 5/28:
@anazariz and All, the Data UI files are not able to generate a Team Data Table when selecting the module as "SP" or "All with SP", **SPECIFICALLY under the condition that it is set to "GMH" in the SPReferrals tab.** 
A Team Data Table file is still generated when it is selected to "SMH" in the SPReferrals tab.

Please note that many of us that tried to create a Team Data Table with SPReferrals tab set to GMH in the clinic referral field in cell E2, we did not get any error pop-ups.
However, I did get this run time error one time I tried to run the file, which points that there is an issue coming from the SPReferrals tab:
![image](https://user-images.githubusercontent.com/59668647/119747983-b9db1e80-be48-11eb-9931-a921e986e0db.png)
![image](https://user-images.githubusercontent.com/59668647/119748073-eabb5380-be48-11eb-8ac9-1d6f12fa12cc.png)

**Comment by lijenn** [comment]
Decision: Always QA test with "All with SP" for Team Data table.

Debug code should show which module/tab the error is occurring (like the error above in this card).
- Include testing each module individually to narrow down the issue.

**Comment by lijenn** [comment]
UPDATE Fri. 5/28:
@staceypark @anazariz Please see my edited findings in the initial/top comment in this post. 
Looks like the bug is occurring only when we select "GMH" in cell E2 the SPReferrals tab. 

To add on the QA test decision in my comment above, we need to include QA test for the SPReferral tabs as well for both SMH and GMH.

FYI @branscombj and @hmarcia

**Comment by anazariz** [comment]
@lijenn 
Cc: @lzim @staceypark @dkngenda 

I found the error that causes the above (screenshot). There was a change in the code (compared to the version a couple of years older), which I did not add! That change was rendering the click on the "Add All" button on the SPReferrals page useless! Not sure how this did not catch our eye earlier. Anyhow, **I fixed it.** 

**After change:**

![image](https://user-images.githubusercontent.com/39805164/120399683-59892880-c2f1-11eb-9356-05869b57fb31.png)

**Before Change:**

![image](https://user-images.githubusercontent.com/39805164/120400203-4b87d780-c2f2-11eb-9a9f-a2971afd9a5b.png)

### However, 
the issue with GMH not producing a file vs the SMH producing a file is totally a different thing. I need to follow several hundred lines of code to figure out why GMH does not produce a file silently (without even throwing an error).

**I see this comment in the code:**    
------------START OF COMMENT-----------------
'need user input to determine which listbox has gmh teams and which one has smh teams
       
If Sheets("SPReferrals").Range("GMHSMH").Value = "SMH" Then 'team is gmh. The drop down now selects what the other team is.
   
-------------END OF COMMENT----------------
**If Sheets("SPReferrals").Range("GMHSMH").Value** is basically the drop down that you select on the SPReferrals page that selects GMH or SMH. The comment is rather confusing because it says is you select 'SMH' then the team is 'GMH' ???
Also, I am not sure what "the drop down now selects what the other team is" means. Is that the "GMHSMH" dropdown or is there a secondary dropdown (perhaps missing) that does something after you select "GMH". Anyhow, I'll have to figure it out, unless ya'll have some ideas.

**Comment by anazariz** [comment]
@lijenn 
Cc: @lzim @staceypark @dkngenda 

It looks like the "GMHSMH" error is caused this way: 
A parent routine connects to the database, then calls a subroutine that also connects to the database again (as a second session) and creates a temp table called "OMHSPICDs" . Then the parent routine tries to access that temp table which is obviously out of scope for the parent routine because the database and the access to it are in two different sessions and in SQL Server you cannot access a temporary table from a different session. This causes the "Invalid Object" error. This situation is for "SP" and "All with SP" only.

------------ here is the call to the subroutine from the parent routine -------------- 
If (Sheets("ClinicSelection").Range("E2") = "SP" Or Sheets("ClinicSelection").Range("E2") = "All with SP") Then
    Call btnSPModel(a, b, c)
End If
------------------------------------------------------------------------------------------   

So what I will try to do is to see if the spawned routine can just use the connection of the parent routine, which also has its own problems if the parent and the subroutine have tables that are named the same and in conflict.

**Comment by anazariz** [comment]
@lijenn 
Cc: @lzim @staceypark @dkngenda 

Probably the best camouflaged bug I have ever found in the Data UI so far. **It's fixed!** 
I'll set up a test ticket for it.

**Comment by staceypark** [comment]
@anazariz testing passed on #2026 and was closed.

**Comment by anazariz** [comment]
Thanks @staceypark 
Cc: @lzim @lijenn 

I will go ahead and propagate the fix to other Facilities. Also, closing this bug ticket.
