### ISSUE TITLE
Recovery of Experiment Files from Runs Prior to 1.52 Release

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#202]
@lzim @staceypark @TomRust @branscombj @dlkibbe @dlounsbu 

Here is a comprehensive listing of experiment runs since the beginning and together.  It also includes the text from the QHFD fields.  I hope this helps.  Let me know if you need more.

Thanks,
James

[PROD-all-saved-experiment-JAN-to-SEP-2018.xlsx](https://github.com/lzim/teampsd/files/2420066/PROD-all-saved-experiment-JAN-to-SEP-2018.xlsx)

**Comment by lzim** [comment]
This gets the rare 😻 heart emojis from me @jamesmrollins , thank you so much!
I'm going to consider this component closed.
- Question: Is this something we can retrieve this way in the future?


**Facilitate Workgroup - we can clean up the *MTL 1.6* PROD worlds for our R21 teams.**
- NOTE on the "need_decision" label: We do need to structure their group for individual and team worlds differently than it was over the summer. We can discuss during our workgroup meeting today. 

Stacey create a group 640_individual_world - but that is too big a group size (an entire VA facility). And, the teams (at present) can only access the 640a0_mpd-user-training-may-2018 from the first log-in dialogue.

Thanks again 👍 

Lindsey

**Comment by staceypark** [comment]
@jamesmrollins We see that there is only q/h/f/d information from the run in this file. Is there any way to get the variable numbers as well? In a similar fashion to the data we get from the exports currently

**Comment by jamesmrollins** [comment]
I have entered this change into the Design Change Order.

**Comment by staceypark** [comment]
@jamesmrollins 
Another issue we've encountered in **TT Reports** #245, @saveth noticed that the file formats vary in PSY exports. It looks like it changes based on what is/is not populated in the q/h/f/d. For example, I think if the F & D are missing, it "pushes up" all the cells underneath it - so appointment supply may be in cell A13 in one report but A11 in the next.

Is there a way to get the exports to standardize, so that the same thing is in the same cell every time?This is important for Savet's work, so she can build code that can be standardized across all teams as we scale and expand.
