### ISSUE TITLE
BUG: MTL Menu - PDF Export loading time out

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2020]
Identified around Wed. 5/26 10am Pacific for @dlkibbe @lzim @clairecollie's team.

@jamesmrollins The MTL Menu PDF export get's stuck at the loading screen and then eventually times out.

Issue is continuing to today. Do you get the same issue?
I am unable to inspect the console since it gets stuck at the loading screen and does not allow me to right click.

- Loading and Time out on Chrome:
![image](https://user-images.githubusercontent.com/59668647/119847256-adde7380-bebf-11eb-8383-8f075e1a95ea.png)
![image](https://user-images.githubusercontent.com/59668647/119846708-3b6d9380-bebf-11eb-9615-174ee443b595.png)
- Time out on Edge:
![image](https://user-images.githubusercontent.com/59668647/119848107-660c1c00-bec0-11eb-8d27-e117e9417e88.png)

**Comment by jamesmrollins** [comment]
Hi @lijenn. 

## Findings

- Inside the domain it appears to be malfunctioning for me also.  Although it doesn't time out on me, it just returns me to the page without opening the PDF tab.

![image](https://user-images.githubusercontent.com/30132017/119865484-8e037b80-bed0-11eb-93a1-05c487ecb769.png)

- Outside the domain it appears to be working, but is returning similar dialogue in the inspect console:

![image](https://user-images.githubusercontent.com/30132017/119865677-c73beb80-bed0-11eb-8b15-fe15f4bb5060.png)

- Still manages to create a PDF though:

![image](https://user-images.githubusercontent.com/30132017/119865764-dc187f00-bed0-11eb-8931-e7762ae622b2.png)

## Next Steps

- [ ]  I have notified Forio.  I am wondering about the 404 errors.  These usually mean a resource call cannot find a server.
- [ ]  @hirenp-waferwire and I will investigate tonight to see if there is a code level issue that might be creating the problem.  I am suspicious, though, since it has been working fine until now.  

I will notify you of my findings by tomorrow morning.

**Comment by jamesmrollins** [comment]
Hi @lijenn  FYI: @lzim @dlkibbe @clairecollie @staceypark 

## Findings

- The reason the page does not render to a PDF is because the pop ups are being blocked by browser security settings.  The site settings in Edge and Chrome must allow pop ups and redirects, so the PDF can be published to a tab.

![image](https://user-images.githubusercontent.com/30132017/119913887-ed36af80-bf13-11eb-85f1-63731d68b78e.png)

- Some VA policies may not allow the user to change the pop up settings.  We will investigate a means to automatically download the PDF, so it can be double-clicked and open in a client Adobe Reader, instead of through the browser.   This workaround will work in all cases, not just in cases where the settings are enabled.

**Comment by staceypark** [comment]
FYI @jamesmrollins we pulled the PDF during a prep session with Jane & Marcia (Wed 6/3 @8:30 Pacific) and the export worked fine for both of them. 

Were you guys able to implement a fix that would make this work or did we just get lucky? 😜
