### ISSUE TITLE
wk1 jun_epic BUG: MTL Menu - Intermittent Loading and Unable to Click Radio Buttons for Menu Questions

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2022]
Identified on Thurs. 5/28 at 9am Pacific with @lzim @branscombj FYI @hmarcia 
 
@jamesmrollins The following issues were documented for the Live team meeting for MTL Menu:
- Loading issues on different browsers, refreshing resolved the loading issue.
- Intermittent issues with answering the "Specific Services" questions, was unable to click the radio buttons.
   - Issue was identified on Chrome at 9:40am Pacific, however it was working for some Learners before then, 
   - Doesn't seem to have been present on Edge.
   - LZ thinks this may be a concurrent user load and location issue since some people in the same region had no trouble, then some did.
    
James is working on adding the MTL Menu to the cookies we have to view where errors started occurring for Learners.

**Comment by jamesmrollins** [comment]
@lijenn 

## Update

- We have loaded SmartLook cookies on mtl.how/menu so we can see the problem first-hand.
- I set @lijenn up with an account so she can explore and see videos of sessions.
- When this phenomenon occurs again, please advise me right away.

**Comment by lijenn** [comment]
@jamesmrollins A member from this same team reported the issue on Thursday 6/3 at 2:15 Central time (12:15pm Pacific) using Chrome. Let's use the cookies to see if we can troubleshoot this?

**Comment by jamesmrollins** [comment]
Hi @lijenn @hmarcia .  I found the SmartLook recording of this session. 

## Follow up Question:
Did anyone advise the user to try "incognito" or "InPrivate" mode? I am wondering if there is a cookie that is interfering.

## Findings
1. I see from the SmartLook recording, the radio buttons do not appear to be working. 
2. According to SmartLook, they were using Edge, not Chrome.  Small matter, they both should work.  
3. I was not able to recreate this problem
4. Others in the group have taken the survey with no issues. 

## Actions
1. I will confer with DEV tonight to see if there is an explanation and a fix.
2. I may need to provide direct support to the user to troubleshoot this problem. Because the problem appears to isolated to this user, there may be a browser problem. The "InPrivate" or "Incognito" mode test may help with further troubleshooting.

**Comment by lijenn** [comment]
@jamesmrollins @hmarcia 
We did not suggest using "InPrivate" or "Incognito" since those modes are not available on VA.

There was also definitely at least 2 others that experienced this same radio button problem during the live meeting on Tues. 5/27 via Chrome, but they were able to click on the radio buttons once they switched to Edge. 

That to me sounds like it might not be isolated to this specific user, but I agree that if there is no explanation for DEV, direct support may be needed.

**Comment by jamesmrollins** [comment]
Hi @lijenn.  Thank you for clarifying the issue with the additional details. 

- Curious about radio buttons working for the others after switching to Edge.
- In Tom's case, he was using Edge, but not able to use radio buttons.  
- It is also curious how some radio buttons work, but not all. 
- Will let you know what I find out from DEV.

**Comment by jamesmrollins** [comment]
Hi @lijenn @branscombj @hmarcia .

After review of the SmartLook recording, we realize the screen was in "tablet mode" when used by Tom.  We have been able to recreate this issue in this mode.  Did the other users who experienced the radio button problem use a tablet, or put their browser in tablet mode also?  I will let you know what we do to resolve the issue.

**Comment by jamesmrollins** [comment]
Hi @lijenn @branscombj @hmarcia 
We have fixed the radio button bug and advanced to PROD via Break Fix. 

FYI @staceypark

**Comment by jamesmrollins** [comment]
hi @lijenn .  I am glad we got to the bottom of this bug!  I viewed the correct recording, because it begins with his login.  He may not have been on a tablet; however, he may have been using a minimized window for his browser, or adjusted his zoom level that put the page into a "tablet" mode, where the page objects are stacked one-on-top-of-the-other, versus side-by-side.  

thanks for the follow up!  I will close this issue.
