### ISSUE TITLE
MTL Video Production - Week of 11/26/2018 - EES St. Louis Studios

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#203]
Hello Everyone,

Moving our discussions and decisions related to our *MTL Video Pre-Production* milestone https://github.com/lzim/teampsd/milestones to our real-time GitHub collaboration platform for our TeamPSD project https://github.com/lzim/teampsd/projects/1 so we can track key workgroup dependencies. *As just two examples, the concurrent MTL 1.7 Release Milestone https://github.com/lzim/teampsd/milestones and the concurrent EES accreditation milestone https://github.com/lzim/teampsd/milestones.*

- **Our MTL Video Pre-Production work is due Friday November 16, 2018** 
- **Please complete work on GitHub and link to the MTL Video Pre-Production milestone.**
*We are moving too quickly, and email is too slow, with too great a risk that dependencies with other Team PSD workgroups will be missed, key partners will be left off of thread, or it will be too much re-work to catch people back up on meetings and emails if/when they miss.*

I've labeled this **need_decision** because I am working on the issue of the 4-day shoot versus the 5-day shoot final decision based on everyone's input on the draft MTL Production schedule. I am concerned that since the care coordination (CC) model is "baked in" to *MTL* and since the *MTL Video* Production is such an expensive and important production already, it is likely un-wise to omit the CC module, if we can get it done too.

I'd like for us to **make this CC decision by COB tomorrow** as it has budgetary implications, but it will likely be more efficient to discuss here and so we can more efficiently reach a **final decision** during our *MTL Launch* call tomorrow morning.

*Here is our draft 4-day schedule, which is already VERY tight, Italics indicate transitions, but are very tight for lighting and make-up changes.*
![4day_mtl_video_production_draft](https://user-images.githubusercontent.com/7454688/46085427-e0f26700-c15a-11e8-884b-739f0f30d232.png)

**Summary for 4-day *DRAFT* MTL Video Production:**
- We will record the 30 minutes of done/do for each of the 12 session plan = 6 hours.
- We will record the 30 minute exercise of sessions 1, 2, 3, 4, 11 and 12 = 3 hours.
- We will record the 30 minute exercise of sessions 5-10 for each module: MM, PSY, AGG and SP = 12 hours.
- We will need 5 hours of transitions and 6 hours of lunches and breaks.

Thanks!

Lindsey

**Comment by branscombj** [comment]
Will we have Team PSD members playing the role of learners in our MTL Videos?

**Comment by dlkibbe** [comment]
Just my 2 cents...If we consider lessons learned from the video shoot in Palo Alto, everything seemed to take a little bit longer than planned. While it may be difficult for people's schedules to commit 5 days, a 5-day shoot may be required to provide sufficient leeway/flexibility to get everything done that is needed (including the CC model). Given all the work done on CC and the need for other facilitators to be trained in its use, I would vote for including CC in the MTL Video production schedule.
@lzim @staceypark @TomRust @branscombj @dlounsbu @holbrooa @AnnHier

**Comment by lzim** [comment]
Hello Everyone,

Thanks for all of your willingness to accommodate the 5-day production schedule. @dlkibbe  @staceypark @TomRust @branscombj @dlounsbu @holbrooa @AnnHier @Bowlied @justinspears1 

Please take a look at the revised draft schedule for *MTL Video* for **Monday 11/26-11/30 (Mon-Friday) at the EES St. Louis studios.** 

![mtl_video_5day](https://user-images.githubusercontent.com/7454688/46318882-dc7be300-c58c-11e8-9eee-336f6b34c70a.JPG)

**The MTL Facilitate Workgroup will discuss this *MTL Video* Production Schedule and our Friday OMHSP TAS call during our Wednesday 10/3 call.**

Thanks!

Lindsey 

FYI @ericasimon

**Comment by branscombj** [comment]
This looks good to me. I'm glad the do/dones are together with their corresponding in-session exercises.

**Comment by dlounsbu** [comment]
@lzim and @staceypark : My MTL jacket arrived today! Thanks!  I love the jacket but the size I received is S (small). I believe I requested a M (medium). 

Question: Are we going for a more 'fitted' behind-camera-look? I can wear the small, but I think a medium or large might be better.  Anyway to swap once I am in St. Louis?

**Comment by branscombj** [comment]
I got mine yesterday too! It is beautiful and warm, and mine is also a bit snug. I figure we may be able to swap around on-site, since only one + LZ will be on camera at a time; but I will want some strong A/C so I don’t stink up someone else’s fleece!
Love the water bottle and the smaller tchotchkes too!

Jane Branscomb, MPH
Senior Research Associate
Georgia Health Policy Center
Andrew Young School of Policy Studies
Georgia State University
55 Park Place 8th Floor, Atlanta, GA 30303
404.413.0317 (direct), 404.413.0316 (fax)
jane@gsu.edu
www.ghpc.gsu.edu<http://www.ghpc.gsu.edu/>

[/Users/lorisolomon/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_1054234362]<https://www.facebook.com/GeorgiaHealthPolicyCenter/>[cid:image011.png@01D4033A.B2EF22F0][/Users/lorisolomon/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_747647809]<https://twitter.com/GSUGHPC>[/Users/lorisolomon/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/Signatures/signature_224188472]<https://vimeo.com/gahealthpolicycenter>

[cid:image006.png@01D475E4.6955A200]

**Comment by staceypark** [comment]
Hi @dlounsbu @branscombj 
Glad you like the jackets! Sorry to hear that they're snug.
Quick explanation on the sizing - We went a size down from the original requested size, based on measurements. We had to switch products/companies from the original one due to logistical issues.  The new product had size measurements that were a size larger (i.e. the Large in the new was the same as the X-Large in the old)

**Comment by branscombj** [comment]
@dlkibbe, @dlo, @TomRust, @lzim, Could we consider revising our video schedule to not record the Done/Do segment for the **beginning** of each session separately from the in-session exercise for that session - but instead have the main session presenters cover all the intro pieces? It should add no more than 5 minutes and be very consistent.

Rationale: That Done/Do is so short - and the Do leads so naturally into the LOs and exercise - that it seems like an unnecessary distraction to switch out there. 

I like a break to different presenters/recording segment for the End-of Session Done/do, and announcing that one a Done/Do Review makes sense because we review what was just done and go over in detail how to do what we're doing before next session.

**Comment by lzim** [comment]
Hi Ann,

The _MTL_ opening chime was written, performed, and recorded by me specifically for _Modeling to Learn_. Therefore, as the creator, I give my permission to use it for _Modeling to Learn_ for free without licensing fees. 🎼 I can bore you some other time 😴  with why that chime from D Dorian sliding up a perfect fifth was crafted on guitar and bass to match this quality improvement program. 💯 
That's why I keep asking if you need me to remove the noise floor, because I haven't taken the room tone to do that (yet), but I can if we need to do so. 😺 

If folks don't catch it here before then (fyi @TomRust @dlounsbu @branscombj and @dlkibbe) let's have the on camera folks add their lower thirds to the Lucid agenda tomorrow AM so that you have everyone's.

Lindsey Zimmerman, PhD
Clinical and Community Psychologist, Implementation Science
VHA National Center for PTSD

The .png bug that points folks to the main location is this one, folks simply type mtl.how into any browser window and they get the home base for all _Modeling to Learn_ resources. To be user-friendly, all other links are co-branded to go with that (e.g., mtl.how/sim and mtl.how/live and mtl.how/data, etc.)
https://github.com/lzim/teampsd/blob/master/resources/logos/mtl_how_sm.png

**Comment by AnnHier** [comment]
Hi Lindsey - 

Love it! You know your music theory - you definitely fit the definition of "Renaissance Woman!" Thanks for offering to do that. 
I believe we should be able to remove the noise floor in our editing software; what audio file formats does the chime exist in?

Thanks for adding the lower thirds note to today's agenda. Got yours and Jane's now, too. Thanks for the PNG bug as well.  Talk to you on the call today!
