### ISSUE TITLE
wk3 jul_epic task: initialize value to 0.1 in Data UI'S SPParams

### ISSUE THREAD

**Issue by anazariz** [lzim/teampsd#2056]
**initialize value to 0.1 in Data UI's SPParams**

Currently the values (in column "value" -  see the description to see which ones) are initialized to 0 and that shuts off the flow. They need to be initialized to 0.1.

**Comment by anazariz** [comment]
Wait for the 6/16 Support Group before you get started on this.

**Comment by lzim** [comment]
@jamesmrollins @staceypark 

I believe we confirmed that we do NOT want any coding on the SQL side that related to these SP initialization values. 

Meaning, I believe this card was created in case it was needed, but the resolution for the SP initiation issues in the Sim UI were resolved via other means.  

Is that correct?

Thanks!

**Comment by jamesmrollins** [comment]
@staceypark @lijenn @lzim @anazariz @TomRust 

## Findings
- The model variable only reads the information in the cell of the Team Data spreadsheet (see model capture below).
- Since it is only passing the value to the sim, it does not have conditional logic to set the minimum of 0.10.
- Although the Team Data table would show a zero, downstream, the variable is automatically adjusted in case it is zero.  The following explanation is provided on the adjusted Data GMH New Patient Wait Time (_Note: New Episode of Care Wait Time is represented in the model as New Patient Wait Time_), see second image below.

  "It is possible for the estimate for the median wait time to be zero, if the team sees many walk-in patients. However the model needs the wait time to represent the average, thus a value of zero is not feasible. In these rare cases, we prevent the model from using a zero average wait time, instead using the Minimum Transfer Time. If the relevant engagement duration is zero (indicating no patients follow this pathway), then the wait time is also set to zero."
 
![image](https://user-images.githubusercontent.com/30132017/126258485-1a672301-0204-41d1-a143-430ca8193117.png)

![image](https://user-images.githubusercontent.com/30132017/126259095-23271f34-1457-46cc-8a03-0258bc9ed3c1.png)

## Recommendation
- Let's discuss this a little further.  We may have accommodated the zero condition in the model already.  However, don't have an explanation ready for the Team Data value.

**Comment by lzim** [comment]
@jamesmrollins @lijenn @staceypark 

Re: "New Episode of Care" C34:D36.
Cross-ref the bugs where this was discussed #2032 & #2033
https://github.com/lzim/teampsd/issues/2032
https://github.com/lzim/teampsd/issues/2033

This is as I remembered, which is potential zeros for "New Episode of Care Wait Time" C34:C36 is handled by the model using the minimum transfer time and the "Adjusted Data GMH New Patient Wait Time" conditional formula. 

Vensim Comment or "i" info:
> "It is possible for the estimate for the median wait time to be zero, if the team sees many walk-in patients. However the model needs the wait time to represent the average, thus a value of zero is not feasible. In these rare cases, we prevent the model from using a zero average wait time, instead using the Minimum Transfer Time. If the relevant engagement duration is zero (indicating no patients follow this pathway), then the wait time is also set to zero."

Therefore, **we want the estimated value from CDW to populate the Team Data Table**, _inclusive of zeroes_, and if/when there is a 0 value for "New Episode of Care" C34-D36, then the model handles it as described in the IF_THEN_ELSE and comment for Adjusted Data GMH New Patient Wat Time above.

@TomRust Are you able to confirm?

**Comment by TomRust** [comment]
Hi @lzim and @jamesmrollins !  I don't quite know what I'm confirming -- but, yes, everything you stated above is right.  Are you asking because the "i" text isn't enough of an explanation?  Do you still have concerns about how the model takes in data on 0 day wait times?

**Comment by jamesmrollins** [comment]
Hi @TomRust .  No I don't think we have concerns about zero day, but were insuring we properly understood how the zero condition was being managed.  We were considering a minimum value of .1, but your model logic already handles the situation (IMHO).
