### ISSUE TITLE
ANDON Due TODAY 6/24 8:00AM Pacific - Cannot Log in to Team World for Team meeting

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#2078]
@jamesmrollins @lijenn @staceypark 

@hmarcia 

I am unable to log in for the team meeting that we have this morning. 
I cannot share a screen shot without identifying the team.

But, I'm getting a greyed out button for "Go to current session" and the red circle slash.
I seem to be able to join other teams, but not the team we have this morning.

Perhaps something is set up incorrectly for the team set up?

**Comment by lijenn** [comment]
@lzim 
I believe there is no current session yet because this is Session 5 for this team.
But if you click "Home", you should be able to enter the team world. Anyone else able to access the world from "Home"?
![image](https://user-images.githubusercontent.com/59668647/123284938-7e705600-d4c1-11eb-8119-4d501bf7f062.png)

@jamesmrollins @staceypark @hmarcia
