### ISSUE TITLE
wk5 jun_epic Resolve missing encounters data in Facility file

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#2089]
vizEnc and dataEnc run only through January in all the facility files

**Comment by staceypark** [comment]
@anazariz Once this issue is fixed, ping @lijenn and @staceypark on #2090.
Then propagate in this order:
1. Marcia's site where the issue was first identified
2. All other facilities engaged in this wave
3. Rest of the country

**Comment by anazariz** [comment]
The issue with SplashMothership.xlsb Excel file:

As this is a 32 Bit Excel file, it cannot handle large data well [(see this)](https://support.microsoft.com/en-us/office/choose-between-the-64-bit-or-32-bit-version-of-office-2dee7807-8f95-4d0c-b5fe-6c6f49b8d261). 

In fact, the file fails often during propagation. At times these failures cause file corruption.
A copy of an uncorrupted version must be available at all times to resume propagation (after configuring the uncorrupted file with the latest data where the corrupted file was interrupted). The exchanging of uncorrupted/corrupted file and preparation for resumption is a lengthy process, which occurs numerous time during the monthly propagation. In one such exchanges an older version of the file was used (as the good copy). This resulted in the VBA (in the Excel file) pointing to a wrong version of  a table in PTSD_OMHO (without the vvc addition), which has not been refreshed since March. Unfortunately the correct version of the code is no longer available (as shown below) because the file that contained it (a good file) is also corrupted.
I know what the corrupted file contained (as I wrote the original coding) and will proceed to correct the  issue.

![image](https://user-images.githubusercontent.com/39805164/123850667-25446000-d8cf-11eb-8fa8-7985f115b611.png)
![image](https://user-images.githubusercontent.com/39805164/123850731-37be9980-d8cf-11eb-8c6c-f3d8a3ad0bf5.png)
![image](https://user-images.githubusercontent.com/39805164/123850767-4016d480-d8cf-11eb-9539-2b9d30eb6536.png)
![image](https://user-images.githubusercontent.com/39805164/123850773-43aa5b80-d8cf-11eb-9eba-6570a91d2145.png)

**Comment by anazariz** [comment]
This item is fixed. RCA (Root Cause Analysis) is in the ticket.      

Root Cause - Explained earlier in this card. 
 
**Note –** Facility file is having a hard time dealing with the large volumes of data in it. This is more pronounced in the cloud than the on-premises. Per my observation there is heavy data traffic between the application (Workbook) and the database, which now has to go through extra layers of security check in the cloud. This causes frequent timeouts with larger datasets (several Facilities). In some cases I have put error trappings that catch and display these timeouts so you can see what is going on. In some cases the errors are not trapped. So they happens all that is observed is missing data. This is not necessarily and error or ANDON, it is just a transaction that did not complete. After fixing 2089, we tested this by comparing the Facility in the cloud and the on-premises. The cloud version had all kinds of issues whereas the onsite did not.

**Comment by lijenn** [comment]
@staceypark & @lijenn to test and check for the missing data in co-planning Facility files and then live teams before propagation.

**Comment by lzim** [comment]
> @staceypark & @lijenn to test and check for the missing data in co-planning Facility files and then live teams before propagation.

I really appreciate your help with these tasks Jenn & Stacey. 
I reminds me of making sure that we have specified the **co-planning tasks** as checklists for CRM.
