### ISSUE TITLE
Question: Are Disaggregated Services by Diagnostic Cohort Charts Intentional?

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#2099]
From @branscombj on Tuesday 6/29:

Does the AGG model disaggregate services by diagnostic cohort? I see all the options - AUD, OUD,PTSD,DEP,Other - under some of the variables in the drop-down menu in Results dashboard, but I don't remember that being part of this

. See screenshot of bc comparing services and showing all the PSY Starting a Service Rate variables. <br/><br/><br/><br/><br/>![image](https://s3.amazonaws.com/epicenter-asset/production/va/va-psd-sim/1624986992743574345_img0.png) <br/>

**Comment by jamesmrollins** [comment]
Hi @TomRust - Please take a look at the above question.  Indeed, it appears that the service variables do disaggregate by diagnostic cohort.  The illustration shown above shows rates for services that are applied to the given AUD, OUD etc . . .  diagnoses. It makes sense since it is showing how the given diagnosis is divided among services for treatment.  However, I cannot answer whether this was intentional or not.

**Comment by lijenn** [comment]
Looping in @branscombj so she's on the thread since she posted this from the Sim!

**Comment by jamesmrollins** [comment]
Discussed with @branscombj in the Support Workgroup Leads meeting 7/7.  Answered that indeed, the diagnostic cohorts were intentionally designed into the AGG model.  Decided to close issue.
