### ISSUE TITLE
wk4 jun_epic: Data UI on SharePoint Online - Confirm vizHF Default Categories and Reset Pivot Chart doesn't reset to the Default Categories

### ISSUE THREAD

**Issue by dlkibbe** [lzim/teampsd#2102]
@hmarcia @dlkibbe were doing an orientation session for the Data UI with the team lead for the team that meets on Tuesdays at 4:30am Pacific.

1. The dataHF tab appears to have complete data but the vizHF tab is not receiving the data correctly; the visual charts are not reading correctly. 

2. When we tried to reset the pivot chart, I received an error message and when we clicked on debug, an error message (screenshot below) was received.
 
![image](https://user-images.githubusercontent.com/59668647/124010718-08be2b80-d994-11eb-8b48-977b3324814a.png)

**Comment by hmarcia** [comment]
not sure why this is assigned to me...?

**Comment by lijenn** [comment]
@hmarcia Was accidently assigned, we unassigned you :)

**Comment by dlkibbe** [comment]
@hmarcia because I don't know what I'm doing when I clicked on the "assign" tab (Sorry!)

**Comment by lzim** [comment]
Discussed at 7/6/21 facilitate_workgroup
@anazariz and @staceypark 

Is this bug ready to close? Thanks!

**Comment by lijenn** [comment]
@lzim @staceypark @anazariz 

Update: vizHF and dataHF both contain the same dataset.

However, 2 issues need to be clarified and resolved:
1. vizHF does not show all the HF categories that are available. After pulling in patient level data, it only defaults to certain categories. You can still manually filter to show all the HF categories.

2. Reset Pivot Chart button does not reset the chart to show the default categories after the data pull. 
This issue was also identified in an older team's data ui file from April (specifically Jane and Matt's team).

**Comment by lzim** [comment]
@anazariz 

These can be the default HF for the viz tab of the Data UI. 
FYI: @staceypark & @lijenn 

<img width="198" alt="default_hf" src="https://user-images.githubusercontent.com/7454688/126022595-08b0b0c3-9423-44af-98a6-819d61cdbf4f.PNG">

**Comment by lijenn** [comment]
UPDATED DECISION: 
We have found the defaults are listed, so we are not going to change the defaults listed in the screenshot above.
However, the bug here is that these defaults listed below and already in the code are not being picked up in the data ui:
![image](https://user-images.githubusercontent.com/59668647/126211492-1b44b403-8f48-4e15-bcc5-3a807e777e47.png)

**Comment by staceypark** [comment]
@afshin

**Comment by staceypark** [comment]
@anazariz For Matt's Thursday 7/22 10am Coplanning Site, I did not see these categories in the vizHF healthfactorcategory button:

- [ ] Opioid Assess
- [ ] PBM PharmD MH Subst Abuse Med
- [ ] Suicide Safety Plan Review

**Comment by dkngenda** [comment]
@staceypark Discussed at HQ workgroup 7/22

If a facility does not use a HF category it wont display which could be all that's going on here per @lzim

**Comment by lzim** [comment]
**Discussed this at team_time 8/3/21 and Ash worked to establish VBA code for the facility file ("Mothership") that dynamically retains the default vizHF even when a facility does not have those HF.**

The code is on #2115 and may also be implemented in "SplashMothership_online_ash_copy1.xlsb" or "SplashMothership_online_ash_copy2.xlsb"

**DECISION: Since we are using the Data UI and it currently is working, and our priority is Power BI, we will NOT implement any code changes to the Data UI Nevermore 23 right now.**

Closing this issue.

**Comment by hnorthcraft** [comment]
#adjuducate_memo @lijenn @lzim @dkngenda 

Should this be re-classed as closed as unplanned. Or since it looks like there was some work, can we _update the SP_, I have already added the operations label.
