### ISSUE TITLE
wk2 jul_epic Bug/Question: SIM UI - Balanced Mode % and Header Name

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2111]
From @branscombj and @MattMoore2 on Tuesday 7/6 at 6:30am Pacific:

1. Should % on Balanced Mode add up to 100%?
2. Should the green header say "Team Data" if it's in Balanced Mode?

![image](https://user-images.githubusercontent.com/59668647/124620608-748a1380-de2e-11eb-8f8a-ac01d98479c4.png)

**Comment by jamesmrollins** [comment]
@lijenn @branscombj @MattMoore2 - I have studied the questions and think I can answer, but need to confer with @TomRust first.

**Comment by jamesmrollins** [comment]
Hi @lijenn @branscombj and @MattMoore2 .  FYI @TomRust 

## Should Percent of Balanced Mode Add Up to 100%?

The term “Balanced” means the proportion of patient treatment start decisions for a given service are calculated by dividing the patients starting a given service per week, by the total number of patients who went through intake and were reviewed. This proportion will influence the treatment decision rate, which moves patients into the Patients Waiting to Start stock position based on the actual start rate.  Therefore, the balancing is not across services; rather, it is between the treatment decision rate and the start rate. In “Balanced” mode, the model will continually adjust treatment decision rate with the start rate to near zero, as the intake and start rates change due to experimentation.

The rates don't necessarily add up to 100%, since they are not related.  Moreover, such as with Team Data, the percentage could be over 100% due to patients using multiple services, or less than 100% because of downstream constraints like RVI and Missed Appointment Rates feeding back on the decision rate.  The "Balanced Mode" is designed to show the contrast between balanced inputs based on current policies versus what is showing in team data.

## Should the Green Header Say "Team Data" if in Balanced Mode?
The header can be changed to something more accurate.  Currently, the variable is named, "Use Team Data on New Patient Referrals."  Since the variable contains the "i" information explaining Balanced Mode, it is named in the header.  It is the mode switch that turns the balanced mode off or on. 

![image](https://user-images.githubusercontent.com/30132017/124824780-afbc3d80-df27-11eb-86b2-aa338d57300c.png)

**Comment by jamesmrollins** [comment]
Decision during Workgroups Leads 7/12  - Rename variable "Balanced Mode."
