### ISSUE TITLE
wk2 jul_epic BUG?: Sim UI - Lag in radio buttons in Display Patient Services 

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2118]
@branscombj @MattMoore2 Identified a lag in the radio buttons for Display Patient Services.
Takes a while for the buttons to register and switch services, it's ~3-4 second lag from what I've noticed. 

![image](https://user-images.githubusercontent.com/59668647/125118390-7d841a80-e0a4-11eb-9a03-3285782efe2f.png)

Console code:
![image](https://user-images.githubusercontent.com/59668647/125118287-5b8a9800-e0a4-11eb-9abc-f9bbf7114fee.png)

**Comment by jamesmrollins** [comment]
@lijenn @branscombj @MattMoore2 - I reviewed the Smart Look video and I believe the simulation is behaving normally.  There is a lag when you click the radio button, because page has to re-render to display the new values.  The time should be around 1 second, but that can vary depending on your processor and how many apps you are running and windows you have displayed (as these take up memory space on your PC).
