### ISSUE TITLE
wk3 sep_epic: Sim UI - Auto-save experiment name in save dialog

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#2130]
@jamesmrollins  

**We can pull up the prior experiment names & values to efficient set up a similar experiment:** _Is it possible to be able to choose your last experiment when saving an experiment run?_

I find that when the experiments get sufficiently complex, I'm doing it in the home screen w/copy & past in the Experiment Maintenance Menu. This is not too bad as a workaround, but I wondered how easily it would be to have a list of prior saved experiments that you could use to more efficient save an experiment that includes all the same changes, plus maybe 1 or 2 more.

Thanks!

### Check off requirements to verify progress through feature_tracker.
- [ ] 1. **DEFINE in work_breakdown**
  - [ ] a. **what & why** - **written definitions of requirements** in a **numbered checklist** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** requirement definitions an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 2. **DESIGN** in **operations_to_do** and **research_to_do**
  - [ ] a. **what & why** - **_MVP_ of design** of requirements in a **algorithm map, wireframes or design** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** design **asynchronously** or an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 3. **DEVELOP** in **under_development** - "frozen"

  Task Cards:
  #
---
- [ ] 4. **TEST in functional_test**
  - [ ] a. **what & why** - **TEST requirements** using **testing_checklist** on the **master_feature_card.**
  - [ ] b. **date & who** -  **Verified** via TEST **asynchronously** or an **existing team meeting.**
  
  Task Cards:
  #
---
- [ ] 5. **PROD in done**
  - [ ] a. **what & why** - **_DOCUMENT_ feature** using **document_tracker** for the **5 D's.** 
  - [ ] b. **date & who** -  **DELEGATE**
    - [ ] **describe_learners** [Jenn & Rita]
    - [ ] **detail_facilitators** [Jane & Debbie]
    - [ ] **document_team** [Anthony]
    - [ ] **disseminate_scientists_va** [Anthony]
    - [ ] **depend_products** [hq & ees]
  
  Task Cards:
  #
---
- [ ] 6. **closed** - fully documented, trained and ready for the next release.

**Comment by jamesmrollins** [comment]
From Workgroups Leads meeting 7/26:

- Instead of dropdown, we would like to automatically gather experimental variable inputs and use them to automatically name the experiment.
- We would use the nomenclature already developed and the value of the experimental setting.

**Comment by jamesmrollins** [comment]
Hi @hirenp-waferwire 

We would need to modify the dialogue below and automatically set the experiment name based on selections made in the Experiments Section. 

## Save Format

1. Gather any pre-run mode switch settings (CC/MM/Agg Balanced Mode versus New Patient Start Rate)
2. Ignore any experiment values set at their default setting.
3. List experiment variables and their respective values.
4. List any Service or Cohort variables next.
5. Date stamp

## Dialogue Change

1. Move the button to top row.
2. Remove lengthy explanation.
3. Remove fields.
4. Make experiment name field editable


![image](https://user-images.githubusercontent.com/30132017/127019823-f328c974-f9fd-4d62-a2dd-6ed4163088b4.png)

**Comment by jamesmrollins** [comment]
@lijenn @staceypark @lzim @branscombj :

1.  There are no technical limitations - we can do this.
2.  It will take us around 20 hours. 
3.  We do have a policy issue to discuss - what do we do with the use case where a simulation is iterated quarter-by-quarter?  I know it isn't supported by the current curriculum, but it is a supported capability.  If we save with every experiment quarter-by-quarter, assuming there are experiment variable changes with each iteration, then the save function would tack that on to the experiment name string.  It could result in very long and unmanageable file names.

**Comment by lijenn** [comment]
Discussed Monday 8AM 8/23 WG:

Discuss at Sim UI 8/25 to see if we should roll this out.

**Comment by staceypark** [comment]
@jamesmrollins not sure how close to down this will be by the end of wk1 september.
if it won't be done, can you split this out; especially when we get to qa for it, so we don't drag the same 25 points across several sprints

**Comment by jamesmrollins** [comment]
Hi @staceypark 
I believe we will have this done by Monday.  So when It comes out, I will check-it and close this card.  Then I will open a QA card to manage the next step.  Thanks, James.  PS, Since we missed the 6th release date, I will update the release too.

**Comment by jamesmrollins** [comment]
Hi @TomRust - I have a question regarding user variables in the SP model.
@staceypark and @lijenn the naming algorithm is working for all the modules except for these three variables in the SP model.  Once @TomRust confirms (hopefully Tuesday), I should be able to have this in test by Wednesday.  

## User GMH High Risk Patient Flag Rate %

This variable and its cohorts SMH and PCMHI are set up in a way that is confusing.  Take a look at the image below:
- The variable name indicates it is a percentage, but the units are 1/wk, versus the usual dmnl.
- The minimum value is -1, but the default is set to -0.01.  Does this mean the range of values is between negative 100% and 100%?
- Or should the default value actually be -1.0?
- This is driving our naming routine a little batty.  It would be great if we could just update the default.  The downstream logic is looking for a >0 value, otherwise it uses the base case, so it shouldn't change anything.  (see second screen capture).
 
![image](https://user-images.githubusercontent.com/30132017/132165514-f25f30c6-65d3-40ca-8bb0-a799aac7ba21.png)

![image](https://user-images.githubusercontent.com/30132017/132165868-888250ca-7c7d-414d-8ce4-30677aa9e349.png)

**Comment by TomRust** [comment]
HI! @jamesmrollins 

- The units are actually "Patients receiving a flag / total patients / week" but the "Patients / patients" cancels, so Vensim shows just "1/wk" 
- The range of user input  probably could be a lot smaller (like from 0 to 10%), as I image it would be unheard of for 10% of a clinic's patients to receive a high-risk flag **_every_** week.  If they held at 10%/wk for a whole year, the clinic would have very few non-flag patients left! 
- Like you say, the default value for "User GMH High Risk Patient Flag Rate %" can be anything less than 0.  If you want to change it to -1, that is fine by me and the model.

**Comment by jamesmrollins** [comment]
Thanks @TomRust . 
- I will modify the model variables to make the trigger value -1.0.
- I will modify the range of values from -1 to 0.10 on the slider.
- Thank you for the explanation of the 1/wk UOM.  

@lijenn and @staceypark we should be able to complete this feature this week.  When complete I will close this card and open a QA card.

**Comment by lijenn** [comment]
## hq_workgroup 9/9
- By end of meeting finalize communication plan w/Liberty about UAT.
- #manuscriptmonday Sign up for office hours, Circulate by Wed COB the week before.
- Tech Lead Behavior Interview at 10AM Tuesday
- Tech Lead Behavior Interview today

Wed Support WG:
- Let James, Matt know they don't need to attend since we are still focusing on SIM UI

Thurs Quant:
- Keep focus on story 13 Power BI

**Comment by jamesmrollins** [comment]
Hi @lijenn @staceypark @lzim   I reopened this issue to make you aware of the specifics of how the save dialogue is going to work.

## If The User Attempts to Close the Browser Tab or the Browser

![image](https://user-images.githubusercontent.com/30132017/134937339-0e193c98-912d-4ab1-a62f-1f5bd36501e2.png)


## If the User Attempts to Log Off

![image](https://user-images.githubusercontent.com/30132017/134937499-3fa0724a-426c-453d-b148-830de07ea7e2.png)
