### ISSUE TITLE
wk5 aug_epic story_1: Github/zenhub data pipe line 

### ISSUE THREAD

**Issue by dkngenda** [lzim/teampsd#2170]
This issue is concerned with establishing a pipe line for getting IIR AIM 3 data (i.e cost of bugs)

- [x] Check data obtained using github API in power BI
- [x] Contact zenhub for insights on how to pull this data
- [x] Schedule a meeting with Herin to discuss possibility of pulling required data using github REST API.

**Comment by staceypark** [comment]
from hq meeting 8/19:

### Costing data parameters needed:
- indication whether issue is bug/feature/ops admin
- label (workgroup)
- story points for estimating work efforts
- collect data in at least 1 month chunks as the smallest size

### ISSUE: 
ZenHub CSV reports do not show the same data that the visualizations necessarily do. Only the control chart lists all the issues individually with: repo, title, estimate (story points), & start/end date. Lacks workgroup labels & trackers (projects) which can be gathered from GitHub API. From David's GitHub API to R data, we still need data on: tracker (aka "Project" on the 9 clicks) all the labels that are attached to an issue and not just the first one.


### DECISION:
We'll join on the issue_number to put the GitHub API (where the workgroup label and project tracker are) and ZenHub API (where the story points are) data together. Probably it wasn't until the Team PSD 2.0 reboot in May 2021 that we really standardized our data. 

We shouldn't need to reapply "bug" and "feature" labels to our first 900 issues (~2200 total) issues, because the we created them contemporaneous to when we started having "bugs" and "features" ~300 bugs~400 featuresWe would have to apply story points retrospectively too, but we can check with Libby to see if using story points just over the period of time we adopted them  (Team PSD 2.0 reboot) would suffice for reporting in the paper.

### For operations costs
- Need to use the Outlook calendars for meetings. Lucid Meetings calendar.Dynamics to track our emailing/scheduling types of operations/admin tasks. 
- So, we'd need to double-check: Outlook API, Lucid Meetings API, Dynamics API



FYI @claradismuke - we've updated our data collection plan a bit (see above)

**Comment by claradismuke** [comment]
Dear Stacey, getting story points by month by workgroup for 1) bugs 2) features 3) other operations was a suggestion so that we could divide salaries by 12 and do a monthly cost by workgroup for the 3 categories. However, if the time issue is a problem (monthly), we can divide salary quarterly or by other time measure consistent with the ease of reporting story points by workgroup and the 3 categories. The goal is to have a SOP not just for the paper but also for future cost estimates and reporting in the most reasonable manner. Thanks Libby

From: Stacey Park ***@***.***>
Sent: Thursday, August 19, 2021 6:25 PM
To: lzim/teampsd ***@***.***>
Cc: Dismuke, Clara E. ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [lzim/teampsd] wk3 aug_epic story_1: Research how to pull github data for IIR cost of bugs (#2170)


from hq meeting 8/19:

Costing data parameters needed:

  *   indication whether issue is bug/feature/ops admin
  *   label (workgroup)
  *   story points for estimating work efforts
  *   collect data in at least 1 month chunks as the smallest size

ISSUE:

ZenHub CSV reports do not show the same data that the visualizations necessarily do. Only the control chart lists all the issues individually with: repo, title, estimate (story points), & start/end date. Lacks workgroup labels & trackers (projects) which can be gathered from GitHub API. From David's GitHub API to R data, we still need data on: tracker (aka "Project" on the 9 clicks) all the labels that are attached to an issue and not just the first one.

DECISION:

We'll join on the issue_number to put the GitHub API (where the workgroup label and project tracker are) and ZenHub API (where the story points are) data together. Probably it wasn't until the Team PSD 2.0 reboot in May 2021 that we really standardized our data.

We shouldn't need to reapply "bug" and "feature" labels to our first 900 issues (~2200 total) issues, because the we created them contemporaneous to when we started having "bugs" and "features" 300 bugs400 featuresWe would have to apply story points retrospectively too, but we can check with Libby to see if using story points just over the period of time we adopted them  (Team PSD 2.0 reboot) would suffice for reporting in the paper.

For operations costs

  *   Need to use the Outlook calendars for meetings. Lucid Meetings calendar.Dynamics to track our emailing/scheduling types of operations/admin tasks.
  *   So, we'd need to double-check: Outlook API, Lucid Meetings API, Dynamics API

FYI @claradismuke<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fclaradismuke&data=04%7C01%7C%7C49020638d2f64d58623708d9636a07ae%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637650130074143924%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=XuijVuEYuWrCNYF4G7rs6ZnYdWG6ept%2Bn0ZBXQY6INw%3D&reserved=0> - we've updated our data collection plan a bit (see above)

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flzim%2Fteampsd%2Fissues%2F2170%23issuecomment-902317040&data=04%7C01%7C%7C49020638d2f64d58623708d9636a07ae%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637650130074153881%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=rBq1W0z5CVsJsylzfvmN%2BDtJv51nkEH6%2FQ379WjjcOY%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FARXOMDC3LRJNUTA5YTR4PJ3T5WHGJANCNFSM5B2EQS7A&data=04%7C01%7C%7C49020638d2f64d58623708d9636a07ae%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637650130074153881%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=x%2BDeM1SsQT2WGVMHBjxt9Ku9HqlQnAvTtvyQoEhXuSM%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C49020638d2f64d58623708d9636a07ae%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637650130074163835%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=QjU79m8%2FVnufQns2EPaUMXURhIhSuaHY7v5KeP%2BJtyk%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7C%7C49020638d2f64d58623708d9636a07ae%7Ce95f1b23abaf45ee821db7ab251ab3bf%7C0%7C0%7C637650130074163835%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=mKQMFJlhkSFTfP%2Bozzyb2cHN%2FUZzSGei6Xpf4D5I1jA%3D&reserved=0>.

**Comment by dkngenda** [comment]
Discussed on 8/22/2021 Workgroup leads:

@dkngenda to review @jamesmrollins feedback on Zenhub endpoints to pull story points for closed issues

**Comment by dkngenda** [comment]
Discussed at 8/23 workgroup leads

David to document discussion with Hiren on using github and zenhub API to pull cost of bugs data

**Comment by dkngenda** [comment]
This issue is closed and under QA
