### ISSUE TITLE
wk5 aug_epic: UAT Bug - Coplanning Email - Unable to see all members/emails in the To field & Email is marked as Complete in Dashboard without being responded to

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2210]
1. **Who encountered the bug:** Jenn

2. **Which instance are you testing in?:** QA

3. **Date/Time of the bug:** Fri. 8/27 at 10:30p

3. **Role:** Admin

4. **Detailed description of the bug:** 

**Unable to see all members/emails in the To field:**
- Setup Coplanning members to receive emails (My VA and my gmail)
- Coplan email was sent to both members, but I'm unable to see both emails in the To field of the email 
*(This makes is hard to know who sent the email/who am I responding to? Both Groups and Teams should be able to see who else is on the email thread)*
   - Point of View from my VA email: ![image](https://user-images.githubusercontent.com/59668647/131221958-344965f8-3441-43ba-906a-4acaa5e4590f.png)
   - Point of View from my gmail: 
![image](https://user-images.githubusercontent.com/59668647/131222451-8aef4241-5e0d-4ea0-b75c-20ad051f008f.png)

**Email is marked complete in Dashboard, despite not being responded to:**
(@hsnyder2 I think I need to check with you if this is an actual bug or not)
- Coplan email was received by VA and gmail
- Gmail responded to the coplan email
- VA email did not receive the response, but the email came through on Dynamics in Dashboard and MTL Help Emails tab for the Team *(I think this might be related to the emails in the To field bug above?)*
- Email on Dashboard marked the receiving of the Gmail response as Complete, but no one responded to it 
*(Is this not a bug because Dynamics received the email so it thinks the Email activity is complete? It looks confusing because the Email Response Date column is blank)*
![image](https://user-images.githubusercontent.com/59668647/131222359-247c63a8-a992-4d0d-a852-f04f60ef632e.png)
Edit: Just noticed the Due date might be wrong? Email was received on Friday night, but due date has it for Sunday.

*Note:* There is ~5 min delay from receiving the response sent from Gmail into Dynamics

**Comment by hsnyder2** [comment]
Replies:
1. Co-Planning Emails were designed to go to individuals (i.e. like an "mail" merge) so, yes, you won't be able to see who all the recipients are from the email along but you should be able to see all the individual emails for that templated email on the MTL Help Emails tab for the Co-Planning Group.  You WILL be able to see all the recipients for Teams templated emails because one email goes out to everyone on the Team (vs copies of the templated Co-Planning emails that each Co-Planning member receives as individual "personalized" emails, e.g. Dear [[MemberName]].
2. MTLH and MTLI emails that haven't been responded to have a blank **Email Response Date**.  Activity Status for any emails coming into MTLH and MTLI, whether responded to or not, will ALWAYS have an **Activity Status** =  _Completed._
3. Regarding  "_VA email did not receive the response, but the email came through on Dynamics in Dashboard and MTL Help Emails tab for the Team (I think this might be related to the emails in the To field bug above?)_", yes, because individual emails were sent, even a "Reply All" will only go to MTLH inbox, not everyone else who also got the same email (per #1, above).
4. Regarding "_Edit: Just noticed the Due date might be wrong? Email was received on Friday night, but due date has it for Sunday._", **_yes, this looks like a bug and Arlene will investigate._**

**Comment by hsnyder2** [comment]
**Regarding #1**, after discussing w Jenn, we want CP Emails to go to all CP Grp Members with "Receive Email" checked (vs sending personalized copies to individuals.  She'll add personalization in Combined Info at the Group Level before sending.
> How might we be able to add those to the email who aren't addressed in the body?  Currently this is done using CC in OL.
**Regarding #3**, this will be addressed when we implement the previous change to send **_one_** email to all CP Grp Members.
**Regarding #4**, Arlene is looking into why this was "Sunday" and not "Monday".

**Comment by hsnyder2** [comment]
OK, I've logged a CR to change Co-Planning emails to work like Teams emails (per above).
As for this issue, also reported above:
_Just noticed the Due date might be wrong? Email was received on Friday night, but due date has it for Sunday._
![image](https://user-images.githubusercontent.com/71669014/131577088-1f3a09e5-ec62-4b06-84d3-d06ced4af713.png)
If you notice, it's Due Date is 10:46PM PT, which is really Monday ET time, which is what the D365 server runs under.  **Is this a problem that still needs to be addressed?**

**Comment by lijenn** [comment]
@hsnyder2 Ohhh, Dynamics runs under Eastern time...I think we might need to look at this tomorrow Wednesday.
FYI @staceypark I might need your help thinking about this.
