### ISSUE TITLE
wk1 sep_epic: UAT Bug - Unable to create a new coplanning group or mtl team (using an existing coplan group)

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2228]
1. **Who encountered the bug:** Jenn

2. **Which instance are you testing in?:** QA

3. **Date/Time of the bug:** 9/7 at 5:44am Pacific

3. **Role:** Admin

4. **Detailed description of the bug:** 

- Tried to create a new group from the Live Blue version 
- Filled out the first 4 fields on the General tab (see screenshot)
- Got the bug in the screenshot
- See MS Teams for log file
- Getting same error message when trying to create a new mtl team from an existing coplan group

![image](https://user-images.githubusercontent.com/59668647/132346923-743ab5c2-8b80-4439-9acd-2c353c86b216.png)

**Comment by hsnyder2** [comment]
@lijenn Looks like this was due to the issue Arlene addressed with the Session Validation functionality that we deployed last week.  She thought she'd cleaned up all the bad data that the new Session Validation now prevents but it looks like this bug is related to some data cleanup that didn't happen on the Live Blue Version.  It should now work for any new Live Blue groups or Teams you create, however you may run into the same issue with any Live Red groups or teams.  Recommend that if you want to test with anything other than Live Blue, just create a new Version to start from scratch so that the new Session Validation provides the session linkage checks that we've added and prevents this from happening going forward.

**Comment by lijenn** [comment]
This has been fixed in Live Blue and the new Live Red Version I created, thanks!
