### ISSUE TITLE
wk2 sep_epic: UAT Usability Feedback - Filtering on the Activity Widget in Dashboard (related to 7.2)

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2232]
1. **Who encountered the bug:** Jenn

2. **Which instance are you testing in?:** QA

3. **Date/Time of the bug:** 9/10 9:27 am Pacific

3. **Role:** Admin

4. **Detailed description of the bug:** 

@hsnyder2 @apisano0920 
- Trying to complete 7.2 to see if MTL Info Emails show up in All Activities view in the Dashboard, but it's really hard to find a specific email due to inability to filter by columns, only sort. 
- I found the email I was looking for before by searching for the subject line, but then lost it and am having a hard time finding it again.
- Any way we can use these filters?
![image](https://user-images.githubusercontent.com/59668647/132886845-a95632d7-7725-46fa-b63b-31f6ddabb7f4.png)

**Comment by hsnyder2** [comment]
Per conversation with Arlene about this, to make the filters available in the Dashboard Widget Columns, we'd need to make the entire widget an editable grid view, which could cause problems due to the fact that you probably don't want users editing all those fields.  Suggest that if you need to filter My Open Activities, just click Activities in the LH Nav.  It's the same list but you CAN filter the columns there.  LMK if that's acceptable.
