### ISSUE TITLE
ANDON SIM UI Due ASAP: Appointment length: All assumed 1pt/1hr?

### ISSUE THREAD

**Issue by branscombj** [lzim/teampsd#2257]
@TomRust @lzim
@hmarcia and I are working with a team in AGG that wants to consider creating a group to manage stable MM patients. I believe the experiment would need to
* Add 1 hr/wk to Group
* Remove 1 hr/wk from MM because it will be led by a MM provider
* Add a % of Appt Supply to Group
* Remove the same % Appt Supply from MM because the same people will be leaving individual MM and going to group MM.

Marcia suggests that many of those MM appointments are like 2 or 3 pts / hr but I am thinking the model assumption is 1/hr. Can you help us think this through?
Thank you!!

**Comment by lzim** [comment]
@branscombj & @hmarcia 

We are going to treat this as an ANDON and scope, alert and communicate until this is resolved.

I posted this on Teams on the prep thread for this team.
> My memory was that the models treat MM as 30 minute encounters, not an hour. So, MM would be able to see 2 patients per hour.  We could have gone to 20 minutes per MM encounter or 3 patients per hour, but many providers felt this was not reliably realistic.

You've brought up something important the Vensim model is normalizing to hours for appointment supply using standards that we synthesized between these standards/sources.
a. CPT coding rules,
b. the 2018 version of the "Mental Health Guidance for Workload Capture" guidance document from OMHSP (@hmarcia has there been a more recent update?), and 
c. input from frontline clinicians.

@jamesmrollins is going to post below four screen captures directly from the Vensim model of the PSY, MM, CC & group appointment supply units where you can see, in the models, we are applying a **1 appt : 1 hour ratio for PSY** and a **1 appt : 0.5 hour ratio for MM**. 

#### We reviewed the SQL VBA code in the Data UI as well 

_Where these are the CPT codes being binned into this categories._

```
select distinct wl.visitsid, wl.visitdatetime, wl.patientsid, wl.LocationSID"
sql = sql & vbNewLine & " ,case when (listICD.depression_EBPharm = 1 or listicd.depression_ebpsy = 1) then 'Dep'"
sql = sql & vbNewLine & " when listICD.AUD_EBPharm = 1 then 'AUD'"
sql = sql & vbNewLine & " when listICD.OUD_EBPharm = 1 then 'OUD'"
sql = sql & vbNewLine & " when listicd.ptsd_ebpsy = 1 then 'PTSD'"
sql = sql & vbNewLine & " Else 'other' end as [Diag]"
sql = sql & vbNewLine & " --re-add intakes so that they don't get lumped into adjunct for supply and referral pcts etc."
sql = sql & vbNewLine & ",case when cpt.CPTCode in ('90791','90792','99201','99202','99203','99204','99205') then 'Intake'"
sql = sql & vbNewLine & " when cpt.CPTCode in ('90834','90837','90833','90836') then 'psy'"
sql = sql & vbNewLine & " when cpt.CPTCode in ('90853') then 'group'"
sql = sql & vbNewLine & " when cpt.CPTCode in ('99212','99213','99214','99215','90833','90836') then 'mm'"
sql = sql & vbNewLine & " when cpt.CPTCode in ('t1016','90832','90839') then 'cc'"
sql = sql & vbNewLine & " Else 'adjunct' end as 'EncounterType'"
sql = sql & vbNewLine & " , 0 as ebpsy"
sql = sql & vbNewLine & " into #Visits"
```

@TomRust Then, we see that these calculations are being applied to these objects 'psy' and 'cc' and then again we see the logic below from Vensim, **which concerns us that these calculations are being applied twice once it he Data UI and again in Vensim.**

`select 'Appointment Supply (median)' as Label, [Intake] as intake, [psy] as psy, [ebpsy] as ebpsy, [cc]*0.5 as cc, [mm]*0.5 as mm , [adjunct]*0.25 as adjunct, ([group]*1.0/6) as 'group'"`

#### We also have a unit label inconsistency in the Sim UI

Where time (hours) listed in the AGG Team Data Table in the Sim UI below (**hrs/wk**)
![image](https://user-images.githubusercontent.com/7454688/134035629-6e5db2a5-ebcb-42d0-b211-65a9d0d952ab.png)

But, the "i" information lists **appt/wk**
![image](https://user-images.githubusercontent.com/7454688/134041475-8c627512-2628-48a1-a699-66accf764977.png)

FYI: @dkngenda @lijenn @staceypark 

**_ANDON Next Steps:_**
- [ ] Clarify whether there is an OMHSP update since the 2018 Workload guidance.
- [ ] Specify in the Data UI. There is the CPT Code cheatsheet in each Sharepoint folder at mtl.how/data, which shows how CPT codes are binned. However the logic of these time based calculations is not in the "i" information in the Data UI, Model or Sim UI (i.e., in only in the equations, not the notes for the user).
- [ ] We need normalizing to time (hrs/wk) to be accurate **_in the Data UI_**, because of _MTL Red_ teams who need this to interpret data (i.e., handling this in the Model alone won't work for _MTL Red_ users).

**Comment by jamesmrollins** [comment]
Hi @TomRust - Here are the screen captures referenced above.

**MM**
![image](https://user-images.githubusercontent.com/30132017/134042808-fd29aaae-c69d-43b8-a0dd-06314c5b44a5.png)

**CC**
![image](https://user-images.githubusercontent.com/30132017/134043193-239c1c29-3db1-4d6a-9b5d-7b07421ed89c.png)

**Psy**
![image](https://user-images.githubusercontent.com/30132017/134043595-6c7bc200-46f5-4299-9d50-0ac682628791.png)

**EBPsy**
![image](https://user-images.githubusercontent.com/30132017/134043770-60c0aad0-fc8f-4483-b0e7-cc98493ff3c4.png)

**Group**
![image](https://user-images.githubusercontent.com/30132017/134043924-25563a2e-7427-4b0d-9ea8-fc3cf555992d.png)

**Adj**
![image](https://user-images.githubusercontent.com/30132017/134044070-466202e6-26e4-4958-aae3-40755c01d27d.png)

**Intake**
![image](https://user-images.githubusercontent.com/30132017/134044459-ab673bbe-8d94-416b-8c91-d176c5ab31b8.png)

**Comment by TomRust** [comment]
@branscombj @lzim  @jamesmrollins -- 
I think we have confusion about the units.  We never use units of "patients/hour," as we didn't want to pretend to be that precise.  We want the teams to focus on long-term impact and sustainable solutions, so, in AGG, our rates are all "x/week."

In the Vensim model, we specify that we are *not* assuming that all appointments are the same length.  For most appointments, there is a 1:1 conversion from provider-time to patients-seen, but not for CC, MM and Group.  Those first two are half-hour visits, and 15 minute visits for Group (so, one provider-hour can be used for 4 group appointments).  We also specify the number of patients per appointment, where all except Group are 1pt/appointment, with Group set to 6pt/appt.  

Note: From a modeling point of view, changing any of these ratios is very easy.  


SO: @branscombj @hmarcia , I think you all are on solid ground.  Shift one provider hour from MM to Group should allow the team to see 22 more patients per week  -- as 1hr in MM = (1 patients / appointment) / (.5 provider hour / appointment) = 2 pts / provider hr, but 1hr in Group = (6 patients / appointment) / (0.25 provider hour / appointment) = 24 pts / provider hr... assuming providers book their patients into the Group, of course.  :)  

That is the tricky part of any experiment in AGG -- changing the service proportions.  I wouldn't guess at those... actually, the one thing I would feel good guessing is that they won't change by the same %.  :)  Accurately guessing at how all these rates and accumulations balance out is too difficult, and why we have the model in the first place -- let it do the work for you.  I'd run the scenario in Balanced Mode, so the team can clearly see the impact of this change.  Or, if they won't let you, then I'd do a prep run in balanced mode on your own, to get a sense for what the % "should be" if the team only wanted to optimize for filling their calendars, not patients' actual conditions/symptoms.

**Comment by TomRust** [comment]
@lzim @jamesmrollins -- About the potential for the SQL and the Vensim repeating the same adjustments and the confusion of units in the Team Data Table and its i-text: *This is a problem.*  Vensim takes "total hours per service summed across all team members / wk"  as it's input on provider capacity, and then calculates the "appt / wk" based on the ratios listed above (and screen shot-ed by James, also above).  The slider is also in units of "total team provider hours offered for a service / wk," not "total appointments offered for a service / wk."

At some point, it looks like we decided to change the Team Data Table to instead show the Appointment supply in units of "Appts / wk"?  Showing "appointments / week" would need the type of conversion that you show in the SQL code snippet.  Even if this were done right -- which it doesn't appear to be -- it would still be confusing for the end users, as their experiment slider for "appointment supply" is in units of "provider-hrs / wk."  

My memory is that we kept everything to do with supply in the units of "provider-hrs / wk," as that was the easiest, most-common unit for our end-users.  We wanted them to think clearly about shifting how they spent their time (their hours), and make it as easy as possible to see that we were conserving staff time with every experiment.  Using "appts/wk," as the base units for thinking, discussing, and experimenting with supply would lead to more confusion than "provider-hrs / wk." 

If, with your experience now, that ISN'T the case, then we can talk about the work it would take to switch the sliders over to "appts / wk." My initial guess, though, is 3 days of work just for me, then another few days working with the James and with the data team.

**Comment by TomRust** [comment]
Oh! and, one qualification: My info is based on AGG model "agg_v15_2019_06_14" which I'm assuming is the most up-to-date version.

**Comment by lzim** [comment]
@TomRust @jamesmrollins 

- I remember it the same as you do Tom, that hrs/wk per service the cleanest for a typical provider to think through. 
- And, yes, I agree it is a problem that we have the calculation applied in Data UI and Vensim.

This phrase from your second post above @TomRust seems important to review in the SQL/VBA code of the Data UI: 
> total hours per service summed across all team members / wk" as it's input on provider capacity 

Because from the code snips above the CPT codes binned into MM, CC, etc. already have a time increment inherent to them (i.e., T1016 for CC is 15 minutes). _So, we would need to determine whether any original estimate of hours per service is coming from, if there is other relevant code FYI: @dkngenda_

**Comment by jamesmrollins** [comment]
Hi @TomRust - your Agg model is a month behind, BUT it is likely ok from a structural perspective as I may have changed just the "i" information content.  In any case, I suggest a new pull via GitHub to cross-level your versions.

**Comment by lzim** [comment]
@jamesmrollins & @TomRust Re: AGG Appointment Supply units
**I still think that hours/week is the clearest for all our users in both the Data UI and the Sim UI.** (meaning no change on this).
- Data UI and Vensim definitions appear to align for all services exception _Adjunct & Group._
- It can be hard to accurately track the variables (& any conversions) across the Data UI, Vensim Model, and the Sim UI screenshots above. So, I'll double-check below.

**VBA/SQL applies this equation to the count of CPT coded encounters for that "bin" (CC, MM, etc.) to derive an estimate of the hours for each service (Can you help confirm @dkngenda).**
`select 'Appointment Supply (median)' as Label, [Intake] as intake, [psy] as psy, [ebpsy] as ebpsy, [cc]*0.5 as cc, [mm]*0.5 as mm , [adjunct]*0.25 as adjunct, ([group]*1.0/6) as 'group'"`

This produces the **Data UI** median and total appointment supply in the **units of hours,** where
Intake = 1 hr
PSY = 1 hr
EBPsy = 1 hr 
CC = .5 hr
MM = .5 hr
_Adjunct = .25 hr
Group = .1667_ (_is this meant to be the conversion for patients?? 1/6?? Should this apply here?_)

In **Vensim**, the exogenous constant for appointment supply (aka "time for appointment") for each service in the units **hours/appt** are specified in equation box as
PSY = 1 hr
EBPsy = 1 hr 
CC = .5 hr
MM = .5 hr
_Adjunct = 1 hr_
_Group = .25 hr_ (_CPT code for 90853 does not have a defined time stamp_)

**So, between the Data UI and the Vensim Model, the only definitional difference arises for _adjunct_ and _group._**

**When I double-check via our AGG documentation** at https://mtl.how/demo (here: https://forio.com/app/va/va-psd-demo/aggsdmdoc.html#a464) I'm seeing **hours/wk** as the units there too for everything related to **appointment supply** for each service.

**Conclusions & Next Steps**
- [ ] **Need to resolve the Adjunct and Group difference, but otherwise the Data UI and Vensim align.** See my questions above about group for our support_workgroups. We'll discuss group psychotherapy business rules for 90853 with the QIICs tomorrow.
- [ ] **Not sure how appt/wk was introduced in the "i" info for the Team Data Table and Sliders in AGG - this needs to be fixed**, but also understood @jamesmrollins if it's related to our GitHub workflow. But, **the hrs/wk label in the Team Data Table and on the sliders is correct and should be retained as is** (see below).
- [ ] **I see the appt/wk unit label used for appointment supply in Sim UI CC, MM, PSY modules too.** I haven't double-checked all the Model files for this, but based on the Data UI code, I expect these **appointment supply** units should be **labeled hrs/wk** in CC, MM & PSY too. Does that sound right @TomRust & @jamesmrollins ?

**CORRECT:**
![image](https://user-images.githubusercontent.com/7454688/134098776-08672fef-12db-4c20-8813-37f3f1ed1f1b.png)

**INCORRECT:**
![image](https://user-images.githubusercontent.com/7454688/134098858-3aa4bff7-054c-49da-bdd6-3a3a33d94a84.png)

![image](https://user-images.githubusercontent.com/7454688/134099175-9dd31ee6-ffd1-43ad-b07f-81450c7496e3.png)

FYI: @staceypark @lijenn @mnallajerla

**Comment by lzim** [comment]
**From meeting on 9/23/21**
Attended by @jamesmrollins @TomRust @dkngenda @jeffhoerle 

@jamesmrollins - **Please communicate with @lijenn @lzim & @staceypark about when to implement this change, given that it would impact our LIVE teams.**

#### Appointment Supply #2257

##### AGG Group

**Keep Data UI** 1hr/6 calculate time in hours.

@jamesmrollins **Sim UI Change**  from .25 to 1 hour.

_Will look like more group for our active teams b/c change is in the Sim UI._

##### AGG Adjunctive

@dkngenda  **Change Data UI** .25 hr to 1 hr

**Keep Sim UI** - 1 hr for adjunctive.

_Will not impact our current teams b/c they will not be pulling data again at this point in the program._

**Comment by jamesmrollins** [comment]
Hi @lzim sorry I can't load the chat into this thread, at least today anyway. Not sure what is going on! I will coordinate model update with @staceypark and @lijenn 

![image](https://user-images.githubusercontent.com/30132017/134596059-6756e38f-0895-4f34-af44-40903cb644da.png)

**Comment by jamesmrollins** [comment]
Hi @lzim @staceypark @lijenn.  I see that you want me to change the default value of "group time per appointment" from 0.25 to 1.0.  This change will take me roughly 15 minutes to make the change and promulgate through CI/CD merges.

**Comment by jamesmrollins** [comment]
Hi @lzim and @TomRust .  Below are results of testing.

# STL Test

## Method

- Downloaded the STL model parameters file.
- Loaded the STL AGG session in the Sim UI (uses current model with 0,25 set for Group Time Per Appointment).
- Loaded the current AGG model in a client version of VENSIM V.9.0.0 along with the STL model parameters file.
- Set the Group Time per Appointment to 1.0.
- Ran comparison tests as shown below.

## Assumption
- Client Vensim model and server run Vensim produce the same model results.

## Test 1 - STL Model Parameters BC Comparison

### Vensim Run with "Group Time per Appointment" set to 1.0

![image](https://user-images.githubusercontent.com/30132017/134712700-22f9ef89-9deb-43ca-a53d-41e2876fb403.png)

### Sim UI Run with "Group Time per Appointment" set to 0.25

![image](https://user-images.githubusercontent.com/30132017/134712943-7a062456-9f15-45ea-af7a-e89d6c4cca29.png)

### Discussion Test 1
- The difference is slight between the results (0.959 - 0.916 = 0.043)
- Base case run seems to have a very slight effect with new Group Time set to 1.0.

## Test 2 - STL Last Experiment Comparison TD_as_psy_26_ebpsy_3

### Vensim Run with "Group Time per Appointment" set to 1.0

![image](https://user-images.githubusercontent.com/30132017/134714140-dacf0e79-6ee4-4681-ae47-4a6accff5563.png)

### Sim UI Run with "Group Time per Appointment" set to 0.25

![image](https://user-images.githubusercontent.com/30132017/134714247-13e98500-95c9-4599-94d2-fc3ac9e293c6.png)

### Discussion Test 2

- The numbers did change due to changes elsewhere in the model (psych and EBpsych), but were very slight ( -0.004)
- Experimental run seems to have a very slight effect with new Group Time set to 1.0.

## Test 3 "User Group Appointment Supply" Set to 3 hrs/wk in Both Models

###  Vensim Run with "Group Time per Appointment" set to 1.0

![image](https://user-images.githubusercontent.com/30132017/134715332-0d235c80-9559-4f4f-94e3-e56f8c74587c.png)

### Sim UI Run with "Group Time per Appointment" set to 0.25

![image](https://user-images.githubusercontent.com/30132017/134715287-74f12ccc-65af-4d2a-9bc5-79285b210b2a.png)

### Discussion Test 3

- Direct adjustment of available hours for Group appears to have little effect; even though the amount of hours per week was tripled.
- This might be due to the Group Completing Rate selecting the smaller of the Desired Completion Rate and the Potential Completion Rate.  However, it uses a Quantum function that I am not qualified to interpret. In all cases, the Desired Completion Rate was smaller, except with the psych and ebpsych run.  

## Conclusion STL Tests

- The differences between the two models are slight and will likely escape notice.
- The model balancing behavior also seems to limit any extremes that changing the factor from 0.25 to 1.0 might cause.

**Comment by jamesmrollins** [comment]
@lzim and @TomRust .  I downloaded the ALT team data file.  They currently have "0" hours for group in their data.  They currently have no saved experiments.  Indeed, they appear in the Sim UI to be doing their BC study, as they do not have a "bc" experiment saved. In any case, the way the model works, zero will always be the minimum value and therefore have no effect not matter what factor you use (.25 or 1).

**Comment by jamesmrollins** [comment]
Hi @lzim and @TomRust  

# K Test Results

## Base Case Run with Legacy Model File (PROD)

![image](https://user-images.githubusercontent.com/30132017/134726677-bfbddee3-e04b-43ca-976b-a25d9f9342d2.png)

## Base Case Run with Updated Model File (TEST)

![image](https://user-images.githubusercontent.com/30132017/134727243-5859e262-cfdf-4dde-a892-37bc00b1b61f.png)

## Discussion
- Appears to be a  0.235 difference, which is larger than the differences shown in the STL analysis.
- Would not be noticeable, since they haven't run their base case yet.

**Comment by lzim** [comment]
Decision 9/24/21 move to PROD.
