### ISSUE TITLE
wk4 sep_epic: Prod Bug - Unable to create a new co-planning group

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2264]
1. **Who encountered the bug:** Jenn

2. **Which instance are you testing in?:** Prod

3. **Date/Time of the bug:** 9/23 12:00p Pacific

3. **Role:** Admin

4. **Detailed description of the bug:** 

Tried to create a new coplanning group in Version Live Blue, getting an invalid argument bug:
![image](https://user-images.githubusercontent.com/59668647/134569664-6552c5cb-0965-4823-8afe-3e4972df427b.png)

Note: I am able to create a new coplanning group for the Version Live Red that I created. This bug may be related to a permission or deployment issue since the Live Blue version looks to be the same as the one in QA.

**Comment by apisano0920** [comment]
Looks like the Live Blue Version is not fully defined. There is a story in the back log that we added because of errors like this that can occur if the sessions have not been defined but are being referenced in the checklists. When that change has been made you would not be allowed to even attempt to add a new group or team using the version. 

Look at the Session list for Live Blue. Note that there are no entries in the Session column. 
![image](https://user-images.githubusercontent.com/60359621/135148565-7a793df5-57ea-41d9-9dab-e75886a24db7.png)

Additionally, if you sort the sessions by the Phase column you will see that there are also no group sessions defined.

I believe if you fix these two things and verify that the checklist and emails are referring to sessions that you have defined in the session list, that the error will go away.
