### ISSUE TITLE
oct_epic: Data UI Bug/Story 13 Power BI - Blank category in vizHF

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2303]
There is a "(blank)" category in vizHF and it looks to make up a big chunk of this facility's health factors ( acility is the coplanning group from Tuesday 10/5 from 10-11am Pacific).

I think this bug will also be a blocker for VA Red teams.

Filtering for blank if the dataHF tabs shows columns A-G populated with data, but columns H-L focusing on Health Factors and Template data are blank:
![image](https://user-images.githubusercontent.com/59668647/136269578-5c42917a-fc85-4279-ad32-2c9c65708eba.png)
![image](https://user-images.githubusercontent.com/59668647/136269983-26d3d290-cf7d-42a5-adc4-b4090081154c.png)

Note: For the "missing" category, the dataHF tabs shows the HealthFactorType as:
- MH ACT 3 CLOSING PHASE [C] or
- MH ACT 2 ACTION PHASE [C]

**Comment by staceypark** [comment]
quant_ops 10/7:

@jeffhoerle 
When the data is getting stitched together, there's a table being referenced in the PTSD_OMHO database called "ListHealthFactorType2" with fields: category, type, ebp template, ebp initiate.

current theory:
When the table was originally created in PTSD_OMHO, it had the most current health factors at the time. There's ~250k health factor types in the dataset, but only ~1/3 in the PTSD_OMHO table. All the health factors that don't have a match (the remaining 2/3) show up as "blank."

Jeff can update the PTSD_OMHO table using LSV table from data warehouse (category & type fields match between the two tables). Concern is that we would be including records that were intentionally subsetted out. 

@lzim 
Any given set of health factors may not match between facilities because it's a "catch all" created with the local adpac.

DECISION: We will use health factory category & type columns and assume there is no further subsetting done. We will pursue the fix on the legacy data UI.

**Comment by lzim** [comment]
**Discussed at quant_research and support_workgroups on 10/13/21**
@mnallajerla 
Will help with adding this to the existing documentation as we update all Data UI related documentation for **Story 13 Power BI**

**_Cross-ref Issue Task for Updating Power BI documentation:_** #2310

**Comment by staceypark** [comment]
hq workgroup 10/14:
DECISION - We decided to close this card. In the future, we will also not keep dev cards open for documentation, but rather close the dev card, and cross ref it to a document card. This ensures we are tracking the efforts & costs associated accurately as well.
