### ISSUE TITLE
Track Power BI use

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#2313]

**Comment by lzim** [comment]
**Discussed at 11/17/21 overflow_meeting**

**TWO Requirements**
- [x] Track unique users/page views in general for Power BI Data UI (annual reports)
- [x] Track use by team so that facilitators know who may need extra help/engagement (facilitator relationships)

1. **Go to the PTSD_OMHO Workspace to Check Usage Reports**
![image.png](https://images.zenhubusercontent.com/5e4ac859b8781e56a5b7d6a1/66c540b1-fea7-4ed3-96c1-9815e2a03560)

**2. Select the relevant NAVY Blue Report -> Select 3 dots and "View Usage Metric Report:**
![image.png](https://images.zenhubusercontent.com/5e4ac859b8781e56a5b7d6a1/cede0f09-d112-4f9b-9f77-ea6625557638)

**3. Looks like this at first:**
![image.png](https://images.zenhubusercontent.com/5e4ac859b8781e56a5b7d6a1/7e955931-dfe3-40c6-a4de-c233b079d88c)

**4. Toggle the view user report ON to see the specific users**
![image.png](https://images.zenhubusercontent.com/5e4ac859b8781e56a5b7d6a1/0a5a3f16-03e0-4026-9832-815bf7d13a9a)

**@mnallajerla We need to document this in the https://mtl.how/manual under the facilitator and admin sections.**
Cross-ref #2310
