### ISSUE TITLE
wk3 oct_epic: SIM UI - TT Reports stop at #2

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2317]
@jamesmrollins When trying to produce the 3rd tt report, the # for the tt report seems to only go up to # 2, when it should go up to 3.

![image](https://user-images.githubusercontent.com/59668647/137985124-e89eb7c7-c3c5-4b0d-a508-bf1f328abd43.png)

**Comment by jamesmrollins** [comment]
Hi @lijenn - we never finished because we didn't determine how we were going to provide the Shewhart chart.  The only difference between TT2 and TT3 is that chart.  So this may be more than a break-fix bug.

**Comment by jamesmrollins** [comment]
Hi @hirenp-waferwire .  FYI @lijenn 

Can we activate the tt3 report please?

- The tt3 report at this point is the same as the tt2 report in terms of content.
- The only difference is "tt3" instead of "tt2" in the header.
- We will attempt to integrate a chart similar to the P-chart in the near future.
- Please run this fix through the breakfix server.

Thanks,
James

**Comment by jamesmrollins** [comment]
@hirenp-waferwire here is the place to put the tt3 option.

![image](https://user-images.githubusercontent.com/30132017/138214376-69b8499a-a02f-432d-b92d-5dadd1580807.png)
