### ISSUE TITLE
wk3 apr_epic QA card: Review Cost diagram LucidChart figures

### ISSUE THREAD

**Issue by mnallajerla** [lzim/teampsd#2320]
Creating a QA card for this task after discussion in 10/25 WorkGroup Leads.
Please review these cost figures to let me know if they look good, or if any changes are needed.

Reference Dev card #2297 

Lucid Chart Links:

https://lucid.app/lucidchart/63986fd2-fef1-48f5-bf30-5dacd4f7600a/edit?viewport_loc=173%2C-363%2C2844%2C1265%2C0_0&invitationId=inv_983b6875-c255-41bf-9175-f0c16c868334

Screenshot here for reference: 
![image.png](https://images.zenhubusercontent.com/6130066bf230e9289f9a2c0c/6b5bf032-54cf-4ad9-bac0-1356eab56a97)

![image.png](https://images.zenhubusercontent.com/6130066bf230e9289f9a2c0c/812194a3-c34f-4d04-a479-2ff4cc18b771)

**Comment by lijenn** [comment]
Discussed team temp 1/27:

Need to reiterate the value streams figure to visualize development work in service of research and ops and how research and ops work can overlap.

**Comment by lijenn** [comment]
Lindsey and Jenn picked this up over wk1-wk3 apr_epic and discussed updated costing figure with Libby. Updated figure is in LucidCharts > manuscripts folder > [manuscripts_participatory_examples](https://lucid.app/lucidchart/cc990fe3-8de7-4898-9b0a-33f361a4a237/edit?page=VcVfwLIricyS&invitationId=inv_56e048a2-50f7-4e9e-9d30-6a89172c611f#)

Closing this card since the work to edit the figure has been done.
