### ISSUE TITLE
MTL HQ issues/questions

### ISSUE THREAD

**Issue by branscombj** [lzim/teampsd#233]
I'm finding myself unable to edit the agenda in today's Lucid meeting. Have I just forgotten how, or am I lacking a necessary permission? Thanks!

![lucidagenda](https://user-images.githubusercontent.com/29778290/47158629-13a30180-d2ba-11e8-8130-4d70c81b8222.png)

**Comment by lzim** [comment]
Morning @branscombj I changed your role from participant to presenter.

What happens when you click on the Agenda tab now? Do you now see the "edit" and "organize" buttons on the right hand side? As shown below?

![lucid_edit_agenda](https://user-images.githubusercontent.com/7454688/47159113-f95d2980-d2a1-11e8-9a45-1564c3a010b7.png)

**Comment by branscombj** [comment]
Hmm. No. Tried logging out and back in but still not seeing them. Thanks for the image to remind me where I'd see them.

**Comment by lzim** [comment]
Hmm... @ericasimon and @staceypark this is odd, because I made everyone a "presenter" and the settings for the meeting say that presenters should be able to edit the agenda. Will HQ please look into it?

Thanks!

**Comment by staceypark** [comment]
@branscombj I figured out where the issue was happening and fixed it. You should be able to edit right now.

@lzim @ericasimon It looks under "Settings" we have to set "Agenda Editors" as "Everyone Invited" even though Lindsey making everyone a "presenter" above should have worked.
