### ISSUE TITLE
wk2 jan_epic Develop Data Export (CC, MM, PSY, AGG) from PBI into SimUI - DEV Card

### ISSUE THREAD

**Issue by jeffhoerle** [lzim/teampsd#2346]

**Comment by jamesmrollins** [comment]
FYI @lijenn @lzim 

## BLUF

The means and methods to transport data between the PowerBI platform and the Sim UI is uncertain.  More exploration is necessary.


## Discussion

Discussed the issue of Team Data transfer between PowerBI and Sim UI with @jeffhoerle.  Below is a summary of our conversation.  We discussed:

- How Vensim variables make calls to xlsx files using addresses ModelParameters.xlsx, to tabs (ccparams) and cells (B1).
- PowerBI limitations regarding how xlsx files are exported from PowerBI and formatted.  While it is possible to pair definitions for data variables with values in PowerBI, it is not necessary to pass the cells with the definitions over to the Sim UI. 
- It would be necessary to output values to support all models; otherwise, the Sim UI would not be able to support a use case of the user exploring in other models besides the team instance. 
- Readdressing the cell address is possible within the model file.  So, if PowerBI outputs could not support the current address scheme for whatever reason, the address could be updated in the model.
- REST API may offer a way to transport directly from PowerBI to the Sim UI.  However there are concerns:
  - API may not work between domains based on current level of permission.  In any case, will require @lzim direct approval.
  - It is not clear if Epicenter supports the use of an API for data transfer, since the variable needs a model parameters file with cell address. 

## Way Forward

- James will investigate API alternatives with Epicenter.
- Jeff will continue explorations of how to export model parameters.

**Comment by jamesmrollins** [comment]
@ Support Workgroup Meeting 11/10 - Decided

 - Export a Team Data .xlsx file with all model information in a single row.
 - Readdress model variables inside each model to find proper location on the row.
 - Test model runs to ensure proper functioning.
 - Will need a sample export file to use for testing and prototyping.

**Comment by dkngenda** [comment]
@jeffhoerle @jamesmrollins  

Needs discussion on 11/17 support workgroup
