### ISSUE TITLE
wk5 dec_epic: story_13 PBI BUG Filter panel of data & viz tabs Division names exceed selections made in "Clinic Selections" tab 

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2371]
![image](https://user-images.githubusercontent.com/59668647/142292149-2c5997c2-438f-4e19-9d24-31963a34c791.png)

**Comment by lijenn** [comment]
@jeffhoerle Not sure if you tested this, but I'm still experiencing the same issue.

**Comment by mnallajerla** [comment]
DECISION @ 8 AM WG Leads: This issue may also be related to "Select All" button 
(Reference #2390). Will revisit & test once 'select all' issue is resolved. 

FYI: @lijenn @jeffhoerle

**Comment by mnallajerla** [comment]
Description to be updated post support WG 2 PM 12.1.21

**Comment by mnallajerla** [comment]
#2371 - The "Select All" button appears in all filter panels and was always working. It was only in the ClinicSelection tab that the "Select All" buttonwas selecting all the data and disrupting the processing of the data in a variety of other views.

The default status of all the tabs is to show all the data in viz or data tabs.Only the ClinicSelection filters the data.

Within a viz tab or a data tab:

The filter menu on the right hand side can filter on a column within that tab, e.g., "DivisionName"

This only applies to simple cases where the entirety of the CBOC is selected.

You must make selections in ClinicSelection tab.

Because unfiltered data w/no ClinicSelection selections retains too much data to process in the viz and data tabs

**Comment by mnallajerla** [comment]
DECISION: Remove "Division Name" and other sections larger than/left of "Clinic Name" in Data tabs to address this. 
Discussed at WG Leads on 12.13.21 

FYI: @jeffhoerle

**Comment by jeffhoerle** [comment]
"Division Name" has been removed from all Data tabs.  Closed.
