### ISSUE TITLE
wk2 dec_epic PBI Documentation Session 3 DEV

### ISSUE THREAD

**Issue by mnallajerla** [lzim/teampsd#2383]
- [x] Session 3 SEE Guide
- [x] Session 3 SAY Guide
- [x] Session 3 SAY Checklist

## 1. Link to the document and add relevant team members to the card.
- [ ] Add the link the current draft of the documentation for the issue:

## 2. Link to issues that must be edited in the document in the **issue_tracker** and **feature_tracker.** _(use the # for the link to the issue)_
- [ ] Issue 
- [ ] Issue 

## 3. Team Review
- [ ] Fidelity - check with Lindsey
- [ ] Data UI - check quant_workgroup
- [ ] Sim UI - check with model_workgroup and/or sim_workgroup

## 4. Review and Open Pull Requests _(use the # for the link to the pull request)_
- [ ] Check the draft for typos
- [ ] Check or open a pull request for the document edits

## 5. Review and/or Update Graphics
- [ ] Screenshots
- [ ] Gifs
- [ ] Logos/Icons
- [ ] Links

## 6. Dependencies
- [ ] Make sure that any edits you make that need to be added to **depend_product** are tracked (e.g., _MTL Video_)

## 7. Close Pull Requests
- [ ] Request review and/or close open pull requests for the document

**Comment by lijenn** [comment]
Discussed 8am WG 12/13:

- [ ] Agg is aggregate mix of services in a team, aggregate is still a mix of services in a team
- [ ] Note: Psy Details: visual is still missing, Jeff needs to find a way to add it in
- [ ] Removed "Params" - 3 left hand tabs 
- [ ] EDIT: in bold "Psychotherapy Patient Cohort" 
     - [ ] Sankey Scalar (row 1)
     New Patient Start Rate (pts/wk) (row 2)
- [ ] 
DOCUMENTATION: Due to the large amount of data in each report, we have to make ClinicSelections twice.Learner - Facing "SEE"First, we make ClinicSelections to zoom in on a particular Veteran's care,  then we can zoom out see what our care decisions are adding up to over time by reviewing team trends over the last in the viz tabs.In the next session, we make ClinicSelections to review team data estimates related to common care problems with Care Coordination, Medication Management, Psychotherapy, Team (Aggregate) Care, and the Mental Health Continuum of Care for Suicide Prevention.Facilitator - Facing - "SAY"  The selections should be the same, so that Data viz and patient reports correspond to Sim UI.MTL Blue - ClinicSelection for the session 2 report and ClinicSelection made for the session 3 report. MTL Red - ClinicSelection for the part 1 report and ClinicSelection for the part 2 report.Making the same ClinicSelections enables clinicians to zoom in on each Veteran's care in the data tabs and zoom out to review their team trends over time overall in the viz tabs and they will correspond.  This will also ensure that decision they review in the Sim UI align with the Data UI.

**Comment by mnallajerla** [comment]
Moving these notes above to the card tracking all theory and consistency review on documentation - #2423.
