### ISSUE TITLE
wk1 jan_epic: story_13 PBI BUG - Select All in ClinicSelection does not produce data in Data and Viz tabs

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2390]

**Comment by mnallajerla** [comment]
Status Update 12.1.21 @ 2PM Support:

- Select All button removed from PBI for now 
- Jeff: Select All button seems to be working in non-intuitive ways. It was selecting not just the clinics populated in the third column but all the clinics 

- Will this bug be resolved at some point? 
- NEED: It would be helpful if teams wanted to select all of the clinics. 

Status: 
- It is removed currently because it is unpredictable. 
- Not a priority at the moment, but come back to it later if possible

**Comment by lijenn** [comment]
Limitations from this came up again on 1/6/2022 with Bindu, Erica, @lzim, @lijenn 

We filtered the light blue column to Bindu & Eria's sta3n and Division Name, they hoped to see the their divisions data in the data & viz tabs. But we cannot show this without manually clicking through all the clinics in the green column.

Note: We plan to meet with again Bindy and Erica with top 3-4 question from them.

Let's wrap this into our next workgroup meeting @jeffhoerle & @mnallajerla

**Comment by jeffhoerle** [comment]
Implementing a "Select All" button that would operate as expected/desired is not possible.

There are two reasons why 
1 - The inherent way that the Power BI implements "Select All"
2 - The flexible clinic selection method we have implemented.

There is no easy way to explain why this is the case.  But they underlying issue is that "Select All" essentially tells Power BI to "remove all filters" from the Clinic Selections Slicer.  Removing all filters means that it will display data for all clinics, regardless of whether the clinic is visible or not.

If you wanted to have a way for users to select all clinics for a division, they only way to do it would be to implement another tab, but it would be called "Division Selection".  Adding this tab could create confusion however, because the selections of each tab would both apply to the viz, data and params tabs at the same time.  In order to use the "Division Selection" tab, the user would need to make 100% certain that all slicers have been cleared from the "Clinic Selection" tab.  The opposite would need to happen for "Clinic Selection" to work correctly.

**Comment by jeffhoerle** [comment]
Discussed at today's Quant WG Call.

Division Selection is not useful, without the ability to remove Clinics from the "Division Group".  Alternate suggestion not viable.  No other alternatives.
