### ISSUE TITLE
wk5 nov_epic story_13 Teams accessing PBI

### ISSUE THREAD

**Issue by mnallajerla** [lzim/teampsd#2393]
Even though the Gateway is fixed - without access to a Workspace, it looks like a Team Member would *not* be able to access either the report OR the app. This would need to be fixed asap in order for our first team to access PBI this week. 

![image.png](https://images.zenhubusercontent.com/6130066bf230e9289f9a2c0c/292e96e0-3ff0-4c9a-92e9-dc63b545847a)

![image.png](https://images.zenhubusercontent.com/6130066bf230e9289f9a2c0c/e85516b0-620f-42cd-9a46-70c28a69d54b)

Thank you @jeffhoerle !
FYI: @lijenn @dkngenda @lzim

**Comment by lijenn** [comment]
Solution: Admin & Facilitators will be able to give access https://mtl.how/data_test_access.
Need to add in Facilitator One-Pager, already in Learner Data UI cheatsheet.

@lijenn @mnallajerla

**Comment by mnallajerla** [comment]
Discussed at 2 PM Support WG on 12.8.21. Good to close.

**Comment by lzim** [comment]
**Discussed again 12/15/21**

Discussed w/BISL - this will be an ongoing issue for specific users.
Summary: The BISL RLS documentation clarifies that some users will experience access denials, and will need to be added to the Power BI "Dynamic Readers Group" for the instance (e.g., TEST, PROD).

Created two new cards for this and added to Power BI Master Documentation for Teams https://github.com/lzim/teampsd/issues/2310
- Track this dependency because our current TEST list of ["Dynamic Readers"]( https://mtl.how/data_test_access) will not carry over PROD. #2429 
- Add in Facilitator One-Pager #2428
