### ISSUE TITLE
wk1 feb_epic Story 13 : PBI - Track PTSD_OMHO Refreshes - coordinate ETL w/going to PROD pre-holidays

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2399]
Discussed from Quant Workgroup 12/2 - need to track how we refresh PTSD_OMHO

**Comment by mnallajerla** [comment]
Confirm if this is about setting up automated refreshes of the Data UI?

**Comment by mnallajerla** [comment]
See #2362 for more information as well

**Comment by lzim** [comment]
Per **support_workgroups** channel on **VA Teams 12/17/2021 10:20AM**

@lzim requested at ETL account for PTSD_OMHO today. Basecamp was finally back up this morning.

Some of the discussion still reflects wk3 jan_epic, but I believe we moved this forward to next week because it was actually much quicker to do than @jeffhoerle originally realized.

- If coordinated with going to PROD on Monday 12/20, it has the advantage of making it less necessary to worry about permissioning our next set of sights, including the Co-facilitator Prep on Monday Jan 3rd.
- AND of course, to help with bookmarks and tracking clinic name changes nearer to real-time.

FYI @lijenn @mnallajerla

**Comment by jeffhoerle** [comment]
We have all resources available to us.  Jobs are can be successfully run in PROD
