### ISSUE TITLE
wk2 jan_epic: "Appointment Slots %" row in MM Params Calculations 

### ISSUE THREAD

**Issue by mnallajerla** [lzim/teampsd#2415]
@lzim , @jeffhoerle & @mnallajerla discussed on Friday 12.10.21 in Support WG Thread. 

The "Appointment Slots % row in MM params tabs value not calculating accurately in the legacy (excel) files. 

"Appointment Slots % (with X waiver)"

- Cell B15 in Legacy Excel File.
- An experimental slider, not estimated from the data.

DECISION:

- Jeff and Lindsey will do a code review of B13 & B14 estimation and how that is being calculated in relation to B15.

Dependency:

- Lindsey will discuss this value w/ @jamesmrollins  to ensure it is being handled properly in the Sim.
- New parameter export file: BF2

Lindsey note: If "Appointment Slots % (with X-waiver)" is not estimated from data"

Then the implications are:
- [ ] Would be a Green Slider Experiment value in the Sim UI

- [ ] Probably we would not want it in the Data UI (review B13 & B14 first to see what makes the most for user interpretation).

Jeff:
- [ ] Review PSY Params for a workable size (~12-14 rows) and greatest corresponence to Sim UI. 

Lindsey: 
- [ ] Code Review B13 & 14 w/Jeff
- [ ] Review Vensim handling of B15 value w/James

[[See Support WG Thread 12.10.21](https://teams.microsoft.com/l/message/19:bfdf92c7846542b58e9961e1d8cc671e@thread.skype/1639154641837?tenantId=e95f1b23-abaf-45ee-821d-b7ab251ab3bf&groupId=1db500d5-0d01-4254-af42-ad3f78bafacd&parentMessageId=1639154617859&teamName=teampsd_vha&channelName=support_workgroup&createdTime=1639154641837) for all details mentioned]

**Comment by jamesmrollins** [comment]
Hi @lzim @mnallajerla @lijenn @jeffhoerle @dkngenda:  Here are some model snippets that show what is happening with the Appointment Supply.

## The Appointment Supply (75th Percentile) Is Split into Two Categories - X-Waiver, No X-Waiver with the 0.50 X Waiver Assumption.

![image](https://user-images.githubusercontent.com/30132017/145876382-e130d1c8-d7b7-4b72-9af0-d133ce56d67e.png)

## The X-Waiver and No X-Waiver Appointments per Week Are Introduced Then Divided Based on Reported Allocations

![image](https://user-images.githubusercontent.com/30132017/145879333-26011aad-2855-49cc-99dd-e208094c9983.png)

## Implications

1. How is the "Data AUD Slots Allcoation % (without X Waiver)" being calculated in the Data UI code without a base count of AUD appointments per week?  It seems impossible to do this without knowing or being able to sum the total count of X-waiver appointments per week. 

2. IF the reported allocations (i.e., "Data AUD Slots Allocation % without X Waiver") are calculated in the Data UI code based on the same base count of appointments per week as "Data Appointment Supply (75th Percentile)" THEN the recalculation of slots in appointments per week in the second diagram may be subject to shrinkage/overallocation because the reported AUD X-Waiver allocation, when summed with other cohorts, may exceed or be less than the assumed 50%. 

## Conclusion

1.  We really need to know how the reported "Data AUD Slots Allocation % without X Waiver" variables are being calculated in the Data UI.
2. If indeed the calculations are correct - then we should be able to find the actual "Data Appointment Slots % (w-waiver)"

**Comment by jamesmrollins** [comment]
## Appointment Supply no X-waiver and Appointment supply w/X-waiver

- Both appropriately refer to whether or not the provider has the X-waiver (numerator).
AND
- They are appropriately calculated as the two terms that sum to the total. 
AND
- Are appropriately derived from the Total Appointment Supply.

## Regarding Red and Pink coloring inside the Vensim model

- "Red with "Data" prefix means read in from Team Data." Meaning the value is calculated for that team.
- Pink means with "User" prefix means a user may provide a new value from the experiment sliders.

## "Data AUD Slots Allocation % (without X waiver)" 

The proportion of appointment slots allocated to each diagnosis for clinics where the provider does not have a DEA X waiver, calculated from the team's data. Providing evidence-based pharmacotherapy for OUD is not possible in these slots. (pct)

## Regarding Dimensionless Units (dmnl)

- dmnl unit = dimensionless unit (e.g. a percent)
- Variables read into the model, "Read into  the model from team data" are "EXOGENOUS"
- Greyed out variables in Vensim are called "SHADOW VARIABLES"

## Regarding MM Appointment Supply for the team

- We should be able to calculate what proportion for the Total MM Appointment supply are w/ and w/out X waiver.

- We should be able to calculate these values too:
  - AUD visit/Total MM visits
  - Dep visits/Total MM visits
  - OUD visits/Total MM visit
  - Other visit/Total MM visit

- We should also be able to estimate what proportion of the visits for each presenting concern were w/ and w/out an X waiver. 

### Using AUD as example

**w/x waiver** 
_numerator:_ 
Provider X waiver visits
_denominator:_ 
Total visits w/AUD as primary diagnostic code

_What we want our numerator to be assessing is whether or not the provider for that visit did or did not have an X waiver._

### Thus, with B15 (proportion of providers with x-waiver)

- We don't need the B15 value, as long as we have the provider & dea code to get an accurate estimate for each concern. Providers are either x-waivered or not.
- Of the AUD visits, how many were x waivered or not. This will need to = 100%.
- Our current "B.S." B15 value of 50% is being applied across the presenting concerns and then being used to calculate a variety of proportions later in the model.

## Next Steps

Finalize the calculations w/Jeff and then ensure that the logic is carried forward appropriately through the model/Sim UI based on the Data UI calculations.

**Comment by jeffhoerle** [comment]
I have implemented "Appointment Slots % (W/ X Waiver)" and published it to the Test App.  Also implemented updated logic for "Slots Allocation % (waiver)" for AUD, Dep, Other and OUD.

Appointment Slots % (W/ X Waiver) = (# Visits where Provider had X Waiver) / (Total # Visits)
Slots Allocation % (W/ X Waiver) -> AUD = (#AUD Visits where Provider had X Waiver) / (Total # AUD Visits)
Slots Allocation % (W/out X Waiver) -> AUD = (#AUD Visits where Provider didn't have X Waiver) / (Total # AUD Visits)

Note: "Slots Allocation % (W/ X Waiver)" + "Slots Allocation % (W/out X Waiver)" = 1

**Comment by lzim** [comment]
Thanks @jeffhoerle This is great! 

This logic makes sense to me and was our original intent for a data-based operational definition. 

@TomRust & @jamesmrollins Do either of you have any time to touch base tomorrow about the **Model**??

> I have implemented "Appointment Slots % (W/ X Waiver)" and published it to the Test App. Also implemented updated logic for "Slots Allocation % (waiver)" for AUD, Dep, Other and OUD.

> Appointment Slots % (W/ X Waiver) = (# Visits where Provider had X Waiver) / (Total # Visits)
Slots Allocation % (W/ X Waiver) -> AUD = (#AUD Visits where Provider had X Waiver) / (Total # AUD Visits)
Slots Allocation % (W/out X Waiver) -> AUD = (#AUD Visits where Provider didn't have X Waiver) / (Total # AUD Visits)

Note: "Slots Allocation % (W/ X Waiver)" + "Slots Allocation % (W/out X Waiver)" = 1

**Comment by jamesmrollins** [comment]
Hi @lzim - Yes I have time today.  Should we meet at the quant meeting at 11 PST?

**Comment by jamesmrollins** [comment]
@lzim @TomRust @jeffhoerle @mnallajerla @lijenn 

## MM Team Data and Model Review

- [ ] After review with @jeffhoerle and @TomRust on 12/20, the model should perform as designed with the newly provided slots allocations data without any changes to the current model.

## New Feature Recommendation

- [ ] Since waivered and non-waivered appointments per week data is available, we recommend using that data instead of proportions. _Keeping in mind:_
  - [ ] The Sim UI Experiments sliders graphic would need to be changed from "%" to "Appts per Wk" (this would be a minor change).
  - [ ] The model would require modification and simplification to remove the current scaled Appointment Slots % calculations (this would be more precise and a minor change).
  - [ ] The curriculum uses AGG for its GIF demonstrations, so there will likely be very little impact to curriculum regarding the new experiment slider visual in MM.  
  - [ ] May affect the video lesson regarding MM.
