### ISSUE TITLE
wk3 dec_epic Blue S2 & S3, Red Part 1 Guides fidelity & consistency review

### ISSUE THREAD

**Issue by mnallajerla** [lzim/teampsd#2423]
- [x] Add instructions on how and when to create a report bookmark

- [x] Meghana to review: Blue Session 1 Done & Do 
- [x] Meghana to review: Blue Session 2 See
- [x] Meghana to review: Blue Session 2 Say
- [x] Meghana to review: Blue Session 2 Checklist
- [ ]  Meghana to review: Data Cheat Sheet
- [x]  Meghana to review: Facilitator One-Pager

- [x] Meghana to review: Blue Session 2 Done & Do 
- [x] Meghana to review: Blue Session 3 See
- [x] Meghana to review: Blue Session 3 Say
- [x] Meghana to review: Blue Session 3 Checklist

- [x] Meghana to review: Red Part 1  See
- [x] Meghana to review: Red Part 1  Say
- [x] Meghana to review: Red Part 1 Checklist

Jenn Final QA:
- [x] Review all Sessions for fidelity to Theory of Change & incorporate info scribed on #2423
- [X] Jenn to review: Blue Session 1 Done & Do 
- [X] Jenn to review: Blue Session 2 See
- [X] Jenn to review: Blue Session 2 Say
- [X] Jenn to review: Blue Session 2 Checklist
- [ ]  Jenn to review: Data Cheat Sheet
- [X]  Jenn to review: Facilitator One-Pager

- [X] Jenn to review: Blue Session 2 Done & Do 
- [X] Jenn to review: Blue Session 3 See
- [X] Jenn to review: Blue Session 3 Say
- [X] Jenn to review: Blue Session 3 Checklist

- [X] Jenn to review: Red Part 1  See
- [X] Jenn to review: Red Part 1  Say
- [X] Jenn to review: Red Part 1 Checklist

**Comment by mnallajerla** [comment]
Discussed 8am WG 12/13:

- [ ] Agg is aggregate mix of services in a team
- [ ] Removed "Params" - 3 left hand tabs 
- [ ] EDIT: in bold "Psychotherapy Patient Cohort" 
     - [ ] Sankey Scalar (row 1)
     New Patient Start Rate (pts/wk) (row 2)
- [ ] DOCUMENTATION:

**Due to the large amount of data in each report, we have to make ClinicSelections twice.**

Learner - Facing "SEE"
First, we make ClinicSelections to zoom in on a particular Veteran's care in the data tabs, then we can zoom out see what our care decisions are adding up to over time by reviewing team trends over the last two years in the viz tabs.

In the next session, we make ClinicSelections to review team data estimates related to common care problems: Care Coordination, Medication Management, Psychotherapy, Team (Aggregate) Care, and the Mental Health Continuum of Care for Suicide Prevention.

Facilitator - Facing - "SAY" _The selections should be the same, so that Data viz and patient reports correspond to Sim UI._

MTL Blue - ClinicSelection for the session 2 report and ClinicSelection made for the session 3 report.
MTL Red - ClinicSelection for the part 1 report and ClinicSelection for the part 2 report.

Making the same ClinicSelections for each report enables clinicians to zoom in on each Veteran's care in the data tabs and zoom out to review their team trends over timein the viz tabs. And, ensures that decisions they review in the Sim UI align with the Data UI team data.

MTL Red: Teams can use team meetings to regularly review data tabs to zoom in make better decisions for individual Veterans, and regularly review viz tabs to zoom out and see whether team trends are trending in a helpful direction.

MTL Blue: Once the team's upgrade their mental models via participatory learning from simulation (MTL Blue), Teams can use team meetings to regularly review data tabs to zoom in make better decisions for individual Veterans, and regularly review viz tabs to zoom out and see whether team trends are trending in a helpful direction.

- [ ] Note: How the Data UI works to create and define a team's local data 

**Key Use Case and "value-add" of the Modeling to Learn Data UI: Teams need to define themselves using Clinics.**

**Local self-definition is the only valid way to define a team over time.**
Providers can be cross-mapped to different sta6a.

e.g., Altoona PCT (PTSD Clinical Team) covered up to 6 sta6a.

LocationSID not all clinics (sta6a) level map VISTA scheduling "clinics" to specific provider names.

**KEY IDEA:** The Data UI exists to standardize the process by which a team defines itself, since there is not data-based standard that could apply everywhere over time.

Team is the unit at which care decisions are coordinate and made.
Team is defined by the Green Box "Vista Clinics"

**Comment by mnallajerla** [comment]
Questions for Review with @lijenn 

- [ ] Blue Session 2 See: Should we emphasize Zoom In and Zoom Out so much, or forward and backward looking from the Say guide?

- [ ] Is all of the below cluttering the See guide? Thoughts on removing it and leaving it in Say guide only?
![image.png](https://images.zenhubusercontent.com/6130066bf230e9289f9a2c0c/2196a646-1b76-48d0-9d4b-3e7d0102ce42)

![image.png](https://images.zenhubusercontent.com/6130066bf230e9289f9a2c0c/d297e73f-a9c3-4aed-935f-cd675cdeb9f7)

**Comment by lijenn** [comment]
Hi @mnallajerla - 

1) Blue Session 2 See: Should we emphasize Zoom In and Zoom Out so much, or forward and backward looking from the Say guide?

Ideally a little bit of both, I think Forward and Backwards looking more easy understood because we have an image for it. We could emphasize Zooming in and Zooming a bit more in the SEE guide.

2)  Is all of the below cluttering the See guide? Thoughts on removing it and leaving it in Say guide only?

I would keep it there since it shows all the different and it can be hard to understand what it means just from looking at the tabs in PBI. I do wonder if we should add the description of each tab, it's not particularly useful just naming the tabs itself in the See guide, although the Facilitators explain it in the Say guide.

 3) You can explore Counts in the "viz" tabs by right clicking on any trend line and "Show As Table" to view the number of visits in a trend. *Do we need this Jenn, also is this accurate
 
This feature is accurate and I would keep it since we had a table-view of the Viz trends to show the # of visits from the legacy file. Would probably remove the word Counts though, I think it used to mean something different in the Excel version. 

Maybe something like: Another way to see encounters or services decreasing or increasing is by viewing the number of visits by right clicking on any trend line and click "Show As Table".

**Comment by mnallajerla** [comment]
Hi @lijenn - I've completed review of all the materials and checked them off above.

The only material I have not reviewed / changed is the datacheatsheet. I wonder if it might be a little overwhelming to look at, perhaps we can review it together in the new year?

**Comment by mnallajerla** [comment]
See MTL #299 Pull Request for QA
