### ISSUE TITLE
wk2 dec_epic BUG: PBI App Access Denied - Different from RLS Bug

### ISSUE THREAD

**Issue by mnallajerla** [lzim/teampsd#2424]
Users are unable to access PBI and receiving this message:
Different from RLS bug (#2393).

![image.png](https://images.zenhubusercontent.com/6130066bf230e9289f9a2c0c/9dc48223-df88-4545-9599-a9b4999a280b)

[Messaged ](https://teams.microsoft.com/l/message/19:bfdf92c7846542b58e9961e1d8cc671e@thread.skype/1639495452983?tenantId=e95f1b23-abaf-45ee-821d-b7ab251ab3bf&groupId=1db500d5-0d01-4254-af42-ad3f78bafacd&parentMessageId=1638232913225&teamName=teampsd_vha&channelName=support_workgroup&createdTime=1639495452983)@jeffhoerle about this on Support WG - to be discussed on 12.15.21 -

**Comment by lzim** [comment]
**Discussed 12/15/2021 Support Workgroups**
- [ ] This problem will resolve when we go to PROD.

**Comment by lijenn** [comment]
Discussed 1/24/2022 8AM WG:

Can we push the Power BI project .pbix file to private GitHub repo for version control and log in bugs?
 - SQL & DAX code can be annotated
 - .pbix file is 50-60GB
 - .pbix file contains PHI
 - PBI template (.pbit file) can be exported to contain the definition (no data) of how the model is configured, editors can go in this file to manage DAX code

**Comment by jeffhoerle** [comment]
Our TEST app is restricted such that users must individually be granted access to the app.  In order to resolve, you must go to the PTSD_OMHO TEST Workspace, then click "Update App" and select "Permissions".  Here you will be able to add individual email addresses to the list.  When you click "Update", this will give that user permission to the TEST app.  (Keep in mind this user may also run into the RLS issue - which can be remedied by adding the user to the Dynamic Readers group)

Note that once we move to the PROD app, it will be configured so that ALL USERS have permission to that app.  So in the future, nobody should encounter this message.
