### ISSUE TITLE
TT reports

### ISSUE THREAD

**Issue by saveth** [lzim/teampsd#245]
@lzim @ericasimon @staceypark 
I've created an initial tt3 report of q/h/f/d for Agg for blue team. I need to know if you guys want format 1 (first table) or format 2 (second table) to be produced for the other model tables.

In order to facilitate running the code for multiple team/models, I recommend that when the sim_ui_report is pulled, it should be pulled as follows:
1) basecase and exp1 done in the first file for tt2 report
2) exp2 and exp3 done in the second file for tt3 report
3) file should be saved as an excel and not a csv file
4) file should be save with the naming convention:  "model_exp#_exp#.xlsx", e.g.
"agg_bc_exp1.xlsx" and "agg_exp2_exp3.xlsx"

**Comment by saveth** [comment]
The file format for Agg seems to be consistent for both team. The file for psy differs in format from pull versions and by team. Can we standardize this @staceypark?

**Comment by lzim** [comment]
@saveth and @staceypark 

We can only standardize to the module...
- CC
- MM
- PSY
- AGG
- SP
...and, as we discussed on Friday, we can standardize when the export is done (ideally bc and exp 1 together for session 5-8 in the tt2report) and then exporting exp 2 and 3 for the tt3 report.

...and we can standardize the naming.

But, are there even more difference that you can help to standardize @staceypark?

**Comment by staceypark** [comment]
Hi @saveth! Thanks for working on these.
I personally think v2 (where each experiment is a row) is more readable.
I'm wondering though, is it possible to make another column for the experiment name headings? (like below)

  | Our Question | Our Hypothesis | Our Findings | Our Decision
-- | -- | -- | -- | --
Base Case |   |   |   |  
Experiment 1 |   |   |   |  
Experiment 2 |   |   |   |  
Experiment 3 |   |   |   |

**Comment by lzim** [comment]
Thanks @saveth and @staceypark!

**Comment by saveth** [comment]
@lzim @staceypark Thanks for the feedback. The code is ready to be merged with master and for you to use for the team files. Remember to place it in the same folder as the the team sim_ui output files and have the specified naming convention mentioned in the Rmd file in order for it to run.

@staceypark let me know when you're able to troubleshoot psy output files and it's ready for me to build the code around it.

**Comment by staceypark** [comment]
@saveth would something break if all the file names were changed to be entirely lowercase? I noticed that they're mixed

**Comment by lzim** [comment]
@saveth @staceypark @ericasimon @joycepyang 
This issue has overlap with issue **#199 Suicide Prevention Model Design Review 1** and **#202 Recovery of Experiment Files from Runes prior to 1.52 Release**.

**Comment by jamesmrollins** [comment]
I will look at the row placement in the export files and verify if we collapse the unused rows.  My thought is that it comes out comma delimited, so it is not a "fixed" field set up.  I will see what can be done . .  .

**Comment by jamesmrollins** [comment]
Hi @saveth,
I just emailed you a pipe delimited file for you to try.  For some reason, it is not a supported file-type in GitHub.  

Thanks,
James

**Comment by saveth** [comment]
@jamesmrollins thanks for the pipe delimited file. It looks good and the content are going into the appropriate columns. I just emailed to say that we should test it out for the psy team data pull that Stacey is doing. If it works there, then make it global?

**Comment by jamesmrollins** [comment]
Hi @saveth , thanks for moving the conversation to GitHub.  The export function is a global function, so I believe we can't test it model-by-model.  But I don't think it is a big deal to change it back if it doesn't meet your needs.  Unless you object, I will go ahead and put in a change order.  Then @staceypark can test it from "pull" all the way through the process.

**Comment by saveth** [comment]
@jamesmrollins Excellent! Glad to hear it won't be a big hassle for you. @staceypark please let me know when you pull bc_exp1 and exp2_exp3 files for psy.

**Comment by staceypark** [comment]
@saveth and @lzim 
I tried pulling the reports into an email and am running into some issues with rendering.
HTML - I can't copy and paste from the html into an email.  Loses all formatting
Word - I added an extra line of code to make it knit to word (always_allow_html).  This destroyed the formatting on the q/h/f/d but gave me proper charts.
PDF - Copy + paste destroys formatting all around.
Insert HTML as text option in Outlook - Keeps q/h/f/d formatting but destroys graphs.

My current solution has been to piece together the q/h/f/d from the "Insert as Text" option in Outlook with the graphs ctrl c+v from Word.  Sent you both an email of this version. Let me know what you think?

**Comment by saveth** [comment]
@staceypark  thanks for pulling the sim files for me! @jamesmrollins can we make the extension .txt instead of .csv? I've also email the report that @staceypark pulled. There's an issue with the export for experiment 1 for psy that doesn't seem to appear in the other three experiments. q/h/f/d is not conforming to 4 rows, 2 columns format.

**Comment by jamesmrollins** [comment]
@staceypark @saveth I will look into getting the file extension changed to txt.  The pipe delimited files are supposed to be in single column format, since they are truly text files, with the delimiter providing the column break.  However, I do notice a few stray rows that are broken into two columns (such as row 14 and 94 in psy_exp2_exp3. I know they look like excel files, but they can be opened with notebook.

**Comment by jamesmrollins** [comment]
I believe so . . . but the question of objective format for the file is something I still lack clarity about.  Do we still want pipes?  Or would you like it in another format.  We have never really discussed a format for the export file.


James Rollins

Managing Partner

Takouba Security, LLC.

1423 E. 29th Street, Suite 238

Tacoma, WA 98404

(425)919-5153[cid:53d1ef16-ce72-4be9-b0fd-1a05cd1846be]

www.takoubasecurity.com<http://www.takoubasecurity.com>




________________________________

**Comment by lzim** [comment]
@jamesmrollins @saveth @staceypark @ericasimon - related to issue #247 

@jamesmrollins question we are working on the export function with @saveth 
And we are trying to find out where it is recorded what the base case values are that the model reads, for example -0.01 or -1. Is that in the master crosswalk?

- https://github.com/lzim/teampsd/blob/master/resources/master_crosswalk/current/master_crosswalk_table_v16.2_5nov18.xlsx

What we want @saveth to be able to list what the experimental values are from the export and filter out those values that were not changed (i.e., base case values), since those are already reflected in the team data table.

**Comment by lzim** [comment]
@jamesmrollins @saveth @staceypark @ericasimon - related to issue #247

@saveth I believe the pipes issue is moot if we export an .xlsx file, right?

@jamesmrollins we are trying to find a file export that:

1. Is easy to work with for the end user provider who exports (e.g., Excel .xlsx)
2. Is easy/efficient to import and summarize visually at scale for end-users in team time reports using the R language so that it can be produced in VHA staff members email.
3. Is not limited in one operating system versus another (e.g., Mac vs. PC, etc.)
4. In the future can be analyzed in planned secondary analyses to determine the extent to which the simulation experiments that teams ran prospectively predict those changes in the subsequent empirical observations.

**Comment by jamesmrollins** [comment]
@savet it may be useful if you provided me a sample .xlsx file that is formatted the way you want, then I can reverse engineer it.


James Rollins

Managing Partner

Takouba Security, LLC.

1423 E. 29th Street, Suite 238

Tacoma, WA 98404

(425)919-5153[cid:498729c3-f167-4714-9fe0-13f47baaf0cd]

www.takoubasecurity.com<http://www.takoubasecurity.com>




________________________________

**Comment by saveth** [comment]
@lzim You're correct that the topic of pipe delimited would be moot if the sim ui is able to export the data directly into excel.
@jamesmrollins the sample .xlsx file is on its way to you via email.

@lzim @staceypark @jamesmrollins thank you for moving so fast and being super responsive. :)

**Comment by saveth** [comment]
@lzim @staceypark I've made the changes per our discussion on Friday and the file has been upload in #271 . I've also email the file location so that you can view the outputs and provide additional feedback. Will the new table be informative enough to help the teams interpret their graphs?

**Comment by lzim** [comment]
Thanks @saveth we’ll take a look today!

**Comment by saveth** [comment]
@lzim can you download and open the xls file that @staceypark uploaded to GitHub? I'm having issues with it. :(

**Comment by lzim** [comment]
@saveth let me see...

**Comment by lzim** [comment]
Unfortunately, no I can't. 😿 

Let's ask @staceypark about it in the AM, she may help us solve it.

Happy Friday 😎

**Comment by saveth** [comment]
@lzim @staceypark @ericasimon 
Glad we've decided that all sim experiments will be downloaded into separate files. This allowed me to create code that loops through all the files and can be run with as many experiment files as the team choose to download.

I've now created tt reports for all 5 models, and the same file can be run for tt2 and tt3. Created pull request for these files in #276. 

@staceypark I look forward to walking you through the code tomorrow so you can troubleshoot while I'm out. :)

**Comment by saveth** [comment]
Thanks @jamesmrollins and @staceypark on figuring out the sim export file format this afternoon and getting me all the necessary files to finish my code. 👍

**Comment by lzim** [comment]
Genius @saveth!

Indeed thanks to @staceypark and @jamesrollins too

**Comment by staceypark** [comment]
@saveth for the tt reports, each report will have all data up to that report (as outlined below) instead of being three separate reports, so I'll be updating the code to reflect that. 

**tt1: MTL menu results and Team Data table**
- @saveth I'm having issues getting both my plots and your data table to render at the same time in tt1? Not sure why, but one makes the other disappear. I'll work on it a bit more and shoot you a pull request if I can't get it.
- @holbrooa I keep getting permissions errors for pulling fresh data/model params in the SharePoint. Can you figure that out?

**tt2: tt1 + bc and exp1**

**tt3: tt1 + tt2 + exp2, exp3, and pcharts**
- @holbrooa For the pcharts, we are set for the current teams (I'm using the teamsprepostMayEBPsy.xlsx file) but moving forward at scale, how do I pull the data that will go into the pcharts? Also, the SharePoint splash pages currently only work in VAPAHCS. When can we expect an update for Splash pages across all of the healthcare systems?

@lzim To send out tt reports for all of the teams, the worlds/experiments need to be rebuilt so I can export files and pull it into the code. Circling back on the world building, I need help from either you or another co-facilitator to do that.

**Comment by saveth** [comment]
@staceypark Assuming the only outstanding issues are:

* export of file in .xlsx file format instead of .csv or .xls, which you're working with @jamesmrollins 
* data export for the pchart, which you're waiting for @holbrooa 
* compiling tt3 to include all previous report files, which I addressed in pull request #296 

Please let me know if there are any other issues on this matter that I've missed. Thanks. :)

**Comment by saveth** [comment]
@lzim @staceypark 

@holbrooa the tt report now includes the p-chart, and as we scale up and produce tt reports for more locations, we need to be able to have the data beyond the two sites currently in the study. To this end, for *sheet 1* in the file **teamsprepostMayEBPsy.xlsx** can you replace the name under team column with their institution code?

**Comment by lzim** [comment]
@holbrooa @saveth and @staceypark

@holbrooa: This sta6a code should match the standardization code that produces the team data table from the data UI, which...
@staceypark: ...is the same as the standardized name of the team world on the sim UI login page.

Thanks!

**Comment by lzim** [comment]
@holbrooa @saveth and @staceypark

I know we are still iterating on the tt reports in some ways, with the addition of code for the Sankey in the Psy tt reports a recent example. I think this larger issue is ready to be closed, so I will close it 😄
