### ISSUE TITLE
Sim UI user name and password reset issue - david.lounsbury@va.gov

### ISSUE THREAD

**Issue by dlounsbu** [lzim/teampsd#2451]
To date, I have been using david.lounsbury@einstein.yu.edu as my user name to log into the Sim UI.

Now I think I should use david.lounsbury@va.gov, but I do not have a Sim UI password set up. I tried to use the reset password feature, but I do not receive instructions via e-mail. 

DL

**Comment by jamesmrollins** [comment]
Hi @dlounsbu  - I sent you a password reset, **please confirm that you received it.**  You did follow the correct process to reset your password, I don't know why it didn't sent out a link.  I will investigate.  Thank you, James.

**Comment by dlounsbu** [comment]
Thanks James. 

I am on line now. I can't seem to find the reset e-mail.  Is there a temp password I can/should use?

DL

**Comment by dlounsbu** [comment]
> Thanks James.
> 
> I am on line now. I can't seem to find the reset e-mail. Is there a temp password I can/should use?
> 
> DL

Sorry for my delayed reply, too!

**Comment by dlounsbu** [comment]
> 

I am looking for the reset e-mail in my VA e-mail Outlook account. david.lounsbury@va.gov

**Comment by jamesmrollins** [comment]
Hi @dlounsbu - I went ahead and reset your password and sent it to your einstein and va accounts.  Let me know if you have further issues.

**Comment by dlounsbu** [comment]
Thanks @jamesmrollins !! 

That worked. Should I try to reset my password, or just keep the one you gave me?!

Best,
DL

**Comment by jamesmrollins** [comment]
Hi @dlounsbu - That is up to you.  Although I do think it is a pretty cool password lol. 

I tried to replicate the problem you had clicking the "reset password" link on the login dialogue.  It worked for me.  The only thing I think could be the problem is perhaps the auto-email got intercepted by your junk email system.  Could you check those folders on your account and see if you can find them there?  Thank you.
