### ISSUE TITLE
ANDON: Inconsistent data transfer between Data UI and Sim UI

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#2469]
we see a discrepancy in the DUI weekly new pt rate (39 pts/wk) and the DUI data pt rate (16.5 pts/wk).

![image](https://s3.amazonaws.com/epicenter-asset/production/va/va-psd-test/1642635059735364939_img0.PNG) <br/>

**Comment by jamesmrollins** [comment]
FYI @lzim @lijenn @mnallajerla 

Hi @jeffhoerle - Below is a synopsis of this bug. Please note that an ANDON alert indicates this issue is top priority for resolution over any other Power BI priorities. We are targeting a Friday 1/21, 0800 EST for resolution, as that is when the end user will be in session 5.  I am available at 0700 PST if you need me to collaborate or check something out with you.  I have attached an anonymous copy of the data file with the unnecessary data highlighted for your convenience. 

[CV_ModelParameters.xlsx](https://github.com/lzim/teampsd/files/7901946/CV_ModelParameters.xlsx)

## Findings

- The data cells that we deleted to remove unnecessary data calls from the export, have reappeared and thrown off the correct mapping.  See image 1 below.
- The mapping to between the export file and the Sim UI is correct. The BZ2 and BU2 callouts indicate the cell locations the "Get Direct Constants" are using to fill in these values in the table. They are verified against the reference ModelParameters.xlsx file. See image 2 below.
- The Team Data upload function appears to be working correctly.  @lzim I cannot explain why the legacy data was displayed in the instance as per the screen capture above.  Moreover, I went into the instance myself and found that it is indeed displaying the correct information.  See image 3 below.

### Image 1 - Obsolete data still being exported.

![image](https://user-images.githubusercontent.com/30132017/150262554-492221ff-f0a2-40f7-a4a6-542f9c7c978b.png)

### Image 2 - Mapping Correct

![image](https://user-images.githubusercontent.com/30132017/150262090-5616facb-2bae-4260-bf04-ac0804019005.png)

![image](https://user-images.githubusercontent.com/30132017/150262147-51f729da-7e4a-4e2e-9551-663e0ffd3bfd.png)

### Image 3 - Data in Team Data table consistent with data file.

![image](https://user-images.githubusercontent.com/30132017/150262324-841fa7db-d2f4-4fc2-8587-bc27c4f87cc3.png)

**Comment by lzim** [comment]
@jamesmrollins 

We discussed this **ANDON at the quant_operations workgroup today at 11AM**.

@jeffhoerle plans have this fixed by ~2PM Pacific, esp. VISN 22.

We still need to pull our Friday 8:30AM data again once the bug is fixed and make sure it works in the Sim UI.

FYI: @lijenn @mnallajerla

**Comment by jamesmrollins** [comment]
@lzim @jeffhoerle @lijenn @mnallajerla - I checked the updated export file against the reference Team Data xlsx file and it lines up perfectly!  Thanks for knocking this out Jeff.
