### ISSUE TITLE
SIM UI TEST - See Sim UI Teams Channel Delete & Upload issues

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#2511]
@jamesmrollins  Delete/upload not working consistently from home screen or from Team Data Setup in Sim UI TEST. Using Chrome and VA GFE.

@lijenn and I both tried to upload our Team (SP) Flow data file in Sim UI TEST (in shared and individual worlds)>
1. The dialogue was inconsistent for me. I clicked on the Delete icon in either user interface, but nothing happened in either the Home Screen Data Menu Maintenance or in the Team Set up Menus.

2. I would use the dialogue, like you see in the first screenshot below, it would work on it, but then the file would not appear. 
_NOTE:_ Using my facilitator login, I uploaded a file earlier today without issue. 

![image](https://user-images.githubusercontent.com/7454688/155637557-bc0d9bf2-34ee-4a0c-a3f9-4e16fcd822a2.png)

Jenn was able to ultimately get the delete and upload working using an ADMIN log in.
I took an Inspector Console Screenshot, but Jenn has the same errors and did not have trouble with the Delete/Add.

![image](https://user-images.githubusercontent.com/7454688/155637036-8838a351-fa89-4e44-9080-7a484e25f987.png)

**Comment by jamesmrollins** [comment]
Hi @lzim - 

IF:  the upload bar indicates the file upload is complete . . . 

Sometimes when the API moves the file from your client to the Epicenter service, it does not return a filename update on your list.  That is why we have a "Refresh" button.  If the name doesn't appear after the upload bar indicates the operation is complete, try clicking the refresh.  That causes the client to ask the server again for a file list update.  We cannot automate the file list update, because it is a server-side operation that we cannot access.

There is no difference between the Admin and Facilitator login in the eyes of Epicenter.  We just hide the Admin pages from the facilitator logins.  So that shouldn't affect how far she gets with uploading files. 

Those errors on the console are not important - they always appear.

**Comment by lzim** [comment]
**Discussed at 8AM Workgroup Leads 02/28/2022**

@jamesmrollins  

Reported that the next step of troubleshooting would be to **check whether the data file is updated in the Model File in Epicenter,** because the refresh icon in **mtl.how/sim_test.**

_Next Steps:_
1. @mnallajerla @lijenn will **document in a) Data Sheet Sheet [LEARNER], b) Facilitator 1-pager [FACILITATOR].**
2. @jamesmrollins **will look into these refreshes with Forio,** current hypothesis is may require server side error checking.

**Comment by jamesmrollins** [comment]
@hirenp-waferwire lets discuss in 2/28 meeting. I want to fully understand how the API updates the file list and explore ways to handle these errors.

**Comment by jamesmrollins** [comment]
Hi @lzim @lijenn @mnallajerla - Learned much about this API tonight.  See below for the step-by-step.

## Conditions

When a team data file is uploaded, it not only must populate the Epicenter Model folder, it must also update the Sim UI repository to support CI/CD.  

## Update Steps

1.  User identifies file for upload.
2. GitHub API grabs the file and moves it to upload in the Sim UI Repo. 
3.  The status bar begins execution.  It builds based on a 20 second cycle, which is the average time it takes for the system to upload the file.
4. When the file lands in the repo, an action fires that pushes the file to Epicenter.
5.  At the end of 20 seconds, the update status bar finishes its execution and asks for an Epicenter file listing.  In effect, it is pressing the "Refresh" button.
6. IF the file is present in Epicenter, it will list in the dialogue.  IF NOT then it will not list and the user must press refresh to ask again.

## Analysis

- The upload routine is dependent on GitHub traffic and availability of an Ubuntu Docker.  While these actions usually take 20 seconds, there can be action delays.
- The problem is not an error.  The file upload routine sometimes takes more time based on resource availability. 
- The "Refresh" button and status bar are **inelegant** solutions - the status bar is misleading.

## Changes

- We are going to automatically press the refresh button on a 5 second cycle and keep the status bar active until we get an answer.
- When the file finally lands in Epicenter, the file will automatically list and end the status bar routine.

**Comment by lzim** [comment]
Thanks @jamesmrollins  This is great!

**Comment by jamesmrollins** [comment]
Hi - @lzim 

- We will use a "loader" (three bar, repeating like a Mustang taillight) instead of a loading progress bar, since the bar is an estimate and misleading.
- We expect this improved call function will work to fix the problem and we don't need the Refresh button and will remove it.
- If the file doesn't go through and we can't complete the list call, then we will throw an error message that says, "File load error - Please try again."
