### ISSUE TITLE
2023_wk2_jun_#story I: 3.0 Workflow Inventory MTL and Team PSD Manual new team member's POV + Facilitator Self-Service

### ISSUE THREAD

**Issue by lijenn** [lzim/teampsd#2617]
[**Reference Lucid #2617_teampsd_draft_manual link**](https://lucid.app/lucidchart/0cd93668-a02d-4176-b97d-4f342985a57f/edit?beaconFlowId=36EBEB95598BCA96&page=0_0&invitationId=inv_89386cd8-aa97-4ee2-9c18-371e4a2b7781#)

DECISION: Discuss with @jamesmrollins  at 8AM Workgroup Leads 4/25/22
@mnallajerla could also help with this task for QA'ing with her perspective as the newest member on the team 

1. Use Case: Missing text in SAY guide in the Master branch identified by @swapmush 
Decision: How to use QA Branch needs to be in both Manuals.

1. Use Case: References to Epicenter and lack of POC made it difficult for @swapmush to understand how to set up a new team in the Sim UI Facilitator Dashboard
Decision: Comb through the MTL Manual for references to outdated platforms or clarify how those platforms are still used in the right context and who "owns" that process (e.g. James will add new members to Epicenter to the right groups and to the correct instances).

**Comment by lzim** [comment]
**Discussed at 04/25/22 8AM Workgroup:**

Facilitator Self-service in the Manual Another important priority is to ensure a shift from Admin to Facilitator for any task the facilitator can now do squarely from the Sim UI.

**Pick up at 04/28/22 train_workgroup** meeting.

**Comment by jamesmrollins** [comment]
Hi @lzim @lijenn @mnallajerla below are some observations from looking over the documentation for Team PSD and MTL


## 1. There are sections in the MTL Manual that are not germane to a facilitator.

![image](https://user-images.githubusercontent.com/30132017/165396036-4532b3b5-841d-43ac-9071-fb7953dcbc4d.png)

## 2.  There are links to graphics that do not work in the MTL Manual.

![image](https://user-images.githubusercontent.com/30132017/165396251-73f9abf4-e166-46d2-aec7-62f5fde39678.png)

## 3. There are multiple legacy feature branches in both the lzim/mtl and lzim/teampsd repositories. 

This adds to visual clutter.  These exist, I believe, because of errors in the graphics links (see third image), where the document author linked to an image in the feature-branch, instead of the main or gh-pages branch.

_lzim/mtl_

![image](https://user-images.githubusercontent.com/30132017/165396673-9603d5a1-c0cf-47a4-9578-abba5de72eb0.png)

_lzim/teampsd_

![image](https://user-images.githubusercontent.com/30132017/165396721-65247b18-806d-4ada-802b-b66ba99ec760.png)

_Incorrect links_

![image](https://user-images.githubusercontent.com/30132017/165397359-9cb6909a-cb41-42c7-a6d7-be61efc3ac20.png)

![image](https://user-images.githubusercontent.com/30132017/165397693-1ee4072d-a4f6-4998-abfa-78b02c2ee373.png)

## 4. Team PSD Manual needs reorganizing and editing so updating a markdown file incorporates the view of the facilitator.

There are also multiple graphics formats, instructional formats and images that need to be standardized.  Some images cannot be read, or are very complicated to follow.

![image](https://user-images.githubusercontent.com/30132017/165398591-0f696fef-fe7f-4e09-a939-401baed0b9b1.png)

**Comment by jamesmrollins** [comment]
FYI @lzim @mnallajerla @lijenn 

# From the training_workflow meeting 4/28

Need to reorient the mtl 3.0 Manual and the Team PSD to better incorporate the Point of View (POV) of their respective target audiences.  Namely, the mtl 3.0 Manual will primarily support Facilitators and Team PSD will support Admins. This scope of work also expands to the repository readme.md files that contain many orientation information pieces.  May need to explore how readme.md files and manuals will work together.

Below is feedback for the example task:  "Update a see or say guide"

Debbie - "I used to be able to do the task.  I can't now because the way I used to do it, doesn't work with the new processes."
Swap - "There is a disassociation between theory and content in the manuals - it is very hard to find all the steps necessary to do a task in one spot."
New User - "It is safe to assume that documentation would be sufficient to learn a task for the first time."
Team PSD 3.0 User - " The manual needs to be written in the desired future state."

##  As a new employee, I need orientation to enterprise support platforms, repositories and documentation structures.

### Enterprise Support Platforms

**Operations (Primarily)**
- GitHub
- ZenHub
- PowerBI
- SimUI
- Lucid
- Forio
- Dynamics
- VA Teams

**Research**
- RedCap
- IRB
- DART
- RDIS
- Dashboard for PCPSD
- OSF

**Documents**
- see guides
- say guides
- cheatsheets
- mtl 3.0 manual
- Team PSD manual

**Repositories** (a complete list provided with exact names to be verified)
- lzim/mtl
- lzim/teampsd
- lzim/research
- jamesmrollins/sim_ui
- jamesmrollins/demo
- jamesmrollins/teampsd

## As a facilitator, I need instructions on how to:

- Edit a see guide
- Edit a say guide
- Edit a cheatsheet
- Edit a manual
- Edit a biography on the Team PSD website (this may result in moving the TeamPSD edit page from the Admin login to the Facilitator login). 

## As a facilitator or an employee, I need clearer means to navigate instructional manuals.

- Organize by use case (more brainstorming needed).
- Clean up legacy workarounds with respect to the use of links and images reference.
- Provide cross-referencing and links throughout the guides to expand content available from third parties (such as providing markdown information from markdownguide.org).
- Provide cross-referencing links with respect to inter-repository resources such as readme.md files.


## James will by COB Friday, 4/28 for discussion on Monday:

- Using the information above provide a draft outline of chapters for both guides.
- Expand as necessary as this effort progresses.

**Comment by jamesmrollins** [comment]
# Team PSD 3.0 Outline

Table of Contents

Topic Index

Purpose of the manual

Organization of the manual

Team PSD values
- Guiding principles
- Scientific principles
- Policy
- Quality Assurance

Team PSD, _Modeling to Learn_, and research grant overview
- R21
- R01
- IRR
- Key partners

Get access to tools and resources
- Get a PIV card
- Talent Management System - information assurance and privacy training
- Microsoft Outlook Account
- VA Citrix Portal
- Microsoft Teams
- GitHub/ZenHub
- Shared drives
- Microsoft CRM
- Lucid Charts
- Forio Epicenter
- OSF
- RedHat
- Power BI
- DART
- RDIS
- PSPST

Introduce yourself - complete a biographical sketch on Team PSD website

Workstreams, workflows and team organization

Use Microsoft Teams to communicate with others

Coordinate work using stories, epics and sprints

Plan and monitor projects with Lucid Charts, GitHub and ZenHub

Maintain version control and store work in GitHub Repositories

Graphically express ideas with Lucid Charts

Manage new clinic subscribers with Microsoft CRM

Set up a new Facilitator or Sim UI Administrator in Forio Epicenter

Set up a new Facilitator in Microsoft Power BI

Use Open Science Framework

Author or edit markdown documents

Use the Sim UI Administrative Dashboard to maintain websites

Glossary of Terms

Acronyms

**Comment by jamesmrollins** [comment]
# _Modeling to Learn_ 3.0 Manual

Table of Contents

Topic Index

Purpose of the manual

Organization of the manual

Introduction to _Modeling to Learn_

Get access to tools and resources

- Sim UI Login
- Data UI Login
- GitHub/Zenhub login

_Modeling to Learn_ resources and references

- Facilitator checklists
- Learner see guides
- Facilitator say guides
- Cheatsheets

Prepare for a session

- Red
- Blue

Use the Sim UI Facilitator Dashboard to facilitate a session

- Orient to the Dashboard
- Introduce yourself - complete a biographical sketch on Team PSD website
- Set up a team
- Check team statistics
- Review tt Menu results
- Set up and publish a tt report
- Load team data
- Use "Team" to manage team discussions
- Strategies for side-by-side comparisons on your computer screen

Glossary

Acronyms

**Comment by lzim** [comment]
**Reviewed the Workflow Inventory at Story I Train on Thurs 05/05/2022**

- [x] Inventory and priorities complete.
- [ ] Rescope @lijenn effort across stories
- [ ] @jamesmrollins will develope the .yml build and .rmd files following the final editing of the **Team PSD 3.0 Manual** chapters on the [LucidChart Inventory](https://lucid.app/lucidchart/0cd93668-a02d-4176-b97d-4f342985a57f/edit?invitationId=inv_89386cd8-aa97-4ee2-9c18-371e4a2b7781&page=0_0#)

#adjudicate_memo by @lzim & @lijenn 
When this is done, we'll close the card for wk1 may_epic.
**Jenn 10 points**
**Lindsey 10 points**
**James 10 points**
Double-check @jamesmrollins points to total points at 8AM Workgroup Leads on Monday 05/10
Removed @mnallajerla effort from this card as she created a separate issue task card #2647

**Comment by lijenn** [comment]
Discussed 8am WG Leads 5/9:
wk2 may_epic: @lijenn will create a card to track "Add all on content" from user_story

**Comment by jamesmrollins** [comment]
Hi @ljmoody - Review this card to get an idea of how we reorganized the _MTL_ and TeamPSD Manuals.  This will be the card we use to track the updates to the TeamPSD manual that needs to be completed.

**Comment by ljmoody** [comment]
Closing this card and replacing with new card #2999 to track updating the Team PSD Manual.
