### ISSUE TITLE
ASAP ANDON: Provider unable to log into MTL Menu 

### ISSUE THREAD

**Issue by swapmush** [lzim/teampsd#2708]
1. Provider unable to "set password" when logging in to mtl.how/menu. Provider received "Email is not valid" when logging in with (1) correct VA email (2) password during first log in attempt. Provider tried to log in by (1) Va email and (2) selecting "log in", same error message. 

1. Discovered 135pm PST on 8.3.22 by provider who contacted Swap via Teams.  

![image](https://user-images.githubusercontent.com/23065779/182710111-6506624c-f664-42c8-8bdc-a779f464de0a.png)

**Comment by jamesmrollins** [comment]
@swapmush can you email me their email address so I can evaluate in SmartLook?

**Comment by jamesmrollins** [comment]
Hi @hirenp-waferwire - The password registration process appears to be not working properly.  I have put a query into David Berkman to ensure there are no issues on the Forio end.

![image](https://user-images.githubusercontent.com/30132017/182722454-9bebbbcf-f5b8-4651-a831-30881f1792b2.png)

**Comment by jamesmrollins** [comment]
**Approval Required**: @lzim 

Hi @swapmush - I wanted to report out on this issue.  I will open a new bug for the issue we found this morning.  

1.  This is not a bug - a team must be set up prior to an user's attempt to set up their password.  The reason is because there must be an end user account with which to associate the password.
2. When the user attempted to login and "Set Password" the system didn't find the email and returned an "Email is invalid" message.

## Suggested Fixes

1.  We add a checklist item to the [Partner Fidelity Checklist](https://github.com/lzim/mtl/blob/master/blue/session02/s02_facilitator/partner_fidelity.md) under Session 2 to say:

- [ ] Set team up in Sim UI (necessary to support mtl.how/menu end user participation)

2.  Inform Facilitators of this need at the next Facilitator Workflow meeting.

## Note

- @jamesmrollins will provide the update to the checklist when approved.

**Comment by lijenn** [comment]
Just want to note that I already have a task for Facilitators in S2 to prep the Sim UI and Menu logins in the CRM.
![image](https://user-images.githubusercontent.com/59668647/183222802-dd33dba3-f56b-43d3-9fe2-3e0bb98ebb86.png)

Not sure if adding that as a step in the partner_fidelity guide is the best place to put it since that guide mainly focuses on fidelity and the theory of change vs technical tasks?

**Comment by lzim** [comment]
@jamesmrollins @swapmush @lijenn 
Can this be closed with story points for the effort?
