### ISSUE TITLE
What are wearing under the MTL Jackets?

### ISSUE THREAD

**Issue by dlkibbe** [lzim/teampsd#273]
@lzim @staceypark @TomRust @branscombj @dlounsbu 

Is there any instructions on what you want us to wear under the MTL jackets?
Avoid white shirts?
Black or Blue T-shirts?
Thanks for guidance.

**Comment by TomRust** [comment]
I thought we were doing black shirts...but that the thing that mattered most was not that each of us look the same, but that individually we can look the same across each day of shooting.

**Comment by lzim** [comment]
@dlkibbe I appreciate the attention to detail! I was showing someone our open science workflow and we had a good chuckle about this issue :rofl: 

@TomRust is right. The main goal is that you look the same every day so that things can be edited as needed in post and maintain continuity for the viewer.

I plan to wear navy or black t-shirts (so I won't be too warm) and I plan to zip up my hoodie so that they don't actually show.

Thanks again!

FYI: @dlounsbu @branscombj
