### ISSUE TITLE
wk4 sept_epic: Generate and send out tt reports for MTL blue sites post s4

### ISSUE THREAD

**Issue by emilymetcalf114** [lzim/teampsd#2740]
wk3 sept_epic team_temp
@emilymetcalf114 & @lzim 
realized we needed to determine if tt reports were sent out to current active _MTL_ Blue teams after s4. 

Emily reviewed MTL Help inbox and sent emails, did not see any emails with tt reports sent out during this time frame. 

@lijenn, do you know if tt reports were generated and sent out for these 2 sessions?

- [ ] 8/16
- [x] 8/18

**Comment by lijenn** [comment]
@emilymetcalf114 I definitely don't recall sending those reports. 

Please check if the reports were ever mentioned in:
- [ ] the Facilitator's prep chat (i.e when Facilitators discuss who is sending the pre/post emails)
- [ ] and if the tt reports exist in Team PSD Shared Drive > Clinics folder by team (please save tt reports and data ui files here as a back-up)

If not, then it's safe to assume the reports did not get sent.

Here's how to [generate (Sim UI Dashboard) and download/view (mtl.how/menu) the Blue reports from _MTL_ Manual](https://lzim.github.io/mtl/7-facilitator-technical-manual.html#set-up-a-blue-tt-report).

Tips: 
- You may need to review the Facilitator prep chat and live meeting chat to know which 'experiments' and 'report' displays to include in the report
   - You can/should confirm the working conceptualization of the team (priorities and needs) with the Facilitators
   - Ideal if Facilitators generated the reports and sent the reports during the pre/post emails (they know the team's needs the best)
- You need to have access to the Sim UI worlds for these 2 _MTL_ Blue teams, otherwise you cannot download the reports on _MTL_ Menu

**Comment by emilymetcalf114** [comment]
It looks like @MattMoore2 generated the tt report for 8/16 and it is in the prep channel, but I can't open or download it (says I don't have access - even though I have access the historical chat, and I have access to the sim ui worlds for both of these teams). They didn't explicitly assign someone to send out the post-session email though so no confirmation it got sent out. I will check on this!

**Comment by emilymetcalf114** [comment]
Update 9/26/22: 
@emilymetcalf114 generated tt report #1 for post-8/18 session and saved in Clinics folder. 
Ready to discuss with @lzim about sending out to the team.

**Comment by emilymetcalf114** [comment]
#adjudicate_memo
should have been closed in Sept.
