### ISSUE TITLE
wk4 sept_epic Bug: Sim UI Shared World Team (AGG) Care Results Dashboard Compare Services Missing PSY & EBPsy Lines Not Rendering

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#2748]
@jamesmrollins I'm still testing Team (AGG) Care for Thursday's _MTL 3.0 Blue_ Live Session 7:

I'm reviewing the Tables in Compare Services against the Graphs:

![image](https://user-images.githubusercontent.com/7454688/193327228-f4eb75d3-5d62-4cbc-9bfb-37e4feaa3d5e.png)

**I'm not seeing PSY or EBPsy in the Graphs**

![image](https://user-images.githubusercontent.com/7454688/193327418-f5952a12-1e81-472e-a01e-2dbbb24e8758.png)

_Any chance this could be fixed before Thursday's team meeting?_

**Comment by jamesmrollins** [comment]
Hi @hirenp-waferwire.  Take a look at the above.  For some reason, the Psy and EBPsy lines are not showing, when there are values represented in the table view.  I was able to replicate this problem.  Please investigate right away and let me know what you think might be happening.  Thanks ~ James.

**Comment by jamesmrollins** [comment]
Hi @lzim and @emilymetcalf114.  I believe we have resolved the issue (see below). The reason a line for Psy doesn't show in the delay to starting a service graph is because it is stacked underneath EBPsy (we haven't developed a decent alternative for stacked lines yet).  Please let me know if you spot something else we need to look at. ~James

<img width="866" alt="image" src="https://user-images.githubusercontent.com/30132017/193615334-a8c5157b-409c-4c78-b6ec-59a01aee4489.png">
