### ISSUE TITLE
wk2 oct_epic Bug: _team world in sim ui not loading 

### ISSUE THREAD

**Issue by emilymetcalf114** [lzim/teampsd#2755]
**During training_workflow 10/13** 
@emilymetcalf114 , @lijenn , and @epearman 

Both Emily (Chrome) and Jenn (Chrome and Edge) tried to enter the sim_ui for _MTL_ blue team (meeting time on Thursdays at 11am) **_team world**, and got grey loading screen that never finished loading. 

Emily tried clearing cache/cookies and logging back in and tried again, same issue. 

Emily tried earlier in the morning ~7:30 am and again ~10:45am with Jenn during training_workflow. 

the _shared world loaded, and so did the _team worlds for our other two current live session teams. 

![image](https://user-images.githubusercontent.com/111393225/195672963-33ae346f-e8ea-4e89-ac1c-f530e3f98624.png)

1. When was the bug discovered? 10/13, ~7:30am, again 10:30 - 11am
2. Is this an invidivual or shared world? _team world

**Comment by jamesmrollins** [comment]
@emilymetcalf114 Did anyone hit control-F5? It's a cache problem.

**Comment by emilymetcalf114** [comment]
@jamesmrollins 

Jenn and I both tried just now, still didn't load. and I cleared all my cache as well. 

![image](https://user-images.githubusercontent.com/111393225/195679137-ba75fc76-a20a-4009-9d59-eb0be8f67fb7.png)

**Comment by jamesmrollins** [comment]
@emilymetcalf114 When I get to the airport, I will look into it and see if I suffer the same fate.

**Comment by jamesmrollins** [comment]
@emilymetcalf114 can you click the drop down in the error messages and capture those please?

**Comment by jamesmrollins** [comment]
Hi @emilymetcalf114 - Ok - not working for me either.  Not sure if this is the Sim UI or at the server level, I will investigate forthwith and get back to you.

@hirenp-waferwire Please see below.  I will also inform David B at Forio.

<img width="946" alt="image" src="https://user-images.githubusercontent.com/30132017/195694566-25ad5923-0977-4625-9386-5f69635f1535.png">
<img width="380" alt="image" src="https://user-images.githubusercontent.com/30132017/195694632-96fa75e6-b29d-47d5-8361-c03dd8fcf31f.png">
<img width="448" alt="image" src="https://user-images.githubusercontent.com/30132017/195694840-5bc1ceac-a967-46e7-8046-ca4430628ef4.png">

**Comment by emilymetcalf114** [comment]
@jamesmrollins 
looks like you got the same errors pulled down but here are my screen shots too: 
FYI this team is fully prepped and will meet again in a week on 10/20. 
Thanks!!
![image](https://user-images.githubusercontent.com/111393225/195695109-6e3cc2e7-8d09-4a81-8f4a-bdf170ed7e69.png)
![image](https://user-images.githubusercontent.com/111393225/195695198-2fc6aa1f-4c78-4ca8-8113-af8b8a640f6f.png)

**Comment by jamesmrollins** [comment]
We'll have it fixed by then.

**Comment by jamesmrollins** [comment]
Hi @emilymetcalf114 - The Sim UI appears to be working now.
FYI @hirenp-waferwire 

## Findings

- [ ] I went the Fac DB and selected the team indicated above. I then selected **Current Session** to see what was up.
- [ ] I detected the same thing as @emilymetcalf114 and @lijenn and was able to pull the same errors.
- [ ] I double checked the team data file, because the step error looked similar to the error that we were seeing with corrupt files.  The TD file was ok.
- [ ] I navigated back to the Home page and the Sim UI threw an error with an old TD filename, "Error filename XXXX_XXXX not found."
- [ ] I then started a new session using the team data file provided in the drop down.
- [ ] The sim UI fired right up (see screen shot below).
- [ ] I ran the sim out 2 years - no problems.

## Hypothesis

The session for this TD file was a legacy session using a corrupt TD file. The good TD file now showing for this team was corrected in the Fac DB screen.  Thus, the session was never reset with the good TD file, and the corrupt TD file (XXXX_XXX) was deleted.  

## Please Confirm

- [ ] @lijenn and @emilymetcalf114 chose the "Current Session" to navigate from the DB to the session, _vice going through the Home page and selecting the new session._

## Meanwhile, back at the ranch

- [ ] @jamesmrollins will check the server side logs (Forio must do this) to see if we tried to run a bad TD file.

![image](https://user-images.githubusercontent.com/30132017/195739878-c7f5253f-14fc-4bd0-93a1-b5dccfde3dd4.png)

**Comment by jamesmrollins** [comment]
@emilymetcalf114  here is the server log verifying the "lost file" error:

<img width="454" alt="image" src="https://user-images.githubusercontent.com/30132017/196215855-34d9172c-16ca-4373-b8c9-cc8abef3983a.png">
