### ISSUE TITLE
Story B: Backup information from Teams to Team PSD folder to address delays in facilitate_workflow channel 

### ISSUE THREAD

**Issue by emilymetcalf114** [lzim/teampsd#2778]
During **facilitate_workflow**, there are significant delays (takes 10+ seconds to unmute after pressing the unmute button, chats being sent, etc.) 

This could be a memory/storage capacity issue within sharepoint. 

One possible option/solution
- [ ] delete old videos from **facilitate_workflow**
- [ ] keep transcripts 

FYI @lzim @epearman

**Comment by emilymetcalf114** [comment]
FYI @lzim and @epearman 
It looks like if you delete a video file from teams/sharepoint, the corresponding transcript is deleted with it. 
I found this by reviewing these [Microsoft support docs](https://support.microsoft.com/en-us/office/view-edit-and-manage-video-transcripts-and-captions-3cb9acb6-05b2-4f59-a50d-7df61123aa20)

**Comment by emilymetcalf114** [comment]
Discussed briefly at **HQ_workflow 11/17** with @lzim and @epearman 
Next steps: 
- [ ] Go into our sharepoint and back up our videos and transcripts to our Team PSD VA Network folder

**Comment by epearman** [comment]
Discussed briefly asynchronously on 11/29. Old transcripts can be downloaded but will take quite a while.

Update on facilitate_workflow backup: I was able to find the transcripts, however, I can only see the most recent 10 transcripts in one convenient place to quickly download. Perhaps Jenn or you can see more transcripts then I can see (see directions below). Otherwise, I can still download older transcripts, however, I have to find them directly in the teams channel chat. Downloading transcripts this way will take a while (est. 3~5 hours manual work depending on Teams lag. There are 41 transcripts to manually find in the chat).

NOTE: The oldest facilitate meeting recording is from Aug 10, 2021 (does that sound right?).

To see the transcripts I did the following:

Navigate to the MTl Facilitate Workgroup meeting and click "View meeting details"


 Click transcripts and download

**Comment by emilymetcalf114** [comment]
Update:
@epearman and @emilymetcalf114 
created a new Teams Mtg link in the facilitate_workflow channel on 12/6/2022. 
We tested the functionality for: 

- [ ] mute/unmute
- [ ] recordings and transcripts
- [ ] chat (how long it takes to send messages) 
- [ ] screen sharing
- [ ] video on 

Starting with a fresh meeting link seemed to solve all delays and glitches when tested with 2 people. New meeting links have been created for both facilitate_workflow and 8am_workflow (where glitches were also starting to occur). 

We will use these new links starting in wk2 dec_epic. 

This leads me to believe that our glitches may not be related to storage, and we may not need to delete old videos/transcripts. 
**_Do you agree, @lzim and @epearman ?_**

**Comment by epearman** [comment]
The delay issues in facilitate_workflow have been resolved by creating a new meeting for facilitate_workflow within the channel.

@emilymetcalf114 @lzim can we go ahead and close this issue?
