### ISSUE TITLE
Enable team data file transfer within the SIM UI

### ISSUE THREAD

**Issue by epearman** [lzim/teampsd#2786]
Once  team data excel file is added to the SIM UI we want to be able to save it to other worlds within the sim UI without having to have a copy of the file on our local machines.

**Comment by jamesmrollins** [comment]
Hi @epearman @emilymetcalf114 @lzim 

I have some concerns about the requested features we should discuss to avoid potential cake wrecks:

1. When the Team Data (TD) File is uploaded fromt he Data UI, it is in a different format than the one the Sim UI uses - we convert it to the needed format with the upload code execution. Once it is in the Sim UI, the same file cannot be reused since the reformatting function will corrupt the file.
2. When the TD file is uploaded, the user can specify all of the worlds it will be applied to - That appears to be the feature above  IMO.
3. The capability to download a TD file from the Sim UI is NOT currently a feature and is NOT recommended, because I cannot mistake proof the uploading of the "already been reformatted" TD file. This has the potential to confuse the user and cause problems.

**Comment by epearman** [comment]
**Needs:** 

1. Move the data file between worlds within the Sim. 
2. Need to bullet proof the file so that it can be downloaded and uploaded into the Sim (when a new member joins).

**Solution**
- [ ] Create two pathways for uploading
1. The facilitator (Already exist)
2. A team lead can upload (need to create)

- [ ] Need to verify that we can use the world assignment feature after the team data file has been uploaded

**Comment by jamesmrollins** [comment]
@epearman Update below:

## Regarding Needs:
1. Moving data between worlds within the simulation is an easy fix.  Recommend we treat it like a bug and just move it through the breakfix test instance and into production.
2. Moving experiments bi directionally is an easy fix. Recommend we treat it like a bug and just move it through the breakfix test instance and into production.
3. There is already the ability to elevate someone to team lead from the facilitator panel!
4. There is already the ability for a team lead to load a team data file into the sim ui.  

## Observations:
1.  It has been so long since we have interacted with the simulation, I have forgotten many of the features.
2. Next time I will spend far more time exploring existing functionality so I can advise you more accurately!
3. I will introduce two updates to the MTL 3.0 Tech manual that explain how to elevate a team player to a team lead from the facilitator panel and how to assign team data to various team instances.

**Comment by jamesmrollins** [comment]
@hirenp-waferwire We need to accomplish the following:

- [ ] After a Team Data file upload, a facilitator must have the capability to assign the TD file to any team.
- [ ] An experiment file, no matter the instance of origin (i.e., _ind, _team, and _shared) can be seen in all instances associated with the team.

Thank you!
