### ISSUE TITLE
wk1_jan: BUG:  Sim UI not logging in users

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#2828]
## Sim UI is not logging in users

- [ ] Server not loading - returning 500 error.
- [ ] Currently elevated to Forio for disposition and troubleshooting.

![image.png](https://images.zenhubusercontent.com/5e4eac12455ade27f3584cea/53f99b34-b883-4417-8a21-830d9aad7edc)

**Comment by lzim** [comment]
@jamesmrollins 
@emilymetcalf114 
- [x] @lzim accessed the**shared world** of the _MTL Blue_ team meeting we rescheduled from today until 01/19.
- [x] @lzim accessed the **team world** of the  _MTL Blue_ team meeting that occurs on Tuesday AM.
- [x] **#adjudicate_memo for cost aim 3:** @lzim updated the labesl to reflect **facilitate_workflow** **operations & development value streams** **pi** and **urgent** since this created a work stoppage and team meeting rescheduling.

@jamesmrollins 
- Please review the standard definitions and standard scale for assigning story points on the [2023 Roadmap](https://lucid.app/lucidchart/4fb06b59-38f5-4d61-86f0-4620ceb93196/edit?invitationId=inv_0896c54a-74c6-4f6c-b4fd-fbb933b75c1f&page=Pkp8eGQCiW5J#)
- _Is this ready to be closed?_
- Please use **planning poker** to assign story points on our standard scale.

**Comment by jamesmrollins** [comment]
Hi @lzim - thank you for the review:

- [ ] So if I apply the points rubric, it would be DEV = 1pt Check a specific functional requirement + DEV=2pt Test a specific functional requirement + OPS=2pts Coordinate work with operations workflow users = 5 pts.  Did I get that right?
- [ ] Yes, this can be closed.
