### ISSUE TITLE
wk1_jun_#story_f: QA PROD: Deploy version_release action

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#2832]
## Deploy Action and Related Documentation

- [ ]  Merge pull request #2830

**Comment by lzim** [comment]
#adjudicate_memo

@jamesmrollins  _How should this be captured?_
**jan_epic** is closed. 
_Is this work ongoing in feb_epic?_

**Comment by jamesmrollins** [comment]
@ljmoody please review the pull request referenced above #2830 for information regarding documentation changes.  After changes are completed, merge pull request and close this issue.

**Comment by ljmoody** [comment]
@jamesmrollins - I responded to the #2380 pull request comments and Emily P. merged the pull request. I did not edit the source files, I suggested in comments what I thought made sense to change. Same with the associated images. 
Have not closed this issue because I'm unclear about this process and need guidance.
