### ISSUE TITLE
Bug Sim UI Team Care: The saving dialogue is saving an RVI experiment for MM with "ED" which should be for engagement duration

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#2852]
FYI @jamesmrollins  
Let's talk about this at **support_workflow** or **sim_ui_workflow**

In the _MTL Blue_ team that I co-facilitate on Thurs (wrapping up 02/02) 
I see that an experiment adjusting the RVI from 9 weeks to 12 weeks is labeled with "ED."

_Shouldn't that be for engagement duration?_

![image](https://user-images.githubusercontent.com/7454688/214448916-b9ef9898-1bf8-49ed-b7e3-299ad54298e4.png)

Also at **wk4 jan_epic** 
@emilymetcalf114 
@epearman 
@lzim

Noticed that the experiment save order does not reflect the order of the drop down menu of changes made in the save dialogue 
See example of intake below.

![image](https://user-images.githubusercontent.com/7454688/214450417-0a1723e0-17ef-4700-8a03-b6f4a9c7beae.png)

**Comment by jamesmrollins** [comment]
@lzim @epearman @emilymetcalf114 @hirenp-waferwire 

## Problem

When the user saves an experiment, there is an inconsistency between the saved filename string and the actual saved variable and value.  

## Hypothesis

If the user saves the experiment multiple times before the run, the algorithm may not be accurately recording the experiment settings. Thus, when the experiment is run and saved, the saved filename string is incorrect.

## Experiment

1.  Open Medication Management Module.  Change the setting of an experiment variable.  Then save the experiment without running the experiment.

![image](https://user-images.githubusercontent.com/30132017/214970842-71e2f531-16f8-4501-97d5-b98dd4955750.png)

2. Change the experiment setting of original variable and add in another experiment variable setting.  Save the experiment without running the experiment.

![image](https://user-images.githubusercontent.com/30132017/214971342-5388c4a9-755f-4a7b-b9ea-8d2407467791.png)

3. Change experiment settings from original setting on ED panel to base case.  Save the experiment. The "edoud" and the "edo" value calculations show negative values.  Since they are on "BC," they should not be reported in the save name string.

![image](https://user-images.githubusercontent.com/30132017/214972145-64f244e1-daa8-4316-8e89-277a064bd555.png)

4. Run the simulation.  Change the RVI value.  Click save.  The Sim UI, now includes the post-run changes to the experiment variables in the save string. RVI change was not a part of the run.

![image](https://user-images.githubusercontent.com/30132017/214972736-d4ff6e67-90d3-4e08-bfeb-262b242b8bf4.png)

## Conclusions

1.  In the use case above, the user may have made a post run change and then clicked save.  Since the Sim UI does not lock out the experiment sliders post-run, this is a failure mode.
2. In the experimentation, the Sim UI does not appear to be gathering some experiment sliders setting properly (ED), indicating another potential failure mode. 

## Recommendations

1.  Lock the experiment sliders after the run, so they do not get saved improperly.
2. Investigate the ED issue at the code level and determine cause.  
3. Double check all the other sliders in all the modules to ensure they are gathering data correctly for the experiment name string.

## Needed Decision

In which order would we like the variables to appear? Experiment variable order or dropdown order? Both were specified during the design phase. 

![image](https://user-images.githubusercontent.com/30132017/214974114-e99fb9b2-a471-45b9-91dd-100f5e5f34e7.png)

**Comment by lzim** [comment]
@jamesmrollins 
- [x] Makes sense to lock the sliders after a run.
- [x] Great to investigate the ED issue, but definitely don't want any trouble for this team's last session, which is Thurs 02/02. 
- [ ] The inconsistency above in list of variables between the ? icon and the sliders isn't even the one I noticed. But, I see it's what's driving the different order in the save dialogue. 
_Recommendation:_ Check align with the **Team Data Table** and ideally ensure that this order also aligns with the **_MTL 3.0_ Power BI Data UI**

_Does that make sense to you?_

**Comment by jamesmrollins** [comment]
@lzim  

lol.  

## Looks like we have an even split (with "?" list consistent with the Data UI).  

![image](https://user-images.githubusercontent.com/30132017/215132630-2b251bb1-37d0-4856-a1cf-045666ac0321.png)


## Deeper Dive

- [ ] CC, MM, Psy and SP Data UI do not line up very well with the Sim UI.
- [ ] While it would be easier to change the Sim UI for the Team (Agg) Care instance above, achieving this consistency across all the modules would be easier in the Data UI.  
- [ ] Which is authoritative?

**Comment by lzim** [comment]
Add to wk1 feb_epic
support_workflow agenda

@epearman 
@emilymetcalf114 
@jamesmrollins 
@lzim

**Comment by emilymetcalf114** [comment]
@lzim 
@jamesmrollins 
@epearman 
Let's move to **wk1 feb_epic sim_ui_workflow agenda** tomorrow  instead, since Lindsey and I will miss support_workflow. 
Thanks!

**Comment by epearman** [comment]
@lzim 
@emilymetcalf114 

Discussed during **support_workflow** **wk1 feb_epic**

- Multiple places (Experiment Slider, Team Data Table, Experiment Values) will need to be changed in the sim UI to match the order of the variables in the Data UI. 
_______________________________________________________________

- [ ] **_Should James proceed with changing all places in the SIM UI that do not match the order of the variable in the Data UI or should the order of the tabs in the Data UI be changed to match the SIM UI?_**
    - [ ] @epearman needs to look into what would be involved in changing the tabs order in the Data UI

**Comment by lzim** [comment]
@epearman 
@emilymetcalf114 
@jamesmrollins 

_I'm surprised @jamesmrollins is the only one to review UAD bookability??_
