### ISSUE TITLE
wk2 feb_epic: R01 progress update in RDIS DUE FEB 16

### ISSUE THREAD

**Issue by epearman** [lzim/teampsd#2867]
@emilymetcalf114 and @epearman submit R01 progress update in RDIS. 

To complete the report please follow the instructions below: 
1.	Log in to the RDIS website http://www.rdispaloalto.net/Pinsite
2.	Enter your User ID, "ZIM", and password.
3.	Select the above named project from the project list.
4.	On the Project Profile page, view all forms to verify they have been submitted. Hint: If any forms are in highlighted in yellow, they need to be submitted.
5.	Your current employment status is VA Full Time. If your status has changed, please contact Luzille Cowlah at luzille.cowlah@va.gov before proceeding to the next step.
6.	On the Project Profile page, click on the "Project Initial/Annual/Final Report" link. Complete all fields on the page, including those for the Initial Report if it was not previously completed.
7.	Click the "Submit & Lock" button

**Comment by emilymetcalf114** [comment]
@epearman and @emilymetcalf114 worked on the RDIS R01 progress report on Monday 2/13. 

- [ ] @lzim and David L have FCOIs that need to be certified in the system (see email from mtl.info) 
- [ ] Need to confirm personnel listed on the project and scopes of work (note: David L's Scope of work needs to be re-certified by @lzim as well): 
_Is this everyone who needs to be removed, and does anyone need to be added?_
Looking at the progress report we submitted to NIH, it looks like Debbie is not listed in RDIS? 

![image](https://user-images.githubusercontent.com/111393225/218580404-97fcaee4-60ca-4f35-9188-bbb7acc7a026.png)

- [x] Progress and findings since last report sections have been copy/pasted (and edited down to fit the character limit) from the progress report submitted to NIH.

**Comment by lzim** [comment]
_Did you all already notify @dlounsbu that we need his FCOI to submit?_ 

- [ ] @dlounsbu _Will you please quickly log-in to RDIS and submit your FCOI. It's a short and painless one?_ 
Thanks!

**Comment by emilymetcalf114** [comment]
@lzim 
I've been trying, but it's one of several of my emails that refuse to send and has been stuck in my outbox due to my tech issues :(

**Comment by lzim** [comment]
Great work on this report @emilymetcalf114  & @epearman 🚀
