### ISSUE TITLE
2023_jul_epic #story_h: Align OMHSP SME competencies for GS-13 Data Scientist Position

### ISSUE THREAD

**Issue by epearman** [lzim/teampsd#2871]

**Comment by epearman** [comment]
**Data Science Lifecycle:**

**Story K Health Equity:** Need-Establishing new data pipelines and dashboards in alignment with PERC guidance and resources. 
_Who else could help with this? Possibly James' new Hire_
    - [ ] Identifies, adapts, and manages changes to data analysis tools in response to evolving
user needs.
    - [ ] The incumbent requires expertise in and management of end-to-end data processes in
the data life cycle. Mastery experience with data science tools to execute duties is
required;these duties including programming, statistics, machine learning, causal
inference, and data visualization.
    - [ ] Constructs data pipelines using complex tools and techniques to handle data at scale.

**Comment by epearman** [comment]
Identifies, adapts, and manages changes to data analysis tools in response to evolving user needs.
 Expertise in and management of end-to-end data processes in the data life cycle.
 Mastery experience with data science tools to execute duties including programming, statistics, machine learning, causal inference, and data visualization.
 Constructs data pipelines using complex tools and techniques to handle data at scale.
 Ensures that data sources are fit for their intended purpose through assessment of potential bias in data ingestion and transmission mechanisms, current data quality, and improvement of data quality.
 Has experience with prediction and causal inference methods.
 Uses appropriate analytic and statistical software to programmatically prepare data for analysis and clean imperfect data such as probabilistic matching and imputation of missing values.
 Articulates findings through data visualization, reports, and operationalized constructs.
 Demonstrates expert level understanding of diverse data science techniques including data pooling, machine learning, natural language processing, deep learning, advanced visualizations, and has the ability to demonstrate how ensembles of these techniques can be harmonized into user-centric solutions.
 Designs, develops, and operates systems for ingesting, storing, and analyzing data at scale.
 Uses data parallelization techniques or streaming technologies to process data.
 Monitors data flows and stored datasets to make improvements to data collection and ingestion mechanisms.
 Serves as a technical advisor and SME in the development of new methods to automate reports and rapid analysis of pilot initiatives and applications.

**Comment by lzim** [comment]
**Discussed at hq_workflow 02/09/2023**
@epearman 
@lzim 
@emilymetcalf114 

**Current DataOps Pain Points to consider with our GS-13 Data Scientist Position**
- [ ] Priority SQL support for @dkngenda based on @epearman's limited bandwidth.
- [ ] Power BI -> VA/CDW experience is critical; Health Informatics, Computer Scientist
- [ ] @dkngenda _Are there any upcoming R01 or IIR analyses that you think we should recruit expertise to address?_

**Comment by dkngenda** [comment]
@lzim  Below are the main skills I can think of

**Computational skills:** 

- Familiarity with R, particularly data manipulation with tidyverse and visualization with ggplot
- Advanced SQL skills

**Statistics:** 

- Hierarchal Linear Modeling (or Growth curve modeling) given the nature of our study design, 
- Basic understanding or interest in psychometric analyses

**Comment by hthrmarsh** [comment]
**Data Science/Stats/Health Informatics skills identified by @epearman and @dkngenda:**
- C++
- API
- Government Cloud Computing support to automatic Data UI Updates
- Power BI --> VA CDW experience is critical
- Familiarity with R, particularly data manipulation with tidyverse and visualization with ggplot
- Advanced SQL skills
- Hierarchal Linear Modeling (or Growth curve modeling) given the nature of our study design,
- Basic understanding or interest in psychometric analyses

**After reviewing the GS13T14 Data Scientist PD and the DataOps PAVIR PD**, here is what I would pull out for competencies for the Job Analysis 0938A form (we cannot call out specific skills, i.e., C++ for example, in the competency list): 
![image.png](https://images.zenhubusercontent.com/6408f6bee4d68058a5b2cf6b/671de58f-fc1b-4b92-ab88-f2eb63b1406e)
![image.png](https://images.zenhubusercontent.com/6408f6bee4d68058a5b2cf6b/0ecf92e4-30df-4479-8df4-d3f820b2c345)
![image.png](https://images.zenhubusercontent.com/6408f6bee4d68058a5b2cf6b/35a2c122-cfe5-4c00-ad49-9af5c2f02107)
![image.png](https://images.zenhubusercontent.com/6408f6bee4d68058a5b2cf6b/90dd32cf-23c7-49f1-b6dc-c41b15e99475)
![image.png](https://images.zenhubusercontent.com/6408f6bee4d68058a5b2cf6b/4218929b-4df7-40c8-9405-04e3d5d3a423)
![image.png](https://images.zenhubusercontent.com/6408f6bee4d68058a5b2cf6b/549fddfa-55a8-4720-8406-52a69505d101)
![image.png](https://images.zenhubusercontent.com/6408f6bee4d68058a5b2cf6b/e52c331f-1dd7-44d9-bf12-e9b84be216c7)
![image.png](https://images.zenhubusercontent.com/6408f6bee4d68058a5b2cf6b/9474bce4-1418-4d91-af06-d806f9aa15f0)
![image.png](https://images.zenhubusercontent.com/6408f6bee4d68058a5b2cf6b/0f2a95ae-8c9a-4e20-aa6e-38b702860654)
![image.png](https://images.zenhubusercontent.com/6408f6bee4d68058a5b2cf6b/386bf55e-0890-46d0-8b65-508aee1a5bbe)
![image.png](https://images.zenhubusercontent.com/6408f6bee4d68058a5b2cf6b/55210323-f964-4dd9-a149-55ff7fb5158e)
![image.png](https://images.zenhubusercontent.com/6408f6bee4d68058a5b2cf6b/93ff645f-c5e3-4aec-bd44-d786aed9eacd)
![image.png](https://images.zenhubusercontent.com/6408f6bee4d68058a5b2cf6b/4328ce42-ab98-4ae8-a952-ce4547aba49b)
![image.png](https://images.zenhubusercontent.com/6408f6bee4d68058a5b2cf6b/171241d8-2dbf-4c6f-825c-0af7c7f7af76)
![image.png](https://images.zenhubusercontent.com/6408f6bee4d68058a5b2cf6b/9d828ebf-663e-47ea-8352-22121f4a4022)
![image.png](https://images.zenhubusercontent.com/6408f6bee4d68058a5b2cf6b/12051621-2cf7-4ff6-b374-0921983bfeff)
![image.png](https://images.zenhubusercontent.com/6408f6bee4d68058a5b2cf6b/e518ec8e-127f-48a2-bea6-c501b6557873)
![image.png](https://images.zenhubusercontent.com/6408f6bee4d68058a5b2cf6b/b8ac21bd-c594-4941-a990-53b0ef4e1f70)

You could word the **Selective Placement Factor** as: The incumbent will have experience with data science, statistics, and health informatics to support the operations and development activities for a national Quality Improvement project within a healthcare organization. This is necessary in order to provide advice and subject-matter expertise in tasks, projects and assignments related to developing, coordinating, and improving database to data science workflows for healthcare quality improvement and health system operational partners.

**Comment by hthrmarsh** [comment]
Considering this closed since completed the Job Analysis form and the Category Rating form - will be submitted to Randy Gieben today.

**Comment by epearman** [comment]
I have tracked the February efforts related to this card in #2920. This card will be tracking April efforts

**Comment by lzim** [comment]
@hthrmarsh 

@lzim - Removing from wk2 due to cross-covering **#people_ops_workstream**
See question on **[wk2 2023_may_epic team_time document](https://dvagov.sharepoint.com/:w:/r/sites/teampsd_vha/Shared%20Documents/General/teampsd_team_time_report/2023_may_epic_tt_report_v3.docx?d=w8bf87990a65749c786db97666d885959&csf=1&web=1&e=jQbsId)** - tracked on #2952 

_When is this likely to actually be due?_

**Comment by hthrmarsh** [comment]
@lzim - I don't know. Randy doesn't know either since this consult process is new with the HRMACS transition and everything has been pretty much delayed by four months and nobody knows when HRMACS staff will dig out. I followed up with him today: 

![image](https://github.com/lzim/teampsd/assets/126210778/6affbab0-9b22-49dc-994b-5f4c5bbd5eef)

**Comment by lzim** [comment]
#### Discussed at wk1 2023_jun_epic

@lzim 
@dkngenda 
@hthrmarsh 

- @lzim **_Update:  VA Form 0938 - Job Analysis - SME_**
- Outline the OMHSP Data Science competencies drawn from the PERC/NEPEC GS-13 Data Science Position
https://www.usajobs.gov/job/726164700
https://www.usajobs.gov/job/726044400

**Comment by hthrmarsh** [comment]
@lzim I misspoke. After further review of the Job Analysis form, you could list a competency and select SME as a drop down. You would need to write a description for it. I've never seen it done where someone created their own competency, but that doesn't mean you can't do it. 

That's a question we could ask the HRMACS Consultant. 

![image.png](https://images.zenhubusercontent.com/6408f6bee4d68058a5b2cf6b/67ee4b05-076c-49c7-bc79-99da6951408d)

**Comment by hthrmarsh** [comment]
![image.png](https://images.zenhubusercontent.com/6408f6bee4d68058a5b2cf6b/ce977944-6fd7-4ffe-8775-d42af5a8efbf)

**Comment by hthrmarsh** [comment]
- [ ] @lzim review competencies
 - [ ] Review Importance/Frequency list (HRMACS consultants suggest that it's unusual to see a lot of 5s)
 - [ ] Specialized Experience statement - statement by which we measure applicants against 
 - Jamie Moceri and Tim Alonzo to draft and provide statement for Specialized Experience comment
 - @lzim Experience with CDW and VA mental health care data but open to the public so shouldn't write it as VA-specific.

**Comment by lzim** [comment]
Done and sent 👍🏽
