### ISSUE TITLE
april_epic QA TEST: Dynamic Decision Dashboard 

### ISSUE THREAD

**Issue by ghost** [lzim/teampsd#2901]
#crossref #2854

Directions for Accessing the Dynamic Decision Dashboard:
#MTL_Pivot

1. Navigate to the [DEV sim environment](https://forio.com/app/va/va-psd-dev/login.html) 
2. Enter the following log in information
    - VA Email: devuser6
    - Password: test123A
3. under world select "test_team"
![image.png](https://images.zenhubusercontent.com/63331eaba895626f74a7c3a6/d398cab4-cdaa-448a-a56e-81359775fc2c)
4. Under Start a Session select "DevModelParameters.xlsx"
![image.png](https://images.zenhubusercontent.com/63331eaba895626f74a7c3a6/ff3169e5-0d29-4cb3-8f75-eb39244c10fa)

_____________________________________________________________________________________

**Comment by epearman** [comment]
**Reviewed briefly during wk2 2023_apr_epic**

@lzim 
@jamesmrollins 
@emilymetcalf114 
@hthrmarsh 

**Requirements:**
[ ] Remove SP from SP Flow
[ ] Address stock labels overlapping with stock visuals
[ ] Standard scale for stock diagrams

![image](https://user-images.githubusercontent.com/67978478/230185059-d78141fc-7a22-45bd-a743-4850ebd6aede.png)

**Comment by hthrmarsh** [comment]
@epearman 
- [ ] Are there specific things we're testing for or just to see that we can login?

**Comment by epearman** [comment]
@jamesmrollins this was discussed during **wk2 2023_apr_epic systyem_sme_workflow** 

### Need the users to be able to use their own Forio Login email & PW to work in the **DEV** instance of the **#sim_ui** for these **user_workflow**
- [ ] #mgmt_trio
- [ ] #systems_sme_workflow
- [ ] #support_workflow

**Comment by jamesmrollins** [comment]
@lzim I don't think it is a good idea to let users into DEV. We are working on the login issue currently, and will move to test slow very soon. Then we can ensure everyone has a login and can conduct testing.

**Comment by hthrmarsh** [comment]
@epearman I took a look at this and here's some feedback (keep in mind I'm not that familiar with this platform and maybe not the best tester)
- As discussed, we may want to come up with a set of directions for how to test when you get to that stage
- Nothing happens when you click ttAdmin under Site Report
- I clicked all the radio buttons and they seems to change the info in the stocks
- The labels "Experiment Maintenance" and "Team Data Maintenance" aren't intuitive but maybe these are described somewhere or maybe it doesn't matter in the dev space

**Comment by jamesmrollins** [comment]
@hthrmarsh @epearman 

Thanks for taking the time to test the interface.

- [ ]  You are correct about needing a test guide.  Typically, we would produce a test card that has testing instructions on it.
- [ ] Site Report is not functional.
- [ ] The radio buttons are for variable arrays, so they should change when you click them.
- [ ] The labels for Experiment Maintenance and Team Data Maintenance aren't intuitive - what do you think would make them clearer in your opinion?

**Comment by lzim** [comment]
### Functional Requirement: ALIGN Sim_UI Logins for internal Team PSD Quality Assurance Tests

@jamesmrollins - Following your response to @epearman. If we want to only TEST in TEST. Great!

I'm having a very hard time with my login and password requiring lookup since it does not align in natural opportunities to vet the Dynamic Decision Dashboard.

These were the **classes of workflow_users** who it made sense to align **#sim_ui Forio** login/pw across **DEV/TEST/PROD**.

- [ ] @lzim #pi
- [ ] @hthrmarsh #mgmt_trio
- [ ] @emilymetcalf114 #mgmt_trio
- [ ] @epearman #mgmt_trio
- [ ] @lijenn #support_workflow

**Comment by hthrmarsh** [comment]
> @jamesmrollins 
> 
> * [ ]  The labels for Experiment Maintenance and Team Data Maintenance aren't intuitive - what do you think would make them clearer in your opinion?

I'm not sure. Is there a way to have a little "i" or info button that describes what each of these spaces are?

**Comment by epearman** [comment]
Update from**wk3 apr_epic 8am_workflow** 
@lzim 
@jamesmrollins 
@hthrmarsh 
@emilymetcalf114 

Likely waste and rework for anyone to be thinking they will TEST this until. 

- [ ] @lzim signs off on whether the standardization and scale functional requirements are approved.
- [ ] May need time with David L, David N on this too.

**Comment by lzim** [comment]
**See above this is for @lzim and @jamesmrollins to review functional requirements** 
- [ ] standardization
- [ ] scale 
at wk3 **sim_ui_workflow**

**Comment by epearman** [comment]
#ajudicate_memo the dynamic decision dashboard is not ready for testing yet, functional requirements still need to be signed off on.

**Comment by lijenn** [comment]
Closing this card since this work is now tracked in #3029 
FYI @ljmoody
