### ISSUE TITLE
wk1 2023_jun_epic Team PSD team_time (tt) Newsletter Revival for may_epic

### ISSUE THREAD

**Issue by epearman** [lzim/teampsd#2952]
### Management Trio Develop Team PSD _Weekly_ Newsletter for May

Located [here](https://dvagov.sharepoint.com/:w:/r/sites/teampsd_vha/Shared%20Documents/General/teampsd_team_time_report/2023_apr_epic_tt_report.docx?d=w1b76e1483d1d41fe854486d0061bd3dc&csf=1&web=1&e=0ZPR5p)

- [x] #2956
tt1 team_time
tt2 team_time
tt3 team_time
tt4 time_time

@lzim 
@hthrmarsh 
@emilymetcalf114 
@epearman 

**wk1 apr_epic** 

### Assignments for developing the sections for the month of April are below:
- Monthly newsletter - Provide the view/orientation for the key deliverables whole month.
- Each Monday highlight the weekly specifics for what needs to occur that week.

- [x] @lzim & @hthrmarsh Education/Growth
- [x] @hthrmarsh Portfolio
- [ ] @hthrmarsh & @epearman & @lzim Research
- [ ] @emilymetcalf114 Operations
- [ ] @epearman for Development

#### After 8am_workflow leads to account for any 

- [x] Use **value stream standard colors** and **order**
- [x] List the relevant **Management Trio** and/or Lindsey
- [x] **Provide links** to the workflow, resource (OSF), meeting link

_Below are examples of the updates needed for each of our 5 value streams_

#### Education/Growth (orange)
- **Story H** – Data Scientist process
- **Key external dates:** Conferences; Annual VHA updates, CDIAS, IRI
- **Mentee dates:** Dissertation dates, etc.

#### Portfolio
- Key deadlines for the next **upcoming grant submission**
- Key **annual reports**, IRB, annual updating

#### Research
- Every key **#health_equity_gran**t meeting (monthly; **co-Is**)
- Every paper milestones (**3 priority papers: mar_epic**/R21; **apr_epic**/fidelity; **may_epic**/cost)

#### Operations
- Every **R01/IIR MTL Co-planning** Meeting with our 30 sites incl. ILEAD
- Every **SAMSHA Cadence** Dates & Point Person, Activity

#### Dev Cadence Milestone
- **DEV/TEST/PROD/TRAIN cadence** milestones 
- **mar_epic** tt_reports
- **apr_epic** #health_equity sankey

**Comment by epearman** [comment]
We tried to do an apr_epic newsletter but didn't complete it in time #crossref #2889

**Comment by hthrmarsh** [comment]
@emilymetcalf114 
@epearman 

I probably spent too much time messing around with this today, but if you could update your sections, that would be great. It would look more Newsletter-ish if we can print to PDF and get rid of the header/footer. I tried following these directions and some other ones in Adobe Pro but couldn't seem to do it. 
https://www.extendoffice.com/documents/word/5453-word-print-without-header-and-footer.html

**Comment by hthrmarsh** [comment]
Reviewed at wk1_2023_may_epic 8am_workflow. @epearman and @emilymetcalf114 to update their respective key priority sections. Will set up a QA card following that.

**Comment by lzim** [comment]
#adjudicate_memo
#pi
@lzim - 5 story points on Friday

- [x] @lzim Reviewed the newsletter for **2023_apr_epic** - began to make edits. Realized non-responsive to prior feedback & out of date. Moved on with fresh copies for may. 
- [x] Unclear based on second stories **wk4 2023_apr_epic** what was identified by **#mgmt_trio** as the process to ensure this is completed for initial review at **#hq_workflow**.

- [x] @lzim Further revised **2023_may_epic** so that related information was together and clarified which leader is accountable for delivering key objectives under each workstream and related to each value stream.
- [x] @lzim Began with most cross-cutting updates for partners about the weeks partnered meetings and responsibilities.
- [x] @lzim Saved additional versions to provide training in the iterative development from april, thru may
- [x] @lzim Began aligning the Newsletter to the **[wk2 weekly sprint](https://app.zenhub.com/workspaces/team-psd-workspace-5e4ac9bd8d388dfba6d9aef5/reports/burndown?milestoneId=Z2lkOi8vcmFwdG9yL1NwcmludC84OTg0OTA&entity=sprints)**  using issue cards, value streams, workstream manager but it is not current (50 points not completed for wk4 2023_apr_epic).
- [x] @lzim Began to update and organize resources at the bottom by Team PSD or _MTL_

**[v3 ] #mgmt_trio needs to work with this version to add the additional details** 
(https://dvagov.sharepoint.com/:w:/r/sites/teampsd_vha/Shared%20Documents/General/teampsd_team_time_report/2023_may_epic_tt_report_v3.docx?d=w8bf87990a65749c786db97666d885959&csf=1&web=1&e=alX3vS)- This should be edited to include the key platform details
- [ ] @emilymetcalf114 - Clarify exactly what you are accountable for completing by Thursday.
   -  - [ ] add site details
   - [ ] Align Board/Map/Newsletter issue card links and storypoints for wk2, 
   - [ ] Clarify assignee and workflow where work will occur.
   
- [ ] @hthrmarsh - Clarify exactly what you are accountable for comleting by Thursday.
   - [ ] Align Board/Map/Newsletter issue card links and storypoints for wk2, 
   - [ ] Clarify assignee and workflow where work will occur.
   
 - [ ] @epearman  - Clarify exactly what you are accountable for comleting by Thursday.
   - [ ] Align Board/Map/Newsletter issue card links and storypoints for wk2, 
   - [ ] Clarify assignee and workflow where work will occur.
      - [ ] No development specifics were included, all under research value stream

**Comment by lzim** [comment]
- [x] @lzim - My sections of **team_time** are current to **wk2 2023_may_epic.**

@hthrmarsh & @epearman please advise when your top priorities are aligned.
Thanks!

**Comment by lzim** [comment]
@hthrmarsh 
@epearman 

1. _Are you done with your sections from my **wk1 2023_may_epic** set of requirements?_
2. _Do you believe that the newsletter is ready to send?_

Thanks for clarifying!

**Comment by lzim** [comment]
Also, looks like this should have been in either **1. priority epi**c or **In progress** pipellne, since we're still trying to get this out the door and doing meaningful work for the **#ARTFlow.**

**Comment by hthrmarsh** [comment]
@lzim 
I updated my section and proofread/reviewed formatting.

**Comment by hthrmarsh** [comment]
Sent out tt_teampsd wk1_jun_2023 newsletter during 8am_workflow:

![image](https://github.com/lzim/teampsd/assets/126210778/1ed6bf88-ca27-425e-929e-974dc6d9d1ae)
