### ISSUE TITLE
may_epic Story B: QA New Data Landing Page with new Links

### ISSUE THREAD

**Issue by epearman** [lzim/teampsd#2955]
Review the following in the TEST instance of the [Data UI ](https://app.powerbigov.us/Redirect?action=OpenApp&appId=857e87fb-976f-49b1-b84f-0f5dc8208e7d&ctid=e95f1b23-abaf-45ee-821d-b7ab251ab3bf)

**I have added the following links as documented in #2909**
- [x] Check the FAQs at https://mtl.how/community 
    - [ ] This link above takes you directly to the MTL wiki are we sure we want users to be led here and not directly to the FAQs at https://github.com/lzim/mtl/issues?
- [x] OMHSP Team Participatory System Dynamics: https://mtl.how/team 
- [x] OMHSP National Quality Improvement Implementation Consultant (QIIC) Sharepoint

**I have resized the _MTL.how_ logo in the data UI #2943**

![image.png](https://images.zenhubusercontent.com/63331eaba895626f74a7c3a6/6ed9499f-817e-47b6-a36b-3a14395ad23d)

**Comment by emilymetcalf114** [comment]
@epearman 
I have QA'ed the links on the Test instance of the data_ui. They all work. 
From a user-centered perspective, I worry about the last link being on 2 separate lines. The layout is confusing currently, at first glance I don't differentiate the last 3 lines as 2 unique links: 
![image](https://user-images.githubusercontent.com/111393225/235782253-c5a72e55-23e2-4d28-8729-d4be3d6d4585.png)

It might help to align the text to the left (instead of centered) and put the last link all on one line? If it is hard to fit, we could make the font size a little smaller. We may also want to update the text for clarity: 

- **_MTL_** FAQs
- OMHSP Team Participatory System Dynamics **(Team PSD) website**

**Comment by epearman** [comment]
I have incorporated the final review and published to production.
