### ISSUE TITLE
2024_06_epic #story_I: As a OMHSP Leader, I need to see how mtl supports Directive 1160.01 DEV

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#2993]
# Research and Develop a Directives matrix that shows how _MTL_ supports specific requirements outlined in Directive 1160.01. 

## Definition of Done

- [x] Review [Directive 1160.1](https://dvagov.sharepoint.com/sites/VACOMentalHealth/SitePages/1160.01.aspx)
- [ ] Look for linkages between the directive and _MTL_ use cases. 
- [ ] Create a crosswalk table that references Directive requirements and specific support mechanisms that _MTL_ provides mental health leaders in the attainment of the spirit of the Directive.
- [ ] Share the mechanisms with National Center leaders for their information and use.

**Comment by lzim** [comment]
@lijenn - Let's add this to **wk4 #sim_ui_workflow** agenda. I'm not sure I can understand the status from the card.

**Comment by lzim** [comment]
@lijenn - 
This this came up at **8am_workflow** and I was unsure if you had completed what you _wanted to before I review something?_
_What is there to review?_

Thanks!

**Comment by lzim** [comment]
@lijenn 
Per our converation at 8am_workflow today 🚀 

[SUD example page](https://dvagov.sharepoint.com/sites/VACOMentalHealth/SitePages/Substance-U.asp)
[BHIP example page](https://dvagov.sharepoint.com/sites/VACOMentalHealth/BHIP)

**Comment by lijenn** [comment]
Note that the text for the MH 1161 Directive sections will be long. See the word count below for Topic 3's Directive:

**UNIFORM MENTAL HEALTH SERVICES IN VHA MEDICAL POINTS OF SERVICE**
**1. PURPOSE**
This Veterans Health Administration (VHA) directive states minimum administrative and clinical requirements for VHA mental health services that must be implemented nationally to ensure that all Veterans and those otherwise eligible for care, wherever they obtain care in VHA, have access to needed recovery-oriented mental health services. Throughout this directive, the term mental health services includes evidence-based services for the prevention, evaluation, diagnosis, treatment and rehabilitation of mental health conditions, including substance use disorders (SUD). Program-specific requirements are discussed in greater detail in program-specific directives. If no program-specific directive is available, access to more detailed information is provided in this directive (see paragraph 16). _**NOTE:** It is not the purpose of this directive to describe all mental health services that may be necessary and appropriate to address the mental health care needs of Veterans. Department of Veterans Affairs (VA) medical facilities are expected to adhere to principles of patient-centered, recovery-oriented mental health care in identifying appropriate resources, in accordance with Veterans’ needs and local challenges, resources and opportunities._ **AUTHORITY:** 38 U.S.C. § 7301(b); 38 C.F.R. § 17.38.

**8. ACCESS TO MENTAL HEALTH CARE**
**b. Screening and Initial Evaluation Requirements.** (needs to be underlined, if possible)

(a) Diagnostic assessment. 
- (5) For established patients, appointments for all mental health services should be scheduled within the requirements of VHA Directive 1230, Outpatient Scheduling Management, dated June 1, 2022. If the treatment requires a series of appointments to provide a complete course of the intervention, the acceptable access timeline applies to the first appointment. All subsequent appointments must be scheduled in accordance with the appropriate clinical timing for the specific intervention/treatment plan (e.g., on a weekly recurring basis for 10-15 weeks for evidence-based psychotherapy. 

**c. Requirements for Points of Service and Extended Hours.** (needs to be underlined, if possible)
- (3) VHA Administrative Parents are required to provide, onsite and at a minimum, a broad range of mental health services delivered through PCMHI, Behavioral Health Interdisciplinary Program (BHIP) or SMH, including treatment for PTSD, SUD and SMI, as well as compensated work therapy, transitional work and supported employment services. Access to peer support services, or any mental health service not required or able to be delivered at the point of care (e.g., residential care, Psychosocial Rehabilitation and Recovery Center (PRRC) services, SUD Intensive Outpatient Programs (IOP) or Intensive Community Mental Health Recovery (ICMHR) services) must be made available either via telehealth or referral for care in the community through VCCP. 
	
**9. CONTINUUM OF CARE**

**a.** VA mental health services are organized across a continuum of care and are provided in a team-based, interprofessional, patient-centered, recovery-oriented structure. The continuum must promote timely and effective treatment at the least intensive level of care appropriate to meet Veterans’ needs, taking into consideration the severity and complexity of illness, what matters most to them in their lives and the Veteran’s expressed preferences for treatment. Options for care include, but are not limited to, self-directed care, PCMHI, GMH services (BHIP), specialty outpatient services, Whole Health services, psychosocial rehabilitation and community-based programs, residential and inpatient programs and crisis services. 

b. **Required Services.** (needs to be underlined, if possible) The following services must be made available by the VHA Administrative Parent across the continuum of care as appropriate to the program and patient care needs _**NOTE:** If a site of care within the VHA Administrative Parent does not offer the required services listed below, the service must be available through another VA resource._ 
   - (2) Individual treatment using evidence-based pharmacotherapy, psychotherapy and somatic therapy (e.g., electroconvulsive therapy (ECT), repetitive transcranial magnetic stimulation (rTMS)) for the full range of mental health conditions including SUD (see VHA Directive 1160.05, Evidence-Based Psychotherapies and Psychosocial Interventions for Mental and Behavioral Health Conditions, dated June 2, 2021). 
   - (3) Group treatment using evidence-based pharmacotherapy or evidence-based psychotherapy. 
      - a) Psychotherapy groups can be either closed (also called cohort-based) or continually open to enrollment of new members. The provision of closed or cohort-based groups are permitted in a point of service only when the site’s care system ensures that the Veteran seeking or referred for such a group can be monitored on a regular basis, evaluated for ongoing care needs and, if clinically appropriate, offered interim treatment. Such treatment may include but is not limited to individual treatment or options for self-help, peer support services or other Veteran-driven self-care activities. 
   - (9) Referrals and coordination of care between other levels of care and community treatment programs. _**NOTE:** Health care should strive to be comprehensive, Veteran-centered and evidence-based. Evidence-based care incorporates the clinical experience of the provider, patient values and preferences and the best available evidence from systematic research. While emphasizing specific treatments based on research, VA clinical practice guidelines are not prescriptions for management of every patient but are used to inform care within that context. It may be appropriate for health care providers to use complementary interventions beyond those defined by systematic research, so long as they are consistent with the clinical judgment of the health care provider and within that health care provider’s scope of practice. In such cases, the potential benefits and risks must be reviewed in a shared decision-making process between providers and Veterans and be in accordance with VHA Directive 1137. These discussions must be documented in the EHR._

c. **Elements of the Continuum of Care.** (needs to be underlined, if possible)
- (4) Mental health services throughout the continuum of care must be team-based. Teams must be interprofessional and appropriate in size, discipline, and clinical expertise to meet the needs of the population served. All points of service must be flexible in the configuration of teams in order to maximize resources and provide a broad range of recovery-oriented and evidence-based mental health services. Flexible teams promote timely initial and sustained access to the appropriate type and level of care within the continuum of care. As Veterans complete an episode of care or move to another level of care, capacity must be created to ensure access for new patients and patients returning for a new episode of care. 
   - (b) Outpatient General Mental Health Service. (needs to be underlined, if possible) Outpatient GMH service is delivered through BHIP teams and provides recovery-oriented care for mental health disorders across a full spectrum of diagnoses and conditions. Services may include those outlined in paragraph 9.b. and others as appropriate to the needs of the Veteran, including but not limited to suicidality, PTSD, mood disorders, traumatic brain injury (TBI), military sexual trauma (MST), SMI and SUD. Every VA medical facility is required to implement BHIP care. Full implementation means each BHIP team must incorporate the evidence-based Collaborative Chronic Care Model (CCM) as the practice model and be staffed to serve approximately 1,000 GMH unique Veterans. VA medical facilities should follow the BHIP model’s staffing ratio, which is considered the minimum necessary to adequately provide evidence-based treatment and other indicated services, care coordination and proactive population management. VA medical facilities must sufficiently staff BHIP teams to provide required CCM elements as outlined in operational guidance. _**NOTE:** For additional information about BHIP, see the OMHSP resource page at: https://dvagov.sharepoint.com/sites/VACOMentalHealth/SitePages/Behavioral-Health-Interdisciplinary-Program-(BHIP).aspx. This is an internal VA website that is not available to the public._
   
   
WORD COUNT: 1170

**Comment by lijenn** [comment]
Here is a rough wireframe as discussed with @tejaspesquare on 04/25/24:

 - [ ] 1. 
 <img width="911" alt="image" src="https://github.com/lzim/teampsd/assets/59668647/bb738edb-14bb-4533-8e26-f86135c80992">
 
 - [ ] 2.
 <img width="1105" alt="image" src="https://github.com/lzim/teampsd/assets/59668647/af2291f5-7cac-4184-af31-ebf4f04084a4">
 
 - [ ] 3. 
 <img width="1084" alt="image" src="https://github.com/lzim/teampsd/assets/59668647/7cf202b0-78b8-4ab9-8587-21b0bf7eb8c4">
   - Note: The body text for each column is incorrect. The text for the header of each column is correct (e.g., Topic #, Video Question, etc.) pending design review.
   
- [ ] 4. 
<img width="1060" alt="image" src="https://github.com/lzim/teampsd/assets/59668647/58070908-1b1d-4218-9210-520f55cd0688">

- [ ] 5. 
<img width="1231" alt="image" src="https://github.com/lzim/teampsd/assets/59668647/f9c9228f-1440-45c0-8afe-4c48391dbc03">

- [ ] 6. 
<img width="1216" alt="image" src="https://github.com/lzim/teampsd/assets/59668647/7612a59e-8df1-47ac-ac6e-e1e96f4365c1">

- [ ] 7. 
<img width="1253" alt="image" src="https://github.com/lzim/teampsd/assets/59668647/d1240eb2-d759-4e36-ae8c-199acd5aa608">

I will try to polish up the table style/color and etc. to conform to _MTL_ design standards.

@lzim Please let us know if you have any design feedback, thanks!

**Comment by lzim** [comment]
**wk3 2024_05 #support_workflow**
@lzim 
@lijenn 
@ljmoody

FYI: @jamesmrollins 

### Requirements
- [ ] Parallel the _MTL 3.7 Consult_
- [ ] Omit rows of the table without a link.

**Comment by jamesmrollins** [comment]
@lijenn @ljmoody 

@lzim @dlkibbe @dlounsbu  
- No SME dependencies at this time. This feature should follow by 5/31 (not including provisioning of information via the admin dashboard).

## 5/29 Sim UI Demo

- (Angels) Need sample text (not image) from directives for design and testing.
- (Angels) Need average word count for text blocks.
- (DEV) Need to add in some form of markup to add headers to text.

**Comment by ljmoody** [comment]
@tejaspesquare, please incorporate the following changes into the directives table:

![image](https://github.com/lzim/teampsd/assets/124643236/5a4d2ba8-5554-4b9c-b0ce-6ba82734e538)

fyi: @jamesmrollins, @lijenn

**Comment by tejaspesquare** [comment]
Hello @ljmoody, changes incorporated into Directives table.

Output-
![image](https://github.com/lzim/teampsd/assets/144898781/102664f7-8e99-40f8-a603-c72e41431f2d)

Configuration- 
![image](https://github.com/lzim/teampsd/assets/144898781/b7ed551c-8581-48a9-a190-19bba2dc053f)

Note: 'Video Topics' appeared as hyperlink, but target location shall be configured by put in details under 'Video Link' column on Administration page. The hyperlink for 'Video Topics' is displayed, however, target info must be specified by entering the details in the 'Video Link' column on the Administration page.

**Comment by ljmoody** [comment]
Hi @tejaspesquare, 
FYI: the Directives mockup content _did_ load the first time for me.

#### Please make the following changes to the Directives pop-up, with the modified screenshot below:
- [ ] Add a checkbox column where shown
- [ ] Add a buttons before table
![image](https://github.com/lzim/teampsd/assets/124643236/7cc33fbc-fc82-42e2-b15a-f28a72465987)
- [ ] Also, per Jenn's wireframe point 7 above, please make sure the Directive column pop-up window is movable and sizable -  its current state is neither:
![image](https://github.com/lzim/teampsd/assets/124643236/027e9179-9a84-4e1f-b5e6-e00dc089f18c)

#### Within the Administration page:
- [ ] change these two headings in the Select Section dropdown:
![image](https://github.com/lzim/teampsd/assets/124643236/506fb523-eb61-49e5-b01b-4df9865c4082)

fyi: @jamesmrollins, @lijenn

**Comment by ljmoody** [comment]
Jambo, @tejaspesquare, 

1. Directives popup: I understand the good point you made. I hadn't thought of admin rights vs field user rights. 👍 
2. Great - I'll test when development is ready for review.
3. 🚀 Excellent - thank you!

fyi: @jamesmrollins @lijenn

**Comment by ljmoody** [comment]
@tejaspesquare, is it possible to have the MTL Dynamic Decision Dashboard Directives Maintenance blue bar checkboxes fall into the column and not overlap the column line?:
![image](https://github.com/lzim/teampsd/assets/124643236/57051479-b769-43c0-a4e8-d8637d1c6652)

**Comment by ljmoody** [comment]
@jamesmrollins, the functionality of the directives is solid, insofar as inputting information and what users see/experience when clicking the DDD Directives icon. 
- FYI: I only tested with Team Care module and did not test deletion of an item (I can do that after training_workflow today). 
- Tejas' team is working to make the Directive column pop-up window movable & sizable.

The screenshots below show the Team Care info input + DDD Team Care Directives look/behavior. 
![image](https://github.com/lzim/teampsd/assets/124643236/9802de07-b173-4222-a94a-04aebfbcac35)

**Comment by tejaspesquare** [comment]
@ljmoody- We have completed remaining points & code moved to Test-slow.

2. Resize & Floating Feature on Popup - 

Default Screen -
![image](https://github.com/lzim/teampsd/assets/144898781/37882af9-8c48-4050-bb6c-3cbe0a1760e9)

Floating on Screen -
![image](https://github.com/lzim/teampsd/assets/144898781/781fcfe8-47cd-4ef9-9236-3a5cc1a935d3)

![image](https://github.com/lzim/teampsd/assets/144898781/5e33cc06-59f2-4ab8-add5-1c2b63607c90)

Resize-
![image](https://github.com/lzim/teampsd/assets/144898781/a794122c-355d-4712-ba6a-44acb509de9a)

Note: If you perform a resize popup from right to left, you will observe that the size automatically adjusts according to the movement of the cursor. However, you can disable this behavior by clicking on the blue bar of the popup. We have made efforts to resolve this issue, but further investigation is needed as it is a third-party feature (text editor).

**Comment by ljmoody** [comment]
@tejaspesquare, I am unable to log in to TEST-slow today, so cannot test/verify the popup functionality and checkboxes alignment. I [recorded this video](https://takouba-my.sharepoint.com/:v:/g/personal/lmoody_praxisanalytix_com/EVYzQQNOpQlAukhbgQv0OToBbtq2AFGyZrtwoiOfVunq3A?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=kQUgHg) to show the behavior and inspect console messages in case it's informative to you.

fyi @jamesmrollins

**Comment by tejaspesquare** [comment]
Hello @ljmoody, the problem has been resolved, allowing you to log in without any issues. Our investigation has revealed that the Delete API is responsible for this issue, and we are working with David to ensure a permanent fix.
Thank You!

**Comment by ljmoody** [comment]
✅ Verified checkboxes under MTL Dynamic Decision Dashboard Directives Maintenance blue bar are aligned. 

@tejaspesquare, with regards to:

> Note: If you perform a resize popup from right to left, you will observe that the size automatically adjusts according to the movement of the cursor. However, you can disable this behavior by clicking on the blue bar of the popup. We have made efforts to resolve this issue, but further investigation is needed as it is a third-party feature (text editor).

Is this currently being investigated by your team? If so, please provide an update with progress or estimated date of completion. 

fyi & questions, @jamesmrollins - The functionality of the feature is ready besides the popup sizing issue quoted above. As such, I don't think this feature can yet be moved to "done." Do you know where the directives document @lijenn worked on formatting is located? How will they be input- via TEST instance, and then migrated to PROD or only input directly in PROD instance?

**Comment by tejaspesquare** [comment]
Hello @ljmoody 

> Is this currently being investigated by your team? If so, please provide an update with progress or estimated date of completion.

The team has initiated an investigation into the issue. Unfortunately, we cannot give precise timeline for when it will be resolved as we are currently dealing with third-party code. We anticipate providing an update shortly. It is our belief that this resizing issue is not hindering user functionality or displaying incorrect content. So, if users are waiting for this functionality, we suggest migration of code to production environment and will subsequently incorporate the solution for resizing once it has been identified.

**Comment by ljmoody** [comment]
@tejaspesquare, I appreciate your opinion on the functionality of this feature and agree. Please migrate to PROD and I'll move this card to "done". 
When you have a resolution for the pop-up sizing, please notify our team via this card. Thanks!

fyi @jamesmrollins

**Comment by ljmoody** [comment]
Development of this feature is complete and live in PROD. 
- @ljmoody and @lijenn will populate Directives with content, this will be tracked via #3184
- Remaining pop-up window sizing issue will be tracked in #3183.

Closing this issue.
