### ISSUE TITLE
2024_07: Consider removing or renaming "Add" button in DDD >Team Data window 

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3215]
Need identified 7/16/2024 by Lindsey in #3211
![image](https://github.com/user-attachments/assets/f59facad-183f-46d3-841d-82cb12be9582)

### Users need intuitive Upload vs. Add distinctions.
- **Upload** = uploading a new file to a team
- **Add** = associating an existing file with a team

### Considerations:
- [ ] Do field users need the ability to associate previously uploaded files to teams? 
  - If not, this "Add" button can be removed. 
    - Admins can still associate previously uploaded data files to teams via the Admin Dashboard. 
    - Be sure that we fully understand the ADD button function on that dialogue before we remove it.
  - If so, this button may need to be renamed (or other action) to reduce user confusion
- [ ] Brainstorm other possible names for this function?
- [ ] Depending on what is done with this Add vs Upload, it may impact Admin Dashboard function that's similar and located here, currently documented in #3187:
![image](https://github.com/user-attachments/assets/9975a683-1ef8-4378-90ac-862271262d5f)

**Comment by ljmoody** [comment]
@tejaspesquare - please see Lindsey's comment above WRT adding wording under the "Add" and "Upload" buttons in both Sim locations mentioned.

fyi @jamesmrollins

**Comment by tejaspesquare** [comment]
Hello @lzim, @ljmoody, 

Please advise if our interpretation deviates from what is anticipated in the following.

**Add Action**
1. Dashboard:
The "Add" action triggers a message prompting the user to select a file. In order to meet the requirement, we need to display a list of all files uploaded by members. We hope this approach is satisfactory.

![image](https://github.com/user-attachments/assets/bedb5423-6ffe-4960-9520-b2f95a269e51)

2. When viewing the home screen, you will come across two separate flow-
![image](https://github.com/user-attachments/assets/c13a31e8-47b2-44d0-9a23-d3341f5dfa08)

i. When Administrator comes from Dashboard: We will display the same list as shown on the Dashboard screen.
ii. Non-admin user directly comes to Home screen: The Add button must be hidden for security purposes; otherwise, unauthorized access to other files may occur.

Thanks!

FYI - @jamesmrollins, @lijenn

**Comment by lijenn** [comment]
Discussed 7/19 Team Praxis Call:
~~- [ ] @matomasz will create the redesign wireframe ~ 2pts~~
~~- [ ] then we will let Dev know when it's ready ~ 3 pts~~
- [ ] @jamesmrollins @matomasz @lijenn verified that the "Add" button was removed in DDD and "Upload" button removed Admin Dashboard in Prod already
<img width="851" alt="image" src="https://github.com/user-attachments/assets/6384ba47-1048-4c9f-b38c-07ed80bcd7d8">
<img width="474" alt="image" src="https://github.com/user-attachments/assets/5e71da90-b5d9-4f20-aebb-60948e331016">
