### ISSUE TITLE
2024_09: add a key/message to clarify how to interpret color stock indicators

### ISSUE THREAD

**Issue by ljmoody** [lzim/teampsd#3248]
(per @lzim's comment in #3072:)
### We need a message to clarify how to interpret color stock indicators 
- [x] Recommend a color key that with this text below
   Red = Inflow > Outflow
   Blue = Outflow > Inflow

![image](https://github.com/user-attachments/assets/7c1c0f1f-1f85-40c8-97f6-a6d89dc1153e)

## AC:
- [x] Key/message is developed
- [x] Key/message approved by Lindsey
- [x] Key/message is added to each module's flow pop-up
  - [x] CC
  - [x] AGG - Team Care
  - [x] MM
  - [x] PSY
  - [x] SP - Team Flow

**Comment by matthewtomo** [comment]
**Discussed DEV Standup 8/12/24**
@matthewtomo @tejaspesquare 

- Prototype is available in DEV (see below)
- Requesting approval from @lzim for the prototype captured below

![image](https://github.com/user-attachments/assets/5d1e3002-057f-450b-adb3-9a47455416ed)
Proposed Text Changes:
Red: Inflow > Outflow
Blue: Inflow <= Outflow

fyi: @lzim @jamesmrollins @lijenn @ljmoody

**Comment by tejaspesquare** [comment]
Hello @lzim , @jamesmrollins , @ljmoody , @lijenn , @matomasz 

 New improved prototype:
![image](https://github.com/user-attachments/assets/6197b51d-765b-46c2-b55a-970516bad6ec)

**Comment by matthewtomo** [comment]
> ## AC:
> - [x] Key/message is developed
> - [ ] **Key/message approved by Lindsey**
> - [ ] Key/message is added to each module's flow pop-up
>   - [ ] CC
>   - [ ] AGG - Team Care
>   - [ ] MM
>   - [ ] PSY
>   - [ ] SP - Team Flow

@lzim, Does the stock color key in the above message from @tejaspesquare look good to you?

**Comment by lzim** [comment]
**wk4 2024_08 #9am_workflow**
@lzim
@jamesmrollins 
@matthewtomo 
@dlkibbe 
@lijenn 
@ljmoody 

**- Stock is programmed for rates to start at the top, but probably filling the flows from bottom to top would be better.**
Discussed the Sankey visual complexity, it should only be included when needed to show the flow, but not in static position. Due to delays and challenges with programming, this is outside the roadmap, but should review with data feeds during testing.

- This message is approved: 😸 
![image](https://github.com/user-attachments/assets/140950de-3b94-4f17-916c-828c91cc4f21)

**Comment by matthewtomo** [comment]
**Discussed Dev Standup wk4 2024_08**
@matthewtomo @tejaspesquare 

- Received approval from Lindsey, so we are ready to include the key on all flow diagrams.

**Comment by matthewtomo** [comment]
**Discussed Dev Standup wk_1 2024_9**
@matthewtomo @tejaspesquare 

- The color key should now be included in all flow diagrams.
- Currently this behavior is only available in DEV environment

fyi: @ljmoody

**Comment by ljmoody** [comment]
### 9/26/24 testing results

fyi @matthewtomo 
- Tested using VA laptop, Chrome browser, TEST instance.

✅ verified inclusion of color key indicator on each module's Flow pop-up:
![image](https://github.com/user-attachments/assets/f835439f-1bbd-4e73-afee-2ae72978b36b)

**Comment by matthewtomo** [comment]
**Tested in Google Chrome on non-VA machine 11/19/2024**
- PSY is currently the only Flow Diagram that is available for regular access in PROD, however I was able to still open the other flow diagrams to ensure the color key was available
- Since all Flow Diagrams have the color key in PROD, I am closing this card

![image](https://github.com/user-attachments/assets/687651c6-5985-4246-90c8-c085f44dd116)
![image](https://github.com/user-attachments/assets/e51b6599-89ef-47cc-8325-604de0985b99)
![image](https://github.com/user-attachments/assets/1c461af1-d913-4f8c-9f30-a24c8585aad9)
![image](https://github.com/user-attachments/assets/16f0cc8c-7c69-43e9-9f15-7cb6240fa47d)
![image](https://github.com/user-attachments/assets/2394b3c8-96d2-4464-925a-743d5a679e08)
