### ISSUE TITLE
Expanded Outputs - Text Navigation

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#343]
Concept 1
![image](https://user-images.githubusercontent.com/30132017/56065084-b51a8580-5d28-11e9-939b-d4eef8a8df67.png)

![image](https://user-images.githubusercontent.com/30132017/56064956-594ffc80-5d28-11e9-8fbb-6f0b5acc8538.png)

Concept 2

![image](https://user-images.githubusercontent.com/30132017/56065199-07f43d00-5d29-11e9-8fd3-4307ee4aa1b7.png)

Concept 3

![image](https://user-images.githubusercontent.com/30132017/56065398-949efb00-5d29-11e9-8ad4-6a5c0a617d9b.png)

![image](https://user-images.githubusercontent.com/30132017/56065473-c748f380-5d29-11e9-9141-453ed46714a8.png)

**Comment by staceypark** [comment]
@jamesmrollins I'm liking concept 2, with having it next to the Save button instead of up in the blue bar

**Comment by jamesmrollins** [comment]
@staceypark @lzim  I agree Stacey, it seems to be the most direct linkage in terms of placement, style and such. If you like the box arrow alternative for the Expand function, that could also be placed next to the Save button on the Text Tile.

**Comment by lzim** [comment]
@staceypark and @jamesmrollins 

James,

Stacey and I reviewed the different viewing states we need to address and realized one was omitted in the mock-up, which is **when the fully expanded "Outputs and Text" section** (new name) is viewed: **We need a blue bar icon that shows us an option to collapse it back to just Text again.** As a result of this need, we decided *we will use the the new suicide prevention expand out icon* (described below), but ***we will also need the collapse/minimize icon*** (not shown above) in the Expanded "Outputs and Text" blue bar for collapsing back to just the floating "Text" section from Expanded "Outputs and Text" view.

See if these decisions are clear enough to you:

***Blue Bar Header Wording***
1. When a user first logs in to default mode and "Texts" is open, but minimized (i.e., text only no expanded output charts), then the blue bar should read "Text" as it does now. 
2. When text is fully collapsed the current "Outputs" Section blue bar should read "Outputs and Text" like in Concept 1. 
3. When the text and output charts are in expanded mode, then the blue bar would still read "Outputs and Text."

***Blue Bar Icon Selection and Location***
1. The newly labeled "Outputs and Text" section (i.e. the old "Outputs" section) needs to retain the white triangle in the blue bar for expanding and collapsing.
2. When the default mode "Text" section is open, but minimized (i.e., text only no expanded output charts), then the blue bar icon should be the suicide prevention expand out icon shown in Concept 3.
3. When the text and output charts are in expanded mode, we need the corresponding suicide prevention collapse/minimize icon in the blue bar.

***Icons below Blue Bar***
1. We will use the new expand icon as shown in concept 3, so that it corresponds with the guidance above.

Let us know if you have any questions! 

Thanks James 💯

**Comment by jamesmrollins** [comment]
So like this . . . 

![image](https://user-images.githubusercontent.com/30132017/56095789-2d05be80-5e95-11e9-81fd-76e5b152975e.png)

Text only . . . 

![image](https://user-images.githubusercontent.com/30132017/56095736-a94bd200-5e94-11e9-919d-b6c25f1c0a61.png)


and Expanded  . . . 

![image](https://user-images.githubusercontent.com/30132017/56095811-57577c00-5e95-11e9-9f5d-84f8cf4669ca.png)

**Comment by lzim** [comment]
Yes! Thanks @jamesrollins

**Comment by lzim** [comment]
@staceypark Should we address these new navigation features in the Sim UI cheatsheet?

@dlkibbe Should we address these new navigation features in the session 5 SEE guide?

Are there .gifs that need to be included/updated to show these functions?

**Comment by dlkibbe** [comment]
@staceypark @lzim @branscombj We will need to go through all the SEE and SAY guides and modify the title of the boxes that are now labelled individually "Text" and "Outputs" to the new title "Outputs and Text"
Copying Jane so she knows about this task.

**Comment by lzim** [comment]
Right! Great catch @dlkibbe

**Comment by staceypark** [comment]
> @staceypark @lzim @branscombj We will need to go through all the SEE and SAY guides and modify the title of the boxes that are now labelled individually "Text" and "Outputs" to the new title "Outputs and Text"
> Copying Jane so she knows about this task.

Great point! 
@dlkibbe @branscombj  I've also been changing references to the Q/H/F/D items to both references the section name and the decision we made to reinforce the Q/H/F/D language.  With the updated section name, we will need to say:
 "Do task xyz in the Q/H/F/D boxes in the Outputs and Text section"

**Comment by lzim** [comment]
@dlkibbe @branscombj

Have these edits been made? Can we close this issue?

Thanks!

FYI: @staceypark
