### ISSUE TITLE
ModelParameters Inconsistent

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#361]
@lzim @jamesmrollins @holbrooa @saveth @TomRust 

My understanding is that the red variables in the ModelParams generated from the data UI should be the same as the Team Data Table in the sim.

In adding the Team Data Tables to the each modules OSF earlier I noticed some things:

1) I'm noticing that the variable names between the sim data table and the model parameters are out of sync. In  CC, I see "Median Engagement"in the model params and "Engagement Duration" in the sim. It looks like we still use "Median Engagement" in MM though - can someone confirm?

2) For the PSY params, I think the "i" info definitions in the sim are incorrect? They are using D40-43 from the Model Params on the PSY tab, but I think they should be using D44-47 (from the most recent version - Version 6 - of Model Params in OSF).

3) In PSY, is it correct that the definitions for "Starters Who Quit %", "Initiators Who Return Later %", "Completers Who Return", "Return Visit Interval", and "Median Engagement Duration" exist only in the sim and not in the model params? And if so, I believe the tt report will not be reflective of the Team Data Table that's in the sim because that code comes from the Model Params and not the sim?

4) AGG has the same inconsistency between "Median Engagement" and "Engagement Duration" as CC. Also, for CC, the sim has "Appointment Supply (total)" but the Model Params doesn't.

**Comment by jamesmrollins** [comment]
Hi @staceypark 
Regarding your questions above:
1.  By inconsistency, do you mean data or labeling?  If I interpret your meaning correctly, the labels are out of sync.  The most current label should be "Engagement Duration" for all sims.
2.  The sim does not read definitions from the Model Parameters file.  It reads in from the model-popup-information.xlsx file.  If they are incorrect in the model-popup-information, then we will need to copy it over from Model Parameters, provided Model Parameters is most up-to-date. Someone (@holbrooa?) please verify which is most current.  In any case, I am not sure which definitions you are referring to, as D44-47 are Med Management "i" information cells. Can you please clarify?
3. Yes, you are correct.  They are calculated by the sim.
4.  See comments in number 1.  Regarding CC, I only see "Appointment Supply (75th Percentile)(appts/wk)" in the team data table in the Sim UI.  The MP file, however, should have three appt supplies for mean and median values (according to the crosswalk table, anyway).

**Comment by saveth** [comment]
Hi @staceypark 

Regarding your concerns:
1.  The r code for the tt report reads in the ModelParameter and replace some of the labels that are out of sync to match what is currently in the sim.
3. The values that are calculated in the sim are also calculated in the Rcode for the tt report.
4. same as 1.

**Comment by lzim** [comment]
@staceypark Thanks for working on this!

FYI: @jamesmrollins @saveth @TomRust @holbrooa @branscombj @dlkibbe 
- Folks, please be generous in keeping team members in the loop as we are doing a lot of "Level 2" Detailed documentation for SAY files right now as we train the OMHSP TAS this week. 🚀 

Also, please do make sure you're checking in/out the relevant workflow on OSF in project **master_crosswalk_workflow** here: https://osf.io/ygp36/

The most current versions of each file are in the OSF project and should be used to get to the bottom of discrepancies.
- It is not always 100% clear which elements are discrepant in @staceypark's post. So, let's work to try to get even clearer, if we can.

![osf_crosswalk](https://user-images.githubusercontent.com/7454688/58841782-4d91ff80-8620-11e9-9d77-4b56438a5e95.png)

@holbrooa and I updated the **SPParams** tab of **ModelParameters.xlsx,** within the last two weeks. We worked with @jamesmrollins @TomRust and the Master Crosswalk workflow to make sure the changes were tracked and @saveth alerted.
- I didn't not review any other tabs w/@holbrooa

My questions re: @staceypark's questions:

1. Do you see "Engagement Duration" **ModelParameters.xlsx** on OSF and in **model-popup-information.xlsx** on OSF?  If so, then Sim UI is consistent with this and Data UI code that produces the CC tab needs to be updated (see #4 below).

2.  Version 6 - of **ModelParameters.xlsx** and Version 3 - **model-popup-information.xlsx** in OSF should be "ground truth" And in sync with one another. So, where are the corresponding details in **model-popup-information.xlsx,** @jamesmrollins, that is where we need to go to resolve any discrepancies, right?

3. @saveth @staceypark So, since this is calculated by the sim per @jamesmrollins, can't we get it from the export, so that these key variables ARE still in the tt report?

4. I believe this is @holbrooa needed to update the CC query to make sure it's consistent with the move to use "Engagement Duration" and include a total appointment supply.

Thanks!

**Comment by staceypark** [comment]
#3 above has been resolved. @saveth tt report code does calculate the variables that do not exist in the model params and are only calculated by the sim.

FYI: @jamesmrollins @saveth @TomRust @holbrooa @branscombj @dlkibbe @lzim 
Using Model Parameters Version 6, Master Crosswalk Table Version 3, and Model PopUp Information Version 3.
Previously, while we did not have @holbrooa we were updating only the sim variable names as these were the learner facing materials (the "describe" level of our 4 documentation levels). However, now as we get ready to launch the r01 and iir trials and work with the TAS, getting the model params and sim UI consistent to each other is needed for our learners/"describe" level. In preparation for the F2F, we also need these updated for the "detail" level so there is no confusion or inconsistencies as folks are working on the SAY guides.

The "Standard Label" column in the master crosswalk table should always be our most current and correct version of the label name (as I understand it).
As such, I've updated the "Standard Label" column to say "Engagement Duration (median)" instead of "Median Engagement" where it is incorrect in the master crosswalk table (now Version 4)
 
@holbrooa 
As your first GANTT task, we need you to update your queries to include all of the changes we made during your hiatus:
1. Look at the master crosswalk table and note all variables names that are inconsistent with the sim.
2. Update model params query so that the labels will be consistent to the sim. 
3. Update master crosswalk table after model params have been updated to reflect changes that you have made.

So far, I have noticed the following:
1. For CC, MM, and AGG, "Median Engagement" needs to be changed to "Engagement Duration"
2. For #4 above, I actually meant AGG not CC. Also it's been clarified that some variables are not in your model params and are only calculated in the sim. So don't worry about this one.

@jamesmrollins 
1. For MM, the team data table in the sim was correctly labelled with "Engagement Duration (median)" but the i information still had "Median Engagement". I updated the model popup information to "Engagement Duration (median)"

@jamesmrollins @lzim @TomRust 
1. For PSY, the definitions used in the model popup information (D78-81) match D40-43 of the PSYParams tab of the model parameters. I think they should be D44-47 of the PSYParams tab of the model parameters. 
For example, right now for "AUD within 3 months %" the model popup information uses the below: 
An  estimate of the proportion of the team's patients with alchohol use disorder   (AUD), calculated from the cohort of patients who completed visits charted   with a primary diagnosis of AUD within **_their entire psychotherapy engagement._**
I'm proposing that it should be this version instead, with the key difference being that our variable is called within the 3 months so we should use the definition that describes it as the patient's first three months:
An estimate of the proportion of the team's patients with alcohol use disorder (AUD), calculated from the cohort of patients who completed visits charted with a primary diagnosis of AUD within **_the patient's first three months._**

**Comment by holbrooa** [comment]
Ok, I made the code edits and checked ModelParameters and master_crosswalk_table back in.
Note that there's still a missing description for agg, down at the bottom for the diagnosis - encounter type table.  I'm not sure why, since I'm pretty sure we had that there. It's probably just a matter of pulling it back in from the sim UI or somewhere, but I couldn't find it on the master crosswalk.
@lzim @saveth @staceypark

**Comment by staceypark** [comment]
@holbrooa So the missing Agg definition was for the services across the primary diagnoses below: 
![image](https://user-images.githubusercontent.com/31089501/59067235-e82f5000-8865-11e9-8658-a4ca2a5ebecc.png)

@lzim @TomRust and I:
1) Added a definition in language that mirrors the other definitions
2) Changed A7-H11 text to be **black** since our rule for red text is that it needs to be part of the Team Data Table in the sim UI. The new Model Parameters (Version 8) has been uploaded to OSF here: https://osf.io/j3ubz/
![image](https://user-images.githubusercontent.com/31089501/59067249-f2e9e500-8865-11e9-8f5f-56f146ccb05b.png)

fyi: @saveth

**Comment by holbrooa** [comment]
We noticed a few extra letters, so I went back through and re-updating the orphan ModelParameters and the crosswalk on osf, as well as the current data tool and code to remove the -ing from start rate for cc and mm. Now I'm noticing that CC and MM say "start rate" where psy and agg say "new patient start rate" (and sp says "new care episode start rate"). So that's slightly inconsistent.

**Comment by holbrooa** [comment]
@lzim @staceypark 

The question is: Do we need to change CC and MM "start rate" to "new patient start rate" as it is in psy and agg, or leave it as is?

**Comment by holbrooa** [comment]
Lindsey's decision is to keep the labels as-is. No additional rework needed on Savet's side. Current versions of ModelParameters and master_crosswalk on OSF are fine. 

Moving card to done and closing issue.

**Comment by saveth** [comment]
Rework is needed on tt with the changes made to ModelParameter during F2F to make it consistent with SIM and master_crosswalk. You asked me to hold off on updating tt until you got your question answered.

**Comment by saveth** [comment]
@staceypark Identified variable changes has been modified in @holbrooa DataUI code and ModelParameter output file, and those changes are now integrated into the R code for tt report. Please review and merge request #432. Once #432 is merged with master, we will close this ticket. thanks.

**Comment by saveth** [comment]
#432 was merged and closed, so the identified inconsistencies in this issue is no longer a problem.
