### ISSUE TITLE
Problem loading sim

### ISSUE THREAD

**Issue by dlounsbu** [lzim/teampsd#386]
@jamesmrollins : I loaded the sim once, no problem. Logged out, then wanted to load the sim again. Now I get this message with running dots. And the sim does not load.

![image](https://user-images.githubusercontent.com/20574023/59389605-b114df00-8d3c-11e9-9d7a-2706068ea51f.png)

**Comment by lzim** [comment]
Hi @jamesmrollins and @dlounsbu 👋 

FYI: @TomRust @dlkibbe @branscombj @saveth @holbrooa 

This is a great time try the **new streamlined Sim Issue Template** that we'll use to save time and standardize reporting of issues during the training:  https://github.com/lzim/teampsd/blob/master/issue_templates/sim-bug-report.md

- You just copy the details as I have below.
- We have one for the [Sim](https://github.com/lzim/teampsd/blob/master/issue_templates/sim-bug-report.md), [Data](https://github.com/lzim/teampsd/blob/master/issue_templates/data-bug-report.md) and [Guides](https://github.com/lzim/teampsd/blob/master/issue_templates/guide-bug-report.md).

_NOTE: We may want to add to the Sim Issue tracker a prompt of what Sim Module you were trying to load._

---
Step 1: Click raw to copy the code text below. 
Step 2: Click the link to create a new issue for the simulation user interface https://github.com/lzim/teampsd/issues/new.
Step 3: Edit the details to create a report that will help us improve the sim UI.
labels: bug
assignees: jamesmrollins

---

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by jamesmrollins** [comment]
Hi @dlounsbu, the sim sometimes hangs.  That is usually a result of internet performance.  In these cases, we just refresh and it normally comes back.  Let me know if this continues repeatedly.  Otherwise, can I close this issue?  Thanks, James

**Comment by lzim** [comment]
@dlounsbu Please do alert @jamesmrollins if this becomes a repeated issue.
But, I will close for now.

Thanks!
