### ISSUE TITLE
Navigating the DUI

### ISSUE THREAD

**Issue by dlounsbu** [lzim/teampsd#390]
Add a SAY guide Session 2: "The only one that does not have a data view on its own is Encounters!

Note to Facilitators: VISTA is the name of the VA clinic grid system. 

Note to the Facilitators: Health Factors are notes on encounters, and EB PSY templates use these notes. If teams are dealing with a supply imbalance. Focus on patterns of engagement. We want everyone to be seen for PSY in more or less weekly encounters!

**Comment by jamesmrollins** [comment]
@dlounsbu @lzim @TomRust @holbrooa @saveth @staceypark @jessfroe  Adding the workbreakdown form so we can triage this request.  

@dlounsbu, if you have an opportunity, please review below.  I did populate the form with your observations above; however, there may be more information you could add to help us fulfill this request.  Thank you, James.

//////////////////////////////////////////////////////////////////////////////////////////////////////////
---
**ORIGINATOR**
*Please follow the steps below to open an issue for the MTL Workgroups to address. Be sure to provide a descriptive title for the issue when saving.*


**Step 1** - Please assign this issue to the issue_tracker, under the “Projects” menu on the right side of your GitHub page.

**Step 2** - Please answer the questions below by placing a lowercase "x" between the applicable brackets below and providing brief narratives and screenshots where appropriate:

1. Is this issue a problem, such as a malfunction in the simulation, an error in documentation or similar concern, or is this a new idea
   we should consider?
   
   - [ ] Problem 
   - [x] New idea
   
2. What team are you on (exg., Menlo Park, Team Blue)?

3. How urgent is this issue?

   - [ ] Urgent - *should be addressed right away!*
   - [x] Non-urgent - *can be prioritized within normal workstreams.*

4. In the space provided below, please describe the information or behavior you expected from the product or otherwise describe what you expected to see or hear. 







5. Please provide a screenshot of the bug, if possible.  Make as many screenshots as you like that would be helpful to illustrate the issue.

   *<< Paste screenshots here>>*



6.  Within which product did you notice the problem? *Check all that apply*

**Data Products**

   - [ ] SharePoint
   - [ ] Data/Queries
   - [ ] Team Data
   - [ ] R-reports
   
**Instructional Products**
  
   - [ ] See Guide
   - [x] Say Guide
   - [ ] Videos
   - [ ] Post tests
   - [ ] Fidelity Checklist
   - [ ] Cheatsheets
   - [ ] Other?  Please describe here >>
   
**Simulations**
   
   Home
   - [ ] Login 
   - [ ] Session
   - [ ] Experiment Maintenance Tile
   - [ ] Team Data Menu Maintenance
   - [ ] Chat
   - [ ] Help
   - [ ] Facilitator Dashboard
   
   Care Coordination
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
   Medication Management
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
   Psychotherapy
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
   Aggregate 
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
   Suicide Prevention
   - [ ] Model Diagram
   - [ ] Outputs and Text
   - [ ] Experiments
   - [ ] Export function
   - [ ] Save function
   - [ ] Run/reset function
   - [ ] "i" Information
   - [ ] Team Data Table
   
7. What kind of device are you using?
   - [ ] Tablet
   - [ ] Smartphone
   - [ ] PC

8. What browser were you using?
   - [ ] Chrome  *What version?*
   - [ ] Edge    *What version?*
   - [ ] Safari  *What version?*


**<< If you are highlighting a new idea, please continue >>**

9. Please describe your idea below.  Feel free to provide a scan or screen capture of a sketch of your idea.

Add a SAY guide Session 2: "The only one that does not have a data view on its own is Encounters!

Note to Facilitators: VISTA is the name of the VA clinic grid system.

Note to the Facilitators: Health Factors are notes on encounters, and EB PSY templates use these notes. If teams are dealing with a supply imbalance. Focus on patterns of engagement. We want everyone to be seen for PSY in more or less weekly encounters!

10. Why is this idea important, in terms of your work?



11. How is this idea related to a problem you face in your daily practice?



12. Is there a deadline or other scheduled constraint driving your request that we should be aware of? *This will help us to prioritize
    this request.*


**THANK YOU!!**


---------------------------------------------------------------------------------------------------------------------------------------
**STOP HERE. INFORMATION BELOW IS TO BE FILLED OUT BY WORKGROUPS AS PART OF TRIAGE AND WORK BREAKDOWN PROCESS**
---------------------------------------------------------------------------------------------------------------------------------------

**Executive Summary**

*Estimated person-hours to complete:*

*Estimated date for completion:*

*Lead team for effort:*

*Key people (use @ assignment for people whose input will be necessary):*



**Step 1 - Complete the Interdependencies Table**

Workgroup Leads review information provided by originator and collaborate to identify interdependencies. Then they describe modifications that are needed in the appropriate column and estimate hours needed to make changes:
 
● *Workgroup Products* - This column identifies the workgroups and the products for which they are responsible. This column can be
  modified by a workgroup lead on an ad-hoc basis to add one-time products or can be modified to include new and enduring products.
  
● *Dependency?* - This column is used by the workgroup leads during collaboration to identify the existence of an interdependency.

● *Description of Change or Action Needed* - Workgroup leads briefly describe the change required.

● *Hours* - Workgroup leads estimate the person-hours required to complete the task.


Workgroup Products        | Dependency?  | Description of Change Needed               |  Hours Estimate
------------------------- | -------------|--------------------------------------------|-----------------
**Documentation**            
Brochures                 |              |                                            |
MTL See Guide             |              |                                            |
MTL Say Guide             |              |                                            |
MTL Videos                |              |                                            |
Post Test                 |              |                                            |
**Investigators**         |              |                                            |
Presentation              |              |                                            |
Quarterly Report          |              |                                            |
Annual Report             |              |                                            |
**Qualitative**           |              |                                            |
MTL Fidelity Checklists   |              |                                            |
Systems Thinking Codebook |              |                                            |
CFIR Codebooks            |              |                                            | 
**Quantitative**          |              |                                            |
Data UI                   |              |                                            |
Data Queries              |              |                                            |
SharePoint                |              |                                            |
Excel Outputs             |              |                                            |
ModelParameters           |              |                                            |
tt Reports                |              |                                            |
**Model**
CC                        |              |                                            |
MM                        |              |                                            |
PSY                       |              |                                            |
AGG                       |              |                                            |
SP                        |              |                                            |
**Sim User Interface**    |              |                                            |
Model Diagram             |              |                                            |
"i"Information            |              |                                            |
Experiments               |              |                                            |
Outputs/Charts            |              |                                            |
Exports                   |              |                                            |
Master Crosswalk Table    |              |                                            |

**Step 2 - Identify Constraints that may affect the team’s ability to complete the necessary actions.** 

Describe the constraint in terms of capability, capacity or affect on grant research goals. If there are no constraints identified, then leave the table blank.

●  Type - The type of constraint identifies one or more resource areas that are affected.  

●  Workgroup - this is the workgroup responsible for developing a new or modifying an existing product.

●  Discussion/recommendation - A brief narrative that expands the information regardingthe constraint and ideally a recommendation for
   overcoming the constraint.

**Type Constraint (check all that apply) / Workgroup(s) Affected / Discussion/Recommendation**

- [ ] Capacity      
- [ ] Cost         
- [ ] Schedule     
- [ ] Interference 
- [ ] Capability   
- [ ] Other (describe)

**Step 3 - Identify supported milestones.** *Affix the milestone at the issue level using available GitHub milestones.*

**Step 4 - Indicate the due date for completing the actions identified above, assuming constraints are removed.**


**Step 5 - Identify the lead workgroup for the action (check one):**

- [ ] Documentation
- [ ] Investigators
- [ ] Quantitative
- [ ] Qualitative
- [ ] Model
- [ ] Sim UI

**Step 6 - Go to the top of this section and complete Executive Summary information**

Note to Workgroups:  Use the issue thread to document further discussion, alternatives development and estimates.  However, be sure to update this form if dates, team responsibility or other information changes.

**Comment by lzim** [comment]
@dlounsbu These are nice edits for the session 2 SEE and SAY guides:

I've furthered edited the recommended content below, will you please edit the SAY file directly?
FYI: @TomRust @staceypark 

1. Across the vizDiag, vizMeas, vizHF, and vizEnc The data view details for Encounters and Diagnoses are combined under dataDiag.

2. VISTA is the name of the VA scheduling system. A "clinic" or a "grid" refers to how patients are scheduled locally.

3. Health Factors are notes on encounters, and EBPsy templates use these notes. 

4. Note that from a systems perspective it's more important to focus on patterns of engagement, than the data detail of whether or not the encounter has the EBPsy template (dynamics before details). We want everyone to be seen for PSY in more or less weekly encounters!

**Comment by staceypark** [comment]
I am moving the below details to the "detail S02" card in the document_tracker to add to the SAY guides. Based on our most recent decisions to only change SEE guides for typos & errors, I do not believe we would be adding these additional details to the SEE guide.

1. Across the vizMeas, vizHF, and vizEnc, the data view details for Encounters and Diagnoses are combined under dataDiag. The vizDiag tab pulls in data from dataDiag and dataEnc - this is a function of switching to having each row in dataEnc a unique visit.

2. VISTA is the name of the VA scheduling system. A "clinic" or a "grid" refers to how patients are scheduled locally.

3. Health Factors are notes on encounters, and EBPsy templates use these notes.

4. Note that from a systems perspective it's more important to focus on patterns of engagement, than the data detail of whether or not the encounter has the EBPsy template (dynamics before details). We want everyone to be seen for PSY in more or less weekly encounters!

**Comment by lzim** [comment]
@staceypark The major exception to the rule about only fixing the “typos” in the SEE guides is if there have been major changes to the actual data UI.

So, is it true that none of these new Data UI details are described incorrectly in the SEE guides? Including the .gifs and screenshots? I would find that surprising!

**Comment by staceypark** [comment]
@lzim you're right and I should have been more clear.
Based on my review of the Session 2 & 3 SEE guides, the content in terms of text won't need any changes. 

But the gifs & screenshots for the SEE and cheatsheets will need to be updated in general due to the many changes to the data UI including the tabs, buttons, SP transfer, etc. (Issue #469)

**Comment by lzim** [comment]
@staceypark and @jessfroe 

Reviewing issues like this one, we need to clarify at least 3 things at the **workgroup leads** meeting and in the **tracker/workflow SOP.**

1) How to use the **checklist** in the **document_tracker** to provide a standard review.
- For the #390 example, the .gifs should only be checked off when they are a) updated, or b) reviewed to ensure that they don't need updating.

2) We also need to make sure everyone knows how to add to or edit **dependent issue cards** to make sure they've been cross-checked.
- For example, this issue #390 needs to be in the list for **describe, detail, and document**.

3) Last, we need to **clarify how/when issues should be closed** when there are dependencies. 
- For example, since you can always check a closed issue. I believe it does make sense to close issues, when the work reflected in that card is done. But, _only when the dependencies have been tracked across other cards._
