### ISSUE TITLE
Participate Button to Report Issues to GitHub Projects

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#410]
**BEFORE FILLING OUT THIS TEMPLATE, PLEASE ASSIGN THIS ISSUE TO THE BUG KANBAN UNDER PROJECTS (YES, EVEN IF IT IS A FEATURE. ALL ISSUES START IN THE BUG KANBAN FOR TRIAGE). --------------------->**

**Describe the opportunity**
To improve the usability of the opportunity gathering process, provide a clickable button that is available in the lower right hand corner of the browser.  When clicked, the user will be presented with this opportunity form.

**READ THIS FIRST**
- _A bug is a developed feature that has been working, that is no longer working._
- _A feature is a function, product or characteristic that requires research, design and development._

**If This Is a Bug, start with number 1 below, if a Feature, skip to number 7.**

**1. Please describe the steps to reproduce the behavior.**
a. Go to '...'
b. Click on '....'
c. Scroll down to '....'
d. See error

**2. Please describe the expected behavior.**

**3. Please provide a(n) screenshot(s) of the bug.**
If applicable, add screenshots to help explain your problem. You can use the Snip tool available in Microsoft Windows 10.

**4. Please identify your operating system and browser version.**
 a. Operating System: [e.g. iOS]
 b. Browser [e.g. chrome, safari]
 c. Version [e.g. 22][You can find version by clicking on "help" then "about Chrome/edge/firefox" to get version information.]

**5. If you are using a smartphone, please complete the following information, otherwise skip to number 6.**

**6. Additional context**
 - Which function, model or team data where you trying to use?
 - Provide any other relevant information that may affect this issue.

**FEATURE**

**7. How would you like this feature to work?**
Describe your expectations in terms of outcomes/products/behaviors.
In the lower right hand corner of the browser, a button will be presented.  When clicked, the user is presented with a data form.  After it is filled out, it will go to the Team PSD GitHub issues list for disposition.  

**8. How urgent is this request? (Urgent/Not Urgent)**
Non-urgent
**9. Why is this feature important to you?**
It will improve the usability of bug/feature reporting; therefore, improving participation because it is quick and easy to give feedback.
**10. Is your feature request related to a problem? Please describe.**
GitHub does not allow automatic assignment of issues to project.  This means some intervention is required by a work group lead.
**11. Is there a deadline or other scheduled constraint driving your request?"**
None
**12. Additional context**

**STOP HERE. INFORMATION BELOW IS TO BE FILLED OUT BY WORKGROUPS AS PART OF TRIAGE AND WORK BREAKDOWN PROCESS**

**Estimated person hours to complete:** 30 Design hrs., 24 DEV hrs.

**Key people (use @ assignment for people whose input will be necessary):**
@jamesmrollins 

**Key dependencies:**
Are there other tasks that need to be completed first?

**Constraints:**
Is there a resource constraint that may affect the development of the feature?

**Gantt chart needed? Attach link and/or screenshot.**

**Comment by jessfroe** [comment]
@staceypark there are dependencies for learner/facilitator documentation and likely other documentation dependencies that we should brainstorm about with this issue.

**Comment by lzim** [comment]
@jamesmrollins @staceypark @jessfroe 

I'm cross-referencing the original issue for this, which wasn't placed on the **feature_tracker** **Participatory Learning, Design and Research #339 - https://github.com/lzim/teampsd/issues/339**

**Comment by staceypark** [comment]
thanks @jessfroe . I added it to all of our meta column cards except describe_learners as I don't think we need to change the SEE guides for this.

> @staceypark there are dependencies for learner/facilitator documentation and likely other documentation dependencies that we should brainstorm about with this issue.

@lzim @jamesmrollins Can we close #339 since it is already referenced in this issue and use this #410 issue to discuss updates? Also, what should be the due date for this? Launch? 2 weeks before launch for testing?

**Comment by jamesmrollins** [comment]
@jamesmrollins OK with me.

**Comment by lzim** [comment]
> thanks @jessfroe . I added it to all of our meta column cards except describe_learners as I don't think we need to change the SEE guides for this.

@staceypark there are dependencies for learner/facilitator documentation and likely other documentation dependencies that we should brainstorm about with this issue.

@lzim @jamesmrollins Can we close #339 since it is already referenced in this issue and use this #410 issue to discuss updates? Also, what should be the due date for this? Launch? 2 weeks before launch for testing?

@staceypark @jessfroe and @jamesmrollins 
I’d rather include #339 in the **document_tracker** rather than #410, which I believe is what we decided at our meeting yesterday. 

My rationale and preferred language for this is in the original issue #339, so I believe it will be more consistent with our edits yesterday and what I would said in documentation re: participatory learning, participatory research and participatory design, with this button being principally about  **participatory design,** albeit, with a partner option, which could lead to being a participatory learner or participatory researcher too.
