### ISSUE TITLE
Team 3 data UI for V21, 630 HCS has discrepant HF tab and AGG ModelParms for EBPsy.

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#416]
**BEFORE FILLING OUT THIS TEMPLATE, PLEASE ASSIGN THIS ISSUE TO THE BUG KANBAN UNDER PROJECTS (YES, EVEN IF IT IS A FEATURE. ALL ISSUES START IN THE BUG KANBAN FOR TRIAGE). --------------------->**

**Describe the opportunity**
Team 3 data UI for V21, 630 HCS has discrepant HF tab and AGG ModelParms for EBPsy.

**READ THIS FIRST**
- _A bug is a developed feature that has been working, that is no longer working._
- _A feature is a function, product or characteristic that requires research, design and development._

**If This Is a Bug, start with number 1 below, if a Feature, skip to number 7.**

**1. Please describe the steps to reproduce the behavior.**
a. Go to V21, 640 on the splashpage
b. Click on 640a0_mpd_team3_data_ui folder and sim ui folder 
c. Open both Excel files (data UI and their Team Data Table for Sim UI (model Parameters)
d. The values between the Data UI and Team Data Table for Sim UI (model Parameters) appear to be inconsistent with one another for EBPsy (at a minimum; noticed the discrepancey for EBPsy not sure if applies across other values).

**2. Please describe the expected behavior.**
If this team typically had 150 to up to 300 EBPsy visits (CBT for Depression), would not expect to see ~0% EBPsy in their ModelParams.

**STOP HERE. INFORMATION BELOW IS TO BE FILLED OUT BY WORKGROUPS AS PART OF TRIAGE AND WORK BREAKDOWN PROCESS**

**Estimated person hours to complete:**

**Key people (use @ assignment for people whose input will be necessary):**

**Key dependencies:**
Are there other tasks that need to be completed first?

**Constraints:**
Is there a resource constraint that may affect the development of the feature?

**Gantt chart needed? Attach link and/or screenshot.**

**Comment by holbrooa** [comment]
I think what happened here is just that you generated the model parameters immediately, and didn't bother with "get patient level data." I think that is what happened here because when I open the sim ui file, I see team blue's parameters, which I can duplicate on my end, but when I open the data ui file, it is full of stockton data. And indeed, stockton does EBPsy, but team blue doesn't. This kind of situation will happen any time a user hits one button but not the other, because the parameter button doesn't fill the data ui's tables and charts with that team's data.  That's confusing and fixable, but we decided to leave it this way so that the parameters can be generated as quickly as possible. I'm open to changing it, but that would need to come in as a new feature request at this point (albeit an easy one).

**Comment by lzim** [comment]
@holbrooa and @jamesmrollins 

FYI: @TomRust @branscombj @staceypark @dlounsbu 

@holbrooa will you please upload the consistent data UI and sim UI for Team 2 no later than 8:30AM, please.

THANKS 😄

**Comment by holbrooa** [comment]
I didn't quite get it in before 8:30, but I did get both files in before 9. So the sim ui folder has a new file with today's date - none of the parameters looked different there to me, except SP, which I went ahead and ran with ATS as the specialty team. The file in data UI I went ahead and ran for team3 and overwrote the file that was there. It now shows the right data, and corroborates that that particular team isn't doing EBPsy.  

If the bug is squashed, please close this issue at your leisure or tell me that I can.

**Comment by lzim** [comment]
Thanks @holbrooa!
