### ISSUE TITLE
Updated pcharts for SDS & SCRA slides

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#437]
What is the eta on the updated pcharts for the new EBPsy & EBPharm definitions?

We need those ASAP for:
- SDS for 5 TeamPSD presenters due tomorrow/Tuesday morning, **_but need to be reviewed by Lindsey today_** 
- SCRA presentation this Thursday for Lindsey & David 

When we discussed last Thursday, you estimated 3-4 hours for updating the pcharts. Is this still true and when can we expect these? As you can see, key materials with urgent deadlines need these updates.

**Comment by saveth** [comment]
Related to #424

**Comment by holbrooa** [comment]
Okay, the source code is re-run, and a new file is in the folder. @saveth will need to re-run her part. It isn't really different. And there's no ebpharm, of course.

**Comment by saveth** [comment]
Reran the pchart R code with minor changes based on the new data pull @holbrooa made. Emailed the results to @staceypark @lzim for review.

**Comment by saveth** [comment]
@holbrooa  please see @lzim comment:

Quoting from the updated slide deck:
•	“the numerator is unique visits where there was a template of interest
•	the denominator is the unique visits where there was a diagnosis of interest”
This is still underspecified for a scientific conference and I’m not sure what is going on related to the issues we discussed on Thursday 

See email for further details

**Comment by saveth** [comment]
@lzim  I'm not sure what was discussed earlier before I got pulled into updating the chart late this morning.

From my understanding, I thought the pchart based on the new data definition that we clarified and defined in the Meeting on Thursday wasn’t going to happen until after Andrew finish updating the EBP Reach query for the site selection. 

As far as I’m aware, his hope is to have the coding for that done for me by tomorrow for review and to implement my part before we validate the data together. Then he’s going to turn to part 1 of the pchart just updating the pchart code  based on the latest EBP reach definition for the R21 site, then part 2 updating the code for all R01/IIR sites. Issue #424 is meant to track all the changes needed for the revised pchart once the new EBP reach definition is coded and implemented.

**Comment by holbrooa** [comment]
Relevant issues are 421, 423, and 424. 
Lindsey, it seems like this deliverable for today is just not possible. If I had grasped all the things you wanted for today, I would have told you that we can't do it when we met on Thursday. That's especially true in this situation where Savet and I didn't even know about this.

As we talked about on Thursday, this research data/analysis piece is a team effort for me and Savet. I was hoping to be done with my part tomorrow (which is doubtful, having spent a chunk of that time on pcharts today), but it will require both of us carrying it forward this week. If you have deliverables and deadlines for that analysis, please let us know so that we can try to make it happen, or at least let you know what's doable. That's the kind of information I was hoping to put into the Kanban and/or Gantt to prevent all this frustrating expedited work and subsequent rework.

**Comment by holbrooa** [comment]
Let's move this discussion, if we need to keep having it, to the existing issues. Closing.

**Comment by staceypark** [comment]
@holbrooa Thanks for identifying the related issues! 
Note, when you ping people please use their github handle (i.e. @holbrooa instead of Andrew) and to link to issues, use the #. This way things are properly pingged and linked.
