### ISSUE TITLE
Mismatch between the list of sta6a that we pull and Jodie's list.

### ISSUE THREAD

**Issue by holbrooa** [lzim/teampsd#441]
**ASSIGN to PROJECT "issue_tracker"**  

**Describe the opportunity**
Mismatch between the list of sta6a that we pull and Jodie's list for comparator data.

**READ THIS FIRST**
- _A bug is a developed feature that has been working, that is no longer working._
- _A feature is a function, product or characteristic that requires research, design and development._

**If This Is a Bug, start with number 1 below, if a Feature, skip to number 7.**

**1. Please describe the steps to reproduce the behavior.**
a. Go to '...'
b. Click on '....'
c. Scroll down to '....'
d. See error

**2. Please describe the expected behavior.**

**3. Please provide a(n) screenshot(s) of the bug.**
If applicable, add screenshots to help explain your problem. You can use the Snip tool available in Microsoft Windows 10.

**4. Please identify your operating system and browser version.**
 a. Operating System: [e.g. iOS]
 b. Browser [e.g. chrome, safari]
 c. Version [e.g. 22][You can find version by clicking on "help" then "about Chrome/edge/firefox" to get version information.]

**5. If you are using a smartphone, please complete the following information, otherwise skip to number 6.**

**6. Additional context**
 - Which function, model or team data where you trying to use?
 - Provide any other relevant information that may affect this issue.

**FEATURE**

**7. How would you like this feature to work?**
Describe your expectations in terms of outcomes/products/behaviors.

**8. How urgent is this request? (Urgent/Not Urgent)**

**9. Why is this feature important to you?**

**10. Is your feature request related to a problem? Please describe.**

**11. Is there a deadline or other scheduled constraint driving your request?"**

**12. Additional context**

**STOP HERE. INFORMATION BELOW IS TO BE FILLED OUT BY WORKGROUPS AS PART OF TRIAGE AND WORK BREAKDOWN PROCESS**

**Estimated person hours to complete:**
8?
**Key people (use @ assignment for people whose input will be necessary):**
@saveth 
**Key dependencies:**
Are there other tasks that need to be completed first?

**Constraints:**
Is there a resource constraint that may affect the development of the feature?

**Gantt chart needed? Attach link and/or screenshot.**

**Comment by holbrooa** [comment]
From meeting:
529A4 does not exist in the division table, which is how we track visits to sta6a. There are a few visits assigned to 529a4 in the institution table, but they're assigned to 529 in the division table, so we capture them as part of 529.
Sites: 549GA, 549GB, 549GI do have visits but they are not getting pulled into Andrew's table 
Andrew is investigating 
549GA is being filtered out because of stop codes. They're using HUD/VASH/Telephone, which isn't in our list of stop codes to pull. It seems like the real visits might be tracked under 549QC

**Comment by holbrooa** [comment]
There's a new comparator dataset in the normal folder, where I've used a different method to pull sta6a. This captured some of the missing sta6a, but @saveth should rerun her part to see if there are any different ones missing now. There's also a new tab where I've put the results of my investigation of the various reasons places are missing.

**Comment by saveth** [comment]
Using the same code, there is a new validation data file in the usual folder. @holbrooa the new method of pulling the data removed 2 clinics from the mismatch list. The other 17 locations are the same sites from Jodie's list that we don't have a corresponding CDW data for. 

@lzim @staceypark  @jessfroe We do need that meeting on August 5 with Jodie to help identify how they're pulling the data and why ours won't match. Also, for most of these 17 sites, the Rurality status has been flagged by Jodie's team as Unknown.

**Comment by holbrooa** [comment]
Wait, removed 2? When I checked the sta6a against the list of mismatches you gave me, I found 9 of them. Does this mean there are new missing ones, as I feared?  Also, the main data point we're using Jodie's list for is the rurality, right? So if it's unknown there, then what are we even trying to do with that information? That's essentially saying the data are missing on both sides, so throwing them out should be a no brainer, unless I'm missing something.

**Comment by saveth** [comment]
@holbrooa I'm comparing the mismatch file I sent you in June to the one generated today. The list of sta6a remains the same except for 2 sta6a are no longer flagged as missing.  However, I don't understand what you mean by your flag for new institution join? 

Since most of of the 17 mismatch sites are ones you found as not having any visits in 2018 in either the institution or division tables, I think it's safe to drop them.

With regards to rurality, yes, we're getting that information from Jodie's data. There are a number of sites her team flagged as "Unknown". I need to see how many sites we have left that are coded as "Unknown" for rurality once we toss out sites without EBP data.

**Comment by saveth** [comment]
@holbrooa It looks like the list of sta6a for Missing CDW data you're using for the validation came from a run in early May, not the ones I sent in June. It's okay. I noticed that once I filter your file to ignore sta6a that had a "new institution join", then the list of remaining 17 sites looks like the validation list I ran this morning. The best part is your notes for those 17 sites indicated that those sites are inactive and did not have any visits for 2018, so we should definitely drop them from our dataset. 

Yay, we did good on our validation! I'm going to close this ticket since this issue is now resolved. :)
