### ISSUE TITLE
V21-Desktop issues

### ISSUE THREAD

**Issue by holbrooa** [lzim/teampsd#453]
This isn't an issue for us to work on, so it's not going into any of our trackers. More just an FYI and a place for me to update everyone on my status with an IT issue.

There was some kind of update to (I think) the OS that the virtual desktop uses, and it has broken some key applications. The full extent of what doesn't work is unknown, but specifically, skype doesn't work at all, and excel workbooks with VBA can't be opened. Obviously that's a major problem, as excel VBA is how the data UI and other tools I have built work.

I can go in to the VA here, which is what I did yesterday in order to complete the Data UI updates from my call with Lindsey (see https://github.com/lzim/teampsd/issues/440), but that isn't reliable, because I don't actually have a computer there. I'm just going in and finding a free computer in the offices of people I know, if there is one. 

I have tickets open with IT, and I'll update this thread with any developments.

@lzim @saveth @staceypark @TomRust @jamesmrollins @dlkibbe @branscombj @jessfroe

**Comment by lzim** [comment]
Thanks @holbrooa for this key update. What a mess!

This will impact @dlkibbe @branscombj and @dlounsbu most acutely because they are MTL Facilitators who have to rely on virtual desktop, as they also do not have a physical machine. It may soon impact @jamesmrollins as well.  It may also impact the TAS (even tomorrow) who frequently have to work remotely due to VA travel.

We have a folder in TeamPSD where we keep all HelpDesk tickets on the team. We do this to add redundancy, so that other team members can follow-up on the issue, if needed, rather than leave to just one team member. 
- The path is TeamPSD > help_desk_tickets

I expect that we all need to create help desk tickets for this issue (all who can, and are likely to be impacted). 

@lzim @saveth @staceypark @TomRust @jamesmrollins @dlkibbe @branscombj @jessfroe

**Comment by holbrooa** [comment]
Ok, I put copies of the auto-generated email in the folder under holbrook. Others who use the virtual desktop, are you having this issue too? It should be easy to check: just try to open skype from the virtual desktop. I get an error about the OS not being configured to run it.

**Comment by saveth** [comment]
My V21 remote desktop won't launch Skype either.

**Comment by holbrooa** [comment]
Error messages:

![SkypeError](https://user-images.githubusercontent.com/33842369/61071661-2db0e100-a401-11e9-84b3-0e1cbb431b29.PNG)
![ExcelError](https://user-images.githubusercontent.com/33842369/61071795-7bc5e480-a401-11e9-9d1a-21f6f3b2da55.PNG)

**Comment by holbrooa** [comment]
I think this is being worked on right now, because I'm getting kicked off Citrix, and seeing a weird login page when I try to reconnect. Fingers crossed.

**Comment by holbrooa** [comment]
Well, Skype worked for me just now. And I was able to open the data UI. 

...But then Citrix immediately disconnected on me. So that's progress, sort of.

**Comment by holbrooa** [comment]
Ok, I believe the issue is solved. I've been using the affected applications this afternoon, and haven't been disconnected again in a while. I'm going to go ahead and close the helpdesk tickets that I have open, and close this issue.
