### ISSUE TITLE
8/15 S05 Team4 team world group possibly corrupt?

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#485]
@jamesmrollins can you check out 640a0_mpd_team4_team?
People are having issues accessing this world even though they are mapped to it in both the "Groups" and in the "world team mapping"

Several issues I'm noticing:
1) Everyone should be a team lead in this team world for the purposes of this training, but it looks like some people got assigned to other worlds and roles. I know I specifically assigned everyone to World001 as Leaders so unclear what happened there.
2) When I try to reassign folks' roles and worlds, it just isn't letting me. As in I'm hitting "Save" and nothing happens after.

My current hypothesis is that the world is corrupted. Thoughts?

Note to self: Cheatsheets need to be updated on 1) how to spot for corrupted worlds and 2) how to fix

**Comment by jamesmrollins** [comment]
Hi @staceypark .  I am not having any issues logging in to this group/world (see below).  Everything seems in order.  So I can't support the corrupt world hypothesis.  

However, I was able to replicate the Epicenter "change player role" issue.  I did notice, that if I changed the role and clicked on save, then click cancel, the role does indeed change. I will report this to Forio.    

Can you be more specific as to what the issues were?  Are the logins incomplete? Is the play screen not building correctly?  Do they get the spinning wheels of death?  Did anyone check their inspect window for error codes on the Console tab? Is everyone certain they chose the correct group/world when they logged in (they do look very similar)?

![image](https://user-images.githubusercontent.com/30132017/63047078-88b67780-be88-11e9-91fa-2f804bd759ce.png)

**Comment by staceypark** [comment]
@jamesmrollins I also tried logging in and I get to the sim fine as well.
I think the folks experiencing issues with logging in had the issues due to being unable to map in the back. 

When I click "save" and then "cancel", the role does change. But when you refresh it, it goes back to blank/unassigned.

**Comment by staceypark** [comment]
@jamesmrollins Ok I found something interesting...
I think just World001 of that group is corrupted. I tried keeping everyone in the same group but in World002 instead. It saved fine and the login works fine (I spot-tested some folks).

I'm still not clear what causes this issue in the first place though?

**Comment by jamesmrollins** [comment]
@staceypark I got the following from Forio:

Thanks for the email.  I tried to edit the roles in the group you showed in the picture, and did not have problems.  Changing a role, then clicking Save worked normally for me.     (note that editing users simultaneously is fine).

**It's possible the browser got into an unexpected condition with the session -- try closing all browser tabs/windows then logging in again to epicenter.**

**Comment by staceypark** [comment]
@jamesmrollins Interesting because I tried it multiple times actually on multiple computers and the issue kept occuring. I'm not sure if they tried editing users into World001, but that's the only world that wasn't working for me.

**Comment by lzim** [comment]
@staceypark and @jamesrollins

Is this issue resolved and can it be closed?

**Comment by jamesmrollins** [comment]
@lzim I don't think we really got to the bottom of this.  It is something that happens very infrequently ( I think it has only happened once before).  However, the disruptive power of this issue is really high.  Therefore, I would like to thoroughly debrief @staceypark and then get back with Forio to see what we can come up with.

**Comment by jamesmrollins** [comment]
@lzim @staceypark I opened a help ticket with Forio to do a deep dive into this world corruption problem.  Will and Dave asked for an active failure, and I provided one yesterday.  I have not heard back but will monitor and follow up.  I will let you know when I learn something.  James

**Comment by lzim** [comment]
Thanks @jamesmrollins

**Comment by staceypark** [comment]
Related to issue #500 
(as discussed in WL meeting) In relation to this issue, in a world that only had one user, once the user is made inactive or assigned to a different world, that world "disappears". We can only make the world "reappear" by unmapping everyone and re-mapping them to start the number sequence again.

Because of this function, when we "suppress worlds" we need to both 1) make the user inactive in their group and 2) take them off the world-team-mapping crosswalk

**Comment by jamesmrollins** [comment]
@staceypark @lzim see below for Forio response.  

**BLUF:  We need to report any further corruption issues immediately.  We will attempt to isolate and rectify.  Also note Epicenter UI update pending.**

**From: James Rollins, Takouba**
I just went back to 640a0_mpd_team4_team to look, and see that world001 is now gone. We don’t have any other corruption issues so far. 
 
Which points to another issue, it seems when we make a single user-world inactive, and then reactivate, the world is gone from the dropdown (unless there are other users in the world).  Could that be related?

**From: David Berkman, Forio**

Yes. I’m not sure what specific call the UI is making to implement the behaviors. One of the options when removing users from a world is to delete the world if all users are removed. In this case, that makes perfect sense and is probably preferable. The world name has no particular meaning and leaving a bunch of empty worlds around is only going to become confusing. That said, I fully believe there’s a problem with the UI. It’s most likely a misunderstanding of the server responses and not actually database corruption (which would be extremely unlikely). I’ll shut down the alt server and next time this happens go ahead and call me, I’ll turn on the alt server, and we’ll try to catch the problem red handed.

This section of the UI is currently slated for an overhaul, which is mostly complete and just awaiting a dev’s time to finish up, so it should improve in the near term… sometime.

**From: James Rollins, Takouba**
Thanks for the update David. I will keep vigil for another instance of the problem and get with you straight away. 

Regarding the reuse of abandoned worlds, the only reason we would want to keep them open is because they are mapped elsewhere.  Since we “flattened” worlds and groups to help end-user navigation, we must map the group to the world in an xlsx so we can put a label up in one of the Sim UI web pages.  So it is an inconvenience if we have to remap the worlds every time.

**Comment by staceypark** [comment]
@jamesmrollins @lzim 
We will continue to report any corruption issues immediately.
I've also made a note in the S05 document card to update the sim UI cheatsheet with guidance on how to troubleshoot worlds (this isn't only caused by a world team mapping issue).
