### ISSUE TITLE
3/11 readme.md updates

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#495]
@lzim

1. https://github.com/lzim/teampsd/tree/master/issue_templates

- [x] Backup of Issue Templates for issue_tracker:
- [x] Backup of Feature Templates for feature_tracker:
- [x] Backup of Document Templates for document_tracker
- [x] Backup of Manscript Teamplate for manuscript_tracker

2. https://github.com/lzim/teampsd/tree/master/mtl_facilitate_workgroup/learner_see

- [x] Make sure that the links on the README.md file go to the current SEE guides in the folder.

3.  Change this 12-session plan link in mtl.how/demo https://forio.com/app/va/va-psd-demo/mtl_demo.html to go to mtl.how

**Comment by lzim** [comment]
@staceypark 

Are these team data items read to be closed or chunked out more?
Here’s my current list of related Maps and SOP tasks:
#495 Read.me Documentation updates.
#833 SOP Training Videos
#921 SOP Policy for Testing (not on OSF yet)
#1055 ZenHub - How to assign epic & Milestone
#1026 Documentation process

Still needed to set up SOP for:
- Community for Team PSD and other repos on GitHub (code of conduct, contribution guidelines, pull request template)
- Clean up stale branches, etc

**Comment by staceypark** [comment]
@lzim thanks for the list.

#495 Read.me Documentation updates - this is this card. moved out of the document_tracker, because this is a task card really. made a few minor edits to the top tasks with a pull request, but otherwise the tasks for these issues are done.

#833 SOP Training Videos - I'm adding this to teams_data as something that needs to be thought through and a plan proposed, as part of the ongoing training.

#921 SOP Policy for Testing (not on OSF yet) - I will ping James about this.

#1055 ZenHub - How to assign epic & Milestone - @anthonycpichardo please add this as part of the ZenHub steps.

#1026 Documentation process - this is a pull request and the task has already been done and closed a while ago.
