### ISSUE TITLE
 Create documentation on how to suppress worlds

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#500]
Document instructions on how to suppress worlds in epicenter

**Comment by lzim** [comment]
@staceypark, can you help @dlounsbu @branscombj and @tomrust with this today? 
Gayle should be only mapped to one Team 2 in PSy, I believe.

Also, since I get in very late on Thursday and will demo on Friday, will you please suppress my worlds (sounds funny out of context, huh?!?) to just Team 2 (team and ind) and Team 4 (team and ind)?

Thanks!

**Comment by jamesmrollins** [comment]
@staceypark the issue with the suppress inactive users function has been fixed.  You should be able to make users inactive, which will remove that group from the World Login drop down.  When the user is made active again, the group returns to the listing.  Cheers!  James

**Comment by jamesmrollins** [comment]
@staceypark with respect to the world disappearing when vacated by all users, I may be able to automate that with an API and do away with the xlsx altogether. That will make the world immaterial. I will advise after I speak with DEV.

**Comment by staceypark** [comment]
@jamesmrollins When you say do away with the xlsx altogether, do you mean we won't need a world-team-mapping xlsx?!?!?! 😱 🤞

**Comment by jamesmrollins** [comment]
@staceypark YEP!

**Comment by staceypark** [comment]
@jamesrollins 

@lzim and I discussed the trade offs between the Event Name option and the API option and decided to do the Event Name option.

We decided to use “Individual World” as the Event Name for all individual worlds regardless of the team.

Question - what implications does this have worlds that are already set up once implemented?

**Comment by lzim** [comment]
@staceypark and @jamesmrollins 

Is this something that needs documentation in **document_teams**and coverage in the HQ admin training?

**Comment by jamesmrollins** [comment]
@lzim I have covered group creation, end user upload and end user world assignment in the Epicenter Admin Training.  Since we don't do world-team-mapping.xlsx anymore, it has simplified this task.

**Comment by lzim** [comment]
@jamesmrollins 

Thanks! We may need to cover this with the facilitators again too, not just Rita and Jenn.
As, I’m not sure I’m tracking all of this and it will be helpful for facilitators to understand.

@staceypark from the title “Create documentation on how to suppress worlds.” I thought this was about how facilitators can show only the team the working with in their drop down, rather than the giant laundry list of teams they are mapped to (i.e., suppress worlds in the dropdown).
- Is that right?

**Comment by staceypark** [comment]
@lzim yes that is right.

> @staceypark from the title “Create documentation on how to suppress worlds.” I thought this was about how facilitators can show only the team the working with in their drop down, rather than the giant laundry list of teams they are mapped to (i.e., suppress worlds in the dropdown).
> 
> * Is that right?
