### ISSUE TITLE
Wishlist Table for MTL v1.5

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#57]
Hello Everyone,

Please see the MTL 1.5 wishlist table James created from our list, available here: https://github.com/lzim/teampsd/tree/master/mtl_1.5

Provide clarification as necessary in this thread below

Thanks!

Lindsey

**Comment by dlounsbu** [comment]
For 'wish list' table row three "Please clarify the italicized text.  Not sure where in the simulation this would be done" --

DAVID: It may not be possible, but can the  dropdown list of variable names that is shown under each graph/figure output window be amended so that the name starts with the model abbrieviation (CC, MM, PSY, or AGG)? If so, I would expect that an alphabetized listing would sort variable names by model, so all the CC variable names would be grouped together. Does this make sense? I think it would make it easier to find the variable you want, since you could focus on just the listing of variables for given model. It think this would only be work it if what is being displayed is a 'look up' table of labels that map to actual variable names. Hope this clarifies my request.

**Comment by branscombj** [comment]
I could clarify #19, Create an Expanded Outputs tile that can be resized or dragged across multi-screen set-ups, to allow for reference back to main UI, without having to close the tile. This means, Add a drag (and maybe resize) functionality to the current Expanded Outputs tile, which is already a pop-up window so might be amenable to it.

**Comment by branscombj** [comment]
#15 The numerical value in the box next to an experiment slider should always reflect where the slider sits; and the slider should start at and reset to the position of the base case.

Right now, the slider sits at the far left of the bar for all default settings - whether they are zero or a non-zero base-case. It would be preferable (to me) for the slider to sit at the place on the bar that represents the numerical value it is contributing to the modeling simulation - even if the box to the left still reads BC when it's in the base case position. Better would be for the box to contain the BC value rather than the letters BC. Users will be taught that resetting always returns settings to their default values (zero or base case). Does this make sense? What's hard, for example, is getting that you may have to move the slider to the right to test a value that is LOWER than the base case. And also just believing that the slider is at the number up in the table when it looks like it's at [zero or minimum].

**Comment by branscombj** [comment]
#9 is new to me but I would wholeheartedly second the automatic naming of simulation runs via a concatenation of metadata reflecting experimental conditions!!!

**Comment by branscombj** [comment]
#6 This would require a significant re-design of the UI model view to take into account the aspect ratio of screens. 
Is there not a way to scale the view in a constant aspect ratio regardless of the local monitor's aspect ratio? Thinking it would look like a window on the screen, with screen background outside it on the relatively larger dimension of the monitor.

**Comment by jamesmrollins** [comment]
Hi Jane,
# 19 is clear to me.  I will refer to the development team.

James

James Rollins
Managing Partner
Takouba
www.takoubasecurity.com
(425)919-5153

**Comment by jamesmrollins** [comment]
Hi Jane,
Regarding #15, the problem is the slider and the number in the box are dependent.  So when “BC” is chosen, the actual number being passed by the slider, is actually a negative number or zero, which signals the model to use the base case number.  So I am afraid this feature is not possible.

James

James Rollins
Managing Partner
Takouba
www.takoubasecurity.com
(425)919-5153

**Comment by jamesmrollins** [comment]
Hi David,
Regarding #4, my confusion is because when you are in a given model, you should only see variables that support that model in the output chart drop downs.  For instance, if you were in the CC model, you would only see CC variables. However, the first part of #4, providing advanced file management, where a user can sort and filter is pretty clear and I will see if we can accommodate.

James

James Rollins
Managing Partner
Takouba
www.takoubasecurity.com
(425)919-5153

**Comment by dlounsbu** [comment]
Makes sense. I was in AGG when that wish occurred to me!

David Lounsbury
Sent from my iPhone

On Jun 4, 2018, at 7:29 PM, jamesmrollins <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi David,
Regarding #4, my confusion is because when you are in a given model, you should only see variables that support that model in the output chart drop downs. For instance, if you were in the CC model, you would only see CC variables. However, the first part of #4, providing advanced file management, where a user can sort and filter is pretty clear and I will see if we can accommodate.

James

James Rollins
Managing Partner
Takouba
www.takoubasecurity.com<http://www.takoubasecurity.com>
(425)919-5153

**Comment by jamesmrollins** [comment]
Hi David,
I went into Agg to investigate, and now I see what you are saying.  The service descriptor comes after the variable name.  If I am now understanding you correctly, you would like the services descriptor to precede the variable name, and then list alphabetically.  If this is correct, then I will put it in as a separate “wish” from the file management “wish.”

James

James Rollins
Managing Partner
Takouba
www.takoubasecurity.com
(425)919-5153

**Comment by lzim** [comment]
Closing this issue!
