### ISSUE TITLE
28 Aug: SP: Upload and Test New Model

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#587]
**1. Add description:** 
Updated SP Model not running correctly in TEST.  Appear to be not handling time correctly.  May be related to report_offset function.  Model also throws a floating point error when using Andrew's OSF reference file (which contains unlikely zero values).

**Time value incorrect in sim ui console**
![image](https://user-images.githubusercontent.com/30132017/63741788-49563680-c84b-11e9-917e-a49226f24295.png)

**Floating point error**
![image](https://user-images.githubusercontent.com/30132017/63741874-9d611b00-c84b-11e9-9b61-2544f11efba8.png)
 
**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_6 hrs modeling, 4 hours sim_ui, XX hours Data UI

**Edit the due date (if necessary)**

**Comment by staceypark** [comment]
@TomRust @holbrooa have you had a chance to test this new version of SP? If not, we want to make sure to test it before Friday, so that we don't run into any surprises during the Friday MTL session.

**Comment by holbrooa** [comment]
@staceypark @jamesmrollins I haven't had the chance add code to the SP parameter query to do anything about the zero wait times. On the data end, here's what's happening:

I calculate almost everything in **days**, then convert to weeks for the models, then round to our chosen level of precision for each parameter.  Using that system means that **"same-day" visits** (actually pretty common in real life for the start of a new care episode!) **are indeed "zero wait."** I even mention in the description in column E that walk-ins get captured as zero wait as well.  We decided to round these wait time parameters to one decimal, so if those zero waits are causing problems on the model end, then we need a floor that just forces it to be 0.1 instead of 0. 

@TomRust @lzim I think we've already implemented floors and/or ceilings on the Vensim side for SP for other parameters, right? Is this one any different? If a team is doing a lot of same day intakes, I think it's pretty gratifying to show them a zero wait time parameter. Then if it needs to get fudged for the model, I can just say so in column D, as we did for time to improve (D40), where it says "...In the model, this estimate is limited to a minimum of 12 weeks."  Anyway, if you decide you'd rather implement the floor on the data side, I can do that.

Prior to some kind of floor being implemented, the way to avoid this problem is to look at your SP parameters and if there are any zero wait times for new care episodes (C34-36) then just manually change it to a 0.1 before uploading the file.  I think that's what @TomRust did for a file this week.

**Comment by lzim** [comment]
@jamesmrollins 

We added the **Master Crosswalk** label 

- @TomRust and @holbrooa implement the floor and details above in SP, we need it tracked.
- Add @TomRust to the **quant_workgroup** meeting on 9/5 to review any remaining "floor" issues.

**Comment by lzim** [comment]
@TomRust and @holbrooa 

Based on our call this morning, does this go back to development -> and testing for the **model workgroup?**

- Based on decisions at this morning's workgroup leads meeting this can be closed as long as the documentatino is tracked i nthe **document_tracker**, but we need to meet on 9/5 to talk about implementing "floors" on the model side, which is why I think it goes back to **development.**

♻️

**Comment by lzim** [comment]
@TomRust and @lzim met about this on 9/5: https://meet.lucidmeetings.com/lucid/meeting/226166

- [ ] Tom will follow up with the questions we have for @holbrooa when he's back in the office
- [ ] Lindsey will consider this with Andrew at the Monday AM Workgroup Leads meeting to see where it fits with other priorities.

FYI: @staceypark

**Comment by TomRust** [comment]
new version that fixes this corner case sent to James.

**Comment by staceypark** [comment]
@TomRust @jamesmrollins please use pull requests to send out updated models instead of emails

**Comment by staceypark** [comment]
@jamesmrollins is testing new models right now & related to #401

**Comment by staceypark** [comment]
models updated at mtl.how
