### ISSUE TITLE
(Due Date to be updated) prototype Data UI: Use PC diagnoses from Jodie for SP instead of using stop codes

### ISSUE THREAD

**Issue by holbrooa** [lzim/teampsd#596]
**1. Add description:** 

Integrate Jodie's MH diagnoses instead of using stop codes to track patients transferring to/from PC for the SP model.

<< Paste screenshots here>>
 
**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_
16
**Edit the due date (if necessary)**

**Comment by holbrooa** [comment]
The plan is to have just the prototype done for the quant meeting with Tom, so that we can look at some preliminary results and get Tom's perspective on any potential issues. Then, with both this PC change and the zeros nailed down (hopefully that's just documentation on the data UI end), the data UI can be wrapped back up and I'll push a new version with both changes.

**Comment by staceypark** [comment]
- [ ] Need to rerun Team4 data after this PC change is implemented

**Comment by holbrooa** [comment]
I've been getting buggy results for this. I'm hoping to have it all sorted tomorrow. Since you have a specific team you want to rerun with this change, perhaps I can use that as part of my testing. We can run it later this week and see what the results look like.

**Comment by lzim** [comment]
Okay, thanks @holbrooa!

- [ ] **Coordinate with @TomRust and @staceypark** to test **Team 4** on **9/5 prototype Data UI: Use PC diagnoses from Jodie for SP instead of using stop codes #596**
- **NOTE**: _This testing should be done by COB Thursday, if we want to prepare for using any updated data for session 7 the following week._
- I won’t be able to test, I’ll be at a conference
- _We may **NOT** be able to use this data for Team 4 at all_, as we are too far into using the PCMHI stop codes and now on session 7 with this testing team

**Comment by lzim** [comment]
@holbrooa @TomRust @staceypark 
Cross-ref #648 Floors point 2.

**Comment by staceypark** [comment]
done and implemented in data UI that @holbrooa will hand off FRE14 aka version Nevermore
