### ISSUE TITLE
9/4 PSY: Patients in Care >3mo's stock value changed

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#612]
1. @branscombj & Claire who are facilitating Team 2/PSY this week noticed that the Stock value for **Patients in Care >3 Months** in PSY went from 80 patients on Wednesday to 95 patients today. We did not change the data file at all either on the front or the back end on the sim.

![image](https://user-images.githubusercontent.com/31089501/64054568-6b4a0480-cb3c-11e9-9357-06380021f330.png)

We will continue reviewing systems stories next Wed 9/4 so would be great to either fix or at least get an explanation before then.

FYI: @lzim @dlkibbe @dlounsbu @jessfroe 

**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_

**Edit the due date (if necessary)**

**Comment by jamesmrollins** [comment]
@staceypark which model parameters file? Was this upon start up or after a run?  If a run, was it base case or an experiment?  If an experiment, was it fresh or a reload from a previous experiment?  If fresh, what were the settings?  If previous, what is the experiment name?

**Comment by staceypark** [comment]
file name:  640a0_team2_2019_08_01.xlsx
no runs. they should have "saved" to keep the text but not "save & reset" since they haven't run basecase yet.

**Comment by jamesmrollins** [comment]
@staceypark , @saveth discovered that Appointment Supply (75th Percentile) was incorrectly mapped last week to C35.  It was changed to C36 last night, resulting in a higher stock value for Patients in Care for more than 3 Months. The value in the sim is consistent with the value in the client version of Vensim.

**Comment by staceypark** [comment]
@jamesmrollins thanks for getting to the bottom of this! In the future, please alert the facilitators when these types of changes are being made overnight, so that we know to expect potentially changing values.

 @branscombj , @TomRust , @dlounsbu , @lzim @jessfroe @dlkibbe 
I added the update on this to the Wednesday facilitation meeting so we can let the TAS know.

**Comment by lzim** [comment]
> @jamesmrollins thanks for getting to the bottom of this! In the future, please alert the facilitators when these types of changes are being made overnight, so that we know to expect potentially changing values.

> @branscombj , @TomRust , @dlounsbu , @lzim @jessfroe @dlkibbe
I added the update on this to the Wednesday facilitation meeting so we can let the TAS know.

@jamesmrollins thanks for tracking this down
@staceypark is SO right! 👌🏽

In **lean** terms, finding an incorrectly mapped variable, is a **stop the line, andon pull.**

- In our _MTL_ case, it means an alert has to go out ASAP, so that training doesn’t continue until folks are 1) notified of the issue, and 2) notified of the fix.

Team PSD facilitators, TAS co-Faciliators (and soon, teams!) are in the Sim UI now prepping any time of day, any day a week based on these values. 

We prepped on the other Team 2 PSY values last week and this week for a total of ~14 scheduled hours of training, plus the TAS folks told me they were studying.

I really hope GitHub can help us rapidly respond as necessary to 1) prevent issues, and 2) slow down/stop when needed to keep _Modeling to Learn_ quality high!

Thanks, in advance, everyone!
🤙🏽

**Comment by lzim** [comment]
@staceypark and @jessfroe

If this weren’t a holiday weekend, I would recommend an immediate update the next AM and NOT wait until Wed.

- We added all the TAS to GitHub, but they will need more **training** for them to catch GitHub this way.

FYI @tomrust @branscombj @dlounsbu @dlkibbe

- We may need to implement this in the **team_tracker** as an **andan_alert** for that week’s team meeting or something??

**Comment by jamesmrollins** [comment]
@lzim I notified @saveth @TomRust and @holbrooa about the root cause of the problem.  I only corrected it, and notified the same, when no one had acted on it at 11pm last night.  

I agree an ANDON alert would be effective - Indeed, we need to create an ANDON list add that to the policy and communicate it to everyone.
