### ISSUE TITLE
wk3 export_tt_check

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#623]
**Andon Policy for Immediate TEAM ACTIONs (pre-launch)**

1. Contact HQ (Lindsey & Stacey; Stacey can make a call if Lindsey is unavailable)

2. Call an immediate meeting to identify and implement the fix.

3. Team PSD will conduct a post-mortem to manage specific learner impacts team-by-team.

**Comment by anthonycpichardo** [comment]
Step 1: Run The Code (If the code runs, logic is still functional). 

- Read error messages if the code does not run to find root cause. Get Export from mtl.how/sim to make sure we have latest data. Mtl.how/data and upload to folder directory with TT report and to SIM (Run fake tests and export)

Step 2: Have open Compiled output from R, Master Crosswalk, SIM, Model Parameter. Checking for consistency between all 4 naming conventions/formatting.

**Comment by staceypark** [comment]
@anthonycpichardo I think we should close this until the automation stuff is complete.
This document card is correct for our current state. We can reopen it and edit once we have new stuff.
