### ISSUE TITLE
nov_epic story13 & story4 Review VA GitHub Guides Bring Data UI QA into GitHub

### ISSUE THREAD

**Issue by staceypark** [lzim/teampsd#627]
**3.5.3.1 Andon Alerts**

**Team PSD uses Andon Principles to manage bug reports and triage the issue as soon as possible.
Team PSD follows three core ideas when addressing an andon.**

1. **Scope** - Analyze the impact of the issue and determine who the critical users are that need to be informed.
2. **Alert** - As soon as scoping is complete inform the impacted users of the issue and how to track it’s resolution. Providing work arounds if needed.
3. **Communicate** - Until the issue is resolved maintain open lines of communication and provide consistent status updates.

Move the current **Chapter 11 Quality Assurance** to **Chapter 3 Standard Operations 3.5.6 Quality Assurance Roles & Responsibilities**

**Team PSD Manual**
https://lzim.github.io/teampsd/11-track-issues-features.html
https://lzim.github.io/teampsd/3-standard-operations.html

**Decision: Create QA Templates for Research and Operations**

**_DEV QA Entails these "Check early" Feature Development functions:_**
- [ ] 1. user hypotheses  (week 1) 
- [ ] 2. MVPs  (week 2)
- [ ] 3. user stories verified (week 3)  
- [ ] 4. sign off on user acceptance requirements (week 4)
- [ ] 5. DEV QA sets up the cards for all QA phases in the epic.

**Still Need automation**

**Definition of QA phases for a resource is defined by feature development QA process.**

**Definition of a bug:** A feature not working "as intended," where "as intended" means you go back to the guides, documentation, and evidence of what the feature functionality intended.

**Research - Grant Documents**
- [ ] DEV QA - @anazariz 
- [ ] TEST QA - @dkngenda @staceypark 
- [ ] PROD QA - @lzim 

**Operations - _Modeling to Learn_ Guides**
- [ ] DEV QA - @anazariz 
- [ ] TEST QA - @dkngenda @lijenn 
- [ ] PROD QA - @staceypark @lijenn

**Comment by ritahitching** [comment]
@holbrooa Any update on the andon checklist for testing the Data UI?

**Comment by lzim** [comment]
@anthonycpichardo 

Changed the title to **wave1** instead of a 4/10 due date.

**Comment by lijenn** [comment]
[still in progess, not final yet]

 ### Data UI - QA Testing 

Standard Testing Guidelines:
1. Test folders and files should always be created on mtl.how/data, the platform where our data is hosted.
We are using our own VISN and Facility to test the data ui features and bugs.
2. Testing should not only be limited to just testing the fixes and features, but also their interaction with the rest of the buttons and existing features in the file.

ClinicalSelection Tab:
- [ ] Make clinic selection filters in Columns C-I exactly how it was in the data ui file where the bug was originally identified in.
- [ ] 
- [ ] Check if clinic selections were made in the SPReferrals tab
- [ ] Click on "Get Patient-level data" and the data ui file will be come unresponsive as it queries
After patient-level data is pulled:
- [ ] Click on B5 to "Remove All" the clinics added to Column A for the data pull
- [ ] Click on B3 to get back the clinics that were just removed. You should see the same clinic list that we just pulled (refer to the selections in Column C clinic name).

After a team data table is created
- [ ]  table name files is in Data UI
- [ ] Can save the team data file to the team_data_table folder on SharePoint
- [ ] 


SPReferrals Tab:
- [ ] 

Data Tabs:

dataEnc Tab:
dataDiag Tab:
dataHF Tab:
dataMeas Tab:

Viz tabs:

vizEnc Tab:
vizDiag Tab:
vizHF Tab:
vizMeas Tab:

### Data UI - QA Propagation 

When new features and fixes (including ANDONs) have underwent testing and is signed off:
- [ ] 1. The master data ui file should be propagated to the most urgent _MTL_ sites/facilities first (determine using _MTL_ Help Calendar)
- [ ] 2. Then, propagate to the other MTL sites/facilities that are active or we have previously met with (Use EES excel table in Facilitate Workgroup channel and/or MTL GANNT on LucidCharts).
- [ ] 3. Lastly, propagate to the rest of the nations site/facilities.

**Comment by lijenn** [comment]
@anazariz Please provide documentation on how to get the Developer tab in the excel file.

**Comment by lzim** [comment]
**Discussed at team_time 8/10** 
Cross-ref #626 (But, may be a closed card soon, if there is no longer a facility and data distinction in Power BI).

@staceypark 
@lijenn 
@dkngenda 

**We want to follow our QA approach for Research like this:** 
https://lzim.github.io/teampsd/11-track-issues-features.html#contribute-to-an-r-notebook

**- VA GitHub - Recommends Enterprise GitHub if you're working directly with the EHR data**
https://department-of-veterans-affairs.github.io/github-handbook/

**Comment by lzim** [comment]
Discussed at **support_workgroup** on 10/27.

Reviewing branching structure or DEV > TEST > PROD approach to Power BI.

Thought this may be on @jamesmrollins plate for **Story 13** but we were not sure if it is this **Master Document** card or described also as a issue task.

**Comment by jamesmrollins** [comment]
FYI @lzim @staceypark @lijenn @jeffhoerle @dkngenda 

## BLUF

PowerBI offers a proprietary [deployment pipeline schema](https://docs.microsoft.com/en-us/power-bi/create-reports/deployment-pipelines-get-started) that has many of the same features as GitHub.  

## Features

1.  Can assign users to a pipeline and assign limitations.
2.  Pipelines are divided into stages.
3.  Can selectively deploy items from stage to stage.
4.  Can employ deployment rules such as automatically pointing the data source from a test database to a production database upon deployment.
5. Can preset deployment settings to "define how content is updated whenever you deploy to this stage."
6. Stage-to-stage metadata comparison - color indicators that highlight differences in the comparison.

![image](https://user-images.githubusercontent.com/30132017/139947448-f437808b-8e93-4149-9222-e8f7ceac38b0.png)

## Drawbacks

1.  All of our other content is on GitHub and follows a similar DEV/TEST/MASTER schema.
2.  This will create a new pipeline and need to learn a different versioning platform. 

## Discussion

1. The .pbx file created by PowerBI is a proprietary, compiled, very- large binary file.
2. The capabilities of GItHub and PowerBI are similar.  It does not appear we would bypass any major GitHub feature (such as actions or other code reviewer) by using the PowerBI pipeline.
3. There are close similarities between PowerBI Pipeline and GitHub, which may make training easier.
4. Because PowerBI is proprietary, it would be advisable to stay on the platform for all of our needs.

**Comment by lzim** [comment]
Pick this up at **12/1 overflow meeting wk5 nov_epic**

- [ ] 1. @jeffhoerle is working on the PBI DEV/TEST/PROD.
- [ ] 2. Review the interoperability w/GitHub after 1 is sorted.
- [ ] 3. Finalize any remaining adaptation of our QA documentation and procedures.
