### ISSUE TITLE
PSY model diagram question

### ISSUE THREAD

**Issue by branscombj** [lzim/teampsd#637]
Claire's question today makes me wonder if it's a bad idea that the last stock - pts > 3 months - is not in the default view. I wonder if we should show the stock and flow of that in the default view, but still have the causal arrows come up in the complexity reveal?
@lzim @TomRust @dlkibbe @dlkibbe @staceypark

**Comment by lzim** [comment]
@branscombj 

We can talk about this on Monday during the Workgroup Leads meeting.
But, I am...

1. very reluctant to re-open design changes of any kind at this point (for many reasons, esp. something like this), and 
2. believe that the actually action of “revealing the complexity” serves exactly the function it’s supposed to serve in session 06:  It reveals what’s getting in the way, the system dynamics of the team’s problem.

Since the user interface is functioning to reinforce this with the reveal, I do NOT believe it should change.

**Comment by staceypark** [comment]
@branscombj we created a new column in the feature tracker called "future_releases" where we will collect ideas like these that are not "essential fixes" to hold off until future releases.

Our priority right now is getting to a robust freeze on documentation, materials, and user interfaces to get ready for launch.

**Comment by branscombj** [comment]
> @branscombj we created a new column in the feature tracker called "future_releases" where we will collect ideas like these that are not "essential fixes" to hold off until future releases.
> 
Good idea! For this specific idea, though, I think @lzim has explained good reasons against it, so I'm fine with that. Thanks, @staceypark !

**Comment by lzim** [comment]
Okay, let’s do this:

1. I’ll close this specific issue and remove it from the new **future_releases** column of the **feature_tracker**
2. We’ll keep this new column, move to a release-based model according principles @staceypark outlined above:
> Our priority right now is getting to a robust freeze on documentation, materials, and user interfaces to get ready for launch.
