### ISSUE TITLE
4/30: Add Experiment Alternative 3 to Control Panel and Add Multiple Alternative Experiment Sankey Charts

### ISSUE THREAD

**Issue by branscombj** [lzim/teampsd#744]
**1. Add description:** 
Is it possible to have a past run selected from the Control Panel show up in the Sankey, or can we only ever compare Current (before resetting) and Base Case?

<< Paste screenshots here>>
 
**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_

**Edit the due date (if necessary)**

**Comment by branscombj** [comment]
I'm now hearing @lzim say no - you can only see a Sankey for an experiment when you're at the end of running it. So unless this is something that can go in the "perhaps in some future sim update" list, feel free to delete this.

**Comment by lzim** [comment]
@jamesmrollins 

Is there a way to pull up prior run Sankeys rather than just current run and Base Case?

If it is possible,  I would put this in **future_release**

**Comment by staceypark** [comment]
@jamesmrollins believes this will likely be feasible. as such, putting in future_release.

**Comment by jamesmrollins** [comment]
### Requirements Testing and Validation Checklist

**Problem Statement:** The current Sankey chart pop up only allows a comparison between base case data and the current experiment.  In the main Expanded Outputs popup, users can select any previously saved experiment as a basis for comparison (including base case) against the current run in charts in the Results Dashboard . 

**Requirements**

**1.0  Provide a means to compare up to 3 Sankey charts and bar charts for saved experiments.**

- [ ] 1.10  Provide a means to select Sankey results to display using the Alternatives dropdowns from the Control Panel of the Expanded Outputs pop-up.

- [ ] 1.20  Provide a revised pop-up that shows the current run and 2 alternatives selected from control panel.

- [ ] 1.30  The pop-up will be able to float over the browser window.

- [ ] 1.40  The pop-up will remain open, even if other outputs pop ups are closed.

**2.0  Provide 508 compliant functionality**

- [ ] 2.10  Provide a logical tab-order.

- [ ] 2.20  Provide a 508 appropriate color contrast scheme

- [ ] 2.30  Provide a table view of charts where technically feasible.
 
   - [ ] 2.31  Provide table titles

   - [ ] 2.32  Provide header row and column labels.

**Comment by lzim** [comment]
@jamesmrollins @branscombj 

Discussed at Sim UI Workgroup Meeting on 4/9/2020:
- Keep in mind a dependency on the tt report.
- Let's not add a table now.

Lindsey likes the idea of adding drop-downs to compare the base case Sankey against all the experimental runs.

**NEXT STEPS: The _MTL_ 12 session plan encourages review of 3 experiments against the base case in this sequence:**

Session 7 - basecase
Session 8 - experiment 1
Session 9 - experiment 2
Session 10 - experiment 3

**James will check on whether Forio & Dev can add:**
1. An additional drop-down in the control panel to reflect 3 alternative experiments, not just two.
2. The output charts would compare 4 total lines (bc, exp 1, 2 & 3).

_If we can switch to see all 4 at once (something we already we already implemented in the tt_reports_ then let's proceed to make the change in the Results Dashboard of the Expanded Outputs section and in this Sankey for PSY._

**Comment by lzim** [comment]
**#744 - "Alt 1" vs. "Exp 1" - Considered, but decided to release to DEV.**
- Does it make sense for the Sim UI to continue to use the language of "Alternatives" (e.g., "Alt 1," "Alt 2"), and all our MTL guides use "Experiments" (e.g., "exp 1" "exp 2")?
- Current Run is always black; When you want to pull up the base case, it may be "Alt 2."
- Future uses: In the future, won't be bound to the MTL guides, so exp 1, exp 2 won't be as meaningful as the "Alteratives" defined by specific decisions are included in the name based on our save dialogue.

**DECISIONs re: #744**
**- Keep use of "alternatives" (not experiments in Control Panel) as it is.**
- Proposal to use "alt a," "alt b" and "alt c." Rejected because it is helpful to use "Alt 1" and Exp 1"
- Base Case - Current Run create problems in changing the Sim UI and are better handled by learner/facilitator.
- Also released for Development

**Comment by staceypark** [comment]
4/27 WG Leads meeting decision:
@jamesmrollins will provide @branscombj with a checklist to review and close this issue.

**Comment by jamesmrollins** [comment]
##Test and Validation Document

**Test and validation assignee:** @branscombj 

**Test case document available here:** No test case document is provided

**Please check off the requirements as they are validated:**

- [ ] 1.0 The Expanded Outputs control panel supports the comparison of up to 4 Sankey charts and bar charts for saved experiments (the current experiment and 3 alternatives).
   - [ ] 1.10 Supports the selection of Sankey results to display using the Alternatives dropdowns from the Control Panel of the Expanded Outputs pop-up.
   - [ ] 1.20 Provides a revised pop-up that shows Sankey Charts from the current run and 3 alternatives selected from control panel. **(Please note that the current run will not display results until it is run to the end.)**
   - [ ] 1.30 The pop-up floats over the browser window. 
   - [ ] 1.40 The pop-up remains open, even if other outputs pop ups are closed.
   - [ ] 1.50 Grammar, spelling and punctuation of titles are correct.

- [ ] 2.0 A 3rd Experiment Alternative Chart Functionality exists in all modules.  **Please note that the tester will require at least 3 saved alternative experiments to test this functionality.**
   - [ ] 2.10 A dropdown for third experiment alternative exists and works in the Expanded Outputs Control Panel of:
       - [ ] 2.11 CC
       - [ ] 2.12 MM
       - [ ] 2.13 PSY
       - [ ] 2.14 AGG
       - [ ] 2.15 SP

 - [ ] 2.20 The third alternative has a chart line reflecting the experimental values to charts in Results Dashboard.
   - [ ] 2.21 Chart line color is indicated in the chart legend.
   - [ ] 2.22 Chart line color is VA Vibrant Green, #78BE43

**Comment by branscombj** [comment]
@jamesmrollins Checklist point 1.50: For consistency with Control Panel and guides, please call the top Sankey chart "Current Experiment". (The only place 1 word is used is in the chart legends, where there's no room for 2, and there it's "Current".) Thanks!

![image](https://user-images.githubusercontent.com/29778290/80400030-35eee580-8888-11ea-8e6b-9cdf04a9dfc1.png)

**Comment by branscombj** [comment]
@dlkibbe Would you be able to log in to the TEST version of the sim UI and try the new multi-run comparison feature in the CC, MM, AGG and SP modules, and check them off above if everything looks good? I already checked it in PSY.

**Comment by dlkibbe** [comment]
Working on it @branscombj

**Comment by dlkibbe** [comment]
@jamesmrollins testing in MM model; when trying to save a sample run I found the Engagement Duration maximum number is 100 and in the data file I was using [583ge_wl_bhip_2019_04_14.xlsx] Engagement Duration (median) (wks) for AUD, DEP, OUD was 111, 136 and 182 weeks respectively. Should the max number be higher?

![image](https://user-images.githubusercontent.com/31182258/80542784-aa568100-897b-11ea-9264-cd6c7afe07b3.png)

**Comment by jamesmrollins** [comment]
> @jamesmrollins testing in MM model; when trying to save a sample run I found the Engagement Duration maximum number is 100 and in the data file I was using [583ge_wl_bhip_2019_04_14.xlsx] Engagement Duration (median) (wks) for AUD, DEP, OUD was 111, 136 and 182 weeks respectively. Should the max number be higher?
> 
> ![image](https://user-images.githubusercontent.com/31182258/80542784-aa568100-897b-11ea-9264-cd6c7afe07b3.png)

Hi @dlkibbe .  It probably should, but the number range is not dynamic - it is hard coded.  We will likely have to put in a bug report and fix this.  Although, it would be good to get a better idea of the possible range of values that can occur in this variable. I think this is a separate issue from #744 and I will open a card up in the bug tracker to manage it.

**Comment by jamesmrollins** [comment]
Hi @branscombj - This has been corrected.

> @jamesmrollins Checklist point 1.50: For consistency with Control Panel and guides, please call the top Sankey chart "Current Experiment". (The only place 1 word is used is in the chart legends, where there's no room for 2, and there it's "Current".) Thanks!
> 
> ![image](https://user-images.githubusercontent.com/29778290/80400030-35eee580-8888-11ea-8e6b-9cdf04a9dfc1.png)

**Comment by dlkibbe** [comment]
General Feedback: @jamesmrollins @branscombj 
1. I have tested CC, MM, Agg & SP. In each, the 3 experiments plus the current simulation are visible.
2. If possible, Sankey tips should only appear in PSY module.
3. AGG Model - Review Rate, "i" information - the end parenthese is missing in... (pts/wk
4. MM - See screen shot - 94880.91 MM appointments seems excessive. Does the "i" information need a timeframe? "i" information reads, "The total number of medication management appointments **on the calendar**. (appts)"
![image](https://user-images.githubusercontent.com/31182258/80649067-544b1180-8a3f-11ea-85c4-126617eca35f.png)

**Comment by jamesmrollins** [comment]
Hi @dlkibbe.  Yes, 94K appointments does seem over the top.  But that is what the Vensim model is returning.  I don't think the VA has limits on appointments, since they can be booked way out, so that may be the true effect of unbridled appointment making.  Perhaps @TomRust can shed some light?

![image](https://user-images.githubusercontent.com/30132017/80668192-0d1c4b00-8a56-11ea-8792-b8583b8f0d22.png)


Regarding the other findings:
1. Thank you for reviewing everything so thoroughly - I know that was a lot of work. 🤗
2. I cannot control the Sankey Quick Tips.  The algorithm simply rolls the dice and presents the tip that comes up.
3.  I fixed the typo in the "i"information spreadsheet files in Epicenter.
4.  Regarding appointments "i" Information. I cannot say, though it sounds like a good idea. @lzim what do you think?

**Comment by lzim** [comment]
This is really interesting @dlkibbe 
Yes, thank you for your thorough review! 🏆 

@anazariz @anthonycpichardo and @staceypark 
Let’s cross-ref this with #1374...and closed issue #1125 

- In this instance Identified by Debbie the appointments value for MM is very large.
- However, this datafile in TEST for training the QIICS was for a HCS, _not a team_ so an observation outside the typical MM boundary (max value) _in the Sim UI_ does **not** surprise me.

However, this file was from **station 583** that we checked out with Matt because we observed went from extremely large splashpage on previous observation, to extremely small for **go_live.**

@TomRust @anazariz and @anthonycpichardo - I’m wondering if we not only have an
- **edge/boundary** case for this specific MM value in the Sim UI, but whether for this site we have
- **corner case** - _multiple values_ in combination outside normal operating parameters. 

We’ve seen odd behavior, which calls into question what **corner case** testing routines we should consider across out **sim_ui,** **model** and **quant_workgroups.**
- And at a minimum, realizing that this file is the dataset in TEST is informative. 
- **We should consider more carefully the data files used to a) validate models, and b) use in the DEV and TEST environments.**

-  **CROSS-REF #1220,** where there are interesting examples of automated testing routines.
NICE Examples for #1220
https://github.com/department-of-veterans-affairs/vets-website
https://github.com/department-of-veterans-affairs/caseflow

- **CROSS-REF **document_tracker** cards: #625 **model_check_procedure** #626 **splashpage_check** etc.

**Comment by dlkibbe** [comment]
@jamesmrollins - One other item which may be obvious but wanted to be sure was noted when I was working in TEST, the range of values in the Experiments section red slider exceeded that of the values in the Save file function.
