### ISSUE TITLE
Rpackages

### ISSUE THREAD

**Issue by saveth** [lzim/teampsd#75]
@lzim please review the package_status.xlsx file here: https://github.com/lzim/teampsd/tree/master/data_script/Rpackages

The file contains all the libraries I was able to install based on libraries listed in the quant and qual working group folders in addition to the ones I use. A zip file of the installed library is in TeamPSD/quant_workgroup/r/3.5.zip on the shared drive. 

The cells highlighted are the packages that  requires  IT install as we don't  have permission to install the extension files.

**Comment by lzim** [comment]
Thanks so much @saveth I spot checked for all the ones I could think of, so this is absolutely great!

Also, @staceypark We may need to see about pointing to some R and R Studio basic resources for the qualitative workgroup, since they are trying to get RQDA analyses going ASAP.

So, we'll need the  R studio and the six extension file packages below. It turns out that Stacey thinks the help desk tickets for the team were created by @swapmush.  We'll work to get the tickets for R Studio update and the six packages tomorrow.

Package missing | Missing Package notes
-- | --
processx | contains an .exe file, permission denied
callr | requires processx
reprex | requires processx and callr
rvest | unable to overwrite previous install
tidyverse | requires all packages listed above
rgdal | contains .MID file, permission denied
tigris | requires rgdal
choroplethr | requires rgdal and tigris

Thanks again!

Lindsey

**Comment by staceypark** [comment]
@saveth Thanks for updating this Savet!
@teampsdkathryn @saveth @joycepyang @swapmush @lzim Ticket has been sent to HelpDesk for updated R Studio and to install the packages Savet indicated.  Ticket can be found in TeamPSD >  Help Desk Tickets > r_rstudio

**Comment by saveth** [comment]
@lzim @teampsdkathryn @joycepyang @swapmush @staceypark 

All the packages listed above (plus some extras) has been installed and saved in TeamPSD > quant_workgroup > r > 3.5 R packages.

Either add the folder to your .libPath() or change your R environment to set that folder as the default library to use all the packages there. We don't have admin rights to install some of the packages in the U drive (where are our current default home folder is set to).

**Comment by staceypark** [comment]
@lzim @teampsdkathryn @joycepyang @swapmush @saveth 
The R Studio ticket's been resolved and everyone should have 1.1.456 now! I just checked mine and it has been updated.  Can everyone else check as well?

**Comment by teampsdkathryn** [comment]
Hello Team, My R Studio has been properly updated. Best, Kathryn

**Comment by lzim** [comment]
@staceypark @lzim @teampsdkathryn @joycepyang @swapmush @saveth

Mine too!

**Comment by saveth** [comment]
Step-by-step instructional sheet to setup personal R library has been shared with the team via email. Everyone should be able to download packages and compile without issues.

**Comment by lzim** [comment]
Thanks so much @saveth!!

**Comment by teampsdkathryn** [comment]
I am not seeing this email. Perhaps you could resend it? Thank you, Kathryn

**Comment by saveth** [comment]
@teampsdkathryn The email and step-by-step instruction referenced in this comment is the one sent via the VA network where @lzim followed up by attaching the instruction in the email since you weren't able to open the link in the email I sent. The instruction is in the folder TeamPSD > quant_workgroup > r.

**Comment by teampsdkathryn** [comment]
Thank you! Kathryn

**Comment by teampsdkathryn** [comment]
The instructions were great. I followed them and encountered this response in the last step:

package ‘colorspace’ successfully unpacked and MD5 sums checked
Error in install.packages : cannot open file '\\r01palhsm07.r01.med.va.gov/homedir$/vhapalazevek/My Documents/R/win-library/3.5/file282c4a8b5d/ps/bin/i386/interrupt.exe': Permission denied

Any ideas on how to trouble shoot this? Thank you, Kathryn

**Comment by lzim** [comment]
@teampsdkathryn @saveth @staceypark 

It looks to me like you were trying to load an executable file (interrupt.exe) that should have been installed on your machine in the help ticket, because you will not have the administrative privileges to load this yourself.

Lindsey

**Comment by lzim** [comment]
@teampsdkathryn @saveth @staceypark 

Hi Kathryn, I removed the path you originally posted in your comment. We don't want to put paths on GitHib, Savet will follow-up with you to help you with this and explain it!

Thanks to you both,

Lindsey
