### ISSUE TITLE
Save Tile Re-design

### ISSUE THREAD

**Issue by jamesmrollins** [lzim/teampsd#81]
@lzim @dlounsbu @dlkibbe  @branscombj @staceypark @TomRust  @holbrooa 

Hi Everyone!
Based on feedback yesterday on the Save tile, Decided its best just to do a redesign.  See the picture below.  Does this meet the intent of the team?  If the model doesn’t support Cohorts or Services, those boxes will be grayed out. I also adjusted the instructions in the header.  If I get agreement today, this can be in place by Monday morning.
![image](https://user-images.githubusercontent.com/30132017/43971372-a2358cf8-9c85-11e8-857b-f298bf3871e8.png)
Thank you,
James

**Comment by branscombj** [comment]
I think this makes sense but I'm not positive that my thinking is correct. If it is, then I'd say Service/Cohort go before Number because they are further specs for the variable being used - i.e. _which_ service's starting rate, or _which_ cohort's RVI - and then you choose the setting (number) for it.

Trying to check out my thinking but the Sim UI is hanging up after I enter my credentials to login right now. Looks like a server issue?

Thanks, Jimmy!
Janie

**Comment by jamesmrollins** [comment]
@branscombj 
I am not having any issues logging in.  Perhaps try assigning yourself your own world (vice using Andrews) and try again.  

So below is what you would like to see:
![image](https://user-images.githubusercontent.com/30132017/43974654-1480d222-9c90-11e8-97d6-37a7858a6e24.png)
 
If so, please promote this to the rest of the group.

Thanks!

James.

**Comment by branscombj** [comment]
yes, thanks!

**Comment by dlkibbe** [comment]
I agree with Jane that re-ordering the list would be helpful for a user. 
Users may not have written down their changes prior to going to the save function. Should there be language in the pop up box that reminds them to do this?

**Comment by jamesmrollins** [comment]
@branscombj @lzim @saveth @TomRust @alballinger @dlkibbe @dlounsbu 

Jane - thanks for the feedback, changes are below
Debbie - regarding adding explanatory text, it may be too late to offer that suggestion in the Save Tile because they would still have to close the tile and go back to gather the information.  Either way, it may not be that helpful.  Did I misunderstand your suggestion?

![image](https://user-images.githubusercontent.com/30132017/43975535-e0851a2a-9c92-11e8-8548-900ea4219d3e.png)  

Thanks,
James

**Comment by lzim** [comment]
Hello @branscombj @lzim @saveth @TomRust @alballinger @dlkibbe @dlounsbu and @jamesmrollins 

Thanks for your hard work on this! 

1. I note in the upper section that the recently re-decided and sortable (ascending/descending by date) file naming conventions isn't used in the mock-up design (all lowercase with underscores): yyyy_mm_dd_hhmm

2. I'm not sure if I'm understanding "service" or "cohort" particularly with the example design for the PSY module which is only one service (and that service is PSY). Is there any option if it doesn't apply for that module?

3. I'm also wondering about when the users want to make more than one change, for example to select more than one variable?  Was this discussed yesterday?

Thanks again, I'll be catching up with the MTL Launch meeting and the Agg Standardization tasks via Lucid and GitHub.

Happy Friday ALL!

Lindsey

**Comment by branscombj** [comment]
I don't know about #1. #2: Those options will be grayed out if you're in a module where they don't apply. #3: I believe yes, you can add more variables in succession - isn't that right? I thought that was what it was set up to do before. #4: The other option would be to include all the variables duplicated for each service/cohort like we do in the menus for charts - I think.

**Comment by jamesmrollins** [comment]
@branscombj @dlkibbe @TomRust @lzim @staceypark @holbrooa 

All,
Jane is correct.  If a model doesn't have multiple cohort or service options, then the drop down would be grayed out (see illustration).  The user can also add as many variables as is desired, by selecting the variable, the number and clicking "Add."

I changed the "Sim Parameters File" to "Team Data File" and the date format to  "yyyy_mm_dd_hhmm."

I tried to clarify the instructions. 

Thank you,
James
![image](https://user-images.githubusercontent.com/30132017/44007448-5bb7f146-9e4a-11e8-8543-c8a4f7bd701e.png)

**Comment by TomRust** [comment]
This looks great, as long as the drop-down contains only and all variables found in the Experiments Tile.

Can we get "Base_Case" added to the drop down?

--TOM

**Comment by jamesmrollins** [comment]
@TomRust 
Tom - I thought that we were going to do all stocks and flows AND Experiments Sliders?  Meaning, that we would be able to describe an experiment by its effect on the main flow, not just describe the settings.

**Comment by staceypark** [comment]
@branscombj @dlkibbe @TomRust @lzim @holbrooa @jamesmrollins 
James and I noticed that we have been adding dates to all of the experiment file run names.  Would it be more helpful for us and the teams to just have the a date/time stamp automatically appended to the end of the experiment run name?

**Comment by jamesmrollins** [comment]
@branscombj @dlkibbe @TomRust @lzim @holbrooa @jamesmrollins
Good idea, I will look into it with the developers.  Should be possible thought.

**Comment by TomRust** [comment]
@jamesmrollins - So the name has two purposes? To say what experiment the team ran, or what they *predict* the outcome will be?  

Since Forio already tracks all the input data (ie, what experiment they ran), maybe their predicted outcome is the most important thing for the name convey.  If we ask for this info, then we won't have to read through all the text in their Question and Hypothesis boxes to know what they wanted to accomplish.

**Comment by lzim** [comment]
Hi @TomRust, @jamesmrollins, @hokbrooa, @brancombj, @dlkibbe, @dlounsbu, @staceypark

Following this good discussion:

1. Getting “bc” or base case is one of the most important goals - I saw in the notes this will be there.
2. Okay, great to have service and cohort when you need them and greyed our otherwise.
3. I see the new date convention is being applied in the new design = hurray!
4. Unless, folks want to try to win me over with a compelling alternative rationale, I think focusing just on the experiment sliders in naming is fine (not major flows/stocks). My rationale: I feel they very well may be wrong about the impacts, and there should typically be MANY impacts (we’ll want to this out and advance them from the simple relationships of level one systems thinking). Consistent with an overall goal of the program: We don’t want to reinforce poor mental models!! But, they shouldn’t be wrong about the decisions (experiment slider adjustments) and we want the facilitators to get them to making good decisions efficiently in session. Good is defined as “experiment” with high leverage or payoff; experiments that generate a key new insight they can apply in their day-to-day clinical practice. 
5. Regarding Stacey’s appending the date to the run name: I think an even more important thing than when it was run, may be tracking with which data it was run, so that learners & facilitators are sure they are making apples to apples comparisons across bc and their alternatives.
6. Last we WANT really good “systems thinking” text in the question, hypothesis, findings, decisions (q/h/f/d or QHFD) boxes. This will be coded qualitatively using our systems thinking codebook in the NIH R01 (the new grant). 
We will give our MTL facilitators a template to ensure they draft higher level (higher than where the team was at the prior session) systems thinking text during their co-facilitation preparation and then strive for that target with everything they do in session.

Hope these comments help situate this design within the larger context of fidelity to our MTL program principles and theory of change.

Thanks!

Lindsey

**Comment by jamesmrollins** [comment]
Hi @TomRust, @jamesmrollins, @holbrooa, @branscombj, @dlkibbe, @dlounsbu, @staceypark

I have tried to capture everyone's feedback into this latest drawing.  Please review and indicate your concurrence.  If it passes, then I will get the changes made.  I tried to adjust the instructions to encourage the user to write down their experiment values prior to saving and explain how to use the function.  The variable drop-down will contain base case and experimental variables.  Variable arrays will activate the service and cohort sub-menus accordingly. Finally, the date of the Team Data run will be added to the end of the string to allow cross referencing to appropriate data.  Note that the team data file name is also recorded in the export file.

![image](https://user-images.githubusercontent.com/30132017/44102522-bc42e156-9f9e-11e8-906d-0733d890552e.png)

I plan to put this into the Thursday push to developers.

Thank you!
James

**Comment by staceypark** [comment]
@TomRust, @jamesmrollins, @holbrooa, @branscombj, @dlkibbe, @dlounsbu, 

Hi Team, I think the new design reflects all the changes we requested and looks good to go.  Could other folks also weigh in and confirm?

@TomRust I know you voiced some concerns on the naming convention in general.  For example, if a team changed 7 variables, it feels impractical to have a file name 7 variables long.

**Comment by jamesmrollins** [comment]
@TomRust, @jamesmrollins, @holbrooa, @branscombj, @dlkibbe, @dlounsbu,

And another suggested change.  I added a Save and Reset button and moved that function and the Discard function to the bottom right.  This will reduce the potential of the user to click the wrong button.

![image](https://user-images.githubusercontent.com/30132017/44240078-45d89b80-a171-11e8-8aa7-71ec9d980238.png)

If no feedback by tomorrow COB, I will publish for dev.

James

**Comment by dlkibbe** [comment]
Hi James, I like this very much. Quick question - what is the reason a user would choose save vs. save and reset. Does something different happen on the screen when you choose one vs. the other?

**Comment by jamesmrollins** [comment]
@TomRust, @jamesmrollins, @holbrooa, @branscombj, @dlkibbe, @dlounsbu,
Note - The date format of the Team Data File is not in standard format.  Therefore, the date in the Experiment Filename string will not be in standard format.

**Comment by lzim** [comment]
Hi @TomRust & @jamesmrollins  !

In AGG we wanted to see the "total number of patients starting a service" (e.g., psychotherapy) collapsed across diagnostic cohort. I believe we found the "Starting a Service Rate" for each service but divvied up into diagnostic cohorts, which for our particular question wasn't of interest.

Did we miss a "starting a service rate" flow that collapses the diagnostic cohorts?

Thanks,

Lindsey

**Comment by jamesmrollins** [comment]
@lzim @TomRust 
After discussion with my Dev team last night, we must settle this issue TODAY.  If not, I will have to push the charts modification off until ver 1.7.  We are really tight on the deadline, so I must maintain focus on getting AGG finished.  Again, charts aren't difficult, buy I need a variable.  

Thank you,
James

**Comment by TomRust** [comment]
@lzim: If you’re looking for charts of the total patients starting in the team (i.e., summed across all services) or the total patients being seen by the team (again, summed across all services), then I’ve got you covered in the version I pushed out to James yesterday.
