### ISSUE TITLE
4/24/2020 RedCAP project for IIR Measures

### ISSUE THREAD

**Issue by jessfroe** [lzim/teampsd#813]
**1. Add description:** 
Create digitized surveys for all measures included in the IIR.

<< Paste screenshots here>>
 
**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_
3 hours (Jessilyn will complete) 
**Edit the due date (if necessary)**

**Comment by jessfroe** [comment]
Updated the due date for this issue @lzim @staceypark to focus on the R21 measures and qual coding before turning to this.

**Comment by staceypark** [comment]
@jessfroe thanks for working on this! I moved this and the R01 Measures to the feature tracker, since it's not an "issue or bug with an existing item"

**Comment by lzim** [comment]
@jessfroe 
Can you please touch base w/@staceypark about some edits we are going to need on the back-end to reflect our decision to go with "MTL Red" and "MTL Blue" rather than "Team Feedback" and  "MTL." 

_It will entail:_
1. Tracking on the backend one as "Red" (formerly known as Team Feedback) and one as "Blue" (formerly known as MTL).
2. Copy to use the same MTL language for both conditions in the actual items (e.g., "_Modeling to Learn_ meets my approval.") We will be calling all versions "Modeling to Learn."
3. But, upload the _MTL Red_ and _MTL Blue_ logos to the surveys so that teams will recognize whether they are in Red or Blue.

For example, we're going to edit the mtl.how master repository to reflect this pending pull request.
https://github.com/lzim/mtl/tree/lzim-patch-2

Please let us know if you have any questions, and very sorry that this decision is leading to some rework programming the measures. Thank you for your help with this!

**Comment by jessfroe** [comment]
@lzim I'll try to touch base with @staceypark sometime today. Shouldn't entail much more rework, so no worries!
Are we using this same system with the other grant - Participatory System Dynamics OR Audit and Feedback?

**Comment by jessfroe** [comment]
@staceypark let me know when you have feedback on the measures. I won't be able to access VA redcap over the holidays, so I'll have to incorporate what we discussed yesterday and any additional information from you next Friday.

**Comment by lzim** [comment]
Thanks @jessfroe!

- Note, in case this wasn’t clear:

- We do need to keep the IIR and R01 separate on the backend. And, of course they are largely different measures with only some overlap. 
- And we need to keep the Red for comparator and Blue for MTL throughout

**Comment by jessfroe** [comment]
@staceypark this is done, can you please double check before I close the issue, thanks!
🤡

**Comment by staceypark** [comment]
@jessfroe thanks! 
@lijenn will you double check her work once you learn REDCap?

**Comment by ritahitching** [comment]
@staceypark @lijenn @ritahitching 
Please clarify the following:
1. @jessfroe has already created the project and instruments for the IIR Measures in VA RedCap
2. Task is to double check the accuracy of the coding already on RedCap.
3. Confirm where is the IIR survey that was submitted to the IRB can be found to compare it to the coded RedCap project. 
4. Access to this RedCap project needed.

Once this specs are clear either @ritahitching or @lijenn will be assigned the task.

**Comment by lijenn** [comment]
Requirements
- [ ] 1. Double check that measures are correct against the draft IIR document. Make sure the measures are correct in the correct projects (MTL Blue Baseline and Red Baseline vs MTL Blue 6 months and MTL Red 6 months).
- [ ] 1a. Each project should have the respective arm logos
- [ ] 2.  Correct all language to say Modeling to Learn

**Comment by ritahitching** [comment]
@ritahitching 
- [ ] Replicate the project for **IIR Team Red Baseline** for **IIR Team Blue Baseline**
- [ ] The instruments in the **IIR Team Red Baseline** project are identical to the **IIR Team Blue Baseline** - no edits to be made
- [ ] Rename the new project to reflect **IIR Team Blue Baseline**
- [ ] Check the content of the instruments in the new **IIR Team Blue Baseline** project match the grant 
- [ ] Double check that measures have no typos or other errors
- [ ] Each project should have the respective arm logos [MTL Red](https://github.com/lzim/teampsd/blob/master/resources/logos/mtl_how_red.png) within Survey Settings
- [ ] Correct all language to say Modeling to Learn (i.e instead of usual QI)
- [ ] Notify @lijenn once the projects have been created and checked

**Comment by ritahitching** [comment]
I checked all the instruments in MTL Red and Blue and did not see any spelling or grammatical errors.

**Comment by ritahitching** [comment]
@staceypark is this issue ready to be closed? thanks

**Comment by staceypark** [comment]
I believe this was on @lijenn plate to review. 
Jenn, if you've reviwed and it looks good to go, we can close it.
