### ISSUE TITLE
RedCAP project for R01 measures

### ISSUE THREAD

**Issue by jessfroe** [lzim/teampsd#814]
**1. Add description:** 
Create digitized surveys of all measures included in the R01.

<< Paste screenshots here>>
 
**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_
2 hrs (Jessilyn will complete)
**Edit the due date (if necessary)**

**Comment by jessfroe** [comment]
Updated the due date for this issue @lzim @staceypark to focus on the R21 measures and qual coding before turning to this.

**Comment by lzim** [comment]
@jessfroe 
Can you please touch base w/@staceypark about some edits we are going to need on the back-end to reflect our decision to go with "MTL Red" and "MTL Blue" rather than "Team Feedback" and  "MTL." 

_It will entail:_
1. Tracking on the backend one as "Red" (formerly known as Team Feedback) and one as "Blue" (formerly known as MTL).
2. Copy to use the same MTL language for both conditions in the actual items (e.g., "_Modeling to Learn_ meets my approval.") We will be calling all versions "Modeling to Learn."
3. But, upload the _MTL Red_ and _MTL Blue_ logos to the surveys so that teams will recognize whether they are in Red or Blue.

For example, we're going to edit the mtl.how master repository to reflect this pending pull request.
https://github.com/lzim/mtl/tree/lzim-patch-2

Please let us know if you have any questions, and very sorry that this decision is leading to some rework programming the measures. Thank you for your help with this!

**Comment by jessfroe** [comment]
R01 Measures are complete. @staceypark if you can run through the measures to see if there is anything wrong/missing before I close the issue. 👍

**Comment by lijenn** [comment]
@lijenn @staceypark Reminder to email RedCap to get access.

**Comment by staceypark** [comment]
@lijenn I updated the deadline again for this. We are doing this tomorrow as part of training.

**Comment by staceypark** [comment]
@lzim

**Comment by staceypark** [comment]
@lzim FYI @lijenn 
Is it important in our programming of the measures to RedCap that:
1. The measures appear in a certain order? 
2. The measures appear as one long survey versus you finish measure 1 > links to measure 2 > links to measure3?

**Comment by lzim** [comment]
@staceypark @lijenn 

I don’t think these things have to be a specific way, what’s key is that the survey is easy to fill out with minimal clicks and/or encouragement that progress has been made, so that we don’t have missing data does that make sense?

**Comment by lijenn** [comment]
Right, the user experience should be as easy as possible to navigate within the surveys. This is should already have been done and I will review it in wk3 in oct_epic.

**Comment by lijenn** [comment]
Measures are all correct and survey looks good. Next step is a quick review by @staceypark (I'll send you the links) to click around the survey before we move it into production and make short links in #1353
