### ISSUE TITLE
9/25 Update Team R library folder

### ISSUE THREAD

**Issue by saveth** [lzim/teampsd#832]
**1. Add description:** 
* update the 3.6 folder with new packages needed in her code. 
* Alert Rita & Stacey when team library has been updated

<< Paste screenshots here>>
 
**2. Click on the right:**
a. **Projects** - assign to **issue_tracker.**
b. **Assignee** - assign relevant team members.
c. **Labels**- review and select all potential _MTL_ dependencies.
d. **Milestones** - select the dependent milestone.

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_

**Edit the due date (if necessary)**

**Comment by lzim** [comment]
@staceypark @saveth & @ritahitching

 This includes:
- [ ] updating the packages
- [ ] updating the R package guide 
- [ ] updating the team in the tt_teampsd report

**Comment by saveth** [comment]
@ritahitching @staceypark I've updated the packages and R package guide. I've emailed the both of you the list of "new" packages so you can include it in the tt report.

FYI: @saveth @lzim

**Comment by staceypark** [comment]
@saveth thanks for updating these in the TeamPSD folder.
Lets make sure to update it on GitHub as well here: https://github.com/lzim/teampsd/tree/master/resources/r/packages

Instead of an xlsx sheet (currently packages_status), I think it would make more sense to have a table of the packages added by date, for folks to quickly see. Also, in this spreadsheet it says that "processx" and "rgdal" needs OIT help for installation. Is that still true now that we can write to our C drive?

**Comment by staceypark** [comment]
@anthonycpichardo this is almost done with the exception of my most recent instructions and question. The question (about whether we need OIT assistance or not for certain packages) can be tested by using the computer in Lindsey's room since that has a new tower and has not had OIT installation for these packages.

> @saveth thanks for updating these in the TeamPSD folder.
> Lets make sure to update it on GitHub as well here: https://github.com/lzim/teampsd/tree/master/resources/r/packages
> 
> Instead of an xlsx sheet (currently packages_status), I think it would make more sense to have a table of the packages added by date, for folks to quickly see. Also, in this spreadsheet it says that "processx" and "rgdal" needs OIT help for installation. Is that still true now that we can write to our C drive?

**Comment by anthonycpichardo** [comment]
It does not appear that you need OIT assistance anymore @staceypark
