### ISSUE TITLE
Due 1/10 Feedback Participatory Design, Learning and Research (PLDR) Button & GitHub Community of Practice

### ISSUE THREAD

**Issue by ritahitching** [lzim/teampsd#864]
cross-ref #339 

## **QIICS:**
Provide comments on: 
- mtl.how/test PLDR button
- first iteration of SOP for **Participatory Design, Learning and Research** and the **GitHub Community of Practice**

**Comment by branscombj** [comment]
I click on Community of Practice and it links to mtl.how (GitHub).

**Comment by theresaschmitz** [comment]
@lzim @clairecollie @JayLCohen @hmarcia @MattMoore2 @jwklocek @gyiwamasa @theresaschmitz @jamesmrollins 

**Notes from the entire QIIC team (Jay Cohen, Claire Collie, Marcia Hunt, Gayle Iwamasa, John Klocek, Matt Moore, & Theresa Schmitz) on issue 864 (QIICs to test the Participatory Learning, Design, and Research (PLDR)) and cross reference #339:** 

**_Some initial reactions to approaching the task_**
1. Clicking people w lightbulb needs to be accompanied by ‘contact us’ option (in text) or some other phrasing. This can help to differentiate between the help question mark and PLDR as a mechanism for sharing feedback. 
2. Additionally, the chat option at the top of the page may also yield some additional confusion. In some online platforms the ‘chat’ option allows access additional customer support, whereas, in this platform we know that the chat option allows the participant to chat with other teammates during a session, or between facilitators and teammates. In any event, as it stands the chat option in this window may not allow for sufficient differentiating between the functions of the chat options at the top of the screen and three people with the lightbulb at the bottom right side of the screen.

**I have an idea**
After submitting the text on the ‘I have an idea’ option, it asked Matt if he wanted to join the MTL world. He was told he would get an email that explains how to join the online community. It’s confusing as Matt is already in the MTL world. It also appears that the email does not include a link or permissions (and the email does not give any info).  Perhaps changing the language to “thank you for sharing your idea.”


**I have an issue**
The automatic response to the submission of the issue indicates that the issue will be addressed, which initially felt spot on to the team. However, one thing that might be useful is a way in which the user could obtain information about or notification when their issue was addressed. It may also be useful to know that the typical turnaround time might be for addressing issues to help shape expectations for the user. 
 Perhaps modifying the language to include some of those facets would be helpful. The current default language is “We have received your issue and will act upon it right away. Should we have any additional questions, we will contact you via this email. Thanks again for your feedback - we really appreciate it!”


**I like something**
1. We tried to add a screen shot but it wouldn’t allow Matt to copy/paste of the screen snip that he took. He tried several options and it didn’t work a few times, but after 3 or 4 copies, the paste option worked. This wasn’t intuitive. 
2. Claire had some success in copy/pasting of a print screen (rather than a snip) but it showed up as a little icon but it didn’t load it into the upload window. 
3. The email response to the “like” submission was spot on and we liked that language: “We are really glad you liked MTL! We will share this feedback with Team PSD and use the information to help us make MTL better and better. “


**I have a question**
Clicking that that takes to a window to click button below to get started.  Clicking the ‘get help’ button it takes the user to the community of practice—which doesn’t allow you to ask a question. This is also not intuitive. It forces the user to have a good sense of what they need, to encourage them to keep clicking through the available links. The format/organization of that page (and the lack of ability to actually type a question in and have options generate that might match the identified issue) isn’t supportive of innate searching for folks new to the work/topics. All of these aspects could leave learners confused about how to get the answer(s) they need. 


**Community of Practice**
Clicking that option takes the group to the same github page as ‘I have a question’ but again, this isn’t terribly intuitive in terms of how to get the help that is needed. 


**Overall feedback across possible submission options** 
1. There’s no mechanism or option to review what is drafted for submission before clicking submit.  
2. Additionally when Claire submitted feedback, she received an email that had a typo (an rather than a, below):
“Thank you for your feedback. We have assigned your feedback an number. We will refer to this number with any correspondence to you. If you have volunteered to participate with us, or you need help, someone will contact you shortly.”

**Comment by branscombj** [comment]
I would edit text here slightly:
We have assigned your feedback **an** _should say "a"_ number. We will refer to this number **with** _I would say "in"_ any correspondence to you. 
![image](https://user-images.githubusercontent.com/29778290/72178839-bfe67180-33b1-11ea-879f-3309616d4847.png)

**Comment by jamesmrollins** [comment]
**Issues for discussion:**

**From Rita:**
1. The "Thank you!...Join us..." message appears after submitting a comment and not before. Any reason why?

Recommend: Offer the "Thank you!...Join us..." message Before and After comment submission.

**There is a "Join us" declaration on the main menu, but the option to actually "join" is not presented until after we address the user's issue.**

2.  I agreed to the "Thank you!...Join us..." message and was not asked to submit an email address.

Recommend: Pop up window that says something like "Which email do you prefer to use in our Community of Practice? [insert email]. We will send you a confirmation email shortly. Please confirm your email address to activate your Community of Practice account.".

I joined the Community of Practice and received an email. **"Dear rita, We are really...". Should the name be lower case? Not sure if capitalization error occurred when I signed up for a Forio/Epicenter account.

**Yes, I will adjust the capitalization issue. With respect to the email address, since we already know the user's email, we don't need to ask them for one.**

4. Does agreeing to join our Community of Practice grant us implied permission to send out an email or do we need express permission? (https://www.campaignmonitor.com/resources/guides/understanding-emails-laws-regulations/)
Recommend A follow up email that includes a message like We are really glad... Please confirm your email address to activate your Community of Practice [link].

**I reviewed these guidelines - they seem to be oriented at commercial entities that are using the email for marketing purposes.  Nevertheless, they appear to be prudent guidelines we should consider. I think the user not only clicks the button to "join us," but must also follow several steps to join GitHub.  It would seem arguable to me, that the user has shown considerable effort to be a part of something, so I am not sure we need to be any more explicit. Furthermore, if they were to opt out of the COP, they would have to do it, as we don't have the ability to manipulate their GitHub user account.**

I agreed to the "Thank you!...Join us..." on a prior section of the Community of Practice* home panel (e.g. "I have an idea") and was asked again to join when I made a second comment, on a separate tab (e.g. "I have an issue")

Recommend: I a person has signed up in a prior tab, not re-offer the opportunity to join.
Main Community of Practice Panel

**James will investigate comparing GitHub aliases to VA users to see if we can make the "Join Us" branch conditional.**

5.  When I made a comment under a section of the Community of Practice (e.g. "I have an idea") it only provides the option to close out the panel. if I have more than 1 concern (e.g. "I like something" and "I have an issue" the only option is to Close out and Re-open the community icon.

**Offer new button to return to main menu. Rather than having to re-navigate to home page once a comment/suggestion has been made.**

6. Sections Not Working:  
Ask a question.
Community of practice

**These sections will work once the COP is populated.  They currently navigate the user to the MLT repository on GitHub. We will refine the navigation once we have determined the appropriate landing pages.**

From Debbie:
I received a message for each post or inquiry that I submitted on PLDR (see screenshot).
Questions: 
1. Should there be a link to MTL resources in the emails?

**Yes, a link can be included in the email.  The emails are entirely customizable by anyone who has facilitator access.**

2. Should the response message have a subject line or title that relates to my submission? i.e. MTL Help, MTL Question, etc.

** Yes, the subject line can be adjusted - I will put in a change request.**

3. Does the "(epicenter)" need to appear in the subject line and the email address? People may wonder what that is or think its spam. 

**Yes I believe it must, as it is an Epicenter API. However, I will investigate.**

4. One message needs a couple corrections: a) change "an" to "a" in "an number" in sentence 2; b) sentence 3 suggested edit: "This number will be referenced in any follow-up correspondence."
    Message: "Thank you for your feedback. We have assigned your feedback an number. We will refer to this number with any correspondence to you. If you have volunteered to participate with us, or you need help, someone will contact you shortly."
![image](https://user-images.githubusercontent.com/31182258/71999829-1a47cc80-3210-11ea-90aa-329f000341d2.png)

**This message is customizable.**

5. One message says: "We have received your issue and will act upon it right away." Should right away be a specific time, i.e. "Thank you for submitting an MTL issue. We will act on this issue within 48 hours and provide a response."

**It can, yes.  But I would caution serious consideration of the ability to sustain this level of response as there has been concern to whether or not we can sustain this level of vigilance over the long-term.**

6. One sentence in one of the response messages: "Should we have any additional questions, we will contact you via this email."  Consider edit: "Any additional questions we have regarding your MTL inquiry will be sent from this email address." or "Should the MTL team have any questions regarding your inquiry, a message will be sent from this email address MTL Info (epicenter) <epicenter@forio.com>.

**This message is customizable. We will workshop this.**

**From QIICS**
Notes from the entire QIIC team (Jay Cohen, Claire Collie, Marcia Hunt, Gayle Iwamasa, John Klocek, Matt Moore, & Theresa Schmitz) on issue 864 (QIICs to test the Participatory Learning, Design, and Research (PLDR)) and cross reference #339:

Some initial reactions to approaching the task

1. Clicking people w lightbulb needs to be accompanied by ‘contact us’ option (in text) or some other phrasing. This can help to differentiate between the help question mark and PLDR as a mechanism for sharing feedback.

**I interpret this as we need to more clearly divide the COP/suggestions/Issues functions from the Help function.  Further, the help function needs to have an email component that allows the user to get one-on-one help. I will develop an alternative to resolve this potential confusion.**

2.  Additionally, the chat option at the top of the page may also yield some additional confusion. In some online platforms the ‘chat’ option allows access additional customer support, whereas, in this platform we know that the chat option allows the participant to chat with other teammates during a session, or between facilitators and teammates. In any event, as it stands the chat option in this window may not allow for sufficient differentiating between the functions of the chat options at the top of the screen and three people with the lightbulb at the bottom right side of the screen.

**Update "Chat" label on icon to say "Team Chat" to differentiate it from customer support.**

3. I have an idea
After submitting the text on the ‘I have an idea’ option, it asked Matt if he wanted to join the MTL world. He was told he would get an email that explains how to join the online community. It’s confusing as Matt is already in the MTL world. It also appears that the email does not include a link or permissions (and the email does not give any info). Perhaps changing the language to “thank you for sharing your idea.”

**While it is true that Matt is a member of an MTL world, Matt is not a (complete) member of the COP until he joins GitHub.  The outgoing message, which is customizable (but not complete yet) in an administration web page, will contain the appropriate instructions to register in GitHub to have full access to the mtl.how repository.** 

4. I have an issue
The automatic response to the submission of the issue indicates that the issue will be addressed, which initially felt spot on to the team. However, one thing that might be useful is a way in which the user could obtain information about or notification when their issue was addressed. It may also be useful to know that the typical turnaround time might be for addressing issues to help shape expectations for the user.

Perhaps modifying the language to include some of those facets would be helpful. The current default language is “We have received your issue and will act upon it right away. Should we have any additional questions, we will contact you via this email. Thanks again for your feedback - we really appreciate it!”

**Agree the language should be better - this is customizable at any time. We will workshop this.**

5. I like something
We tried to add a screen shot but it wouldn’t allow Matt to copy/paste of the screen snip that he took. He tried several options and it didn’t work a few times, but after 3 or 4 copies, the paste option worked. This wasn’t intuitive.  Claire had some success in copy/pasting of a print screen (rather than a snip) but it showed up as a little icon but it didn’t load it into the upload window.

**I'm not sure what to do about this - it is a common method for gathering screen captures. When a user pastes inside the window, a thumbnail appears that indicates the capture is complete.**

The email response to the “like” submission was spot on and we liked that language: “We are really glad you liked MTL!  We will share this feedback with Team PSD and use the information to help us make MTL better and better. “

6. I have a question
Clicking that that takes to a window to click button below to get started. Clicking the ‘get help’ button it takes the user to the community of practice—which doesn’t allow you to ask a question. This is also not intuitive. It forces the user to have a good sense of what they need, to encourage them to keep clicking through the available links. The format/organization of that page (and the lack of ability to actually type a question in and have options generate that might match the identified issue) isn’t supportive of innate searching for folks new to the work/topics. All of these aspects could leave learners confused about how to get the answer(s) they need.

**These are great suggestions on how to field questions a user might have.  When the GitHub wiki is built, the user will be placed in the Wiki tab of mtl.how.  From there they will have options to search for answers.**

7. Community of Practice
Clicking that option takes the group to the same GitHub page as ‘I have a question’ but again, this isn’t terribly intuitive in terms of how to get the help that is needed.

**HQ will provide a draft of material for the creation and implementation of COP in GitHub by Jan 22 meeting.**

Overall feedback across possible submission options

8. There’s no mechanism or option to review what is drafted for submission before clicking submit.

**I will check to see if this can be designed in.  However, it does add another click.**

Additionally when Claire submitted feedback, she received an email that had a typo (an rather than a, below):
“Thank you for your feedback. We have assigned your feedback an number. We will refer to this number with any correspondence to you. If you have volunteered to participate with us, or you need help, someone will contact you shortly.”

**We will workshop these outgoing messages.**

**Comment by branscombj** [comment]
Suggest (if possible) not offering multiple invitations to "join us to participate as a..." after someone has clicked to Join already. I submitting a like and clicked to Join, then submitted something else and got the Join pop-up message again.

Also, I think I got this email after clicking Join. This doesn't  seem to me to make a lot of sense, since a) I just clicked Join already; and b) the email tells me to "join" you but doesn't provide any steps to do so.

>Dear Jane, Modeling to Learn is a partnership. Join us to participate as a learner, designer or researcher. Thanks, Team Participatory System Dynamic (Team PSD)

**Comment by jamesmrollins** [comment]
Hi @branscombj @dlkibbe @staceypark @lzim, login as a facilitator in the Test session to get the Facilitator Dashboard.  Click on the PLDR option in the header menu buttons.  It will load an admin panel that has the capability to adjust the language of outgoing messages.  I recommend we workshop these altogether, that will save some time and iterations.

Select PLDR

![image](https://user-images.githubusercontent.com/30132017/72191646-caa40500-33b7-11ea-998e-e290955c945e.png)

Land Here

![image](https://user-images.githubusercontent.com/30132017/72191683-e7403d00-33b7-11ea-9b5b-3e35cc870038.png)

Scroll down to here

![image](https://user-images.githubusercontent.com/30132017/72193006-89622400-33bc-11ea-9d26-f3b4591d75e8.png)

**Comment by jamesmrollins** [comment]
@lzim @clairecollie @JayLCohen @hmarcia @MattMoore2 @jwklocek @gyiwamasa @theresaschmitz @staceypark @branscombj @dlkibbe @dlounsbu @ritahitching 

Please see below for proposed design changes:

**Regarding the Navigation Bar**

![image](https://user-images.githubusercontent.com/30132017/72367557-413f4c00-36b1-11ea-8cab-51517176eab8.png)

**Regarding the NEWS flash**
Changed the color to blue to make it more of a "normal" vice "urgent" communication implied by the color red.

![image](https://user-images.githubusercontent.com/30132017/72367662-721f8100-36b1-11ea-832f-851363cf1ceb.png)

**Regarding ALERTS**
Introduced a new message category called "ALERTS." The ALERT is red and pops up when the user logs in.  It persists until dismissed by the user.

![image](https://user-images.githubusercontent.com/30132017/72368524-1950e800-36b3-11ea-82e6-420faf4c8d5b.png)

**Comment by jamesmrollins** [comment]
@lzim I just want to make sure we want to adjust the PLDR button to the below based on QIICs feedback.  

![image](https://user-images.githubusercontent.com/30132017/73112809-29dc3c00-3ec5-11ea-96bd-35b7436e5ad3.png)

They also want to update the language from "_Modeling to Learn_ is a partnership. Join us to participate as a learner, designer or researcher."  to "_Modeling to Learn_ is a community. Join us to participate as a learner, designer or researcher."

![image](https://user-images.githubusercontent.com/30132017/73112868-88a1b580-3ec5-11ea-83d1-f3f7424e6af5.png)

**Comment by jamesmrollins** [comment]
FOR RELEASE DECISION

- [x] **QIICS Review Complete.**

- [x] **DEV Complete**  Will need to point "I Need Help" to the Wiki FAQ when migrating and update logos shown in the previous post.

- [ ] Outgoing Email Messages Edited and Complete.  This still needs to be work shopped.  Again, this is editable and should not delay release. 

- [ ] **WIKI FAQ Complete** This still in draft. However, we should not delay release as this will always be a work in progress.

**Comment by lijenn** [comment]
crossref: #898 SIM UI Cookies Typo (issue closed and merged here at #864)

Not sure where to find and how to edit the Cookies Pop-Up typos on the mtl.how/test log-in page.

<img width="771" alt="Screen Shot 2020-01-21 at 9 56 37 AM" src="https://user-images.githubusercontent.com/59668647/72829840-68a79300-3c34-11ea-9f73-828e1320c932.png">

Hi @jamesmrollins 

**For SIM UI Cookies Typos/Language:**
Let's rephrase the message to be in blocks (separate title and message, not have the continuation from title to message). I think a lot of us were confused and didn't read the original message as a continuation. Could you change it to something like this:

Cookies & Privacy Policy
We use cookies to remember your simulation settings, enhance security, and provide information about your interactions with the simulation. This information will not be shared with anyone of Team Participatory System Dynamics.

**Comment by jamesmrollins** [comment]
@lijenn I will make the changes below:

![image](https://user-images.githubusercontent.com/30132017/73614147-596c0200-45b1-11ea-9e67-9d2ad0618548.png)

**Comment by jamesmrollins** [comment]
## Some PLDR requirements were missed:

1.  QIICs wanted the Community button to represent inviting members to the greater Community (upvote/downvote).
2.  Users should know if button presses are going to pull them out of the simulation.
3.  The "L" (learning) functionality of the PLDR should be in a navigation bar for the most part. 

JMR Note:>> After review of the lucid meeting record, I found the directions above.  I interpret these 3 requirements as:  Dropping the "I have a question" button from the Community dialogue and moving it to the Navigation bar.  Any navigation away from the Sim UI should give a warning dialogue, such as, "MTL wants to open another window, is this OK?" Changing the "PLDR" underneath the button to "Community"  and replacing "partnership" with "Community" in the opening splash.  See illustrations below.

**As a result of clicking the "Community" icon, the menu below is presented:** If the user selects one of the buttons, they will present information as stipulated in the algorithm and in previous versions.

**Click Community Icon**
![image](https://user-images.githubusercontent.com/30132017/73791812-e781ed00-4757-11ea-8c8e-e68405261128.png)

**Then menu is presented**
![image](https://user-images.githubusercontent.com/30132017/73791765-d20cc300-4757-11ea-97f3-d422e02daa67.png)

**After the Issue, Like or Idea submission is complete, the "Join Us" request below will be presented.** If the person has already joined, the "Join Us" request will not be presented.

![image](https://user-images.githubusercontent.com/30132017/73793920-30d43b80-475c-11ea-818b-66c8ce1114b0.png)

**After the "Join Us" window has been presented and clicked by the user, the window below will be presented giving information about next steps.**

![image](https://user-images.githubusercontent.com/30132017/73794210-ca035200-475c-11ea-8ec4-939ba3fce0ad.png)


**The navigation bar will now include an icon that will open a window to the MTL wiki page.**

![image](https://user-images.githubusercontent.com/30132017/73793157-a50ddf80-475a-11ea-8080-cc3af741c996.png)

**And if the browser opens a page in the Wiki, it will present the following dialogue**

![image](https://user-images.githubusercontent.com/30132017/73793682-befbf200-475b-11ea-84d3-fc16d890ee60.png)

**Comment by lzim** [comment]
January 15th - https://meet.lucidmeetings.com/meeting/239210

Community of Practice

- Underlying principle to empower users to answer each others questions and become increasingly self-sufficient.  Devise an ptions for users to meet own needs in real time without an email.

- Decisions:

1) We decided to change to "Team" for the "Chat" icon in the Nav bar

2) James will a) mock up a button that says "Community" under it and b) mockup a "Community" icon in the Nav bar

3) We decied that the PLDR functions to remain outside of the nav bar:

(i) I have an idea 

(ii) I like something

(iii) I have an question

We decided we would like to offer users the options "Try A first and if you can't get your question answered, try B" type of coaching - suggested question content:

(a) "Do you want to see if someone has already answered your question within our Community?"

(b) "Do you want to send an email mtl.help@va.gov?"

We decided to also offer the option: "Would you like to actively participate in our Community of Practice?" (including an explanation).

4) We decided to add an "Issue" Icon to the nav bar (instead of "I have an issue" option in the Community button.

**Comment by lijenn** [comment]
@jamesmrollins  Just checked the cookies message! It looks better and makes a lot more sense! Thank you, James!

**PLDR button and dashboard and general functions** [will go over in Support WG 2/6/2020]

- [ ] **Issue 1**: **"paste your screenshot here" function** (issue only applies to **VA computers**).
   **Proposed solution**: Have a note/notice saying that you cannot copy and paste saved screenshot files on VA computers due to PHI concerns. Either have screenshot saved onto clipboard and paste from there or copy the screenshot after opening the screenshot file and then paste. 

I'm the type of user that automatically has their screenshots saved onto their desktop as a file. From there, I like to copy the file of the screenshot and paste it into the screenshot box. **Cannot do this on a VA computer!** See GIF below for what I mean when copying the screenshot as a file:
![ezgif com-optimize](https://user-images.githubusercontent.com/59668647/73699873-d7a3d380-4699-11ea-8f2c-39cd3b128c4f.gif)

I believe that this is **due to the VA's PHI concern** and their inability to scan a screenshot to detect if any PHI is present. As of right now, seems like the **only way to circumvent this issue is by having the screenshot saved into the user's immediate clipboard and pasting it right away or have the user actually click and open the file and then copy the image from the opened file. Or just use the 'Upload your files' button.**


- [ ] **Issue 2**: **Adding photos in the 'Outgoing Message Management' message texts for any of the Message Types** (outgoing emails, 'I have a question', 'Join us!', 'News Flash', & 'Alert')
   **Proposed solution**: TBD

The photos show up in the message texts, but do not show up when implemented. Here are the following errors that I get for each of the Message Types:

Outgoing emails:
![image](https://user-images.githubusercontent.com/59668647/73862970-2e252500-47f4-11ea-9308-83e6d9e3489c.png)

'I have a question' 
![i have a question screenshot](https://user-images.githubusercontent.com/59668647/73894122-53d01f80-4830-11ea-969b-3f1ced429e77.PNG)

'Join us!'
![join us screenshot](https://user-images.githubusercontent.com/59668647/73894026-166b9200-4830-11ea-8c68-98fb1f5b08f3.PNG)

'News Flash'
![image](https://user-images.githubusercontent.com/59668647/73863010-3da46e00-47f4-11ea-8d73-ab2379635ef4.png)

'Alert' (image link just shows up in the alert instead of the actual image)
![alert issue](https://user-images.githubusercontent.com/59668647/73798423-9bd73f80-4767-11ea-9f2f-87f434e95a32.PNG)

- [ ] **Issue 2a**: **Editing (adding or removing) the photo link in the 'Outgoing Message Management' message texts for any of the Message Types** (outgoing emails, 'I have a question', 'Join us!', 'News Flash', & 'Alert')
   **Proposed solution**: TBD/Photo link should show up in the message texts boxes so the user can edit the photo link.

Currently, the photo/image link disappears when trying to edit it in the message texts boxes. This makes it hard to see where the photo/image link is and to remove the photo link if it needs to be removed or add another photo link. 
![editing a photo link screenshot disappearing link in message texts](https://user-images.githubusercontent.com/59668647/73894229-ad384e80-4830-11ea-9463-a38e0791aecc.PNG)

Can also see something is there by the word count being 1. 
![word count 1](https://user-images.githubusercontent.com/59668647/73894063-284d3500-4830-11ea-8186-19133255ce34.PNG)

- [ ] **Issue 3**: **Fix typo in the outgoing email signature**
   **Proposed solution**: Change 'Dynamic' to 'Dynamic***s***'
![Dynamic to Dynamics](https://user-images.githubusercontent.com/59668647/73798161-e0161000-4766-11ea-96dc-a3097c3079d9.png)

**Comment by jamesmrollins** [comment]
Hi @lijenn - Thanks for your detailed feedback above.  Some of the issues you are having with photos and such are because you are not correctly configuring the system.  We will cover how to do this in MTL Demo and Team PSD Web Master training. With the remainder, we will consider these when we re-develop the PLDR capability.  

@staceypark , I would like to collapse this issue with #339 and return all to Work Breakdown.  Do you agree?

**Comment by lijenn** [comment]
@jamesmrollins Hi James, @staceypark  has agreed with the collapse. We should continue with updates going back in #339 and moving that card into Work Breakdown. I can get this done!
