### ISSUE TITLE
4/30 - MORE INFORMATION Page Redesign

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#886]
James,<br><br>I was closing out of my TEST session and I noticed how much sharper the “Select Team Data” section is than the other three image files here.<br><br>I know we’re working to get all the icons crisp, and I thought I would bring this one to your attention.<br><br>I believe you were going to see about uploading everything as vector (.svg) or something.<br><br>Thanks!<br><br>Lindsey<br></br></br></br></br></br>![image](https://s3.amazonaws.com/epicenter-asset/production/va/va-psd-test/1578698265197562816_img0.PNG) <br/>

**Comment by jamesmrollins** [comment]
The screen captures can be loaded at a higher resolution.  Not sure SVG will work in this circumstance since they are not drawings.

![image](https://user-images.githubusercontent.com/30132017/72575087-338bf100-3880-11ea-881a-0e86dac9a332.png)

**Comment by jamesmrollins** [comment]
@lzim there are 22 of these bitmapped images in the FAQ.  Will take roughly 3 hours for me to process the graphics into SVG and then roughly the same for DEV to place on the page and adjust for dynamic resolution. 

- [ ] 3 Hours design time

- [ ] 3 Hous DEV time

- [ ]  Release for DEV?

**Comment by staceypark** [comment]
Below approved during Thurs 1/30 Support Workgroup meeting

> @lzim there are 22 of these bitmapped images in the FAQ. Will take roughly 3 hours for me to process the graphics into SVG and then roughly the same for DEV to place on the page and adjust for dynamic resolution.
> 
> * [ ]  3 Hours design time
> * [ ]  3 Hous DEV time
> * [ ]   Release for DEV?

**Comment by staceypark** [comment]
@jamesmrollins I noticed you cross-referenced this in #949 as a sub-item to be completed together by 2/14. I updated the due date to match.

**Comment by staceypark** [comment]
We decide to gather requirements for this issue at the Thursday Support Workgroups Meeting.

**Comment by jamesmrollins** [comment]
Cross reference #989 Section is cut off.

**Comment by lzim** [comment]
@jamesmrollins 

Do you still need existing meeting time to gather requirements for this?
I added it to the release date section of "New Business" in tomorrow's workgroup leads meeting.

**Comment by jamesmrollins** [comment]
I also think we should consider adding an Admin page functionality to this page, so we can add sections and adjust content.

**Comment by lzim** [comment]
@jamesmrollins @staceypark 

Cross-ref #339

From the meeting: https://meet.lucidmeetings.com/meeting/240523

Within the ? "MORE INFO" Icon of the Navigation Bar
1. First Blue Bar the "MTL Road Map"
2. Links should be separated from References and be the second blue bar.
3. References blue bar will remain last in the list.
4. ​​​​​Need instruction on how to expand the blue bars too - it's not obvious.

**Comment by jamesmrollins** [comment]
Design reviewed:   [Adobe XD File] (https://xd.adobe.com/view/b7bd674a-fa80-47bd-79a9-9719965026dd-c18c/)]

Requirements Document: 
[#885 more info page design rtvm.xlsx](https://github.com/lzim/teampsd/files/4389809/885.more.info.page.design.rtvm.xlsx)

Design Review #1 Checklist:

- [ ] 1.  Change order of tiles as follows
    - _MTL_ Guides
    - _MTL_ Links
    - _MTL_ Navigation
    - _MTL_ Modules
    - _MTL_ Sections
    - _MTL_ References

- [ ] 2. Change phrase on _MTL_ Guides page to "_MTL_ blue guides and _MTL_ red guides are available at mtl.how (as a hyperlink)."

- [ ] 3. _MTL_ Links tile.  Change the descriptions as shown below:
   - mtl.how - "Click to access _MTL_ Guides."
   - mtl.how/data - "Click to navigate to the _MTL_ Data User Interface. **Internal for VHA providers only."
   - mtl.how/sim - remove this icon
   - mtl.how/menu - "Click to access the _MTL_ Menu survey of team priorities. **Internal for VHA providers only."
   - mtl.how/live - "Click to access online team meetings."
   - mtl.how/videos - "Click to access _MTL_ Videos."

- [ ] 4. MTL Navigation
   - "Top Navigation Bar"  - Keep as is.
   - Change Navigate to the Model Diagram to "Navigate the Home Screen"
   - Insert a drawing of the Home Screen that shows the 3 menus left to right how a typical user would see them. Session, Experiment Maintenance, Team Data Dropdown Maintenance.]
      - Add phrase: "The Sim UI home screen includes 3 menus when learning in an individual world or for team leads learning in their team world."
    - [Insert a drawing of the Home Screen that shows the 1 Session Menu]. 
       - Add phrase: "If you are learning with your team, and not a team lead, or if you are testing out the Sim UI at mtl.how/demo, then you will not see menus for maintaining your experiments or uploading team data."
   - Keep the map for how to navigate the three Home Screen sections
   - Edit the following:
      - Keep the Red Play icon as the main end point; but remove the "Sim Ui Model Diagram" light blue box.
      - Connect visually "You must select a team data file before clicking "Play" with the "Team Data Dropdown Maintenance."

- [ ] 5. _MTL_ Modules  (This is added requirement 885-3-5 - Provide subsection text element that is uses markdown language character set for bold, italics, bullets, and H1, H2 and H3 organization)
   - Keep the same overall.
   - When the Experiments Section for that Module has an expandable menu, include sub-headers consistent with experiments panels found in the Sim UI, then provide the list of experiment variables.
   - Example from SP: 
      - # H1 Experiment Variables
      - ## H2 GMH (or SMH or PC/PCMHI)
      - ### H3 The expandable section headers

- [ ] 6. MTL_ Sections
   - Consider one drawing per row, so that you can scroll down.
   - Try vertical scroll, order of the Session guides:
      - Text (session 5)
      - Experiments (session 5)
      - Model (session 6)
      - Outputs and Text (session 7)
      - Expanded Outputs and Text Screen (session 7 on...)
   - Provide a full screen view to orient the view of the user to the layout.

- [ ] 7. _MTL_ References
   - Add "To download pdf files for free, go to mtl.how/refs [link] and ask to join the Team PSD Zotero library.

**Comment by jamesmrollins** [comment]
@lzim @staceypark  Here is the revised drawing file with the changes we discussed yesterday.  I plan to get this version costed out on Sunday night by DEV.  Will be ready to receive a go decision by Monday if you are ready and have no further changes. Thanks, James

[more_info_page copy.pdf](https://github.com/lzim/teampsd/files/4396492/more_info_page.copy.pdf)

**Comment by ritahitching** [comment]
@jamesmrollins @lzim asked me to look over [more_info_page copy.pdf](https://github.com/lzim/teampsd/files/4396492/more_info_page.copy.pdf)
Please see very minor comments below.  Overall looks excellent. 
thanks

## Comments
### **Is there a way to make the information on the bullets fit into one line? I think it makes it easier to read.**

**Example 1:**
![image](https://user-images.githubusercontent.com/54862187/78169850-e3e0ae80-7406-11ea-8969-17318e02313c.png)

**Example 2:**
![image](https://user-images.githubusercontent.com/54862187/78169932-08d52180-7407-11ea-9154-938ed04bd7fd.png)

### **The icon looks out of sync with text on my screen.**
![image](https://user-images.githubusercontent.com/54862187/78170247-81d47900-7407-11ea-8be5-cff8fc6ec78b.png)

### **The font in the small side box is too small for my eyes to read.**
![image](https://user-images.githubusercontent.com/54862187/78170427-c95b0500-7407-11ea-9658-3aa1575d8b8b.png)

# Suggestions

### **Suggestion to show options in pull down menus (e.g. MM Experiment 1 /2  and Waiting to Start). May help users see the different options.**
![image](https://user-images.githubusercontent.com/54862187/78170607-07f0bf80-7408-11ea-9053-2f029b934025.png)

### **Suggestion for References section:**  _To learn more about the scientific literature about MTL and to download pdf files for free.....Zotero library._
![image](https://user-images.githubusercontent.com/54862187/78170778-51d9a580-7408-11ea-894f-1c1994510b16.png)

**Comment by jamesmrollins** [comment]
Hi @ritahitching , is this what you meant with respect to the comment about bullets?  The italics are subheadings, so their needs to be some subordination.  What do you think of the below?

![image](https://user-images.githubusercontent.com/30132017/78180714-04653480-7418-11ea-98f6-6b801d28b00e.png)

**Comment by lzim** [comment]
@jamesmrollins 

**_Modeling to Learn_ Guides**
1. Add periods after each of the four sentences.

**_Modeling to Learn_ Links**
1. light blue "mtl" logo should be flat, the "l" is flat, sometimes the "m" and the "t" have a highlight - no worries if this a quirk & they are vector files.
2. Add periods after each sentence. Currently only the last sentence has a period. [*Note: The "MTL Demo" logo sentence at mtl.how/demo also needs a period after it.]

__**Modeling to Learn_ Navigation**
1. Edit to say "Top Navigation Bar" (remove word "Icons")

_Navigating the Home Screen_
2. Edit: "The Sim UI home screen includes 3 sections in an individual world. Three sections are also displayed for team leads in their team world."
3. Edit: "The Sim UI home screen only displays the Session section at mtl.how/demo. If you are not a team lead, the Session menu is also the only section displayed in the team world."
_
1. Remove the bullets added since last review. Just keep the sub-headers

**Comment by jamesmrollins** [comment]
@lzim @staceypark   I don't think the single line rule for the "_Modeling to Learn_ Module" section is a good idea.  I think we underestimated just how long some of the Experiment Titles are (in one case, there was a line with 72 characters).    Doubling up the longer lines is better visually, I think. I left the modules above the same for comparison.  See below:

![image](https://user-images.githubusercontent.com/30132017/78207885-c982f100-7457-11ea-8126-9fd7648c46fa.png)

**Comment by ritahitching** [comment]
@jamesmrollins 
I was referring to the possibility of having the full description of an item within each bullet be in a single line - no wrap around of text, to look more elegant.
I realize you need and are using italics as demarcation for subheadings - which is a fine choice.  On my screen the font size in italics appears smaller, and when I read, my brain associates smaller text to indicate subordination more clearly than italics. Not a big issue at all. It was just my humble opinion 😄 .  

> Hi @ritahitching , is this what you meant with respect to the comment about bullets? The italics are subheadings, so their needs to be some subordination. What do you think of the below?
> 
> ![image](https://user-images.githubusercontent.com/30132017/78180714-04653480-7418-11ea-98f6-6b801d28b00e.png)

**Comment by jamesmrollins** [comment]
@ritahitching  THanks for the clarification.  I don't have room for full descriptions, and have tried the single-line variable idea.  But I don't think it will be workable with respect to column balance.  I will experiment with increasing the size of the Italics, or just using normal text.  I don't want to use boldface, as that is already used for H1.  Thanks for your time reviewing this.  James

**Comment by lzim** [comment]
> @lzim @staceypark I don't think the single line rule for the "_Modeling to Learn_ Module" section is a good idea. I think we underestimated just how long some of the Experiment Titles are (in one case, there was a line with 72 characters). Doubling up the longer lines is better visually, I think. I left the modules above the same for comparison. See below:
> 
> ![image](https://user-images.githubusercontent.com/30132017/78207885-c982f100-7457-11ea-8126-9fd7648c46fa.png)

@jamesmrollins I substantially prefer the bottom example that 
1. Makes the experiments clear to read and look uniform
2. Still includes a lot of what space
3. Substantially reduces the length of the "More Info" page.

**Comment by staceypark** [comment]
@lzim @jamesmrollins Yes, I can agree that when the single line is 72 chars long it starts to look a bit silly. What's a good character stop then - 50?

**Comment by jamesmrollins** [comment]
@staceypark @lzim, I think 50 could work.  Just something to balance out the columns a bit and match the title length of 4/5ths of the other lines.  Yes, it would add about 10 more lines.

**Comment by jamesmrollins** [comment]
@lzim and @staceypark   Here is a sample with Stacey's suggestion applied.  Give me 25 or so more spaces to balance-out the columns.  It only adds 6 more lines.  I also adjusted the Aggregate line to show how it looks with shorter titles.  Psych is the same for comparison. I think this is a good compromise.

**Comment by lzim** [comment]
#886 - More Info > "Modeling to Learn" Sections Drop Down
- Already in DEV ... Need to
- Blue Bars within...Or expand/collapse...to be more consistent with how the Sections really work.
- @jamesmrollins will add this addition to "Icebox"

**Comment by lzim** [comment]
@jamesmrollins and @lzim discussed this via teams today 4/20/20

- Tom and Lindsey are doing a talk that will walk through DEMO on Friday at 11AM Pacific, 2PM Eastern.

- It would be great if this is in TEST tomorrow, Tuesday 4/21, if tester could provide efficient feedback, in case this could move to PROD in team for the walk through.

- James said we could walk through DEMO in TEST on Friday, but my point is whether in TEST or PROD, hoping we could ID and squash bugs before then 🐞 

Are you testing this @branscombj @dlkibbe ?

**Comment by branscombj** [comment]
@lzim No, I did not have testing this on my ⚫)))) radar (emoji improv). But can. is the idea that I should check it out in simUI TEST tomorrow and give feedback here?

@jamesmrollins @dlkibbe

**Comment by jamesmrollins** [comment]
Hi @branscombj - it is not available on TEST yet and is overdue.  I am meeting with DEV tonight and will see where it is at.  I will provide an update tonight.  And thank you for volunteering to test - I will prepare the documentation.  BTW, I love the radar emoji!

**Comment by dlkibbe** [comment]
@jamesmrollins @branscombj  
Happy to test tomorrow late in the day or evening if its ready.

**Comment by jamesmrollins** [comment]
@dlkibbe @branscombj we should be ready for formal testing by tomorrow morning.  I have a few glaring errors to fix on the Admin Page.  I also need to populate the references and their associated hyperlink titles and URLs.  The More Info page is in TEST if you want a peek.

**Comment by jamesmrollins** [comment]
**THIS IS A PROVISIONAL DOCUMENT - DO NOT START UNTIL THIS LABEL IS REMOVED**

### Testing and Validation Document

**Test/validate assignee:** @branscombj @lrollins33 @dlkibbe 

**Test case document available here:** 
https://github.com/lzim/teampsd/blob/quick_tips_webmaster/resources/training_guides/mtl_how_facilitate/mtl_more_info_webmaster/more_info_webmaster.md

**Please check off these requirements as they are validated.** 

- [ ] 1.  The order of the sections are as follows
      - _MTL_ Guides
      - _MTL_ Links
      - _MTL_ Navigation
      - _MTL_ Modules
      -  _MTL_ Sections
      -  _MTL_ References 

- [ ] 2. _MTL_ Guides section.
   - [ ] Punctuation, spelling and grammar are correct.
   - [ ] Links work properly and direct to correct URL.
   - [ ]  Page is responsive to different resolutions.

- [ ] 3. _MTL_ Links section.
   - [ ] Punctuation, spelling and grammar are correct.
   - [ ] Links work properly and direct to correct URL.
   - [ ]  Page is responsive to different resolutions.

- [ ] 4. _MTL_ Navigation section.
   - [ ] Punctuation, spelling and grammar are correct.
   - [ ]  Page is responsive to different resolutions.
   - [ ]  Graphics are clear when shown at high zooms.

- [ ] 5. _MTL_ Modules 
   - [ ] Punctuation, spelling and grammar are correct.
   - [ ]  Page is responsive to different resolutions.
   - [ ]  Graphics are clear when shown at high zooms.
   - [ ]  Experiment variables are reflected in heading style consistent with Experiments Section header/sub-header arragement.
   - [ ]  All Experiment variables are present on the list.
   - [ ] All Complexity Reveals are present.

- [ ] 6. MTL_ Sections
   - [ ] Punctuation, spelling and grammar are correct.
   - [ ]  Page is responsive to different resolutions.
   - [ ]  Graphics are clear when shown at high zooms.
   - [ ] Vertical scroll - is in correct order of Session Guides:
      - [ ]  Text (session 5)
      - [ ]  Experiments (session 5)
      - [ ]  Model (session 6)
      - [ ]  Outputs and Text (session 7)
      - [ ]  Expanded Outputs and Text Screen (session 7 on...)

- [ ] 7. _MTL_ References
   - [ ] Punctuation, spelling and grammar are correct.
   - [ ] Links work properly and direct to correct URL.
   - [ ]  Page is responsive to different resolutions.

**Comment by branscombj** [comment]
**MTL Guides Section**

Recommend
- Italicize _Modeling to Learn_ in header phrase
- Delete "(MTL)" in header phrase; just use it without prior definition in the sub-text (it's obvious, especially when italicized).
![image](https://user-images.githubusercontent.com/29778290/80006592-16744900-8493-11ea-9eeb-674836aa0db0.png)

Recommend
- Omit the first "guides" and make the 2nd "guides" black font.
- Check link for mtl.how - it's linking back to the current page now for me.
- Un-bold the last bullet.
![image](https://user-images.githubusercontent.com/29778290/80006491-efb61280-8492-11ea-99f6-0ce2a680f7a5.png)

Top arrow in map is thinner than the others:
![image](https://user-images.githubusercontent.com/29778290/80006965-9ac6cc00-8493-11ea-8a87-f41c2f83ed75.png)

The Community button lines show through the label "Click to expand" - Makes it look garbled.
I recommend deleting that text in all the blue bars. Up/down triangles are pretty universally understood.
![image](https://user-images.githubusercontent.com/29778290/80007014-afa35f80-8493-11ea-8cd2-0acf82f34cf3.png)

**Comment by branscombj** [comment]
**MTL Links section**

Another reason to delete the "click to expand" verbiage - it says that even when you would click to minimize the open section:
![image](https://user-images.githubusercontent.com/29778290/80007670-94851f80-8494-11ea-866b-f2cb52a32428.png)

Should this be replaced with separate MTL Red and MTL Blue guides links?
![image](https://user-images.githubusercontent.com/29778290/80007833-d2824380-8494-11ea-9c4b-6768db05244a.png)

Consider replacing "**Internal for VHA providers only" with "(only accessible within VA)" or "(accessible behind VA firewall)" - because regardless of staff affiliation, those links won't work if you aren't behind the firewall.
![image](https://user-images.githubusercontent.com/29778290/80007882-e7f76d80-8494-11ea-9dc8-4f18d219b118.png)

The mtl.how icon links properly, but all the others open a new window with "about:blank" in the search bar. I am not behind the VA firewall, so that might be what I'd expect to get for Data and Menu; but Live and Video should work.

**Comment by lrollins33** [comment]
**Broken links in the MTL References section of the MOREINFO page**  
@staceypark I don't have the resources to fix these. Who should be assigned to fix them?  
Thanks  
Lucy

Reference # | Message  
----------------|-------------   
18 | link to wrong paper  
59 | 404 Page not Found  
119 | 403 Forbidden  
135 | 404 Error message, then takes you to https://case.edu/nursing/  
149 | 404 Not Found  
150 | blank page  
179 | This site is not secure   
181 | takes you to Accords webpage; Zotero link not working either

**Comment by lzim** [comment]
Thanks for the review @branscombj 

**I approve this language change: "accessible behind VA firewall"** 

I agree with this logic:  "because regardless of staff affiliation, those links won't work if you aren't behind the firewall."

**Comment by lzim** [comment]
> **Broken links in the MTL References section of the MOREINFO page**
> @staceypark I don't have the resources to fix these. Who should be assigned to fix them?
> Thanks
> Lucy
> 
> Reference #	Message
> 18	link to wrong paper
> 59	404 Page not Found
> 119	403 Forbidden
> 135	404 Error message, then takes you to https://case.edu/nursing/
> 149	404 Not Found
> 150	blank page
> 179	This site is not secure
> 181	takes you to Accords webpage; Zotero link not working either

@ritahitching Can you help @lrollins33 find updated links for the 7 references?

@lrollins33 and @ritahitching - The Team PSD Zotero library should help answer this question.

**Comment by jamesmrollins** [comment]
Hi @lzim , I checked Zotero and found issues there too.  I have a feeling these may have to be relinked by someone with access to stacks. 

FYI @ritahitching @lrollins33

**Comment by staceypark** [comment]
Thanks @jamesmrollins.
@ritahitching this should be in the "URL" section of the meta data for each reference in Zotero. Can you make sure both the link in Zotero is correct/updated and @lrollins33 has the links she needs as well?

> Hi @lzim , I checked Zotero and found issues there too. I have a feeling these may have to be relinked by someone with access to stacks.
> 
> FYI @ritahitching @lrollins33

**Comment by lzim** [comment]
>Hi @lzim , I checked Zotero and found issues there too. I have a feeling these may have to be relinked by someone with access to stacks.

@jamesmrollins I'm not sure what you mean by "stacks"

**Comment by jamesmrollins** [comment]
@lzim ye old library stacks. Meaning stacks of journals we used to dive into for research. Sorry for the archaic term.

**Comment by ritahitching** [comment]
@ritahitching this is a priority for Thursday 4/23 - will be needed by Friday for presentation.

**Comment by dlkibbe** [comment]
@jamesmrollins I've attached a review of the More Info content ment for your consideration. Take or leave as you see fit.
[More_info_page_copy review.docx](https://github.com/lzim/teampsd/files/4519443/More_info_page_copy.review.docx)
@branscombj  FYI

**Comment by jamesmrollins** [comment]
Thanks @dlkibbe !  I will process these tonight.

**Comment by jamesmrollins** [comment]
Hi @dlkibbe, after parsing through your feedback, I finally realized that you reviewed the design document, which was accepted and released into DEV last week. We are now making "small" adjustments to the web page in TEST ( https://forio.com/app/va/va-psd-test/moreinfo.html).

**Comment by dlkibbe** [comment]
@jamesmrollins @branscombj see feedback on the site noted in James' comment above.

Are we thinking that users will access more than 1 guide? I ask because of...:
1. MTL Guides in green box - should be singular "Guide"?
2. Last bullet - should be singular guide in "Use the map to determine which guides you should use"?

Use of asterisks in **Accessible behind VA firewall - bold or italics suggested as asterisks suggest there is a footnote at the bottom of the screen

Seems like the words "... the key is Modeling to Learn..." - should be bolded since the whole text is italicized to set them apart

Bottom navigation - phrasing? "Click here to the community of practice supporting Modeling to Learn"  Click here to join....  Click here to access... Click here to engage with...

MTL  Modules, Care Coordination - spelling correction needed: New Patients and **Rererrals** should be Referrals

MTL Modules, Psychotherapy - General Question: Is use of the apostrophe in “Patient’s” correct? In the text “Change in RVI of Patient’s Past 3 Months” and “Change in Engagement Duration of Patient’s Past 3 Months.” Patient’s – one patient has something vs. Patients’ many patients have something; isn't the model referring to a group of patients? In the “i” in the PSY module we use “Patient’s” in the title but the description says, “This is a relative change in **patients'** return-to-clinic visit interval after their first three months in psychotherapy.”

MTL Modules, Aggregate -  
1. Descriptive text: "...affect your overall mix of services..." - should this be "...affect your clinic's overall mix of services..."
2. List of Experiment Variables, last bullet needs "i" removed and hyphen inserted to be "Short-Term": Sensitivity of Staff Missed Appointments Due to **Shorti** Term Overtime

MTL Modules, SP - 
1. Descriptive text: should the risk be plural "risks" in the phrase? Seems like there are symptoms and risks.: "This model shows the effects of measurement based stepped care on patients' symptoms and risk." 
2. first bullet under Experiment Variables has spaces between the semi-colons and the text. The other bullets do not.

MTL Sections, Play Screen – instead of “*This* screen…” perhaps the text should say “A model diagram screen specific to your module will load after clicking “Play” on the Sim UI home screen.” People may expect to see the actual screen image shown below the text.

MTL Sections, Text - spelling correction - *receive** in "Click the Tutor to *recieve* helpful prompts
about the section."

MTL Sections, Experiments -
1. spelling correction - **adjustable** in "The Experiments section includes the Team Data Table and *adjustible* experiment sliders." 
2. Spelling correction - **retrieved** in “The Team Data Table lists your team’s data retreived from the Corporate Data Warehouse.”

MTL Sections, Model Diagram -
Experiment Slider Icon doesn't need to be capitalized in "This Experiment Slider Icon has a corresponding slider in the Experiments section."

**Comment by branscombj** [comment]
Follow-up on @dlkibbe 's notes:

> Are we thinking that users will access more than 1 guide? I ask because of...:
> MTL Guides in green box - should be singular "Guide"?
> Last bullet - should be singular guide in "Use the map to determine which guides you should use"?

Plural is correct here because this is directing learners to which set of guides is appropriate for them, depending on whether they are in Red, Blue, or self-learning via Video.

> Use of asterisks in **Accessible behind VA firewall - bold or italics suggested as asterisks suggest there is a footnote at the bottom of the screen

We just decided on some different wording (see above approval by LZ) so the asterisks will go away.

**Comment by jamesmrollins** [comment]
@dlkibbe @branscombj   See below.  The checks indicate I have either made the edit or the change is reflected in tonight's bug report.  I will discuss unchecked issues with @lzim in the Sim UI meeting later this morning.

 - [x]  Are we thinking that users will access more than 1 guide? I ask because of...:
      1. MTL Guides in green box - should be singular "Guide"? **OK AS-IS**
      2. Last bullet - should be singular guide in "Use the map to determine which guides you should use"? **OK AS-IS**

- [x] Use of asterisks in **Accessible behind VA firewall - bold or italics suggested as asterisks suggest there is a footnote at the bottom of the screen **RESOLVED**

 - [ ] Seems like the words "... the key is Modeling to Learn..." - should be bolded since the whole text is italicized to set them apart **ON MTL HOME PAGE: Italicize "Modeling to Learn" in both places. No bold or whole paragraph bold. Exclamation point in plain text (not italics). Add comma in 2nd sentence after "Remember".**  

**-  jmr note: This will require a change to all Home Screen verbiages.**

- [x] Bottom navigation - phrasing? "Click here to the community of practice supporting Modeling to Learn"  Click here to join....  Click here to access... Click here to engage with... **ADD THE WORD "join"**

- [x] MTL  Modules, Care Coordination - spelling correction needed: New Patients and **Rererrals** should be Referrals **See heading under Experiment Variables**

- [ ] MTL Modules, Psychotherapy - General Question: Is use of the apostrophe in “Patient’s” correct? In the text “Change in RVI of Patient’s Past 3 Months” and “Change in Engagement Duration of Patient’s Past 3 Months.” Patient’s – one patient has something vs. Patients’ many patients have something; isn't the model referring to a group of patients? In the “i” in the PSY module we use “Patient’s” in the title but the description says, “This is a relative change in **patients'** return-to-clinic visit interval after their first three months in psychotherapy.”

- [x] MTL Modules, Aggregate -  
1. Descriptive text: "...affect your overall mix of services..." - should this be "...affect your clinic's overall mix of services..."
2. List of Experiment Variables, last bullet needs "i" removed and hyphen inserted to be "Short-Term": Sensitivity of Staff Missed Appointments Due to **Shorti** Term Overtime

- [x] MTL Modules, SP - 
1. Descriptive text: should the risk be plural "risks" in the phrase? Seems like there are symptoms and risks.: "This model shows the effects of measurement based stepped care on patients' symptoms and risk." 
2. First bullet under Experiment Variables has spaces between the semi-colons and the text. The other bullets do not.

- [ ] MTL Sections, Play Screen – instead of “*This* screen…” perhaps the text should say “A model diagram screen specific to your module will load after clicking “Play” on the Sim UI home screen.” People may expect to see the actual screen image shown below the text.

- [x] MTL Sections, Text - spelling correction - **receive** in "Click the Tutor to *recieve* helpful prompts
about the section."

- [x] MTL Sections, Experiments -
      1. spelling correction - **adjustable** in "The Experiments section includes the Team Data Table and *adjustible* experiment sliders." **DONE**
      2. Spelling correction - **retrieved** in “The Team Data Table lists your team’s data retreived from the Corporate Data Warehouse.” **STILL NEEDED**

- [x] MTL Sections, Model Diagram -
Experiment Slider Icon doesn't need to be capitalized in "This Experiment Slider Icon has a corresponding slider in the Experiments section."

**Comment by ritahitching** [comment]
@lrollins33 
I'm updating the broken / incorrect links to the references.
- [ ] Will you please clarify where you found the references you mentioned? 
- [ ] I looked in [mtl.how/refs](https://www.mtl.how/refs) - Modeling to Learn References - is this the correct location? I found 51 references in that library.
- [ ] How are you associating the reference number to the publication/author?
- [ ] When I looked at #18 below - Maghill & Ray (2009)  Cognitive-behavioral treatment with adult alcohol and illicit drug users: A meta-analysis of randomized controlled trials. It links to the correct paper [here](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2696292/)
 

> **Broken links in the MTL References section of the MOREINFO page**
> I don't have the resources to fix these. Who should be assigned to fix them?
> Thanks
> Lucy
> 
> Reference #	Message
> 18	link to wrong paper
> 59	404 Page not Found
> 119	403 Forbidden
> 135	404 Error message, then takes you to https://case.edu/nursing/
> 149	404 Not Found
> 150	blank page
> 179	This site is not secure
> 181	takes you to Accords webpage; Zotero link not working either

**Comment by ritahitching** [comment]
@jamesmrollins 
I updated the Zotero library & More Info page for the references below.

Reference # | More info | Zotero
----------------|-------------   |-------------   
18 |  done |  done 
59 | done |  done
119 | done |  done
135 | done |  done
149 | done |  done
150 | done |  done
179 |done |  done
181 | done |  done

FYI @staceypark @lzim @lrollins33

**Comment by staceypark** [comment]
4/27 WG Leads meeting decision:
@branscombj will close out review and finish checking off boxes

**Comment by lrollins33** [comment]
@ritahitching 
I checked the links for the references 18, 59, 119, 135, 149, 150, 179 and 181 on the MORE INFORMATION page and they all are working properly.

**Comment by branscombj** [comment]
Hi @staceypark @jamesmrollins @dlkibbe @ritahitching @lijenn I apologize that I did not close this issue before the end of April. I had checked off all the validation boxes and didn't realize it was for me to make the card disappear:)

**Comment by staceypark** [comment]
Thanks @branscombj !

**Comment by lzim** [comment]
> Thanks @branscombj !

Whoo hoo!! Yes, thanks Jane!
