### ISSUE TITLE
Data Exploration and Validation

### ISSUE THREAD

**Issue by lzim** [lzim/teampsd#9]
Lead = Joyce

aka "Operations Data" session

**Comment by joycepyang** [comment]
Hi Lindsey,

I'm trying to do the workaround of being able to respond to your GitHub comments to me while working at my Team PSD desktop computer - however, the notifications from GitHub go to my gmail; which as you know is inaccessible. Since at the moment, I cannot find where the Patch request commentary line is within GitHub, I'm just going to try commenting on it here and hope that you will see it!

You responded saying that there was a way to push to the facilitation guide rather than create a new branch, per what you, Alexandra, Swap, and I figured out together in the office that day.  Melissa, Myra, and I were noticing that we were having difficulty pushing to the facilitation guide IF we used the "Create new file" option.  We CAN push directly to the facilitation guide, if we don't use "Create new file", but rather, use "Upload file", once our code is complete elsewhere.  This latter option is what Alexandra and Swap have always used; I checked with both of them and they both said that the way they used GitHub has been to upload finalized code, not to work on code within GitHub.  I have noticed the same discrepancy, where if I work on code within GitHub, it generates that patch thing that gets sent to you, because the option to commit to Facilitation Guide Branch is not available in the section on the bottom where you chose where to save to.

At the moment, I have completed code / .rmd to upload for Operations See and Say files. However, since I couldn't work on them in GitHub (per that problem above), I have to wait until I get wifi again to upload it (later today; I just did a loop around the outside of MPD with my cell phone trying to do the wifi personal hotspot thing, to no avail).

It's cool that you've connected GitHub and Basecamp!  It makes sense to me that you want to see this all in a "feed" sort of way, so I hope this comment shows up for you too.

Joyce

**Comment by joycepyang** [comment]
Hmmm I'm seeing the Data See / Data Say milestones - I believe these refer to me. I'm not sure how best to upload the OperationsSay.rmd and OperationsSee.rmd files here in order to close out and meet the milestone. However, I have added both to the facilitation guide branch, so hopefully they show up there?

**Comment by lzim** [comment]
Hey Joyce,

Thanks for working on this and updating me. 
I'll take a look at the push work issue when I'm at a computer.

From the VA or any computer messaging directly from the GitHub messaging thread is probably easier than through email. I'm using email here so you can get it lots of places. But, if you go to "Projects" or "Issues" you should be able to connect to this conversation there and I will see it.

Last, hot tip: If download the GitHub Desktop software to your VA desktop and/or personal laptop, you may find the workflow and tracking of updates even more user-friendly. There's a column on the left that shows if anything new has happened on anything you've worked on.

You comment there too.

Have a great weekend with your friends!

Lindsey 



Sent from my iPhone
Lindsey Zimmerman, Ph.D.
Clinical and Community Psychologist, Implementation Science
National Center for PTSD,
Dissemination and Training Division
VA Palo Alto Health Care System
