### ISSUE TITLE
sim UI login hang-up

### ISSUE THREAD

**Issue by branscombj** [lzim/teampsd#998]
**1. Add description:** 
I'm proof-reading facilitator SAY guides. I logged in to the Test environment – because I was already assigned as a team member there vs Prod where I’m currently Facilitator – to check some labels and layout against descriptions in the guides. While there, I realized I needed to look at the Select Prior Experiments function, so I ran a bc. When I tried to save it, the sim UI hung up (three "working" dots). I exited the browser (Chrome) window without logging out (because I couldn’t). That has always caused problems – which is why I am so emphatic about reminding people to log off before exiting the sim UI.

Anyway now I continue to find the sim UI hung up (see below) when I try to open it. @jamesmrollins can you advise? Is there a way I can resolve this with the facilitator functions in Epicenter? I’m asking for my current need as well as for future repeats of this situation.

Note that when I go to mtl.how/sim in a different (Edge) browser, it gives me the login screen unlike the screen below - but I've forgotten my password so I'm not able to test whether that's a solution (argh). I believe that in the past it has been - I could log on in a different browser, log off, and then be ok back in Chrome - but I'm not positive about that, it was a while ago.

![image](https://user-images.githubusercontent.com/29778290/74609984-13d52c00-50bd-11ea-8f68-d5be80d0a0a0.png)

**2. Click on the right:**  
a. **Projects** - assign to **issue_tracker.**  
b. **Assignee** - assign relevant team members.  
c. **Labels**- review and select labels to indicate the responsible workgroup and all potential dependencies 
d. **Milestones** - select the dependent milestone.  

-----------------------------------------------------------------------------------------
**Workgroups leads**
**Identify Constraints (check all that apply):**
- [ ]   Capacity
- [ ]   Cost
- [ ]   Schedule
- [ ]   Interference
- [ ]   Capability
- [ ]   Other (describe)

_Add estimated person-hours to complete:_

**Edit the due date (if necessary)**

**Comment by branscombj** [comment]
Oh, hey, I just looked at the screenshot above and realized the url there is the prod one, not test. Let me try that.

**Comment by jamesmrollins** [comment]
Hi @branscombj .  I checked this out, and because I am the repair person, it didn't present a problem for me.  However, based on your description, I believe this was a server unavailable issue. This can happen for a variety of reasons, including internet traffic but should only be temporary.

  The easy way to check, is to right click with your mouse pointer on the browser window and select "inspect."  When the inspect window appears, navigate to the Console tab and see what is there.  Typically, when you get the three dots, it is because a server is unavailable. No way to know for sure without looking at the console.  Another thing to do to clear the three dots cycle, is to refresh the page.  ~ James

![image](https://user-images.githubusercontent.com/30132017/74780048-a7d8fc00-5253-11ea-9512-22e3e8520853.png)

**Comment by branscombj** [comment]
OK thanks, James. I will follow this advice if it happens again.
